# Experiment Multiclass

In [1]:
import pandas as pd

In [53]:
import pandas as pd
import numpy as np
import os
import gzip
from scipy.io import arff
import warnings
warnings.filterwarnings('ignore')

print("="*80)
print("🔍 ANALISIS DATASET MULTICLASS - IDENTIFIKASI FILE DAN STRUKTUR DATA")
print("="*80)

# Base path for multiclass data
base_path = r"c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\data multiclass"

# Dictionary to store all loaded datasets
multiclass_datasets = {}
dataset_info = {}

def read_data_file(filepath):
    """Read .data file (comma-separated values)"""
    return pd.read_csv(filepath, header=None)

def read_arff_file(filepath):
    """Read ARFF file"""
    data, meta = arff.loadarff(filepath)
    df = pd.DataFrame(data)
    # Convert byte strings to regular strings if present
    for col in df.columns:
        if df[col].dtype == 'object':
            try:
                df[col] = df[col].str.decode('utf-8')
            except:
                pass
    return df

def read_names_file(filepath):
    """Read .names file to get attribute information"""
    try:
        with open(filepath, 'r') as f:
            content = f.read()
        return content
    except:
        return "Could not read names file"

print("\n🔎 SCANNING SEMUA DATASET MULTICLASS...")
print("-" * 60)

================================================================================
🔍 ANALISIS DATASET MULTICLASS - IDENTIFIKASI FILE DAN STRUKTUR DATA
================================================================================

🔎 SCANNING SEMUA DATASET MULTICLASS...
------------------------------------------------------------

In [54]:
# 1. CAR EVALUATION DATASET
print("\n1️⃣ CAR EVALUATION DATASET")
print("-" * 40)
try:
    car_path = os.path.join(base_path, "car+evaluation")
    car_data_file = os.path.join(car_path, "car.data")
    car_names_file = os.path.join(car_path, "car.names")
    
    # Read data
    car_df = read_data_file(car_data_file)
    car_names = read_names_file(car_names_file)
    
    # Based on UCI repository, car evaluation has these attributes:
    car_columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
    car_df.columns = car_columns
    
    multiclass_datasets['car_evaluation'] = car_df
    
    print(f"✅ File type: .data (CSV format)")
    print(f"✅ Shape: {car_df.shape}")
    print(f"✅ Features: {car_columns[:-1]}")
    print(f"✅ Target: {car_columns[-1]} (Classes: {car_df['class'].unique()})")
    print(f"✅ Class distribution:\n{car_df['class'].value_counts()}")
    
    dataset_info['car_evaluation'] = {
        'file_type': '.data',
        'shape': car_df.shape,
        'features': car_columns[:-1],
        'target': car_columns[-1],
        'n_classes': len(car_df['class'].unique()),
        'classes': list(car_df['class'].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading car evaluation: {e}")

1️⃣ CAR EVALUATION DATASET
----------------------------------------
✅ File type: .data (CSV format)
✅ Shape: (1728, 7)
✅ Features: ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']
✅ Target: class (Classes: ['unacc' 'acc' 'vgood' 'good'])
✅ Class distribution:
unacc    1210
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [55]:
# 2. COVERTYPE DATASET  
print("\n2️⃣ COVERTYPE DATASET")
print("-" * 40)
try:
    covertype_path = os.path.join(base_path, "covertype")
    covertype_file = os.path.join(covertype_path, "covtype.data.gz")
    
    # Read compressed data file
    with gzip.open(covertype_file, 'rt') as f:
        covertype_df = pd.read_csv(f, header=None)
    
    # Covertype has 54 features + 1 target (last column)
    # Features 1-10: quantitative, 11-54: binary (wilderness areas and soil types)
    n_cols = covertype_df.shape[1]
    feature_names = [f'feature_{i}' for i in range(1, n_cols)]
    feature_names.append('cover_type')
    covertype_df.columns = feature_names
    
    multiclass_datasets['covertype'] = covertype_df
    
    print(f"✅ File type: .data.gz (Compressed CSV)")
    print(f"✅ Shape: {covertype_df.shape}")
    print(f"✅ Features: {feature_names[:-1]} (54 features total)")
    print(f"✅ Target: cover_type (Classes: {sorted(covertype_df['cover_type'].unique())})")
    print(f"✅ Class distribution:\n{covertype_df['cover_type'].value_counts().sort_index()}")
    
    dataset_info['covertype'] = {
        'file_type': '.data.gz',
        'shape': covertype_df.shape,
        'features': feature_names[:-1],
        'target': 'cover_type',
        'n_classes': len(covertype_df['cover_type'].unique()),
        'classes': sorted(covertype_df['cover_type'].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading covertype: {e}")

2️⃣ COVERTYPE DATASET
----------------------------------------
✅ File type: .data.gz (Compressed CSV)
✅ Shape: (581012, 55)
✅ Features: ['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54'] (54 features total)
✅ Target: cover_type (Classes: [1, 2, 3, 4, 5, 6, 7])
✅ Class distribution:
1    211840
2    283301
3     35754
4      2747
5      9493
6     17367
7     20510
Name: cover_type, dtype: int64

In [56]:
# 3. DRY BEAN DATASET
print("\n3️⃣ DRY BEAN DATASET")
print("-" * 40)
try:
    bean_path = os.path.join(base_path, "dry+bean+dataset", "DryBeanDataset")
    
    # Try different file formats
    bean_files = {
        'arff': os.path.join(bean_path, "Dry_Bean_Dataset.arff"),
        'xlsx': os.path.join(bean_path, "Dry_Bean_Dataset.xlsx"),
        'txt': os.path.join(bean_path, "Dry_Bean_Dataset.txt")
    }
    
    bean_df = None
    file_used = None
    
    # Try ARFF first
    try:
        bean_df = read_arff_file(bean_files['arff'])
        file_used = 'arff'
    except:
        # Try Excel
        try:
            bean_df = pd.read_excel(bean_files['xlsx'])
            file_used = 'xlsx'
        except:
            # Try text file
            try:
                bean_df = pd.read_csv(bean_files['txt'], sep='\t')
                file_used = 'txt'
            except:
                pass
    
    if bean_df is not None:
        multiclass_datasets['dry_bean'] = bean_df
        
        # Assume last column is target
        features = list(bean_df.columns[:-1])
        target = bean_df.columns[-1]
        
        print(f"✅ File type: .{file_used}")
        print(f"✅ Shape: {bean_df.shape}")
        print(f"✅ Features: {features[:5]}... (Total: {len(features)} features)")
        print(f"✅ Target: {target}")
        print(f"✅ Classes: {bean_df[target].unique()}")
        print(f"✅ Class distribution:\n{bean_df[target].value_counts()}")
        
        dataset_info['dry_bean'] = {
            'file_type': f'.{file_used}',
            'shape': bean_df.shape,
            'features': features,
            'target': target,
            'n_classes': len(bean_df[target].unique()),
            'classes': list(bean_df[target].unique())
        }
    else:
        print("❌ Could not read dry bean dataset")
        
except Exception as e:
    print(f"❌ Error loading dry bean: {e}")

3️⃣ DRY BEAN DATASET
----------------------------------------
✅ File type: .arff
✅ Shape: (13611, 17)
✅ Features: ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation']... (Total: 16 features)
✅ Target: Class
✅ Classes: ['SEKER' 'BARBUNYA' 'BOMBAY' 'CALI' 'HOROZ' 'SIRA' 'DERMASON']
✅ Class distribution:
DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1928
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: Class, dtype: int64

In [3]:
cirrhosis

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,414,681,D,NaN,24472,F,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174.0,10.9,3.0
414,415,1103,C,NaN,14245,F,NaN,NaN,NaN,N,0.9,NaN,3.83,NaN,NaN,NaN,NaN,180.0,11.2,4.0
415,416,1055,C,NaN,20819,F,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143.0,9.9,3.0
416,417,691,C,NaN,21185,F,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269.0,10.4,3.0
417,418,976,C,NaN,19358,F,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,350.0,10.6,4.0

In [5]:
# Cirrhosis+patient+survival+prediction+dataset-1
cirrhosis = pd.read_csv('C:\\Users\\Asus\\Documents\\S1 Statistika\\Skripsi\\pycalib\\data multiclass\\cirrhosis+patient+survival+prediction+dataset-1\\cirrhosis.csv')
cirrhosis
# target is in 'Status'
# show shape, features, target, classes, class distribution
print("\n4️⃣ CIRRHOSIS PATIENT SURVIVAL PREDICTION DATASET")
print("-" * 40)
try:

    features = list(cirrhosis.columns)
    features.remove('Status')
    target = 'Status'
    
    print(f"✅ File type: .csv")
    print(f"✅ Shape: {cirrhosis.shape}")
    print(f"✅ Features: {features}")
    print(f"✅ Target: {target} (Classes: {cirrhosis[target].unique()})")
    print(f"✅ Class distribution:\n{cirrhosis[target].value_counts()}")
    
    dataset_info['cirrhosis'] = {
        'file_type': '.csv',
        'shape': cirrhosis.shape,
        'features': features,
        'target': target,
        'n_classes': len(cirrhosis[target].unique()),
        'classes': list(cirrhosis[target].unique())
    }

except Exception as e:
    print(f"❌ Error loading cirrhosis dataset: {e}")

4️⃣ CIRRHOSIS PATIENT SURVIVAL PREDICTION DATASET
----------------------------------------
✅ File type: .csv
✅ Shape: (418, 20)
✅ Features: ['ID', 'N_Days', 'Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage']
✅ Target: Status (Classes: ['D' 'C' 'CL'])
✅ Class distribution:
C     232
D     161
CL     25
Name: Status, dtype: int64
❌ Error loading cirrhosis dataset: name 'dataset_info' is not defined

In [6]:
air = pd.read_csv("C:\\Users\\Asus\\Documents\\S1 Statistika\\Skripsi\\pycalib\\data multiclass\\air\\updated_pollution_dataset.csv")
air
#target is in 'Air Quality'
# show shape, features, target, classes, class distribution
print("\n5️⃣ AIR QUALITY DATASET")
print("-" * 40)
try:

    features = list(air.columns)
    features.remove('Air Quality')
    target = 'Air Quality'
    
    print(f"✅ File type: .csv")
    print(f"✅ Shape: {air.shape}")
    print(f"✅ Features: {features}")
    print(f"✅ Target: {target} (Classes: {air[target].unique()})")
    print(f"✅ Class distribution:\n{air[target].value_counts()}")
    
    dataset_info['air_quality'] = {
        'file_type': '.csv',
        'shape': air.shape,
        'features': features,
        'target': target,
        'n_classes': len(air[target].unique()),
        'classes': list(air[target].unique())
    }

except Exception as e:
    print(f"❌ Error loading air quality dataset: {e}")
print("\n🔍 SUMMARY OF ALL MULTICLASS DATASETS LOADED")

5️⃣ AIR QUALITY DATASET
----------------------------------------
✅ File type: .csv
✅ Shape: (5000, 10)
✅ Features: ['Temperature', 'Humidity', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Proximity_to_Industrial_Areas', 'Population_Density']
✅ Target: Air Quality (Classes: ['Moderate' 'Good' 'Hazardous' 'Poor'])
✅ Class distribution:
Good         2000
Moderate     1500
Poor         1000
Hazardous     500
Name: Air Quality, dtype: int64
❌ Error loading air quality dataset: name 'dataset_info' is not defined

🔍 SUMMARY OF ALL MULTICLASS DATASETS LOADED

In [59]:
print(air['Air Quality'].value_counts())

Good         2000
Moderate     1500
Poor         1000
Hazardous     500
Name: Air Quality, dtype: int64

In [60]:
# 4. NURSERY DATASET
print("\n4️⃣ NURSERY DATASET")
print("-" * 40)
try:
    nursery_path = os.path.join(base_path, "nursery")
    nursery_data_file = os.path.join(nursery_path, "nursery.data")
    nursery_names_file = os.path.join(nursery_path, "nursery.names")
    
    # Read data
    nursery_df = read_data_file(nursery_data_file)
    
    # Based on UCI repository, nursery has these attributes:
    nursery_columns = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'class']
    nursery_df.columns = nursery_columns
    
    multiclass_datasets['nursery'] = nursery_df
    
    print(f"✅ File type: .data (CSV format)")
    print(f"✅ Shape: {nursery_df.shape}")
    print(f"✅ Features: {nursery_columns[:-1]}")
    print(f"✅ Target: {nursery_columns[-1]} (Classes: {nursery_df['class'].unique()})")
    print(f"✅ Class distribution:\n{nursery_df['class'].value_counts()}")
    
    dataset_info['nursery'] = {
        'file_type': '.data',
        'shape': nursery_df.shape,
        'features': nursery_columns[:-1],
        'target': nursery_columns[-1],
        'n_classes': len(nursery_df['class'].unique()),
        'classes': list(nursery_df['class'].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading nursery: {e}")

# 5. STUDENT DROPOUT DATASET
print("\n5️⃣ STUDENT DROPOUT AND ACADEMIC SUCCESS")
print("-" * 40)
try:
    student_path = os.path.join(base_path, "predict+students+dropout+and+academic+success")
    student_file = os.path.join(student_path, "data.csv")
    
    student_df = pd.read_csv(student_file, sep=';')
    
    multiclass_datasets['student_dropout'] = student_df
    
    # Assume last column is target
    features = list(student_df.columns[:-1])
    target = student_df.columns[-1]
    
    print(f"✅ File type: .csv")
    print(f"✅ Shape: {student_df.shape}")
    print(f"✅ Features: {features[:5]}... (Total: {len(features)} features)")
    print(f"✅ Target: {target}")
    print(f"✅ Classes: {student_df[target].unique()}")
    print(f"✅ Class distribution:\n{student_df[target].value_counts()}")
    
    dataset_info['student_dropout'] = {
        'file_type': '.csv',
        'shape': student_df.shape,
        'features': features,
        'target': target,
        'n_classes': len(student_df[target].unique()),
        'classes': list(student_df[target].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading student dropout: {e}")

# 6. TELCO CHURN DATASET
print("\n6️⃣ TELCO CHURN DATASET")
print("-" * 40)
try:
    telco_path = os.path.join(base_path, "telco churn")
    telco_file = os.path.join(telco_path, "WA_Fn-UseC_-Telco-Customer-Churn.csv")
    
    telco_df = pd.read_csv(telco_file)
    
    multiclass_datasets['telco_churn'] = telco_df
    
    # Features exclude target (Churn)
    features = [col for col in telco_df.columns if col != 'Churn']
    target = 'Churn'
    
    print(f"✅ File type: .csv")
    print(f"✅ Shape: {telco_df.shape}")
    print(f"✅ Features: {features[:5]}... (Total: {len(features)} features)")
    print(f"✅ Target: {target}")
    print(f"✅ Classes: {telco_df[target].unique()}")
    print(f"✅ Class distribution:\n{telco_df[target].value_counts()}")
    
    dataset_info['telco_churn'] = {
        'file_type': '.csv',
        'shape': telco_df.shape,
        'features': features,
        'target': target,
        'n_classes': len(telco_df[target].unique()),
        'classes': list(telco_df[target].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading telco churn: {e}")

# 7. CIRRHOSIS PATIENT SURVIVAL PREDICTION
print("\n7️⃣ CIRRHOSIS PATIENT SURVIVAL PREDICTION")
print("-" * 40)
try:
    cirrhosis_path = os.path.join(base_path, "cirrhosis+patient+survival+prediction+dataset-1")
    cirrhosis_file = os.path.join(cirrhosis_path, "cirrhosis.csv")
    
    cirrhosis = pd.read_csv(cirrhosis_file)
    
    multiclass_datasets['cirrhosis'] = cirrhosis
    
    # Features exclude ID and target (Status)
    features = [col for col in cirrhosis.columns if col not in ['ID', 'Status']]
    target = 'Status'
    
    print(f"✅ File type: .csv")
    print(f"✅ Shape: {cirrhosis.shape}")
    print(f"✅ Features: {features[:5]}... (Total: {len(features)} features)")
    print(f"✅ Target: {target}")
    print(f"✅ Classes: {cirrhosis[target].unique()}")
    print(f"✅ Class distribution:\n{cirrhosis[target].value_counts()}")
    
    dataset_info['cirrhosis'] = {
        'file_type': '.csv',
        'shape': cirrhosis.shape,
        'features': features,
        'target': target,
        'n_classes': len(cirrhosis[target].unique()),
        'classes': list(cirrhosis[target].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading cirrhosis: {e}")

# 8. AIR QUALITY DATASET  
print("\n8️⃣ AIR QUALITY DATASET")
print("-" * 40)
try:
    air_path = os.path.join(base_path, "air")
    air_file = os.path.join(air_path, "updated_pollution_dataset.csv")
    
    # Load the air quality dataset (already has proper format and target column)
    air_df = pd.read_csv(air_file)
    
    multiclass_datasets['air_quality'] = air_df
    
    # Features exclude target (Air Quality)
    features = [col for col in air_df.columns if col != 'Air Quality']
    target = 'Air Quality'
    
    print(f"✅ File type: .csv")
    print(f"✅ Shape: {air_df.shape}")
    print(f"✅ Features: {features}")
    print(f"✅ Target: {target}")
    print(f"✅ Classes: {air_df[target].unique()}")
    print(f"✅ Class distribution:\n{air_df[target].value_counts()}")
    
    dataset_info['air_quality'] = {
        'file_type': '.csv',
        'shape': air_df.shape,
        'features': features,
        'target': target,
        'n_classes': len(air_df[target].unique()),
        'classes': list(air_df[target].unique())
    }
    
except Exception as e:
    print(f"❌ Error loading air quality: {e}")

# 9. ROCKET LEAGUE SKILLSHOTS
print("\n9️⃣ ROCKET LEAGUE SKILLSHOTS")
print("-" * 40)
try:
    rocket_path = os.path.join(base_path, "rocket+league+skillshots")
    
    # Try to find csv file in the directory
    rocket_files = [f for f in os.listdir(rocket_path) if f.endswith('.csv')]
    
    if rocket_files:
        rocket_data_file = os.path.join(rocket_path, rocket_files[0])
        rocketleague = pd.read_csv(rocket_data_file)
        
        multiclass_datasets['rocket_league'] = rocketleague
        
        # Assume last column is target or look for common target names
        if 'label' in rocketleague.columns:
            target = 'label'
        elif 'class' in rocketleague.columns:
            target = 'class'
        elif 'target' in rocketleague.columns.str.lower():
            target = [col for col in rocketleague.columns if 'target' in col.lower()][0]
        else:
            target = rocketleague.columns[-1]
        
        features = [col for col in rocketleague.columns if col != target]
        
        print(f"✅ File type: .csv ({rocket_files[0]})")
        print(f"✅ Shape: {rocketleague.shape}")
        print(f"✅ Features: {features[:5]}... (Total: {len(features)} features)")
        print(f"✅ Target: {target}")
        print(f"✅ Classes: {rocketleague[target].unique()}")
        print(f"✅ Class distribution:\n{rocketleague[target].value_counts()}")
        
        dataset_info['rocket_league'] = {
            'file_type': '.csv',
            'shape': rocketleague.shape,
            'features': features,
            'target': target,
            'n_classes': len(rocketleague[target].unique()),
            'classes': list(rocketleague[target].unique())
        }
    else:
        print("❌ No CSV file found in rocket league directory")
        
except Exception as e:
    print(f"❌ Error loading rocket league: {e}")

print("\n" + "="*80)
print(f"📊 SUMMARY: {len(multiclass_datasets)} datasets berhasil dimuat")
print("="*80)

4️⃣ NURSERY DATASET
----------------------------------------
✅ File type: .data (CSV format)
✅ Shape: (12960, 9)
✅ Features: ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health']
✅ Target: class (Classes: ['recommend' 'priority' 'not_recom' 'very_recom' 'spec_prior'])
✅ Class distribution:
not_recom     4320
priority      4266
spec_prior    4044
very_recom     328
recommend        2
Name: class, dtype: int64

5️⃣ STUDENT DROPOUT AND ACADEMIC SUCCESS
----------------------------------------
✅ File type: .csv
✅ Shape: (4424, 37)
✅ Features: ['Marital status', 'Application mode', 'Application order', 'Course', 'Daytime/evening attendance\t']... (Total: 36 features)
✅ Target: Target
✅ Classes: ['Dropout' 'Graduate' 'Enrolled']
✅ Class distribution:
Graduate    2209
Dropout     1421
Enrolled     794
Name: Target, dtype: int64

6️⃣ TELCO CHURN DATASET
----------------------------------------
✅ File type: .csv
✅ Shape: (7043, 21)
✅ Features: ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents']... (Total: 20 features)
✅ Target: Churn
✅ Classes: ['No' 'Yes']
✅ Class distribution:
No     5174
Yes    1869
Name: Churn, dtype: int64

7️⃣ CIRRHOSIS PATIENT SURVIVAL PREDICTION
----------------------------------------
✅ File type: .csv
✅ Shape: (418, 20)
✅ Features: ['N_Days', 'Drug', 'Age', 'Sex', 'Ascites']... (Total: 18 features)
✅ Target: Status
✅ Classes: ['D' 'C' 'CL']
✅ Class distribution:
C     232
D     161
CL     25
Name: Status, dtype: int64

8️⃣ AIR QUALITY DATASET
----------------------------------------
✅ File type: .csv
✅ Shape: (5000, 10)
✅ Features: ['Temperature', 'Humidity', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Proximity_to_Industrial_Areas', 'Population_Density']
✅ Target: Air Quality
✅ Classes: ['Moderate' 'Good' 'Hazardous' 'Poor']
✅ Class distribution:
Good         2000
Moderate     1500
Poor         1000
Hazardous     500
Name: Air Quality, dtype: int64

9️⃣ ROCKET LEAGUE SKILLSHOTS
----------------------------------------
❌ No CSV file found in rocket league directory

================================================================================
📊 SUMMARY: 8 datasets berhasil dimuat
================================================================================

In [61]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
import copy

print("="*80)
print("🔧 PRA-PEMROSESAN DATA - MENANGANI MISSING VALUES")
print("="*80)

def preprocess_dataset(df, dataset_name, target_col):
    """
    Comprehensive preprocessing function:
    - Fill numeric missing values with median
    - Fill categorical missing values with mode
    - Handle special data types
    """
    print(f"\n📊 Processing: {dataset_name.upper().replace('_', ' ')}")
    print("-" * 50)
    
    # Create a copy to avoid modifying original data
    df_processed = df.copy()
    
    # Get initial missing value statistics
    initial_missing = df_processed.isnull().sum().sum()
    print(f"Initial missing values: {initial_missing}")
    
    if initial_missing == 0:
        print("✅ No missing values found - no preprocessing needed!")
        return df_processed, {}
    
    # Separate features from target
    if target_col in df_processed.columns:
        features = [col for col in df_processed.columns if col != target_col]
        X = df_processed[features].copy()
        y = df_processed[target_col].copy()
    else:
        X = df_processed.copy()
        y = None
    
    # Identify numeric and categorical columns
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
    
    print(f"Numeric columns: {len(numeric_cols)}")
    print(f"Categorical columns: {len(categorical_cols)}")
    
    preprocessing_info = {
        'initial_missing': initial_missing,
        'numeric_cols': numeric_cols,
        'categorical_cols': categorical_cols,
        'imputation_values': {}
    }
    
    # Handle numeric columns with median imputation
    if numeric_cols:
        print(f"\n🔢 Processing numeric columns...")
        numeric_missing = X[numeric_cols].isnull().sum()
        numeric_missing_cols = numeric_missing[numeric_missing > 0].index.tolist()
        
        if numeric_missing_cols:
            print(f"Numeric columns with missing values: {numeric_missing_cols}")
            
            # Use SimpleImputer with median strategy
            numeric_imputer = SimpleImputer(strategy='median')
            X[numeric_cols] = numeric_imputer.fit_transform(X[numeric_cols])
            
            # Store imputation values for reference
            for i, col in enumerate(numeric_cols):
                if col in numeric_missing_cols:
                    preprocessing_info['imputation_values'][col] = {
                        'type': 'numeric',
                        'method': 'median',
                        'value': numeric_imputer.statistics_[i]
                    }
                    print(f"  - {col}: filled with median = {numeric_imputer.statistics_[i]:.4f}")
        else:
            print("  ✅ No missing values in numeric columns")
    
    # Handle categorical columns with mode imputation
    if categorical_cols:
        print(f"\n🏷️ Processing categorical columns...")
        categorical_missing = X[categorical_cols].isnull().sum()
        categorical_missing_cols = categorical_missing[categorical_missing > 0].index.tolist()
        
        if categorical_missing_cols:
            print(f"Categorical columns with missing values: {categorical_missing_cols}")
            
            # Use SimpleImputer with most_frequent strategy (mode)
            categorical_imputer = SimpleImputer(strategy='most_frequent')
            X[categorical_cols] = categorical_imputer.fit_transform(X[categorical_cols])
            
            # Store imputation values for reference
            for i, col in enumerate(categorical_cols):
                if col in categorical_missing_cols:
                    preprocessing_info['imputation_values'][col] = {
                        'type': 'categorical',
                        'method': 'mode',
                        'value': categorical_imputer.statistics_[i]
                    }
                    print(f"  - {col}: filled with mode = '{categorical_imputer.statistics_[i]}'")
        else:
            print("  ✅ No missing values in categorical columns")
    
    # Combine processed features with target
    if y is not None:
        df_processed = pd.concat([X, y], axis=1)
    else:
        df_processed = X.copy()
    
    # Final verification
    final_missing = df_processed.isnull().sum().sum()
    preprocessing_info['final_missing'] = final_missing
    
    print(f"\n✅ Preprocessing completed!")
    print(f"Missing values: {initial_missing} → {final_missing}")
    print(f"Final shape: {df_processed.shape}")
    
    return df_processed, preprocessing_info

# Dictionary to store processed datasets and preprocessing information
processed_multiclass_datasets = {}
preprocessing_logs = {}

print(f"\n🔄 STARTING PREPROCESSING FOR ALL DATASETS...")
print("-" * 60)

================================================================================
🔧 PRA-PEMROSESAN DATA - MENANGANI MISSING VALUES
================================================================================

🔄 STARTING PREPROCESSING FOR ALL DATASETS...
------------------------------------------------------------

In [62]:
# Process each dataset
for dataset_name, df in multiclass_datasets.items():
    target_col = dataset_info[dataset_name]['target']
    
    try:
        processed_df, preprocessing_info = preprocess_dataset(df, dataset_name, target_col)
        processed_multiclass_datasets[dataset_name] = processed_df
        preprocessing_logs[dataset_name] = preprocessing_info
        
    except Exception as e:
        print(f"❌ Error processing {dataset_name}: {e}")
        # Keep original dataset if preprocessing fails
        processed_multiclass_datasets[dataset_name] = df.copy()
        preprocessing_logs[dataset_name] = {'error': str(e)}

print(f"\n" + "="*80)
print(f"📊 PREPROCESSING SUMMARY")
print("="*80)

📊 Processing: CAR EVALUATION
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

📊 Processing: COVERTYPE
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

📊 Processing: DRY BEAN
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

📊 Processing: NURSERY
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

📊 Processing: STUDENT DROPOUT
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

📊 Processing: TELCO CHURN
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

📊 Processing: CIRRHOSIS
--------------------------------------------------
Initial missing values: 1033
Numeric columns: 13
Categorical columns: 6

🔢 Processing numeric columns...
Numeric columns with missing values: ['Cholesterol', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage']
  - Cholesterol: filled with median = 309.5000
  - Copper: filled with median = 73.0000
  - Alk_Phos: filled with median = 1259.0000
  - SGOT: filled with median = 114.7000
  - Tryglicerides: filled with median = 108.0000
  - Platelets: filled with median = 251.0000
  - Prothrombin: filled with median = 10.6000
  - Stage: filled with median = 3.0000

🏷️ Processing categorical columns...
Categorical columns with missing values: ['Drug', 'Ascites', 'Hepatomegaly', 'Spiders']
  - Drug: filled with mode = 'D-penicillamine'
  - Ascites: filled with mode = 'N'
  - Hepatomegaly: filled with mode = 'Y'
  - Spiders: filled with mode = 'N'

✅ Preprocessing completed!
Missing values: 1033 → 0
Final shape: (418, 20)

📊 Processing: AIR QUALITY
--------------------------------------------------
Initial missing values: 0
✅ No missing values found - no preprocessing needed!

================================================================================
📊 PREPROCESSING SUMMARY
================================================================================

In [63]:
# Create comprehensive preprocessing summary
summary_table = []
total_initial_missing = 0
total_final_missing = 0

print(f"\n📋 DETAILED PREPROCESSING RESULTS:")
print("-" * 80)
print(f"{'Dataset':<20} {'Initial Missing':<15} {'Final Missing':<15} {'Status':<15}")
print("-" * 80)

for dataset_name, log in preprocessing_logs.items():
    if 'error' in log:
        print(f"{dataset_name:<20} {'Error':<15} {'Error':<15} {'Failed':<15}")
        continue
    
    initial = log.get('initial_missing', 0)
    final = log.get('final_missing', 0)
    total_initial_missing += initial
    total_final_missing += final
    
    status = "✅ Clean" if initial == 0 else "🔧 Processed"
    
    print(f"{dataset_name:<20} {initial:<15} {final:<15} {status:<15}")
    
    summary_table.append({
        'Dataset': dataset_name,
        'Initial_Missing': initial,
        'Final_Missing': final,
        'Numeric_Cols': len(log.get('numeric_cols', [])),
        'Categorical_Cols': len(log.get('categorical_cols', [])),
        'Imputed_Features': len(log.get('imputation_values', {}))
    })

print("-" * 80)
print(f"{'TOTAL':<20} {total_initial_missing:<15} {total_final_missing:<15} {'Complete':<15}")

# Show detailed imputation information
print(f"\n🔧 DETAILED IMPUTATION INFORMATION:")
print("-" * 70)

for dataset_name, log in preprocessing_logs.items():
    if 'imputation_values' in log and log['imputation_values']:
        print(f"\n📊 {dataset_name.upper().replace('_', ' ')}:")
        for feature, imp_info in log['imputation_values'].items():
            method = imp_info['method']
            value = imp_info['value']
            ftype = imp_info['type']
            if ftype == 'numeric':
                print(f"  - {feature}: {method} = {value:.4f}")
            else:
                print(f"  - {feature}: {method} = '{value}'")

# Create summary DataFrame
preprocessing_summary_df = pd.DataFrame(summary_table)

print(f"\n📈 PREPROCESSING STATISTICS:")
print("-" * 50)
print(f"Total datasets processed: {len(processed_multiclass_datasets)}")
print(f"Datasets requiring preprocessing: {sum(1 for log in preprocessing_logs.values() if log.get('initial_missing', 0) > 0)}")
print(f"Total missing values eliminated: {total_initial_missing}")
print(f"Success rate: {len([log for log in preprocessing_logs.values() if 'error' not in log]) / len(preprocessing_logs) * 100:.1f}%")

# Show before/after comparison
print(f"\n🔍 BEFORE vs AFTER COMPARISON:")
print("-" * 60)
for dataset_name in multiclass_datasets.keys():
    original_shape = multiclass_datasets[dataset_name].shape
    processed_shape = processed_multiclass_datasets[dataset_name].shape
    original_missing = multiclass_datasets[dataset_name].isnull().sum().sum()
    processed_missing = processed_multiclass_datasets[dataset_name].isnull().sum().sum()
    
    print(f"{dataset_name:20}: Shape {original_shape} → {processed_shape}, Missing {original_missing} → {processed_missing}")

print(f"\n💾 DATASETS TERSIMPAN DALAM VARIABEL:")
print("-" * 40)
print("Akses dataset yang telah diproses dengan: processed_multiclass_datasets['nama_dataset']")
print("Available processed datasets:")
for i, dataset_name in enumerate(processed_multiclass_datasets.keys(), 1):
    print(f"  {i}. processed_multiclass_datasets['{dataset_name}']")

print(f"\n🎯 DATASET SIAP UNTUK MODELING & KALIBRASI!")
print("="*80)

📋 DETAILED PREPROCESSING RESULTS:
--------------------------------------------------------------------------------
Dataset              Initial Missing Final Missing   Status
--------------------------------------------------------------------------------
car_evaluation       0               0               ✅ Clean
covertype            0               0               ✅ Clean
dry_bean             0               0               ✅ Clean
nursery              0               0               ✅ Clean
student_dropout      0               0               ✅ Clean
telco_churn          0               0               ✅ Clean
cirrhosis            1033            0               🔧 Processed
air_quality          0               0               ✅ Clean
--------------------------------------------------------------------------------
TOTAL                1033            0               Complete

🔧 DETAILED IMPUTATION INFORMATION:
----------------------------------------------------------------------

📊 CIRRHOSIS:
  - Cholesterol: median = 309.5000
  - Copper: median = 73.0000
  - Alk_Phos: median = 1259.0000
  - SGOT: median = 114.7000
  - Tryglicerides: median = 108.0000
  - Platelets: median = 251.0000
  - Prothrombin: median = 10.6000
  - Stage: median = 3.0000
  - Drug: mode = 'D-penicillamine'
  - Ascites: mode = 'N'
  - Hepatomegaly: mode = 'Y'
  - Spiders: mode = 'N'

📈 PREPROCESSING STATISTICS:
--------------------------------------------------
Total datasets processed: 8
Datasets requiring preprocessing: 1
Total missing values eliminated: 1033
Success rate: 100.0%

🔍 BEFORE vs AFTER COMPARISON:
------------------------------------------------------------
car_evaluation      : Shape (1728, 7) → (1728, 7), Missing 0 → 0
covertype           : Shape (581012, 55) → (581012, 55), Missing 0 → 0
dry_bean            : Shape (13611, 17) → (13611, 17), Missing 0 → 0
nursery             : Shape (12960, 9) → (12960, 9), Missing 0 → 0
student_dropout     : Shape (4424, 37) → (4424, 37), Missing 0 → 0
telco_churn         : Shape (7043, 21) → (7043, 21), Missing 0 → 0
cirrhosis           : Shape (418, 20) → (418, 20), Missing 1033 → 0
air_quality         : Shape (5000, 10) → (5000, 10), Missing 0 → 0

💾 DATASETS TERSIMPAN DALAM VARIABEL:
----------------------------------------
Akses dataset yang telah diproses dengan: processed_multiclass_datasets['nama_dataset']
Available processed datasets:
  1. processed_multiclass_datasets['car_evaluation']
  2. processed_multiclass_datasets['covertype']
  3. processed_multiclass_datasets['dry_bean']
  4. processed_multiclass_datasets['nursery']
  5. processed_multiclass_datasets['student_dropout']
  6. processed_multiclass_datasets['telco_churn']
  7. processed_multiclass_datasets['cirrhosis']
  8. processed_multiclass_datasets['air_quality']

🎯 DATASET SIAP UNTUK MODELING & KALIBRASI!
================================================================================

In [64]:
#multiclass_datasets['telco_churn'] drop customerID
if 'customerID' in processed_multiclass_datasets['telco_churn'].columns:
    processed_multiclass_datasets['telco_churn'].drop(columns=['customerID'], inplace=True)
    print("Removed 'customerID' column from telco_churn dataset.")

Removed 'customerID' column from telco_churn dataset.

In [65]:
# convert total charges to numeric
if 'TotalCharges' in processed_multiclass_datasets['telco_churn'].columns:
    processed_multiclass_datasets['telco_churn']['TotalCharges'] = pd.to_numeric(processed_multiclass_datasets['telco_churn']['TotalCharges'], errors='coerce')
    # Impute any new missing values created by conversion
    if processed_multiclass_datasets['telco_churn']['TotalCharges'].isnull().sum() > 0:
        median_value = processed_multiclass_datasets['telco_churn']['TotalCharges'].median()
        processed_multiclass_datasets['telco_churn']['TotalCharges'].fillna(median_value, inplace=True)
        print(f"Converted 'TotalCharges' to numeric and filled missing values with median: {median_value:.4f}")

Converted 'TotalCharges' to numeric and filled missing values with median: 1397.4750

In [66]:
processed_multiclass_datasets['telco_churn'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [67]:
processed_multiclass_datasets['telco_churn']

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [68]:
# Value counts for each object column in telco_churn dataset
print("="*60)
print("📊 VALUE COUNTS FOR OBJECT COLUMNS IN TELCO_CHURN DATASET")
print("="*60)

# Get the telco_churn dataset
telco_data = processed_multiclass_datasets['telco_churn']

# Get object columns only
object_columns = telco_data.select_dtypes(include=['object']).columns.tolist()

print(f"\nFound {len(object_columns)} object columns:")
print(f"Columns: {object_columns}")

# Display value counts for each object column
for col in object_columns:
    print(f"\n{'='*50}")
    print(f"📋 {col.upper()}")
    print('='*50)
    
    value_counts = telco_data[col].value_counts()
    
    print(f"Unique values: {len(value_counts)}")
    print(f"Total non-null: {telco_data[col].count()}")
    print(f"Null values: {telco_data[col].isnull().sum()}")
    
    print(f"\nValue counts:")
    for value, count in value_counts.items():
        percentage = (count / len(telco_data)) * 100
        print(f"  {value:<25}: {count:>6} ({percentage:>5.1f}%)")

print(f"\n{'='*60}")
print("📈 SUMMARY STATISTICS")
print('='*60)
print(f"Total rows: {len(telco_data)}")
print(f"Total object columns: {len(object_columns)}")
print(f"Dataset shape: {telco_data.shape}")

============================================================
📊 VALUE COUNTS FOR OBJECT COLUMNS IN TELCO_CHURN DATASET
============================================================

Found 16 object columns:
Columns: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

==================================================
📋 GENDER
==================================================
Unique values: 2
Total non-null: 7043
Null values: 0

Value counts:
  Male                     :   3555 ( 50.5%)
  Female                   :   3488 ( 49.5%)

==================================================
📋 PARTNER
==================================================
Unique values: 2
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   3641 ( 51.7%)
  Yes                      :   3402 ( 48.3%)

==================================================
📋 DEPENDENTS
==================================================
Unique values: 2
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   4933 ( 70.0%)
  Yes                      :   2110 ( 30.0%)

==================================================
📋 PHONESERVICE
==================================================
Unique values: 2
Total non-null: 7043
Null values: 0

Value counts:
  Yes                      :   6361 ( 90.3%)
  No                       :    682 (  9.7%)

==================================================
📋 MULTIPLELINES
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   3390 ( 48.1%)
  Yes                      :   2971 ( 42.2%)
  No phone service         :    682 (  9.7%)

==================================================
📋 INTERNETSERVICE
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  Fiber optic              :   3096 ( 44.0%)
  DSL                      :   2421 ( 34.4%)
  No                       :   1526 ( 21.7%)

==================================================
📋 ONLINESECURITY
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   3498 ( 49.7%)
  Yes                      :   2019 ( 28.7%)
  No internet service      :   1526 ( 21.7%)

==================================================
📋 ONLINEBACKUP
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   3088 ( 43.8%)
  Yes                      :   2429 ( 34.5%)
  No internet service      :   1526 ( 21.7%)

==================================================
📋 DEVICEPROTECTION
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   3095 ( 43.9%)
  Yes                      :   2422 ( 34.4%)
  No internet service      :   1526 ( 21.7%)

==================================================
📋 TECHSUPPORT
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   3473 ( 49.3%)
  Yes                      :   2044 ( 29.0%)
  No internet service      :   1526 ( 21.7%)

==================================================
📋 STREAMINGTV
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   2810 ( 39.9%)
  Yes                      :   2707 ( 38.4%)
  No internet service      :   1526 ( 21.7%)

==================================================
📋 STREAMINGMOVIES
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   2785 ( 39.5%)
  Yes                      :   2732 ( 38.8%)
  No internet service      :   1526 ( 21.7%)

==================================================
📋 CONTRACT
==================================================
Unique values: 3
Total non-null: 7043
Null values: 0

Value counts:
  Month-to-month           :   3875 ( 55.0%)
  Two year                 :   1695 ( 24.1%)
  One year                 :   1473 ( 20.9%)

==================================================
📋 PAPERLESSBILLING
==================================================
Unique values: 2
Total non-null: 7043
Null values: 0

Value counts:
  Yes                      :   4171 ( 59.2%)
  No                       :   2872 ( 40.8%)

==================================================
📋 PAYMENTMETHOD
==================================================
Unique values: 4
Total non-null: 7043
Null values: 0

Value counts:
  Electronic check         :   2365 ( 33.6%)
  Mailed check             :   1612 ( 22.9%)
  Bank transfer (automatic):   1544 ( 21.9%)
  Credit card (automatic)  :   1522 ( 21.6%)

==================================================
📋 CHURN
==================================================
Unique values: 2
Total non-null: 7043
Null values: 0

Value counts:
  No                       :   5174 ( 73.5%)
  Yes                      :   1869 ( 26.5%)

============================================================
📈 SUMMARY STATISTICS
============================================================
Total rows: 7043
Total object columns: 16
Dataset shape: (7043, 20)

In [69]:
# drop telco_churn dataset
if 'telco_churn' in processed_multiclass_datasets:
    del processed_multiclass_datasets['telco_churn']
    print("Dropped 'telco_churn' dataset from processed datasets.")

Dropped 'telco_churn' dataset from processed datasets.

In [70]:
# drop rocket_league dataset
if 'rocket_league' in processed_multiclass_datasets:
    del processed_multiclass_datasets['rocket_league']
    print("Dropped 'rocket_league' dataset from processed datasets.")

In [71]:
#covertype
if 'covertype' in processed_multiclass_datasets:
    del processed_multiclass_datasets['covertype']
    print("Dropped 'covertype' dataset from processed datasets.")

Dropped 'covertype' dataset from processed datasets.

## Splitting

In [72]:
from sklearn.model_selection import train_test_split
from collections import Counter
import numpy as np

print("="*80)
print("🔀 STRATIFIED DATA SPLITTING - 70% TRAIN, 10% CALIBRATION, 20% TEST")
print("="*80)

# Dictionary to store split datasets
split_datasets = {}
split_info = {}

def stratified_split_three_way(X, y, train_size=0.7, calib_size=0.1, test_size=0.2, random_state=42):
    """
    Split data into train, calibration, and test sets with stratified sampling
    """
    # First split: separate training from (calibration + test)
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, 
        test_size=(calib_size + test_size),
        stratify=y, 
        random_state=random_state
    )
    
    # Second split: separate calibration from test
    # Adjust the test_size for the remaining data
    adjusted_test_size = test_size / (calib_size + test_size)
    
    X_calib, X_test, y_calib, y_test = train_test_split(
        X_temp, y_temp,
        test_size=adjusted_test_size,
        stratify=y_temp,
        random_state=random_state
    )
    
    return X_train, X_calib, X_test, y_train, y_calib, y_test

def analyze_class_distribution(y_train, y_calib, y_test, dataset_name):
    """
    Analyze and display class distribution across splits
    """
    train_dist = Counter(y_train)
    calib_dist = Counter(y_calib) 
    test_dist = Counter(y_test)
    
    print(f"\n📊 Class Distribution for {dataset_name}:")
    print("-" * 60)
    
    # Get all unique classes
    all_classes = sorted(set(list(train_dist.keys()) + list(calib_dist.keys()) + list(test_dist.keys())))
    
    print(f"{'Class':<15} {'Train':<10} {'Calib':<10} {'Test':<10} {'Total':<10}")
    print("-" * 60)
    
    for cls in all_classes:
        train_count = train_dist.get(cls, 0)
        calib_count = calib_dist.get(cls, 0)
        test_count = test_dist.get(cls, 0)
        total_count = train_count + calib_count + test_count
        
        print(f"{str(cls):<15} {train_count:<10} {calib_count:<10} {test_count:<10} {total_count:<10}")
    
    # Calculate percentages
    total_samples = len(y_train) + len(y_calib) + len(y_test)
    train_pct = len(y_train) / total_samples * 100
    calib_pct = len(y_calib) / total_samples * 100
    test_pct = len(y_test) / total_samples * 100
    
    print(f"\n📈 Split Sizes:")
    print(f"Training:   {len(y_train):>6} samples ({train_pct:>5.1f}%)")
    print(f"Calibration:{len(y_calib):>6} samples ({calib_pct:>5.1f}%)")
    print(f"Testing:    {len(y_test):>6} samples ({test_pct:>5.1f}%)")
    print(f"Total:      {total_samples:>6} samples")
    
    return {
        'train_dist': dict(train_dist),
        'calib_dist': dict(calib_dist),
        'test_dist': dict(test_dist),
        'train_size': len(y_train),
        'calib_size': len(y_calib),
        'test_size': len(y_test),
        'train_pct': train_pct,
        'calib_pct': calib_pct,
        'test_pct': test_pct
    }

print("\n🔎 PROCESSING ALL DATASETS...")
print("-" * 60)

================================================================================
🔀 STRATIFIED DATA SPLITTING - 70% TRAIN, 10% CALIBRATION, 20% TEST
================================================================================

🔎 PROCESSING ALL DATASETS...
------------------------------------------------------------

In [73]:
# Process each preprocessed dataset
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, StandardScaler
from sklearn.compose import ColumnTransformer
import numpy as np
import pandas as pd

for dataset_name, df in processed_multiclass_datasets.items():
    print(f"\n{dataset_name.upper().replace('_', ' ')}")
    print("=" * 50)
    
    try:
        # Get target column
        target_col = dataset_info[dataset_name]['target']
        
        # Separate features and target
        X = df.drop(columns=[target_col])
        y = df[target_col]
        
        print(f"Original dataset shape: {df.shape}")
        print(f"Features shape: {X.shape}")
        print(f"Target shape: {y.shape}")
        print(f"Number of classes: {y.nunique()}")
        
        # Identify categorical and numerical columns
        categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
        numerical_cols = X.select_dtypes(include=[np.number]).columns.tolist()
        
        print(f"Categorical columns: {len(categorical_cols)} - {categorical_cols[:3]}..." if len(categorical_cols) > 3 else f"Categorical columns: {categorical_cols}")
        print(f"Numerical columns: {len(numerical_cols)}")
        
        # Create preprocessing pipeline
        if categorical_cols:
            print("🔧 Applying One-Hot Encoding for categorical variables...")
            
            # Create column transformer with corrected OneHotEncoder parameters
            # Remove drop='first' and handle_unknown='ignore' combination which causes conflict
            preprocessor = ColumnTransformer(
                transformers=[
                    ('num', StandardScaler(), numerical_cols),
                    ('cat', OneHotEncoder(sparse=False, handle_unknown='error'), categorical_cols)
                ],
                remainder='passthrough'
            )
            
            # Fit and transform the features
            X_transformed = preprocessor.fit_transform(X)
            
            # Get feature names after transformation
            try:
                # Try new method first (sklearn >= 1.2)
                feature_names = (
                    numerical_cols + 
                    list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols))
                )
            except AttributeError:
                # Fallback for older sklearn versions
                feature_names = (
                    numerical_cols + 
                    [f"{col}_{val}" for col in categorical_cols 
                     for val in preprocessor.named_transformers_['cat'].categories_[categorical_cols.index(col)]]
                )
            
            # Convert back to DataFrame
            X = pd.DataFrame(X_transformed, columns=feature_names, index=X.index)
            
            print(f"✅ After one-hot encoding: {X.shape[1]} features")
            print(f"Features added: {X.shape[1] - len(numerical_cols) - len(categorical_cols)}")
            
        else:
            print("ℹ️  No categorical variables found - applying only numerical scaling...")
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X)
            X = pd.DataFrame(X_scaled, columns=X.columns, index=X.index)
        
        # Check if we have enough samples for stratified splitting
        min_class_count = y.value_counts().min()
        if min_class_count < 10:  # Need at least 10 samples per class for reliable splitting
            print(f"⚠️  Warning: Minimum class count ({min_class_count}) is very small for stratified splitting")
            if min_class_count < 3:
                print(f"❌ Skipping {dataset_name} - insufficient samples per class for 3-way split")
                continue
        
        # Perform stratified 3-way split
        X_train, X_calib, X_test, y_train, y_calib, y_test = stratified_split_three_way(
            X, y, random_state=42
        )
        
        # Store the splits
        split_datasets[dataset_name] = {
            'X_train': X_train,
            'X_calib': X_calib, 
            'X_test': X_test,
            'y_train': y_train,
            'y_calib': y_calib,
            'y_test': y_test,
            'feature_names': list(X.columns),
            'target_name': target_col,
            'original_categorical_cols': categorical_cols,
            'original_numerical_cols': numerical_cols,
            'final_feature_count': X.shape[1]
        }
        
        # Analyze class distribution
        dist_info = analyze_class_distribution(y_train, y_calib, y_test, dataset_name)
        
        # Store split information
        split_info[dataset_name] = dist_info
        
        print(f"✅ Successfully split {dataset_name}")
        print(f"Final feature dimensions: Train {X_train.shape}, Calib {X_calib.shape}, Test {X_test.shape}")
        
    except Exception as e:
        print(f"❌ Error splitting {dataset_name}: {e}")
        import traceback
        print(f"Full error traceback: {traceback.format_exc()}")

print(f"\n" + "="*80)
print(f"📊 SPLITTING SUMMARY: {len(split_datasets)} datasets successfully split")
print("="*80)

# Display preprocessing summary
print(f"\n🔧 PREPROCESSING SUMMARY:")
print("-" * 60)
print(f"{'Dataset':<20} {'Orig_Features':<12} {'Final_Features':<13} {'Categorical':<12} {'Numerical':<10}")
print("-" * 60)

for dataset_name, data_splits in split_datasets.items():
    orig_features = len(data_splits['original_categorical_cols']) + len(data_splits['original_numerical_cols'])
    final_features = data_splits['final_feature_count']
    cat_count = len(data_splits['original_categorical_cols'])
    num_count = len(data_splits['original_numerical_cols'])
    
    print(f"{dataset_name:<20} {orig_features:<12} {final_features:<13} {cat_count:<12} {num_count:<10}")

print("-" * 60)

CAR EVALUATION
==================================================
Original dataset shape: (1728, 7)
Features shape: (1728, 6)
Target shape: (1728,)
Number of classes: 4
Categorical columns: 6 - ['buying', 'maint', 'doors']...
Numerical columns: 0
🔧 Applying One-Hot Encoding for categorical variables...
✅ After one-hot encoding: 21 features
Features added: 15

📊 Class Distribution for car_evaluation:
------------------------------------------------------------
Class           Train      Calib      Test       Total
------------------------------------------------------------
acc             269        38         77         384
good            48         7          14         69
unacc           847        121        242        1210
vgood           45         7          13         65

📈 Split Sizes:
Training:     1209 samples ( 70.0%)
Calibration:   173 samples ( 10.0%)
Testing:       346 samples ( 20.0%)
Total:        1728 samples
✅ Successfully split car_evaluation
Final feature dimensions: Train (1209, 21), Calib (173, 21), Test (346, 21)

DRY BEAN
==================================================
Original dataset shape: (13611, 17)
Features shape: (13611, 16)
Target shape: (13611,)
Number of classes: 7
Categorical columns: []
Numerical columns: 16
ℹ️  No categorical variables found - applying only numerical scaling...

📊 Class Distribution for dry_bean:
------------------------------------------------------------
Class           Train      Calib      Test       Total
------------------------------------------------------------
BARBUNYA        925        132        265        1322
BOMBAY          365        52         105        522
CALI            1141       163        326        1630
DERMASON        2482       354        710        3546
HOROZ           1350       193        385        1928
SEKER           1419       203        405        2027
SIRA            1845       264        527        2636

📈 Split Sizes:
Training:     9527 samples ( 70.0%)
Calibration:  1361 samples ( 10.0%)
Testing:      2723 samples ( 20.0%)
Total:       13611 samples
✅ Successfully split dry_bean
Final feature dimensions: Train (9527, 16), Calib (1361, 16), Test (2723, 16)

NURSERY
==================================================
Original dataset shape: (12960, 9)
Features shape: (12960, 8)
Target shape: (12960,)
Number of classes: 5
Categorical columns: 8 - ['parents', 'has_nurs', 'form']...
Numerical columns: 0
🔧 Applying One-Hot Encoding for categorical variables...
✅ After one-hot encoding: 27 features
Features added: 19
⚠️  Warning: Minimum class count (2) is very small for stratified splitting
❌ Skipping nursery - insufficient samples per class for 3-way split

STUDENT DROPOUT
==================================================
Original dataset shape: (4424, 37)
Features shape: (4424, 36)
Target shape: (4424,)
Number of classes: 3
Categorical columns: []
Numerical columns: 36
ℹ️  No categorical variables found - applying only numerical scaling...

📊 Class Distribution for student_dropout:
------------------------------------------------------------
Class           Train      Calib      Test       Total
------------------------------------------------------------
Dropout         994        142        285        1421
Enrolled        556        79         159        794
Graduate        1546       221        442        2209

📈 Split Sizes:
Training:     3096 samples ( 70.0%)
Calibration:   442 samples ( 10.0%)
Testing:       886 samples ( 20.0%)
Total:        4424 samples
✅ Successfully split student_dropout
Final feature dimensions: Train (3096, 36), Calib (442, 36), Test (886, 36)

CIRRHOSIS
==================================================
Original dataset shape: (418, 20)
Features shape: (418, 19)
Target shape: (418,)
Number of classes: 3
Categorical columns: 6 - ['Drug', 'Sex', 'Ascites']...
Numerical columns: 13
🔧 Applying One-Hot Encoding for categorical variables...
✅ After one-hot encoding: 26 features
Features added: 7

📊 Class Distribution for cirrhosis:
------------------------------------------------------------
Class           Train      Calib      Test       Total
------------------------------------------------------------
C               162        23         47         232
CL              17         3          5          25
D               113        16         32         161

📈 Split Sizes:
Training:      292 samples ( 69.9%)
Calibration:    42 samples ( 10.0%)
Testing:        84 samples ( 20.1%)
Total:         418 samples
✅ Successfully split cirrhosis
Final feature dimensions: Train (292, 26), Calib (42, 26), Test (84, 26)

AIR QUALITY
==================================================
Original dataset shape: (5000, 10)
Features shape: (5000, 9)
Target shape: (5000,)
Number of classes: 4
Categorical columns: []
Numerical columns: 9
ℹ️  No categorical variables found - applying only numerical scaling...

📊 Class Distribution for air_quality:
------------------------------------------------------------
Class           Train      Calib      Test       Total
------------------------------------------------------------
Good            1399       200        401        2000
Hazardous       350        50         100        500
Moderate        1050       150        300        1500
Poor            700        100        200        1000

📈 Split Sizes:
Training:     3499 samples ( 70.0%)
Calibration:   500 samples ( 10.0%)
Testing:      1001 samples ( 20.0%)
Total:        5000 samples
✅ Successfully split air_quality
Final feature dimensions: Train (3499, 9), Calib (500, 9), Test (1001, 9)

================================================================================
📊 SPLITTING SUMMARY: 5 datasets successfully split
================================================================================

🔧 PREPROCESSING SUMMARY:
------------------------------------------------------------
Dataset              Orig_Features Final_Features Categorical  Numerical
------------------------------------------------------------
car_evaluation       6            21            6            0
dry_bean             16           16            0            16
student_dropout      36           36            0            36
cirrhosis            19           26            6            13
air_quality          9            9             0            9
------------------------------------------------------------

In [74]:
# drop convertype dataset

# Fit Model

In [75]:
#check cuda availability
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    print("CUDA is available. Using GPU.")
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Version: {torch.version.cuda}")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
else:
    device = torch.device("cpu")
    print("CUDA is not available. Using CPU.")
    print(f"PyTorch version: {torch.__version__}")

CUDA is not available. Using CPU.
PyTorch version: 1.10.2+cpu

In [76]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import BernoulliNB
#xgboost
from xgboost import XGBClassifier

multiclass_classifiers = {
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
#    'LogisticRegression': LogisticRegression(random_state=42, max_iter=1000, multi_class='multinomial'),
    'AdaBoost': AdaBoostClassifier(random_state=42),
    'NaiveBayes': GaussianNB(),
    #'DecisionTree': DecisionTreeClassifier(random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'XGBoost': XGBClassifier(random_state=42, n_jobs=-1),
    'DecisionTree' : DecisionTreeClassifier(random_state=42),
    'SVC' : SVC(random_state=42, probability=True),
    'ExtraTree' : ExtraTreeClassifier(random_state=42),
    'SGD':SGDClassifier(random_state=42,loss='log'),
    'MLP' : MLPClassifier(random_state=42, max_iter=500),
    'BernoulliNB' : BernoulliNB()
    }

In [77]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import log_loss, accuracy_score
import numpy as np
import pandas as pd
from sklearn.calibration import calibration_curve
import time
import warnings
warnings.filterwarnings('ignore')

# Import ECE from pycalib scoring module
from pycalib.scoring import expected_calibration_error

print("="*80)
print("🤖 FITTING MULTICLASS CLASSIFIERS & CALCULATING ECE + LOG LOSS")
print("="*80)

def encode_target_if_needed(y_train, y_test):
    """
    Encode target variables if they are categorical strings
    """
    # Check if target is string/object type
    if y_train.dtype == 'object' or y_test.dtype == 'object':
        # Create label encoder
        label_encoder = LabelEncoder()
        
        # Fit on combined data to ensure consistency
        combined_labels = pd.concat([y_train, y_test])
        label_encoder.fit(combined_labels)
        
        # Transform both sets
        y_train_encoded = label_encoder.transform(y_train)
        y_test_encoded = label_encoder.transform(y_test)
        
        return y_train_encoded, y_test_encoded, label_encoder
    else:
        return y_train.values, y_test.values, None

# Dictionary to store all results
results = []
detailed_results = {}

print(f"\n🔄 PROCESSING {len(split_datasets)} DATASETS with {len(multiclass_classifiers)} CLASSIFIERS...")
print("-" * 80)

total_combinations = len(split_datasets) * len(multiclass_classifiers)
current_combination = 0

# Process each dataset
for dataset_name, data_splits in split_datasets.items():
    print(f"\n📊 DATASET: {dataset_name.upper().replace('_', ' ')}")
    print("-" * 60)
    
    # Extract splits
    X_train = data_splits['X_train']
    X_test = data_splits['X_test'] 
    y_train = data_splits['y_train']
    y_test = data_splits['y_test']
    
    # Encode target if needed (for string labels)
    y_train_encoded, y_test_encoded, label_encoder = encode_target_if_needed(y_train, y_test)
    
    print(f"Training set: {X_train.shape}, Test set: {X_test.shape}")
    print(f"Classes: {len(np.unique(y_train_encoded))}")
    
    detailed_results[dataset_name] = {}
    
    # Try each classifier
    for clf_name, classifier in multiclass_classifiers.items():
        current_combination += 1
        progress = (current_combination / total_combinations) * 100
        
        print(f"\n🤖 [{progress:5.1f}%] {clf_name}...")
        
        try:
            # Start timing
            start_time = time.time()
            
            # Fit the classifier
            classifier.fit(X_train, y_train_encoded)
            fit_time = time.time() - start_time
            
            # Predict probabilities on test set
            start_pred_time = time.time()
            y_pred_proba = classifier.predict_proba(X_test)
            pred_time = time.time() - start_pred_time
            
            # Get hard predictions
            y_pred = classifier.predict(X_test)
            
            # Calculate metrics
            accuracy = accuracy_score(y_test_encoded, y_pred)
            
            # Calculate log loss
            try:
                logloss = log_loss(y_test_encoded, y_pred_proba)
            except Exception as e:
                print(f"    ⚠️  Log loss calculation failed: {e}")
                logloss = np.nan
            
            # Calculate ECE using pycalib scoring module
            try:
                # Use the expected_calibration_error function from pycalib.scoring
                ece = expected_calibration_error(y_test_encoded, y_pred_proba, n_bins=10)
            except Exception as e:
                print(f"    ⚠️  ECE calculation failed: {e}")
                ece = np.nan
            
            # Store results
            result = {
                'Dataset': dataset_name,
                'Classifier': clf_name,
                'Accuracy': accuracy,
                'ECE': ece,
                'LogLoss': logloss,
                'FitTime': fit_time,
                'PredTime': pred_time,
                'TrainSamples': len(X_train),
                'TestSamples': len(X_test),
                'NumClasses': len(np.unique(y_train_encoded)),
                'NumFeatures': X_train.shape[1]
            }
            
            results.append(result)
            detailed_results[dataset_name][clf_name] = result
            
            print(f"    ✅ Accuracy: {accuracy:.4f}, ECE: {ece:.4f}, LogLoss: {logloss:.4f}")
            print(f"    ⏱️  Fit: {fit_time:.2f}s, Predict: {pred_time:.3f}s")
            
        except Exception as e:
            print(f"    ❌ Error with {clf_name}: {e}")
            
            # Store error result
            error_result = {
                'Dataset': dataset_name,
                'Classifier': clf_name,
                'Accuracy': np.nan,
                'ECE': np.nan,
                'LogLoss': np.nan,
                'FitTime': np.nan,
                'PredTime': np.nan,
                'TrainSamples': len(X_train),
                'TestSamples': len(X_test),
                'NumClasses': len(np.unique(y_train_encoded)),
                'NumFeatures': X_train.shape[1],
                'Error': str(e)
            }
            results.append(error_result)

print(f"\n" + "="*80)
print(f"✅ COMPLETED: {len(results)} classifier-dataset combinations processed")
print("="*80)

================================================================================
🤖 FITTING MULTICLASS CLASSIFIERS & CALCULATING ECE + LOG LOSS
================================================================================

🔄 PROCESSING 5 DATASETS with 11 CLASSIFIERS...
--------------------------------------------------------------------------------

📊 DATASET: CAR EVALUATION
------------------------------------------------------------
Training set: (1209, 21), Test set: (346, 21)
Classes: 4

🤖 [  1.8%] RandomForest...
    ✅ Accuracy: 0.9798, ECE: 0.1291, LogLoss: 0.1691
    ⏱️  Fit: 0.27s, Predict: 0.123s

🤖 [  3.6%] AdaBoost...
    ✅ Accuracy: 0.7919, ECE: 0.1006, LogLoss: 0.5450
    ⏱️  Fit: 0.11s, Predict: 0.018s

🤖 [  5.5%] NaiveBayes...
    ✅ Accuracy: 0.7977, ECE: 0.0333, LogLoss: 4.8376
    ⏱️  Fit: 0.02s, Predict: 0.002s

🤖 [  7.3%] KNN...
    ✅ Accuracy: 0.8931, ECE: 0.1061, LogLoss: 0.4035
    ⏱️  Fit: 0.00s, Predict: 0.020s

🤖 [  9.1%] XGBoost...
[14:28:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ Accuracy: 0.9942, ECE: 0.0586, LogLoss: 0.0310
    ⏱️  Fit: 0.51s, Predict: 0.006s

🤖 [ 10.9%] DecisionTree...
    ✅ Accuracy: 0.9711, ECE: 0.0211, LogLoss: 0.9982
    ⏱️  Fit: 0.01s, Predict: 0.002s

🤖 [ 12.7%] SVC...
    ✅ Accuracy: 0.9740, ECE: 0.0507, LogLoss: 0.0562
    ⏱️  Fit: 0.32s, Predict: 0.026s

🤖 [ 14.5%] ExtraTree...
    ✅ Accuracy: 0.8844, ECE: 0.0656, LogLoss: 3.9929
    ⏱️  Fit: 0.00s, Predict: 0.005s

🤖 [ 16.4%] SGD...
    ✅ Accuracy: 0.9104, ECE: 0.0790, LogLoss: 0.2169
    ⏱️  Fit: 0.03s, Predict: 0.009s

🤖 [ 18.2%] MLP...
    ✅ Accuracy: 0.9913, ECE: 0.0568, LogLoss: 0.0332
    ⏱️  Fit: 3.91s, Predict: 0.007s

🤖 [ 20.0%] BernoulliNB...
    ✅ Accuracy: 0.8728, ECE: 0.0923, LogLoss: 0.2792
    ⏱️  Fit: 0.00s, Predict: 0.004s

📊 DATASET: DRY BEAN
------------------------------------------------------------
Training set: (9527, 16), Test set: (2723, 16)
Classes: 7

🤖 [ 21.8%] RandomForest...
    ✅ Accuracy: 0.9177, ECE: 0.0316, LogLoss: 0.3954
    ⏱️  Fit: 0.59s, Predict: 0.119s

🤖 [ 23.6%] AdaBoost...
    ✅ Accuracy: 0.4679, ECE: 0.2159, LogLoss: 1.7752
    ⏱️  Fit: 1.71s, Predict: 0.044s

🤖 [ 25.5%] NaiveBayes...
    ✅ Accuracy: 0.8924, ECE: 0.0692, LogLoss: 0.9678
    ⏱️  Fit: 0.01s, Predict: 0.003s

🤖 [ 27.3%] KNN...
    ✅ Accuracy: 0.9130, ECE: 0.0287, LogLoss: 0.9623
    ⏱️  Fit: 0.00s, Predict: 0.824s

🤖 [ 29.1%] XGBoost...
[14:28:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ Accuracy: 0.9170, ECE: 0.0284, LogLoss: 0.2727
    ⏱️  Fit: 3.45s, Predict: 0.023s

🤖 [ 30.9%] DecisionTree...
    ✅ Accuracy: 0.8902, ECE: 0.0598, LogLoss: 3.7925
    ⏱️  Fit: 0.32s, Predict: 0.000s

🤖 [ 32.7%] SVC...
    ✅ Accuracy: 0.9240, ECE: 0.0355, LogLoss: 0.2125
    ⏱️  Fit: 3.85s, Predict: 0.579s

🤖 [ 34.5%] ExtraTree...
    ✅ Accuracy: 0.8806, ECE: 0.0694, LogLoss: 4.1223
    ⏱️  Fit: 0.01s, Predict: 0.000s

🤖 [ 36.4%] SGD...
    ✅ Accuracy: 0.9097, ECE: 0.0538, LogLoss: 0.2563
    ⏱️  Fit: 0.16s, Predict: 0.000s

🤖 [ 38.2%] MLP...
    ✅ Accuracy: 0.9232, ECE: 0.0333, LogLoss: 0.2143
    ⏱️  Fit: 19.15s, Predict: 0.006s

🤖 [ 40.0%] BernoulliNB...
    ✅ Accuracy: 0.7150, ECE: 0.1397, LogLoss: 1.1424
    ⏱️  Fit: 0.01s, Predict: 0.007s

📊 DATASET: STUDENT DROPOUT
------------------------------------------------------------
Training set: (3096, 36), Test set: (886, 36)
Classes: 3

🤖 [ 41.8%] RandomForest...
    ✅ Accuracy: 0.7856, ECE: 0.0786, LogLoss: 0.6187
    ⏱️  Fit: 0.39s, Predict: 0.114s

🤖 [ 43.6%] AdaBoost...
    ✅ Accuracy: 0.7664, ECE: 0.3805, LogLoss: 1.0561
    ⏱️  Fit: 0.35s, Predict: 0.014s

🤖 [ 45.5%] NaiveBayes...
    ✅ Accuracy: 0.6840, ECE: 0.2014, LogLoss: 2.6933
    ⏱️  Fit: 0.01s, Predict: 0.003s

🤖 [ 47.3%] KNN...
    ✅ Accuracy: 0.6840, ECE: 0.0447, LogLoss: 3.1689
    ⏱️  Fit: 0.01s, Predict: 0.067s

🤖 [ 49.1%] XGBoost...
[14:29:18] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ Accuracy: 0.7765, ECE: 0.0703, LogLoss: 0.6116
    ⏱️  Fit: 0.78s, Predict: 0.009s

🤖 [ 50.9%] DecisionTree...
    ✅ Accuracy: 0.7122, ECE: 0.2378, LogLoss: 9.9406
    ⏱️  Fit: 0.05s, Predict: 0.004s

🤖 [ 52.7%] SVC...
    ✅ Accuracy: 0.7686, ECE: 0.0470, LogLoss: 0.5922
    ⏱️  Fit: 2.34s, Predict: 0.171s

🤖 [ 54.5%] ExtraTree...
    ✅ Accuracy: 0.6546, ECE: 0.2954, LogLoss: 11.9287
    ⏱️  Fit: 0.01s, Predict: 0.006s

🤖 [ 56.4%] SGD...
    ✅ Accuracy: 0.7551, ECE: 0.0277, LogLoss: 0.6788
    ⏱️  Fit: 0.14s, Predict: 0.022s

🤖 [ 58.2%] MLP...
    ✅ Accuracy: 0.7156, ECE: 0.1619, LogLoss: 1.4514
    ⏱️  Fit: 13.19s, Predict: 0.003s

🤖 [ 60.0%] BernoulliNB...
    ✅ Accuracy: 0.7404, ECE: 0.0945, LogLoss: 0.8490
    ⏱️  Fit: 0.00s, Predict: 0.000s

📊 DATASET: CIRRHOSIS
------------------------------------------------------------
Training set: (292, 26), Test set: (84, 26)
Classes: 3

🤖 [ 61.8%] RandomForest...
    ✅ Accuracy: 0.7619, ECE: 0.1099, LogLoss: 0.6345
    ⏱️  Fit: 0.28s, Predict: 0.123s

🤖 [ 63.6%] AdaBoost...
    ✅ Accuracy: 0.7619, ECE: 0.1979, LogLoss: 0.7679
    ⏱️  Fit: 0.10s, Predict: 0.011s

🤖 [ 65.5%] NaiveBayes...
    ✅ Accuracy: 0.2143, ECE: 0.7226, LogLoss: 11.1010
    ⏱️  Fit: 0.01s, Predict: 0.000s

🤖 [ 67.3%] KNN...
    ✅ Accuracy: 0.6667, ECE: 0.1165, LogLoss: 4.5147
    ⏱️  Fit: 0.01s, Predict: 0.004s

🤖 [ 69.1%] XGBoost...
[14:29:36] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ Accuracy: 0.7500, ECE: 0.1438, LogLoss: 0.9150
    ⏱️  Fit: 0.23s, Predict: 0.007s

🤖 [ 70.9%] DecisionTree...
    ✅ Accuracy: 0.6905, ECE: 0.2595, LogLoss: 10.6906
    ⏱️  Fit: 0.00s, Predict: 0.002s

🤖 [ 72.7%] SVC...
    ✅ Accuracy: 0.7262, ECE: 0.0723, LogLoss: 0.6449
    ⏱️  Fit: 0.03s, Predict: 0.006s

🤖 [ 74.5%] ExtraTree...
    ✅ Accuracy: 0.6071, ECE: 0.3429, LogLoss: 13.5688
    ⏱️  Fit: 0.00s, Predict: 0.002s

🤖 [ 76.4%] SGD...
    ✅ Accuracy: 0.7976, ECE: 0.1674, LogLoss: 1.7397
    ⏱️  Fit: 0.01s, Predict: 0.002s

🤖 [ 78.2%] MLP...
    ✅ Accuracy: 0.6905, ECE: 0.1838, LogLoss: 1.0871
    ⏱️  Fit: 1.26s, Predict: 0.004s

🤖 [ 80.0%] BernoulliNB...
    ✅ Accuracy: 0.6071, ECE: 0.2625, LogLoss: 1.1268
    ⏱️  Fit: 0.00s, Predict: 0.007s

📊 DATASET: AIR QUALITY
------------------------------------------------------------
Training set: (3499, 9), Test set: (1001, 9)
Classes: 4

🤖 [ 81.8%] RandomForest...
    ✅ Accuracy: 0.9530, ECE: 0.0647, LogLoss: 0.1395
    ⏱️  Fit: 0.28s, Predict: 0.122s

🤖 [ 83.6%] AdaBoost...
    ✅ Accuracy: 0.6144, ECE: 0.4355, LogLoss: 1.3139
    ⏱️  Fit: 0.29s, Predict: 0.020s

🤖 [ 85.5%] NaiveBayes...
    ✅ Accuracy: 0.9201, ECE: 0.0271, LogLoss: 0.3399
    ⏱️  Fit: 0.00s, Predict: 0.000s

🤖 [ 87.3%] KNN...
    ✅ Accuracy: 0.9351, ECE: 0.0393, LogLoss: 0.7026
    ⏱️  Fit: 0.04s, Predict: 0.029s

🤖 [ 89.1%] XGBoost...
[14:29:39] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ Accuracy: 0.9530, ECE: 0.0334, LogLoss: 0.1556
    ⏱️  Fit: 0.71s, Predict: 0.007s

🤖 [ 90.9%] DecisionTree...
    ✅ Accuracy: 0.9111, ECE: 0.0389, LogLoss: 3.0709
    ⏱️  Fit: 0.03s, Predict: 0.002s

🤖 [ 92.7%] SVC...
    ✅ Accuracy: 0.9411, ECE: 0.0382, LogLoss: 0.1533
    ⏱️  Fit: 0.52s, Predict: 0.079s

🤖 [ 94.5%] ExtraTree...
    ✅ Accuracy: 0.8701, ECE: 0.0799, LogLoss: 4.4856
    ⏱️  Fit: 0.01s, Predict: 0.006s

🤖 [ 96.4%] SGD...
    ✅ Accuracy: 0.8362, ECE: 0.1326, LogLoss: 0.5357
    ⏱️  Fit: 0.08s, Predict: 0.004s

🤖 [ 98.2%] MLP...
    ✅ Accuracy: 0.9510, ECE: 0.0283, LogLoss: 0.1466
    ⏱️  Fit: 8.16s, Predict: 0.004s

🤖 [100.0%] BernoulliNB...
    ✅ Accuracy: 0.8252, ECE: 0.0357, LogLoss: 0.3893
    ⏱️  Fit: 0.00s, Predict: 0.005s

================================================================================
✅ COMPLETED: 55 classifier-dataset combinations processed
================================================================================

In [80]:
# Create comprehensive results DataFrame
results_df = pd.DataFrame(results)

print("="*80)
print("📊 COMPREHENSIVE RESULTS SUMMARY")
print("="*80)

# Summary table with Dataset, ECE, LogLoss as requested
print("\n📋 SUMMARY TABLE: Dataset, ECE, LogLoss")
print("-" * 70)

# Create summary by dataset (average across all classifiers)
summary_by_dataset = results_df.groupby('Dataset').agg({
    'ECE': ['mean', 'std', 'min', 'max'],
    'LogLoss': ['mean', 'std', 'min', 'max'],
    'Accuracy': ['mean', 'std', 'min', 'max']
}).round(4)

print(f"{'Dataset':<20} {'ECE_Mean':<10} {'ECE_Std':<10} {'LogLoss_Mean':<12} {'LogLoss_Std':<12}")
print("-" * 70)

for dataset in summary_by_dataset.index:
    ece_mean = summary_by_dataset.loc[dataset, ('ECE', 'mean')]
    ece_std = summary_by_dataset.loc[dataset, ('ECE', 'std')]
    logloss_mean = summary_by_dataset.loc[dataset, ('LogLoss', 'mean')]
    logloss_std = summary_by_dataset.loc[dataset, ('LogLoss', 'std')]
    
    print(f"{dataset:<20} {ece_mean:<10.4f} {ece_std:<10.4f} {logloss_mean:<12.4f} {logloss_std:<12.4f}")

# Detailed results table
print(f"\n📋 DETAILED RESULTS TABLE")
print("-" * 100)
print(f"{'Dataset':<15} {'Classifier':<15} {'Accuracy':<10} {'ECE':<8} {'LogLoss':<10} {'FitTime':<8} {'PredTime':<8}")
print("-" * 100)

for _, row in results_df.iterrows():
    print(f"{row['Dataset']:<15} {row['Classifier']:<15} {row['Accuracy']:<10.4f} {row['ECE']:<8.4f} {row['LogLoss']:<10.4f} {row['FitTime']:<8.2f} {row['PredTime']:<8.3f}")

# Best and worst performers
print(f"\n🏆 BEST PERFORMERS")
print("-" * 50)

# Best ECE (lowest is better)
best_ece = results_df.loc[results_df['ECE'].idxmin()]
print(f"Best ECE: {best_ece['Dataset']} + {best_ece['Classifier']} = {best_ece['ECE']:.4f}")

# Best LogLoss (lowest is better) 
best_logloss = results_df.loc[results_df['LogLoss'].idxmin()]
print(f"Best LogLoss: {best_logloss['Dataset']} + {best_logloss['Classifier']} = {best_logloss['LogLoss']:.4f}")

# Best Accuracy (highest is better)
best_accuracy = results_df.loc[results_df['Accuracy'].idxmax()]
print(f"Best Accuracy: {best_accuracy['Dataset']} + {best_accuracy['Classifier']} = {best_accuracy['Accuracy']:.4f}")

print(f"\n📉 WORST PERFORMERS")
print("-" * 50)

# Worst ECE (highest is worst)
worst_ece = results_df.loc[results_df['ECE'].idxmax()]
print(f"Worst ECE: {worst_ece['Dataset']} + {worst_ece['Classifier']} = {worst_ece['ECE']:.4f}")

# Worst LogLoss (highest is worst)
worst_logloss = results_df.loc[results_df['LogLoss'].idxmax()]
print(f"Worst LogLoss: {worst_logloss['Dataset']} + {worst_logloss['Classifier']} = {worst_logloss['LogLoss']:.4f}")

# Performance statistics
print(f"\n📈 OVERALL STATISTICS")
print("-" * 40)
print(f"Mean ECE across all combinations: {results_df['ECE'].mean():.4f} ± {results_df['ECE'].std():.4f}")
print(f"Mean LogLoss across all combinations: {results_df['LogLoss'].mean():.4f} ± {results_df['LogLoss'].std():.4f}")
print(f"Mean Accuracy across all combinations: {results_df['Accuracy'].mean():.4f} ± {results_df['Accuracy'].std():.4f}")

print(f"\n💾 RESULTS SAVED IN VARIABLES:")
print("-" * 40)
print("- results_df: Complete DataFrame with all results")
print("- summary_by_dataset: Summary statistics by dataset")
print("- detailed_results: Dictionary with nested results")

print(f"\n🎯 ANALYSIS COMPLETE!")
print("="*80)

================================================================================
📊 COMPREHENSIVE RESULTS SUMMARY
================================================================================

📋 SUMMARY TABLE: Dataset, ECE, LogLoss
----------------------------------------------------------------------
Dataset              ECE_Mean   ECE_Std    LogLoss_Mean LogLoss_Std
----------------------------------------------------------------------
air_quality          0.0867     0.1198     1.0394       1.4328
car_evaluation       0.0721     0.0327     1.0512       1.6972
cirrhosis            0.2345     0.1799     4.2537       5.0070
dry_bean             0.0696     0.0583     1.2831       1.4133
student_dropout      0.1491     0.1166     3.0536       4.0168

📋 DETAILED RESULTS TABLE
----------------------------------------------------------------------------------------------------
Dataset         Classifier      Accuracy   ECE      LogLoss    FitTime  PredTime
----------------------------------------------------------------------------------------------------
car_evaluation  RandomForest    0.9798     0.1291   0.1691     0.27     0.123
car_evaluation  AdaBoost        0.7919     0.1006   0.5450     0.11     0.018
car_evaluation  NaiveBayes      0.7977     0.0333   4.8376     0.02     0.002
car_evaluation  KNN             0.8931     0.1061   0.4035     0.00     0.020
car_evaluation  XGBoost         0.9942     0.0586   0.0310     0.51     0.006
car_evaluation  DecisionTree    0.9711     0.0211   0.9982     0.01     0.002
car_evaluation  SVC             0.9740     0.0507   0.0562     0.32     0.026
car_evaluation  ExtraTree       0.8844     0.0656   3.9929     0.00     0.005
car_evaluation  SGD             0.9104     0.0790   0.2169     0.03     0.009
car_evaluation  MLP             0.9913     0.0568   0.0332     3.91     0.007
car_evaluation  BernoulliNB     0.8728     0.0923   0.2792     0.00     0.004
dry_bean        RandomForest    0.9177     0.0316   0.3954     0.59     0.119
dry_bean        AdaBoost        0.4679     0.2159   1.7752     1.71     0.044
dry_bean        NaiveBayes      0.8924     0.0692   0.9678     0.01     0.003
dry_bean        KNN             0.9130     0.0287   0.9623     0.00     0.824
dry_bean        XGBoost         0.9170     0.0284   0.2727     3.45     0.023
dry_bean        DecisionTree    0.8902     0.0598   3.7925     0.32     0.000
dry_bean        SVC             0.9240     0.0355   0.2125     3.85     0.579
dry_bean        ExtraTree       0.8806     0.0694   4.1223     0.01     0.000
dry_bean        SGD             0.9097     0.0538   0.2563     0.16     0.000
dry_bean        MLP             0.9232     0.0333   0.2143     19.15    0.006
dry_bean        BernoulliNB     0.7150     0.1397   1.1424     0.01     0.007
student_dropout RandomForest    0.7856     0.0786   0.6187     0.39     0.114
student_dropout AdaBoost        0.7664     0.3805   1.0561     0.35     0.014
student_dropout NaiveBayes      0.6840     0.2014   2.6933     0.01     0.003
student_dropout KNN             0.6840     0.0447   3.1689     0.01     0.067
student_dropout XGBoost         0.7765     0.0703   0.6116     0.78     0.009
student_dropout DecisionTree    0.7122     0.2378   9.9406     0.05     0.004
student_dropout SVC             0.7686     0.0470   0.5922     2.34     0.171
student_dropout ExtraTree       0.6546     0.2954   11.9287    0.01     0.006
student_dropout SGD             0.7551     0.0277   0.6788     0.14     0.022
student_dropout MLP             0.7156     0.1619   1.4514     13.19    0.003
student_dropout BernoulliNB     0.7404     0.0945   0.8490     0.00     0.000
cirrhosis       RandomForest    0.7619     0.1099   0.6345     0.28     0.123
cirrhosis       AdaBoost        0.7619     0.1979   0.7679     0.10     0.011
cirrhosis       NaiveBayes      0.2143     0.7226   11.1010    0.01     0.000
cirrhosis       KNN             0.6667     0.1165   4.5147     0.01     0.004
cirrhosis       XGBoost         0.7500     0.1438   0.9150     0.23     0.007
cirrhosis       DecisionTree    0.6905     0.2595   10.6906    0.00     0.002
cirrhosis       SVC             0.7262     0.0723   0.6449     0.03     0.006
cirrhosis       ExtraTree       0.6071     0.3429   13.5688    0.00     0.002
cirrhosis       SGD             0.7976     0.1674   1.7397     0.01     0.002
cirrhosis       MLP             0.6905     0.1838   1.0871     1.26     0.004
cirrhosis       BernoulliNB     0.6071     0.2625   1.1268     0.00     0.007
air_quality     RandomForest    0.9530     0.0647   0.1395     0.28     0.122
air_quality     AdaBoost        0.6144     0.4355   1.3139     0.29     0.020
air_quality     NaiveBayes      0.9201     0.0271   0.3399     0.00     0.000
air_quality     KNN             0.9351     0.0393   0.7026     0.04     0.029
air_quality     XGBoost         0.9530     0.0334   0.1556     0.71     0.007
air_quality     DecisionTree    0.9111     0.0389   3.0709     0.03     0.002
air_quality     SVC             0.9411     0.0382   0.1533     0.52     0.079
air_quality     ExtraTree       0.8701     0.0799   4.4856     0.01     0.006
air_quality     SGD             0.8362     0.1326   0.5357     0.08     0.004
air_quality     MLP             0.9510     0.0283   0.1466     8.16     0.004
air_quality     BernoulliNB     0.8252     0.0357   0.3893     0.00     0.005

🏆 BEST PERFORMERS
--------------------------------------------------
Best ECE: car_evaluation + DecisionTree = 0.0211
Best LogLoss: car_evaluation + XGBoost = 0.0310
Best Accuracy: car_evaluation + XGBoost = 0.9942

📉 WORST PERFORMERS
--------------------------------------------------
Worst ECE: cirrhosis + NaiveBayes = 0.7226
Worst LogLoss: cirrhosis + ExtraTree = 13.5688

📈 OVERALL STATISTICS
----------------------------------------
Mean ECE across all combinations: 0.1224 ± 0.1267
Mean LogLoss across all combinations: 2.1362 ± 3.2607
Mean Accuracy across all combinations: 0.8080 ± 0.1451

💾 RESULTS SAVED IN VARIABLES:
----------------------------------------
- results_df: Complete DataFrame with all results
- summary_by_dataset: Summary statistics by dataset
- detailed_results: Dictionary with nested results

🎯 ANALYSIS COMPLETE!
================================================================================

In [81]:
# Create the exact summary table requested: Dataset, ECE, LogLoss
print("="*60)
print("📊 REQUESTED SUMMARY TABLE: Dataset | ECE | LogLoss")
print("="*60)

# Calculate mean ECE and LogLoss per dataset
summary_table = results_df.groupby('Dataset').agg({
    'ECE': 'mean',
    'LogLoss': 'mean'
}).round(4)

# Reset index to make Dataset a column
summary_table = summary_table.reset_index()

# Display the table
print(f"{'Dataset':<25} {'ECE':<15} {'LogLoss':<15}")
print("-" * 60)

for _, row in summary_table.iterrows():
    print(f"{row['Dataset']:<25} {row['ECE']:<15.4f} {row['LogLoss']:<15.4f}")

print("-" * 60)
print(f"{'OVERALL MEAN':<25} {summary_table['ECE'].mean():<15.4f} {summary_table['LogLoss'].mean():<15.4f}")

# Save this as a clean DataFrame for export
final_summary_df = summary_table.copy()
final_summary_df.columns = ['Dataset', 'ECE', 'LogLoss']

print(f"\n💾 Clean summary saved as 'final_summary_df'")
print("Columns: Dataset, ECE, LogLoss")
print(f"Shape: {final_summary_df.shape}")

# Show the DataFrame
print(f"\nDataFrame Preview:")
print(final_summary_df)

============================================================
📊 REQUESTED SUMMARY TABLE: Dataset | ECE | LogLoss
============================================================
Dataset                   ECE             LogLoss
------------------------------------------------------------
air_quality               0.0867          1.0394
car_evaluation            0.0721          1.0512
cirrhosis                 0.2345          4.2537
dry_bean                  0.0696          1.2831
student_dropout           0.1491          3.0536
------------------------------------------------------------
OVERALL MEAN              0.1224          2.1362

💾 Clean summary saved as 'final_summary_df'
Columns: Dataset, ECE, LogLoss
Shape: (5, 3)

DataFrame Preview:
           Dataset     ECE  LogLoss
0      air_quality  0.0867   1.0394
1   car_evaluation  0.0721   1.0512
2        cirrhosis  0.2345   4.2537
3         dry_bean  0.0696   1.2831
4  student_dropout  0.1491   3.0536

# Perform Calibration

In [82]:
# Import calibration methods from pycalib
from pycalib.calibration_methods import (
    PlattScaling, 
    IsotonicRegression, 
    GPCalibration
)
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import log_loss, accuracy_score
import numpy as np
import pandas as pd
import time
import warnings
warnings.filterwarnings('ignore')

# Import ECE from pycalib scoring module
from pycalib.scoring import expected_calibration_error

print("="*80)
print("🔧 PERFORMING CALIBRATION ON ALL MULTICLASS CLASSIFIERS")
print("="*80)

# First, let's fix the XGBoost issue by ensuring proper num_class parameter
def fix_xgboost_multiclass(n_classes):
    """Create XGBoost classifier with proper multiclass configuration"""
    if n_classes <= 2:
        return XGBClassifier(
            random_state=42, 
            n_jobs=-1,
            objective='binary:logistic'
        )
    else:
        return XGBClassifier(
            random_state=42, 
            n_jobs=-1,
            objective='multi:softprob',
            num_class=n_classes
        )

# Dictionary of calibration methods to test
calibration_methods = {
    'Uncalibrated': None,  # No calibration baseline
    'PlattScaling': PlattScaling(random_state=42),
    #'IsotonicRegression': IsotonicRegression(out_of_bounds='raise'),
    'IsotonicRegression': IsotonicRegression(),
    'GPCalibration': GPCalibration(n_classes=None, maxiter=500, n_inducing_points=10, verbose=False)
}

def encode_target_if_needed_calib(y_train, y_calib, y_test):
    """
    Encode target variables if they are categorical strings for calibration
    """
    if y_train.dtype == 'object' or y_calib.dtype == 'object' or y_test.dtype == 'object':
        # Create label encoder
        label_encoder = LabelEncoder()
        
        # Fit on combined data to ensure consistency
        combined_labels = pd.concat([y_train, y_calib, y_test])
        label_encoder.fit(combined_labels)
        
        # Transform all sets
        y_train_encoded = label_encoder.transform(y_train)
        y_calib_encoded = label_encoder.transform(y_calib)
        y_test_encoded = label_encoder.transform(y_test)
        
        return y_train_encoded, y_calib_encoded, y_test_encoded, label_encoder
    else:
        return y_train.values, y_calib.values, y_test.values, None

def ensure_float64_dtype(probabilities, targets):
    """
    Ensure consistent float64 dtype for GPCalibration compatibility
    """
    # Convert probabilities to float64
    if hasattr(probabilities, 'astype'):
        probabilities = probabilities.astype(np.float64)
    else:
        probabilities = np.array(probabilities, dtype=np.float64)
    
    # Convert targets to int64 (standard for labels)
    if hasattr(targets, 'astype'):
        targets = targets.astype(np.int64)
    else:
        targets = np.array(targets, dtype=np.int64)
    
    return probabilities, targets

# Store calibration results
calibration_results = []
detailed_calibration_results = {}

total_combinations = len(split_datasets) * len(multiclass_classifiers) * len(calibration_methods)
current_combination = 0

print(f"\n🔄 PROCESSING {len(split_datasets)} DATASETS with {len(multiclass_classifiers)} CLASSIFIERS and {len(calibration_methods)} CALIBRATION METHODS...")
print(f"📊 Total combinations: {total_combinations}")
print("-" * 80)

# Process each dataset
for dataset_name, data_splits in split_datasets.items():
    print(f"\n📊 DATASET: {dataset_name.upper().replace('_', ' ')}")
    print("-" * 60)
    
    # Extract all splits (now we use calibration data)
    X_train = data_splits['X_train']
    X_calib = data_splits['X_calib']
    X_test = data_splits['X_test']
    y_train = data_splits['y_train']
    y_calib = data_splits['y_calib']
    y_test = data_splits['y_test']
    
    # Encode target if needed
    y_train_encoded, y_calib_encoded, y_test_encoded, label_encoder = encode_target_if_needed_calib(
        y_train, y_calib, y_test
    )
    
    n_classes = len(np.unique(y_train_encoded))
    print(f"Training set: {X_train.shape}, Calibration set: {X_calib.shape}, Test set: {X_test.shape}")
    print(f"Number of classes: {n_classes}")
    
    detailed_calibration_results[dataset_name] = {}
    
    # Process each classifier from multiclass_classifiers
    for clf_name, base_classifier in multiclass_classifiers.items():
        print(f"\n🤖 Processing {clf_name} classifier...")
        print("-" * 50)
        
        try:
            # Create a fresh copy of the classifier for each dataset
            if clf_name == 'XGBoost':
                # Use the fixed XGBoost configuration
                classifier = fix_xgboost_multiclass(n_classes)
            else:
                # Create a copy of the original classifier to avoid fitting conflicts
                from sklearn.base import clone
                classifier = clone(base_classifier)
                
                # For sklearn classifiers, ensure they support multiclass
                if hasattr(classifier, 'set_params'):
                    if clf_name == 'LogisticRegression':
                        classifier.set_params(multi_class='multinomial')
            
            print(f"    🏋️  Training {clf_name} base classifier...")
            
            # Train the base classifier
            start_time = time.time()
            classifier.fit(X_train, y_train_encoded)
            fit_time = time.time() - start_time
            
            # Get uncalibrated predictions on calibration and test sets
            start_pred_time = time.time()
            y_calib_proba_uncal = classifier.predict_proba(X_calib)
            y_test_proba_uncal = classifier.predict_proba(X_test)
            pred_time = time.time() - start_pred_time
            
            # Ensure consistent dtypes for calibration (especially for GPCalibration)
            y_calib_proba_uncal, y_calib_encoded_safe = ensure_float64_dtype(y_calib_proba_uncal, y_calib_encoded)
            y_test_proba_uncal, y_test_encoded_safe = ensure_float64_dtype(y_test_proba_uncal, y_test_encoded)
            
            print(f"    ✅ {clf_name} base classifier trained successfully")
            print(f"    ⏱️  Fit: {fit_time:.2f}s, Predict: {pred_time:.3f}s")
            print(f"    📊 Uncalibrated probabilities shape: {y_test_proba_uncal.shape}")
            print(f"    🔧 Data types - Proba: {y_test_proba_uncal.dtype}, Labels: {y_test_encoded_safe.dtype}")
            
            # Initialize classifier results storage
            detailed_calibration_results[dataset_name][clf_name] = {}
            
            # Now test each calibration method for this classifier
            for calib_name, calib_method in calibration_methods.items():
                current_combination += 1
                progress = (current_combination / total_combinations) * 100
                
                print(f"\n    🔧 [{progress:5.1f}%] Testing calibration method: {calib_name} on {clf_name}")
                
                try:
                    if calib_name == 'Uncalibrated':
                        # No calibration - use uncalibrated predictions
                        y_test_proba_cal = y_test_proba_uncal
                        calib_fit_time = 0.0
                        calib_pred_time = 0.0
                        
                    else:
                        # Configure GPCalibration with correct n_classes and handle dtype issues
                        if calib_name == 'GPCalibration':
                            calib_method = GPCalibration(
                                n_classes=n_classes, 
                                maxiter=200,  # Reduced iterations for faster training
                                n_inducing_points=min(12, len(X_calib)//3),  # Fewer inducing points
                                verbose=False,
                                random_state=42,
                                kernel= 'rbf',
                                add_white_noise=True
                            )
                            
                            # Ensure we have enough calibration samples for GP
                            if len(X_calib) < 20:
                                print(f"        ⚠️  Skipping GPCalibration - insufficient calibration samples ({len(X_calib)})")
                                continue
                        
                        # Fit calibration method on calibration data
                        start_calib_fit = time.time()
                        
                        # Additional safety check for GPCalibration
                        if calib_name == 'GPCalibration':
                            # Ensure data is in the right format and dtype
                            calib_proba_safe = np.array(y_calib_proba_uncal, dtype=np.float64)
                            calib_labels_safe = np.array(y_calib_encoded_safe, dtype=np.int64)
                            
                            print(f"        🔧 GP input shapes: proba {calib_proba_safe.shape}, labels {calib_labels_safe.shape}")
                            print(f"        🔧 GP input dtypes: proba {calib_proba_safe.dtype}, labels {calib_labels_safe.dtype}")
                            
                            calib_method.fit(calib_proba_safe, calib_labels_safe)
                        else:
                            calib_method.fit(y_calib_proba_uncal, y_calib_encoded_safe)
                        
                        calib_fit_time = time.time() - start_calib_fit
                        
                        # Apply calibration to test data
                        start_calib_pred = time.time()
                        
                        if calib_name == 'GPCalibration':
                            # Ensure test data has the same dtype
                            test_proba_safe = np.array(y_test_proba_uncal, dtype=np.float64)
                            y_test_proba_cal = calib_method.predict_proba(test_proba_safe)
                        else:
                            y_test_proba_cal = calib_method.predict_proba(y_test_proba_uncal)
                        
                        calib_pred_time = time.time() - start_calib_pred
                    
                    # Get hard predictions
                    y_test_pred = np.argmax(y_test_proba_cal, axis=1)
                    
                    # Calculate metrics
                    accuracy = accuracy_score(y_test_encoded_safe, y_test_pred)
                    
                    # Calculate log loss
                    try:
                        logloss = log_loss(y_test_encoded_safe, y_test_proba_cal)
                    except Exception as e:
                        print(f"        ⚠️  Log loss calculation failed: {e}")
                        logloss = np.nan
                    
                    # Calculate ECE using pycalib scoring module
                    try:
                        ece = expected_calibration_error(y_test_encoded_safe, y_test_proba_cal, n_bins=10)
                    except Exception as e:
                        print(f"        ⚠️  ECE calculation failed: {e}")
                        ece = np.nan
                    
                    # Store results
                    result = {
                        'Dataset': dataset_name,
                        'Classifier': clf_name,  # Use actual classifier name
                        'CalibrationMethod': calib_name,
                        'Accuracy': accuracy,
                        'ECE': ece,
                        'LogLoss': logloss,
                        'BaseFitTime': fit_time,
                        'BasePredTime': pred_time,
                        'CalibFitTime': calib_fit_time,
                        'CalibPredTime': calib_pred_time,
                        'TotalTime': fit_time + calib_fit_time + pred_time + calib_pred_time,
                        'TrainSamples': len(X_train),
                        'CalibSamples': len(X_calib),
                        'TestSamples': len(X_test),
                        'NumClasses': n_classes,
                        'NumFeatures': X_train.shape[1]
                    }
                    
                    calibration_results.append(result)
                    detailed_calibration_results[dataset_name][clf_name][calib_name] = result
                    
                    print(f"        ✅ Accuracy: {accuracy:.4f}, ECE: {ece:.4f}, LogLoss: {logloss:.4f}")
                    print(f"        ⏱️  Calib Fit: {calib_fit_time:.2f}s, Calib Pred: {calib_pred_time:.3f}s")
                    
                except Exception as e:
                    print(f"        ❌ Error with {calib_name} on {clf_name}: {e}")
                    
                    # Store error result
                    error_result = {
                        'Dataset': dataset_name,
                        'Classifier': clf_name,
                        'CalibrationMethod': calib_name,
                        'Accuracy': np.nan,
                        'ECE': np.nan,
                        'LogLoss': np.nan,
                        'BaseFitTime': fit_time if 'fit_time' in locals() else np.nan,
                        'BasePredTime': pred_time if 'pred_time' in locals() else np.nan,
                        'CalibFitTime': np.nan,
                        'CalibPredTime': np.nan,
                        'TotalTime': np.nan,
                        'TrainSamples': len(X_train),
                        'CalibSamples': len(X_calib),
                        'TestSamples': len(X_test),
                        'NumClasses': n_classes,
                        'NumFeatures': X_train.shape[1],
                        'Error': str(e)
                    }
                    calibration_results.append(error_result)
            
        except Exception as e:
            print(f"    ❌ Error with base {clf_name} classifier for {dataset_name}: {e}")
            continue

print(f"\n" + "="*80)
print(f"✅ CALIBRATION COMPLETED: {len(calibration_results)} combinations processed")
print(f"📊 Total classifier-calibration combinations: {len(multiclass_classifiers)} × {len(calibration_methods)} = {len(multiclass_classifiers) * len(calibration_methods)} per dataset")
print("="*80)

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\session_manager.py:31: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\session_manager.py:31: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\misc.py:27: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\misc.py:27: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:156: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:156: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdagradDAOptimizer is deprecated. Please use tf.compat.v1.train.AdagradDAOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdagradDAOptimizer is deprecated. Please use tf.compat.v1.train.AdagradDAOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdagradOptimizer is deprecated. Please use tf.compat.v1.train.AdagradOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdagradOptimizer is deprecated. Please use tf.compat.v1.train.AdagradOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.FtrlOptimizer is deprecated. Please use tf.compat.v1.train.FtrlOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.FtrlOptimizer is deprecated. Please use tf.compat.v1.train.FtrlOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.ProximalAdagradOptimizer is deprecated. Please use tf.compat.v1.train.ProximalAdagradOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.ProximalAdagradOptimizer is deprecated. Please use tf.compat.v1.train.ProximalAdagradOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.ProximalGradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.ProximalGradientDescentOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.ProximalGradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.ProximalGradientDescentOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\training\tensorflow_optimizer.py:169: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\saver\coders.py:80: The name tf.data.Iterator is deprecated. Please use tf.compat.v1.data.Iterator instead.

WARNING:tensorflow:From c:\Users\Asus\Documents\S1 Statistika\Skripsi\pycalib\.venv\lib\site-packages\gpflow\saver\coders.py:80: The name tf.data.Iterator is deprecated. Please use tf.compat.v1.data.Iterator instead.

================================================================================
🔧 PERFORMING CALIBRATION ON ALL MULTICLASS CLASSIFIERS
================================================================================

🔄 PROCESSING 5 DATASETS with 11 CLASSIFIERS and 4 CALIBRATION METHODS...
📊 Total combinations: 220
--------------------------------------------------------------------------------

📊 DATASET: CAR EVALUATION
------------------------------------------------------------
Training set: (1209, 21), Calibration set: (173, 21), Test set: (346, 21)
Number of classes: 4

🤖 Processing RandomForest classifier...
--------------------------------------------------
    🏋️  Training RandomForest base classifier...
    ✅ RandomForest base classifier trained successfully
    ⏱️  Fit: 0.27s, Predict: 0.240s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [  0.5%] Testing calibration method: Uncalibrated on RandomForest
        ✅ Accuracy: 0.9798, ECE: 0.1291, LogLoss: 0.1691
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [  0.9%] Testing calibration method: PlattScaling on RandomForest
        ✅ Accuracy: 0.9711, ECE: 0.0549, LogLoss: 0.4339
        ⏱️  Calib Fit: 0.05s, Calib Pred: 0.000s

    🔧 [  1.4%] Testing calibration method: IsotonicRegression on RandomForest
        ✅ Accuracy: 0.9682, ECE: 0.0479, LogLoss: 0.5332
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [  1.8%] Testing calibration method: GPCalibration on RandomForest
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.603853
  Number of iterations: 200
  Number of functions evaluations: 223

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.603853
  Number of iterations: 200
  Number of functions evaluations: 223

        ✅ Accuracy: 0.9798, ECE: 0.0525, LogLoss: 0.0716
        ⏱️  Calib Fit: 1.78s, Calib Pred: 0.260s

🤖 Processing AdaBoost classifier...
--------------------------------------------------
    🏋️  Training AdaBoost base classifier...
    ✅ AdaBoost base classifier trained successfully
    ⏱️  Fit: 0.11s, Predict: 0.026s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [  2.3%] Testing calibration method: Uncalibrated on AdaBoost
        ✅ Accuracy: 0.7919, ECE: 0.1006, LogLoss: 0.5450
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [  2.7%] Testing calibration method: PlattScaling on AdaBoost
        ✅ Accuracy: 0.8121, ECE: 0.0734, LogLoss: 0.4859
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.003s

    🔧 [  3.2%] Testing calibration method: IsotonicRegression on AdaBoost
        ✅ Accuracy: 0.8353, ECE: 0.0812, LogLoss: 0.5193
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [  3.6%] Testing calibration method: GPCalibration on AdaBoost
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.395303
  Number of iterations: 200
  Number of functions evaluations: 233

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.395303
  Number of iterations: 200
  Number of functions evaluations: 233

        ✅ Accuracy: 0.7832, ECE: 0.0937, LogLoss: 0.4132
        ⏱️  Calib Fit: 1.54s, Calib Pred: 0.225s

🤖 Processing NaiveBayes classifier...
--------------------------------------------------
    🏋️  Training NaiveBayes base classifier...
    ✅ NaiveBayes base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.007s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [  4.1%] Testing calibration method: Uncalibrated on NaiveBayes
        ✅ Accuracy: 0.7977, ECE: 0.0333, LogLoss: 4.8376
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [  4.5%] Testing calibration method: PlattScaling on NaiveBayes
        ✅ Accuracy: 0.7977, ECE: 0.0549, LogLoss: 0.5347
        ⏱️  Calib Fit: 0.03s, Calib Pred: 0.000s

    🔧 [  5.0%] Testing calibration method: IsotonicRegression on NaiveBayes
        ✅ Accuracy: 0.8613, ECE: 0.0638, LogLoss: 0.6426
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [  5.5%] Testing calibration method: GPCalibration on NaiveBayes
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 226.574226
  Number of iterations: 41
  Number of functions evaluations: 74

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 226.574226
  Number of iterations: 41
  Number of functions evaluations: 74

        ✅ Accuracy: 0.8555, ECE: 0.0564, LogLoss: 1.3956
        ⏱️  Calib Fit: 1.62s, Calib Pred: 0.229s

🤖 Processing KNN classifier...
--------------------------------------------------
    🏋️  Training KNN base classifier...
    ✅ KNN base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.020s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [  5.9%] Testing calibration method: Uncalibrated on KNN
        ✅ Accuracy: 0.8931, ECE: 0.1061, LogLoss: 0.4035
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [  6.4%] Testing calibration method: PlattScaling on KNN
        ✅ Accuracy: 0.9162, ECE: 0.0792, LogLoss: 0.2873
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [  6.8%] Testing calibration method: IsotonicRegression on KNN
        ✅ Accuracy: 0.8555, ECE: 0.0859, LogLoss: 0.3698
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.008s

    🔧 [  7.3%] Testing calibration method: GPCalibration on KNN
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 768.429869
  Number of iterations: 200
  Number of functions evaluations: 219

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 768.429869
  Number of iterations: 200
  Number of functions evaluations: 219

        ✅ Accuracy: 0.8844, ECE: 0.0740, LogLoss: 0.3819
        ⏱️  Calib Fit: 1.73s, Calib Pred: 0.225s

🤖 Processing XGBoost classifier...
--------------------------------------------------
    🏋️  Training XGBoost base classifier...
[14:33:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ XGBoost base classifier trained successfully
    ⏱️  Fit: 0.41s, Predict: 0.012s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [  7.7%] Testing calibration method: Uncalibrated on XGBoost
        ✅ Accuracy: 0.9942, ECE: 0.0586, LogLoss: 0.0310
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [  8.2%] Testing calibration method: PlattScaling on XGBoost
        ✅ Accuracy: 0.9942, ECE: 0.0451, LogLoss: 0.0256
        ⏱️  Calib Fit: 0.03s, Calib Pred: 0.002s

    🔧 [  8.6%] Testing calibration method: IsotonicRegression on XGBoost
        ✅ Accuracy: 0.9942, ECE: 0.0507, LogLoss: 0.0151
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [  9.1%] Testing calibration method: GPCalibration on XGBoost
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.711445
  Number of iterations: 200
  Number of functions evaluations: 229

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.711445
  Number of iterations: 200
  Number of functions evaluations: 229

        ✅ Accuracy: 0.9942, ECE: 0.0476, LogLoss: 0.0252
        ⏱️  Calib Fit: 1.68s, Calib Pred: 0.422s

🤖 Processing DecisionTree classifier...
--------------------------------------------------
    🏋️  Training DecisionTree base classifier...
    ✅ DecisionTree base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.005s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [  9.5%] Testing calibration method: Uncalibrated on DecisionTree
        ✅ Accuracy: 0.9711, ECE: 0.0211, LogLoss: 0.9982
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 10.0%] Testing calibration method: PlattScaling on DecisionTree
        ✅ Accuracy: 0.9711, ECE: 0.0424, LogLoss: 0.1598
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.003s

    🔧 [ 10.5%] Testing calibration method: IsotonicRegression on DecisionTree
        ✅ Accuracy: 0.9711, ECE: 0.0424, LogLoss: 0.1598
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 10.9%] Testing calibration method: GPCalibration on DecisionTree
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 10565.459810
  Number of iterations: 41
  Number of functions evaluations: 129

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 10565.459810
  Number of iterations: 41
  Number of functions evaluations: 129

        ✅ Accuracy: 0.9711, ECE: 0.2547, LogLoss: 0.3934
        ⏱️  Calib Fit: 1.56s, Calib Pred: 0.256s

🤖 Processing SVC classifier...
--------------------------------------------------
    🏋️  Training SVC base classifier...
    ✅ SVC base classifier trained successfully
    ⏱️  Fit: 0.41s, Predict: 0.045s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 11.4%] Testing calibration method: Uncalibrated on SVC
        ✅ Accuracy: 0.9798, ECE: 0.0507, LogLoss: 0.0562
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 11.8%] Testing calibration method: PlattScaling on SVC
        ✅ Accuracy: 0.9769, ECE: 0.0524, LogLoss: 0.2024
        ⏱️  Calib Fit: 0.03s, Calib Pred: 0.000s

    🔧 [ 12.3%] Testing calibration method: IsotonicRegression on SVC
        ✅ Accuracy: 0.9711, ECE: 0.0463, LogLoss: 0.2390
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 12.7%] Testing calibration method: GPCalibration on SVC
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

        ✅ Accuracy: 0.9798, ECE: 0.0507, LogLoss: 0.0562
        ⏱️  Calib Fit: 1.39s, Calib Pred: 0.245s

🤖 Processing ExtraTree classifier...
--------------------------------------------------
    🏋️  Training ExtraTree base classifier...
    ✅ ExtraTree base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.007s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 13.2%] Testing calibration method: Uncalibrated on ExtraTree
        ✅ Accuracy: 0.8844, ECE: 0.0656, LogLoss: 3.9929
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 13.6%] Testing calibration method: PlattScaling on ExtraTree
        ✅ Accuracy: 0.8844, ECE: 0.0576, LogLoss: 0.4395
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 14.1%] Testing calibration method: IsotonicRegression on ExtraTree
        ✅ Accuracy: 0.8844, ECE: 0.0576, LogLoss: 0.4395
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 14.5%] Testing calibration method: GPCalibration on ExtraTree
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 25880.112080
  Number of iterations: 37
  Number of functions evaluations: 131

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 25880.112080
  Number of iterations: 37
  Number of functions evaluations: 131

        ✅ Accuracy: 0.8844, ECE: 0.0656, LogLoss: 3.9929
        ⏱️  Calib Fit: 1.50s, Calib Pred: 0.244s

🤖 Processing SGD classifier...
--------------------------------------------------
    🏋️  Training SGD base classifier...
    ✅ SGD base classifier trained successfully
    ⏱️  Fit: 0.04s, Predict: 0.001s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 15.0%] Testing calibration method: Uncalibrated on SGD
        ✅ Accuracy: 0.9104, ECE: 0.0790, LogLoss: 0.2169
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 15.5%] Testing calibration method: PlattScaling on SGD
        ✅ Accuracy: 0.9046, ECE: 0.0627, LogLoss: 0.1880
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 15.9%] Testing calibration method: IsotonicRegression on SGD
        ✅ Accuracy: 0.9191, ECE: 0.0562, LogLoss: 0.3600
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.010s

    🔧 [ 16.4%] Testing calibration method: GPCalibration on SGD
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.556358
  Number of iterations: 200
  Number of functions evaluations: 240

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.556358
  Number of iterations: 200
  Number of functions evaluations: 240

        ✅ Accuracy: 0.9104, ECE: 0.0700, LogLoss: 0.2099
        ⏱️  Calib Fit: 1.73s, Calib Pred: 0.232s

🤖 Processing MLP classifier...
--------------------------------------------------
    🏋️  Training MLP base classifier...
    ✅ MLP base classifier trained successfully
    ⏱️  Fit: 4.23s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 16.8%] Testing calibration method: Uncalibrated on MLP
        ✅ Accuracy: 0.9913, ECE: 0.0568, LogLoss: 0.0332
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 17.3%] Testing calibration method: PlattScaling on MLP
        ✅ Accuracy: 0.9913, ECE: 0.0491, LogLoss: 0.0363
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 17.7%] Testing calibration method: IsotonicRegression on MLP
        ✅ Accuracy: 0.9913, ECE: 0.0514, LogLoss: 0.2102
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 18.2%] Testing calibration method: GPCalibration on MLP
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.746404
  Number of iterations: 200
  Number of functions evaluations: 223

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.746404
  Number of iterations: 200
  Number of functions evaluations: 223

        ✅ Accuracy: 0.9913, ECE: 0.0536, LogLoss: 0.0309
        ⏱️  Calib Fit: 2.02s, Calib Pred: 0.250s

🤖 Processing BernoulliNB classifier...
--------------------------------------------------
    🏋️  Training BernoulliNB base classifier...
    ✅ BernoulliNB base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (346, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 18.6%] Testing calibration method: Uncalibrated on BernoulliNB
        ✅ Accuracy: 0.8728, ECE: 0.0923, LogLoss: 0.2792
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 19.1%] Testing calibration method: PlattScaling on BernoulliNB
        ✅ Accuracy: 0.8786, ECE: 0.0501, LogLoss: 0.2526
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.003s

    🔧 [ 19.5%] Testing calibration method: IsotonicRegression on BernoulliNB
        ✅ Accuracy: 0.8960, ECE: 0.0651, LogLoss: 0.2259
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.003s

    🔧 [ 20.0%] Testing calibration method: GPCalibration on BernoulliNB
        🔧 GP input shapes: proba (173, 4), labels (173,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.087344
  Number of iterations: 200
  Number of functions evaluations: 231

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.087344
  Number of iterations: 200
  Number of functions evaluations: 231

        ✅ Accuracy: 0.8757, ECE: 0.0575, LogLoss: 0.2533
        ⏱️  Calib Fit: 1.82s, Calib Pred: 0.292s

📊 DATASET: DRY BEAN
------------------------------------------------------------
Training set: (9527, 16), Calibration set: (1361, 16), Test set: (2723, 16)
Number of classes: 7

🤖 Processing RandomForest classifier...
--------------------------------------------------
    🏋️  Training RandomForest base classifier...
    ✅ RandomForest base classifier trained successfully
    ⏱️  Fit: 0.63s, Predict: 0.229s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 20.5%] Testing calibration method: Uncalibrated on RandomForest
        ✅ Accuracy: 0.9177, ECE: 0.0316, LogLoss: 0.3954
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 20.9%] Testing calibration method: PlattScaling on RandomForest
        ✅ Accuracy: 0.9174, ECE: 0.0341, LogLoss: 0.2819
        ⏱️  Calib Fit: 0.06s, Calib Pred: 0.002s

    🔧 [ 21.4%] Testing calibration method: IsotonicRegression on RandomForest
        ✅ Accuracy: 0.9163, ECE: 0.0314, LogLoss: 0.2819
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.006s

    🔧 [ 21.8%] Testing calibration method: GPCalibration on RandomForest
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914497
  Number of iterations: 27
  Number of functions evaluations: 31

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914497
  Number of iterations: 27
  Number of functions evaluations: 31

        ✅ Accuracy: 0.9174, ECE: 0.0313, LogLoss: 0.3954
        ⏱️  Calib Fit: 1.67s, Calib Pred: 0.369s

🤖 Processing AdaBoost classifier...
--------------------------------------------------
    🏋️  Training AdaBoost base classifier...
    ✅ AdaBoost base classifier trained successfully
    ⏱️  Fit: 1.77s, Predict: 0.091s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 22.3%] Testing calibration method: Uncalibrated on AdaBoost
        ✅ Accuracy: 0.4679, ECE: 0.2159, LogLoss: 1.7752
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 22.7%] Testing calibration method: PlattScaling on AdaBoost
        ✅ Accuracy: 0.4341, ECE: 0.0416, LogLoss: 1.3013
        ⏱️  Calib Fit: 0.05s, Calib Pred: 0.002s

    🔧 [ 23.2%] Testing calibration method: IsotonicRegression on AdaBoost
        ✅ Accuracy: 0.4708, ECE: 0.0847, LogLoss: 1.2270
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 23.6%] Testing calibration method: GPCalibration on AdaBoost
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1811.889908
  Number of iterations: 200
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1811.889908
  Number of iterations: 200
  Number of functions evaluations: 244

        ✅ Accuracy: 0.4326, ECE: 0.0881, LogLoss: 1.3168
        ⏱️  Calib Fit: 2.52s, Calib Pred: 0.311s

🤖 Processing NaiveBayes classifier...
--------------------------------------------------
    🏋️  Training NaiveBayes base classifier...
    ✅ NaiveBayes base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.016s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 24.1%] Testing calibration method: Uncalibrated on NaiveBayes
        ✅ Accuracy: 0.8924, ECE: 0.0692, LogLoss: 0.9678
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 24.5%] Testing calibration method: PlattScaling on NaiveBayes
        ✅ Accuracy: 0.8931, ECE: 0.0483, LogLoss: 0.4496
        ⏱️  Calib Fit: 0.05s, Calib Pred: 0.000s

    🔧 [ 25.0%] Testing calibration method: IsotonicRegression on NaiveBayes
        ✅ Accuracy: 0.9005, ECE: 0.0295, LogLoss: 0.3769
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 25.5%] Testing calibration method: GPCalibration on NaiveBayes
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 763.457476
  Number of iterations: 200
  Number of functions evaluations: 290

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 763.457476
  Number of iterations: 200
  Number of functions evaluations: 290

        ✅ Accuracy: 0.8696, ECE: 0.0400, LogLoss: 0.5973
        ⏱️  Calib Fit: 3.06s, Calib Pred: 0.373s

🤖 Processing KNN classifier...
--------------------------------------------------
    🏋️  Training KNN base classifier...
    ✅ KNN base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 1.281s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 25.9%] Testing calibration method: Uncalibrated on KNN
        ✅ Accuracy: 0.9130, ECE: 0.0287, LogLoss: 0.9623
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 26.4%] Testing calibration method: PlattScaling on KNN
        ✅ Accuracy: 0.9141, ECE: 0.0396, LogLoss: 0.3007
        ⏱️  Calib Fit: 0.05s, Calib Pred: 0.002s

    🔧 [ 26.8%] Testing calibration method: IsotonicRegression on KNN
        ✅ Accuracy: 0.9152, ECE: 0.0342, LogLoss: 0.2792
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.005s

    🔧 [ 27.3%] Testing calibration method: GPCalibration on KNN
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.663008
  Number of iterations: 28
  Number of functions evaluations: 29

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.663008
  Number of iterations: 28
  Number of functions evaluations: 29

        ✅ Accuracy: 0.9133, ECE: 0.0452, LogLoss: 0.9737
        ⏱️  Calib Fit: 1.45s, Calib Pred: 0.559s

🤖 Processing XGBoost classifier...
--------------------------------------------------
    🏋️  Training XGBoost base classifier...
[14:34:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ XGBoost base classifier trained successfully
    ⏱️  Fit: 3.77s, Predict: 0.034s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 27.7%] Testing calibration method: Uncalibrated on XGBoost
        ✅ Accuracy: 0.9170, ECE: 0.0284, LogLoss: 0.2727
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 28.2%] Testing calibration method: PlattScaling on XGBoost
        ✅ Accuracy: 0.9166, ECE: 0.0183, LogLoss: 0.3255
        ⏱️  Calib Fit: 0.07s, Calib Pred: 0.004s

    🔧 [ 28.6%] Testing calibration method: IsotonicRegression on XGBoost
        ✅ Accuracy: 0.9163, ECE: 0.0339, LogLoss: 0.3841
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 29.1%] Testing calibration method: GPCalibration on XGBoost
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 250.002495
  Number of iterations: 128
  Number of functions evaluations: 140

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 250.002495
  Number of iterations: 128
  Number of functions evaluations: 140

        ✅ Accuracy: 0.9188, ECE: 0.0364, LogLoss: 0.2276
        ⏱️  Calib Fit: 2.71s, Calib Pred: 0.335s

🤖 Processing DecisionTree classifier...
--------------------------------------------------
    🏋️  Training DecisionTree base classifier...
    ✅ DecisionTree base classifier trained successfully
    ⏱️  Fit: 0.27s, Predict: 0.005s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 29.5%] Testing calibration method: Uncalibrated on DecisionTree
        ✅ Accuracy: 0.8902, ECE: 0.0598, LogLoss: 3.7925
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 30.0%] Testing calibration method: PlattScaling on DecisionTree
        ✅ Accuracy: 0.8902, ECE: 0.0575, LogLoss: 0.5049
        ⏱️  Calib Fit: 0.04s, Calib Pred: 0.004s

    🔧 [ 30.5%] Testing calibration method: IsotonicRegression on DecisionTree
        ✅ Accuracy: 0.8902, ECE: 0.0575, LogLoss: 0.5049
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.008s

    🔧 [ 30.9%] Testing calibration method: GPCalibration on DecisionTree
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 103478.698074
  Number of iterations: 67
  Number of functions evaluations: 163

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 103478.698074
  Number of iterations: 67
  Number of functions evaluations: 163

        ✅ Accuracy: 0.8902, ECE: 0.1450, LogLoss: 0.6197
        ⏱️  Calib Fit: 1.85s, Calib Pred: 0.299s

🤖 Processing SVC classifier...
--------------------------------------------------
    🏋️  Training SVC base classifier...
    ✅ SVC base classifier trained successfully
    ⏱️  Fit: 3.87s, Predict: 1.005s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 31.4%] Testing calibration method: Uncalibrated on SVC
        ✅ Accuracy: 0.9225, ECE: 0.0355, LogLoss: 0.2125
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 31.8%] Testing calibration method: PlattScaling on SVC
        ✅ Accuracy: 0.9247, ECE: 0.0307, LogLoss: 0.2737
        ⏱️  Calib Fit: 0.05s, Calib Pred: 0.000s

    🔧 [ 32.3%] Testing calibration method: IsotonicRegression on SVC
        ✅ Accuracy: 0.9210, ECE: 0.0295, LogLoss: 0.4519
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 32.7%] Testing calibration method: GPCalibration on SVC
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 33
  Number of functions evaluations: 36

        ✅ Accuracy: 0.9225, ECE: 0.0355, LogLoss: 0.2125
        ⏱️  Calib Fit: 1.99s, Calib Pred: 0.299s

🤖 Processing ExtraTree classifier...
--------------------------------------------------
    🏋️  Training ExtraTree base classifier...
    ✅ ExtraTree base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 33.2%] Testing calibration method: Uncalibrated on ExtraTree
        ✅ Accuracy: 0.8806, ECE: 0.0694, LogLoss: 4.1223
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 33.6%] Testing calibration method: PlattScaling on ExtraTree
        ✅ Accuracy: 0.8806, ECE: 0.0148, LogLoss: 0.5386
        ⏱️  Calib Fit: 0.04s, Calib Pred: 0.002s

    🔧 [ 34.1%] Testing calibration method: IsotonicRegression on ExtraTree
        ✅ Accuracy: 0.8806, ECE: 0.0148, LogLoss: 0.5386
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 34.5%] Testing calibration method: GPCalibration on ExtraTree
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 134280.984243
  Number of iterations: 46
  Number of functions evaluations: 142

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 134280.984243
  Number of iterations: 46
  Number of functions evaluations: 142

        ✅ Accuracy: 0.8806, ECE: 0.1881, LogLoss: 0.6886
        ⏱️  Calib Fit: 1.83s, Calib Pred: 0.309s

🤖 Processing SGD classifier...
--------------------------------------------------
    🏋️  Training SGD base classifier...
    ✅ SGD base classifier trained successfully
    ⏱️  Fit: 0.20s, Predict: 0.007s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 35.0%] Testing calibration method: Uncalibrated on SGD
        ✅ Accuracy: 0.9097, ECE: 0.0538, LogLoss: 0.2563
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 35.5%] Testing calibration method: PlattScaling on SGD
        ✅ Accuracy: 0.9185, ECE: 0.0382, LogLoss: 0.2714
        ⏱️  Calib Fit: 0.06s, Calib Pred: 0.001s

    🔧 [ 35.9%] Testing calibration method: IsotonicRegression on SGD
        ✅ Accuracy: 0.9111, ECE: 0.0331, LogLoss: 0.3986
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.003s

    🔧 [ 36.4%] Testing calibration method: GPCalibration on SGD
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 318.347533
  Number of iterations: 146
  Number of functions evaluations: 166

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 318.347533
  Number of iterations: 146
  Number of functions evaluations: 166

        ✅ Accuracy: 0.9089, ECE: 0.0339, LogLoss: 0.2453
        ⏱️  Calib Fit: 2.92s, Calib Pred: 0.292s

🤖 Processing MLP classifier...
--------------------------------------------------
    🏋️  Training MLP base classifier...
    ✅ MLP base classifier trained successfully
    ⏱️  Fit: 18.00s, Predict: 0.013s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 36.8%] Testing calibration method: Uncalibrated on MLP
        ✅ Accuracy: 0.9232, ECE: 0.0333, LogLoss: 0.2143
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 37.3%] Testing calibration method: PlattScaling on MLP
        ✅ Accuracy: 0.9236, ECE: 0.0281, LogLoss: 0.2783
        ⏱️  Calib Fit: 0.05s, Calib Pred: 0.002s

    🔧 [ 37.7%] Testing calibration method: IsotonicRegression on MLP
        ✅ Accuracy: 0.9221, ECE: 0.0347, LogLoss: 0.4170
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.003s

    🔧 [ 38.2%] Testing calibration method: GPCalibration on MLP
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325741
  Number of iterations: 33
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325741
  Number of iterations: 33
  Number of functions evaluations: 38

        ✅ Accuracy: 0.9232, ECE: 0.0333, LogLoss: 0.2143
        ⏱️  Calib Fit: 1.71s, Calib Pred: 0.294s

🤖 Processing BernoulliNB classifier...
--------------------------------------------------
    🏋️  Training BernoulliNB base classifier...
    ✅ BernoulliNB base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.004s
    📊 Uncalibrated probabilities shape: (2723, 7)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 38.6%] Testing calibration method: Uncalibrated on BernoulliNB
        ✅ Accuracy: 0.7150, ECE: 0.1397, LogLoss: 1.1424
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 39.1%] Testing calibration method: PlattScaling on BernoulliNB
        ✅ Accuracy: 0.7312, ECE: 0.0272, LogLoss: 0.8529
        ⏱️  Calib Fit: 0.04s, Calib Pred: 0.002s

    🔧 [ 39.5%] Testing calibration method: IsotonicRegression on BernoulliNB
        ✅ Accuracy: 0.7492, ECE: 0.0271, LogLoss: 0.7783
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.002s

    🔧 [ 40.0%] Testing calibration method: GPCalibration on BernoulliNB
        🔧 GP input shapes: proba (1361, 7), labels (1361,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1117.894974
  Number of iterations: 200
  Number of functions evaluations: 285

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1117.894974
  Number of iterations: 200
  Number of functions evaluations: 285

        ✅ Accuracy: 0.7154, ECE: 0.0378, LogLoss: 0.9158
        ⏱️  Calib Fit: 3.47s, Calib Pred: 0.314s

📊 DATASET: STUDENT DROPOUT
------------------------------------------------------------
Training set: (3096, 36), Calibration set: (442, 36), Test set: (886, 36)
Number of classes: 3

🤖 Processing RandomForest classifier...
--------------------------------------------------
    🏋️  Training RandomForest base classifier...
    ✅ RandomForest base classifier trained successfully
    ⏱️  Fit: 0.38s, Predict: 0.243s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 40.5%] Testing calibration method: Uncalibrated on RandomForest
        ✅ Accuracy: 0.7856, ECE: 0.0786, LogLoss: 0.6187
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 40.9%] Testing calibration method: PlattScaling on RandomForest
        ✅ Accuracy: 0.7912, ECE: 0.0591, LogLoss: 0.5366
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.001s

    🔧 [ 41.4%] Testing calibration method: IsotonicRegression on RandomForest
        ✅ Accuracy: 0.7889, ECE: 0.0420, LogLoss: 0.7671
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 41.8%] Testing calibration method: GPCalibration on RandomForest
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 270.831498
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 270.831498
  Number of iterations: 200
  Number of functions evaluations: 230

        ✅ Accuracy: 0.7867, ECE: 0.0556, LogLoss: 0.6102
        ⏱️  Calib Fit: 1.76s, Calib Pred: 0.229s

🤖 Processing AdaBoost classifier...
--------------------------------------------------
    🏋️  Training AdaBoost base classifier...
    ✅ AdaBoost base classifier trained successfully
    ⏱️  Fit: 0.30s, Predict: 0.032s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 42.3%] Testing calibration method: Uncalibrated on AdaBoost
        ✅ Accuracy: 0.7664, ECE: 0.3805, LogLoss: 1.0561
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 42.7%] Testing calibration method: PlattScaling on AdaBoost
        ✅ Accuracy: 0.7483, ECE: 0.1460, LogLoss: 0.6778
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 43.2%] Testing calibration method: IsotonicRegression on AdaBoost
        ✅ Accuracy: 0.7664, ECE: 0.0659, LogLoss: 0.7579
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 43.6%] Testing calibration method: GPCalibration on AdaBoost
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 349.788951
  Number of iterations: 200
  Number of functions evaluations: 260

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 349.788951
  Number of iterations: 200
  Number of functions evaluations: 260

        ✅ Accuracy: 0.7483, ECE: 0.0741, LogLoss: 0.6351
        ⏱️  Calib Fit: 1.87s, Calib Pred: 0.244s

🤖 Processing NaiveBayes classifier...
--------------------------------------------------
    🏋️  Training NaiveBayes base classifier...
    ✅ NaiveBayes base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.005s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 44.1%] Testing calibration method: Uncalibrated on NaiveBayes
        ✅ Accuracy: 0.6840, ECE: 0.2014, LogLoss: 2.6933
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 44.5%] Testing calibration method: PlattScaling on NaiveBayes
        ✅ Accuracy: 0.6761, ECE: 0.0904, LogLoss: 0.7978
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 45.0%] Testing calibration method: IsotonicRegression on NaiveBayes
        ✅ Accuracy: 0.6874, ECE: 0.0619, LogLoss: 0.7968
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 45.5%] Testing calibration method: GPCalibration on NaiveBayes
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 891.118414
  Number of iterations: 200
  Number of functions evaluations: 252

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 891.118414
  Number of iterations: 200
  Number of functions evaluations: 252

        ✅ Accuracy: 0.5621, ECE: 0.1570, LogLoss: 2.0198
        ⏱️  Calib Fit: 1.83s, Calib Pred: 0.294s

🤖 Processing KNN classifier...
--------------------------------------------------
    🏋️  Training KNN base classifier...
    ✅ KNN base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.110s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 45.9%] Testing calibration method: Uncalibrated on KNN
        ✅ Accuracy: 0.6840, ECE: 0.0447, LogLoss: 3.1689
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 46.4%] Testing calibration method: PlattScaling on KNN
        ✅ Accuracy: 0.6998, ECE: 0.0650, LogLoss: 0.7436
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.001s

    🔧 [ 46.8%] Testing calibration method: IsotonicRegression on KNN
        ✅ Accuracy: 0.7088, ECE: 0.0592, LogLoss: 0.8018
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 47.3%] Testing calibration method: GPCalibration on KNN
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 37795.352761
  Number of iterations: 97
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 37795.352761
  Number of iterations: 97
  Number of functions evaluations: 244

        ✅ Accuracy: 0.6727, ECE: 0.0762, LogLoss: 0.8680
        ⏱️  Calib Fit: 1.63s, Calib Pred: 0.230s

🤖 Processing XGBoost classifier...
--------------------------------------------------
    🏋️  Training XGBoost base classifier...
[14:35:05] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ XGBoost base classifier trained successfully
    ⏱️  Fit: 0.73s, Predict: 0.017s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 47.7%] Testing calibration method: Uncalibrated on XGBoost
        ✅ Accuracy: 0.7765, ECE: 0.0703, LogLoss: 0.6116
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 48.2%] Testing calibration method: PlattScaling on XGBoost
        ✅ Accuracy: 0.7799, ECE: 0.0825, LogLoss: 0.5923
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.002s

    🔧 [ 48.6%] Testing calibration method: IsotonicRegression on XGBoost
        ✅ Accuracy: 0.7630, ECE: 0.0386, LogLoss: 0.7495
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.003s

    🔧 [ 49.1%] Testing calibration method: GPCalibration on XGBoost
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.248149
  Number of iterations: 200
  Number of functions evaluations: 218

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.248149
  Number of iterations: 200
  Number of functions evaluations: 218

        ✅ Accuracy: 0.7777, ECE: 0.0304, LogLoss: 0.5527
        ⏱️  Calib Fit: 1.71s, Calib Pred: 0.518s

🤖 Processing DecisionTree classifier...
--------------------------------------------------
    🏋️  Training DecisionTree base classifier...
    ✅ DecisionTree base classifier trained successfully
    ⏱️  Fit: 0.04s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 49.5%] Testing calibration method: Uncalibrated on DecisionTree
        ✅ Accuracy: 0.7122, ECE: 0.2378, LogLoss: 9.9406
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 50.0%] Testing calibration method: PlattScaling on DecisionTree
        ✅ Accuracy: 0.7122, ECE: 0.1056, LogLoss: 0.7823
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.001s

    🔧 [ 50.5%] Testing calibration method: IsotonicRegression on DecisionTree
        ✅ Accuracy: 0.7122, ECE: 0.1056, LogLoss: 0.7823
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 50.9%] Testing calibration method: GPCalibration on DecisionTree
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 125840.553971
  Number of iterations: 53
  Number of functions evaluations: 145

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 125840.553971
  Number of iterations: 53
  Number of functions evaluations: 145

        ✅ Accuracy: 0.7122, ECE: 0.0449, LogLoss: 0.8031
        ⏱️  Calib Fit: 1.46s, Calib Pred: 0.234s

🤖 Processing SVC classifier...
--------------------------------------------------
    🏋️  Training SVC base classifier...
    ✅ SVC base classifier trained successfully
    ⏱️  Fit: 2.30s, Predict: 0.247s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 51.4%] Testing calibration method: Uncalibrated on SVC
        ✅ Accuracy: 0.7596, ECE: 0.0470, LogLoss: 0.5922
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 51.8%] Testing calibration method: PlattScaling on SVC
        ✅ Accuracy: 0.7596, ECE: 0.0588, LogLoss: 0.6077
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 52.3%] Testing calibration method: IsotonicRegression on SVC
        ✅ Accuracy: 0.7641, ECE: 0.0284, LogLoss: 0.7003
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 52.7%] Testing calibration method: GPCalibration on SVC
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 37

        ✅ Accuracy: 0.7596, ECE: 0.0469, LogLoss: 0.5922
        ⏱️  Calib Fit: 1.32s, Calib Pred: 0.229s

🤖 Processing ExtraTree classifier...
--------------------------------------------------
    🏋️  Training ExtraTree base classifier...
    ✅ ExtraTree base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.004s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 53.2%] Testing calibration method: Uncalibrated on ExtraTree
        ✅ Accuracy: 0.6546, ECE: 0.2954, LogLoss: 11.9287
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 53.6%] Testing calibration method: PlattScaling on ExtraTree
        ✅ Accuracy: 0.6558, ECE: 0.0827, LogLoss: 0.8543
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.002s

    🔧 [ 54.1%] Testing calibration method: IsotonicRegression on ExtraTree
        ✅ Accuracy: 0.6558, ECE: 0.0827, LogLoss: 0.8543
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 54.5%] Testing calibration method: GPCalibration on ExtraTree
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 139159.699948
  Number of iterations: 42
  Number of functions evaluations: 127

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 139159.699948
  Number of iterations: 42
  Number of functions evaluations: 127

        ✅ Accuracy: 0.6546, ECE: 0.0415, LogLoss: 0.8894
        ⏱️  Calib Fit: 1.39s, Calib Pred: 0.228s

🤖 Processing SGD classifier...
--------------------------------------------------
    🏋️  Training SGD base classifier...
    ✅ SGD base classifier trained successfully
    ⏱️  Fit: 0.13s, Predict: 0.000s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 55.0%] Testing calibration method: Uncalibrated on SGD
        ✅ Accuracy: 0.7551, ECE: 0.0277, LogLoss: 0.6788
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 55.5%] Testing calibration method: PlattScaling on SGD
        ✅ Accuracy: 0.7562, ECE: 0.0665, LogLoss: 0.6475
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 55.9%] Testing calibration method: IsotonicRegression on SGD
        ✅ Accuracy: 0.7494, ECE: 0.0546, LogLoss: 0.9209
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 56.4%] Testing calibration method: GPCalibration on SGD
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.295254
  Number of iterations: 200
  Number of functions evaluations: 242

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.295254
  Number of iterations: 200
  Number of functions evaluations: 242

        ✅ Accuracy: 0.7573, ECE: 0.0457, LogLoss: 0.6632
        ⏱️  Calib Fit: 1.89s, Calib Pred: 0.230s

🤖 Processing MLP classifier...
--------------------------------------------------
    🏋️  Training MLP base classifier...
    ✅ MLP base classifier trained successfully
    ⏱️  Fit: 11.88s, Predict: 0.009s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 56.8%] Testing calibration method: Uncalibrated on MLP
        ✅ Accuracy: 0.7156, ECE: 0.1619, LogLoss: 1.4514
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 57.3%] Testing calibration method: PlattScaling on MLP
        ✅ Accuracy: 0.7280, ECE: 0.0712, LogLoss: 0.7243
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 57.7%] Testing calibration method: IsotonicRegression on MLP
        ✅ Accuracy: 0.7528, ECE: 0.0605, LogLoss: 0.8131
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 58.2%] Testing calibration method: GPCalibration on MLP
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 511.753543
  Number of iterations: 200
  Number of functions evaluations: 268

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 511.753543
  Number of iterations: 200
  Number of functions evaluations: 268

        ✅ Accuracy: 0.6806, ECE: 0.0750, LogLoss: 1.0153
        ⏱️  Calib Fit: 1.84s, Calib Pred: 0.240s

🤖 Processing BernoulliNB classifier...
--------------------------------------------------
    🏋️  Training BernoulliNB base classifier...
    ✅ BernoulliNB base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.006s
    📊 Uncalibrated probabilities shape: (886, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 58.6%] Testing calibration method: Uncalibrated on BernoulliNB
        ✅ Accuracy: 0.7404, ECE: 0.0945, LogLoss: 0.8490
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 59.1%] Testing calibration method: PlattScaling on BernoulliNB
        ✅ Accuracy: 0.7573, ECE: 0.0523, LogLoss: 0.6749
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.004s

    🔧 [ 59.5%] Testing calibration method: IsotonicRegression on BernoulliNB
        ✅ Accuracy: 0.7415, ECE: 0.0294, LogLoss: 0.7657
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 60.0%] Testing calibration method: GPCalibration on BernoulliNB
        🔧 GP input shapes: proba (442, 3), labels (442,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 342.862028
  Number of iterations: 200
  Number of functions evaluations: 242

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 342.862028
  Number of iterations: 200
  Number of functions evaluations: 242

        ✅ Accuracy: 0.7302, ECE: 0.0438, LogLoss: 0.7367
        ⏱️  Calib Fit: 1.90s, Calib Pred: 0.222s

📊 DATASET: CIRRHOSIS
------------------------------------------------------------
Training set: (292, 26), Calibration set: (42, 26), Test set: (84, 26)
Number of classes: 3

🤖 Processing RandomForest classifier...
--------------------------------------------------
    🏋️  Training RandomForest base classifier...
    ✅ RandomForest base classifier trained successfully
    ⏱️  Fit: 0.28s, Predict: 0.508s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 60.5%] Testing calibration method: Uncalibrated on RandomForest
        ✅ Accuracy: 0.7619, ECE: 0.1099, LogLoss: 0.6345
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 60.9%] Testing calibration method: PlattScaling on RandomForest
        ✅ Accuracy: 0.7619, ECE: 0.1281, LogLoss: 0.6298
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 61.4%] Testing calibration method: IsotonicRegression on RandomForest
        ✅ Accuracy: 0.7262, ECE: 0.1426, LogLoss: 2.1405
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 61.8%] Testing calibration method: GPCalibration on RandomForest
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 35
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 35
  Number of functions evaluations: 41

        ✅ Accuracy: 0.7619, ECE: 0.1099, LogLoss: 0.6345
        ⏱️  Calib Fit: 1.22s, Calib Pred: 0.223s

🤖 Processing AdaBoost classifier...
--------------------------------------------------
    🏋️  Training AdaBoost base classifier...
    ✅ AdaBoost base classifier trained successfully
    ⏱️  Fit: 0.10s, Predict: 0.016s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 62.3%] Testing calibration method: Uncalibrated on AdaBoost
        ✅ Accuracy: 0.7619, ECE: 0.1979, LogLoss: 0.7679
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 62.7%] Testing calibration method: PlattScaling on AdaBoost
        ✅ Accuracy: 0.7381, ECE: 0.1085, LogLoss: 0.6711
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 63.2%] Testing calibration method: IsotonicRegression on AdaBoost
        ✅ Accuracy: 0.7500, ECE: 0.1133, LogLoss: 1.8328
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 63.6%] Testing calibration method: GPCalibration on AdaBoost
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878012
  Number of iterations: 38
  Number of functions evaluations: 50

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878012
  Number of iterations: 38
  Number of functions evaluations: 50

        ✅ Accuracy: 0.7619, ECE: 0.1979, LogLoss: 0.7679
        ⏱️  Calib Fit: 1.30s, Calib Pred: 0.220s

🤖 Processing NaiveBayes classifier...
--------------------------------------------------
    🏋️  Training NaiveBayes base classifier...
    ✅ NaiveBayes base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.004s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 64.1%] Testing calibration method: Uncalibrated on NaiveBayes
        ✅ Accuracy: 0.2143, ECE: 0.7226, LogLoss: 11.1010
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 64.5%] Testing calibration method: PlattScaling on NaiveBayes
        ✅ Accuracy: 0.6190, ECE: 0.0341, LogLoss: 0.8165
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 65.0%] Testing calibration method: IsotonicRegression on NaiveBayes
        ✅ Accuracy: 0.6310, ECE: 0.1336, LogLoss: 1.5078
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 65.5%] Testing calibration method: GPCalibration on NaiveBayes
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 854.111577
  Number of iterations: 200
  Number of functions evaluations: 274

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 854.111577
  Number of iterations: 200
  Number of functions evaluations: 274

        ✅ Accuracy: 0.4643, ECE: 0.3860, LogLoss: 3.5520
        ⏱️  Calib Fit: 1.64s, Calib Pred: 0.240s

🤖 Processing KNN classifier...
--------------------------------------------------
    🏋️  Training KNN base classifier...
    ✅ KNN base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.009s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 65.9%] Testing calibration method: Uncalibrated on KNN
        ✅ Accuracy: 0.6667, ECE: 0.1165, LogLoss: 4.5147
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 66.4%] Testing calibration method: PlattScaling on KNN
        ✅ Accuracy: 0.6667, ECE: 0.1497, LogLoss: 1.0113
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.006s

    🔧 [ 66.8%] Testing calibration method: IsotonicRegression on KNN
        ✅ Accuracy: 0.6667, ECE: 0.1129, LogLoss: 0.7507
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 67.3%] Testing calibration method: GPCalibration on KNN
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 6038.437862
  Number of iterations: 166
  Number of functions evaluations: 298

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 6038.437862
  Number of iterations: 166
  Number of functions evaluations: 298

        ✅ Accuracy: 0.6548, ECE: 0.1243, LogLoss: 4.5570
        ⏱️  Calib Fit: 1.61s, Calib Pred: 0.219s

🤖 Processing XGBoost classifier...
--------------------------------------------------
    🏋️  Training XGBoost base classifier...
[14:35:41] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ XGBoost base classifier trained successfully
    ⏱️  Fit: 0.24s, Predict: 0.011s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 67.7%] Testing calibration method: Uncalibrated on XGBoost
        ✅ Accuracy: 0.7500, ECE: 0.1438, LogLoss: 0.9150
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 68.2%] Testing calibration method: PlattScaling on XGBoost
        ✅ Accuracy: 0.7500, ECE: 0.1088, LogLoss: 0.6781
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.002s

    🔧 [ 68.6%] Testing calibration method: IsotonicRegression on XGBoost
        ✅ Accuracy: 0.7381, ECE: 0.1024, LogLoss: 1.3636
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 69.1%] Testing calibration method: GPCalibration on XGBoost
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 34.214963
  Number of iterations: 106
  Number of functions evaluations: 112

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 34.214963
  Number of iterations: 106
  Number of functions evaluations: 112

        ✅ Accuracy: 0.7024, ECE: 0.1217, LogLoss: 0.6647
        ⏱️  Calib Fit: 1.32s, Calib Pred: 0.214s

🤖 Processing DecisionTree classifier...
--------------------------------------------------
    🏋️  Training DecisionTree base classifier...
    ✅ DecisionTree base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.000s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 69.5%] Testing calibration method: Uncalibrated on DecisionTree
        ✅ Accuracy: 0.6905, ECE: 0.2595, LogLoss: 10.6906
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 70.0%] Testing calibration method: PlattScaling on DecisionTree
        ✅ Accuracy: 0.7143, ECE: 0.0651, LogLoss: 0.7476
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 70.5%] Testing calibration method: IsotonicRegression on DecisionTree
        ✅ Accuracy: 0.7143, ECE: 0.0651, LogLoss: 0.7476
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 70.9%] Testing calibration method: GPCalibration on DecisionTree
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11788.011839
  Number of iterations: 45
  Number of functions evaluations: 127

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11788.011839
  Number of iterations: 45
  Number of functions evaluations: 127

        ✅ Accuracy: 0.6905, ECE: 0.2595, LogLoss: 10.6906
        ⏱️  Calib Fit: 1.31s, Calib Pred: 0.220s

🤖 Processing SVC classifier...
--------------------------------------------------
    🏋️  Training SVC base classifier...
    ✅ SVC base classifier trained successfully
    ⏱️  Fit: 0.02s, Predict: 0.000s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 71.4%] Testing calibration method: Uncalibrated on SVC
        ✅ Accuracy: 0.7619, ECE: 0.0723, LogLoss: 0.6449
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 71.8%] Testing calibration method: PlattScaling on SVC
        ✅ Accuracy: 0.7381, ECE: 0.1084, LogLoss: 0.6696
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 72.3%] Testing calibration method: IsotonicRegression on SVC
        ✅ Accuracy: 0.6667, ECE: 0.1486, LogLoss: 1.0180
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 72.7%] Testing calibration method: GPCalibration on SVC
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.050093
  Number of iterations: 200
  Number of functions evaluations: 223

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.050093
  Number of iterations: 200
  Number of functions evaluations: 223

        ✅ Accuracy: 0.7619, ECE: 0.0701, LogLoss: 0.6444
        ⏱️  Calib Fit: 1.81s, Calib Pred: 0.210s

🤖 Processing ExtraTree classifier...
--------------------------------------------------
    🏋️  Training ExtraTree base classifier...
    ✅ ExtraTree base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 73.2%] Testing calibration method: Uncalibrated on ExtraTree
        ✅ Accuracy: 0.6071, ECE: 0.3429, LogLoss: 13.5688
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 73.6%] Testing calibration method: PlattScaling on ExtraTree
        ✅ Accuracy: 0.6667, ECE: 0.0586, LogLoss: 0.7732
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.001s

    🔧 [ 74.1%] Testing calibration method: IsotonicRegression on ExtraTree
        ✅ Accuracy: 0.6667, ECE: 0.0195, LogLoss: 0.7877
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 74.5%] Testing calibration method: GPCalibration on ExtraTree
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 13565.906768
  Number of iterations: 41
  Number of functions evaluations: 128

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 13565.906768
  Number of iterations: 41
  Number of functions evaluations: 128

        ✅ Accuracy: 0.6071, ECE: 0.3429, LogLoss: 13.5688
        ⏱️  Calib Fit: 1.43s, Calib Pred: 0.226s

🤖 Processing SGD classifier...
--------------------------------------------------
    🏋️  Training SGD base classifier...
    ✅ SGD base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 75.0%] Testing calibration method: Uncalibrated on SGD
        ✅ Accuracy: 0.7976, ECE: 0.1674, LogLoss: 1.7397
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 75.5%] Testing calibration method: PlattScaling on SGD
        ✅ Accuracy: 0.7976, ECE: 0.0813, LogLoss: 0.6275
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.004s

    🔧 [ 75.9%] Testing calibration method: IsotonicRegression on SGD
        ✅ Accuracy: 0.7976, ECE: 0.0660, LogLoss: 1.3398
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 76.4%] Testing calibration method: GPCalibration on SGD
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.688664
  Number of iterations: 200
  Number of functions evaluations: 242

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.688664
  Number of iterations: 200
  Number of functions evaluations: 242

        ✅ Accuracy: 0.7143, ECE: 0.1402, LogLoss: 1.0814
        ⏱️  Calib Fit: 1.55s, Calib Pred: 0.228s

🤖 Processing MLP classifier...
--------------------------------------------------
    🏋️  Training MLP base classifier...
    ✅ MLP base classifier trained successfully
    ⏱️  Fit: 1.32s, Predict: 0.004s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 76.8%] Testing calibration method: Uncalibrated on MLP
        ✅ Accuracy: 0.6905, ECE: 0.1838, LogLoss: 1.0871
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 77.3%] Testing calibration method: PlattScaling on MLP
        ✅ Accuracy: 0.7143, ECE: 0.0435, LogLoss: 0.7474
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 77.7%] Testing calibration method: IsotonicRegression on MLP
        ✅ Accuracy: 0.6905, ECE: 0.0847, LogLoss: 2.5657
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.002s

    🔧 [ 78.2%] Testing calibration method: GPCalibration on MLP
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 47.040050
  Number of iterations: 123
  Number of functions evaluations: 142

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 47.040050
  Number of iterations: 123
  Number of functions evaluations: 142

        ✅ Accuracy: 0.5952, ECE: 0.1506, LogLoss: 0.7889
        ⏱️  Calib Fit: 1.37s, Calib Pred: 0.217s

🤖 Processing BernoulliNB classifier...
--------------------------------------------------
    🏋️  Training BernoulliNB base classifier...
    ✅ BernoulliNB base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.007s
    📊 Uncalibrated probabilities shape: (84, 3)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 78.6%] Testing calibration method: Uncalibrated on BernoulliNB
        ✅ Accuracy: 0.6071, ECE: 0.2625, LogLoss: 1.1268
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 79.1%] Testing calibration method: PlattScaling on BernoulliNB
        ✅ Accuracy: 0.6071, ECE: 0.1122, LogLoss: 0.7871
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 79.5%] Testing calibration method: IsotonicRegression on BernoulliNB
        ✅ Accuracy: 0.5952, ECE: 0.1340, LogLoss: 1.1285
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 80.0%] Testing calibration method: GPCalibration on BernoulliNB
        🔧 GP input shapes: proba (42, 3), labels (42,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.630424
  Number of iterations: 200
  Number of functions evaluations: 228

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.630424
  Number of iterations: 200
  Number of functions evaluations: 228

        ✅ Accuracy: 0.5833, ECE: 0.1370, LogLoss: 0.8036
        ⏱️  Calib Fit: 1.58s, Calib Pred: 0.220s

📊 DATASET: AIR QUALITY
------------------------------------------------------------
Training set: (3499, 9), Calibration set: (500, 9), Test set: (1001, 9)
Number of classes: 4

🤖 Processing RandomForest classifier...
--------------------------------------------------
    🏋️  Training RandomForest base classifier...
    ✅ RandomForest base classifier trained successfully
    ⏱️  Fit: 0.37s, Predict: 0.246s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 80.5%] Testing calibration method: Uncalibrated on RandomForest
        ✅ Accuracy: 0.9530, ECE: 0.0647, LogLoss: 0.1395
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 80.9%] Testing calibration method: PlattScaling on RandomForest
        ✅ Accuracy: 0.9540, ECE: 0.0489, LogLoss: 0.1531
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 81.4%] Testing calibration method: IsotonicRegression on RandomForest
        ✅ Accuracy: 0.9540, ECE: 0.0430, LogLoss: 0.2755
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.007s

    🔧 [ 81.8%] Testing calibration method: GPCalibration on RandomForest
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.626123
  Number of iterations: 114
  Number of functions evaluations: 128

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.626123
  Number of iterations: 114
  Number of functions evaluations: 128

        ✅ Accuracy: 0.9540, ECE: 0.0490, LogLoss: 0.1256
        ⏱️  Calib Fit: 1.55s, Calib Pred: 0.245s

🤖 Processing AdaBoost classifier...
--------------------------------------------------
    🏋️  Training AdaBoost base classifier...
    ✅ AdaBoost base classifier trained successfully
    ⏱️  Fit: 0.32s, Predict: 0.040s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 82.3%] Testing calibration method: Uncalibrated on AdaBoost
        ✅ Accuracy: 0.6144, ECE: 0.4355, LogLoss: 1.3139
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 82.7%] Testing calibration method: PlattScaling on AdaBoost
        ✅ Accuracy: 0.8262, ECE: 0.1410, LogLoss: 0.6182
        ⏱️  Calib Fit: 0.03s, Calib Pred: 0.001s

    🔧 [ 83.2%] Testing calibration method: IsotonicRegression on AdaBoost
        ✅ Accuracy: 0.7812, ECE: 0.1702, LogLoss: 0.5523
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 83.6%] Testing calibration method: GPCalibration on AdaBoost
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 292.836698
  Number of iterations: 200
  Number of functions evaluations: 245

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 292.836698
  Number of iterations: 200
  Number of functions evaluations: 245

        ✅ Accuracy: 0.7782, ECE: 0.1031, LogLoss: 0.5506
        ⏱️  Calib Fit: 2.20s, Calib Pred: 0.231s

🤖 Processing NaiveBayes classifier...
--------------------------------------------------
    🏋️  Training NaiveBayes base classifier...
    ✅ NaiveBayes base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.006s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 84.1%] Testing calibration method: Uncalibrated on NaiveBayes
        ✅ Accuracy: 0.9201, ECE: 0.0271, LogLoss: 0.3399
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 84.5%] Testing calibration method: PlattScaling on NaiveBayes
        ✅ Accuracy: 0.9201, ECE: 0.0217, LogLoss: 0.2937
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.001s

    🔧 [ 85.0%] Testing calibration method: IsotonicRegression on NaiveBayes
        ✅ Accuracy: 0.9201, ECE: 0.0340, LogLoss: 0.6668
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 85.5%] Testing calibration method: GPCalibration on NaiveBayes
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 175.348249
  Number of iterations: 88
  Number of functions evaluations: 97

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 175.348249
  Number of iterations: 88
  Number of functions evaluations: 97

        ✅ Accuracy: 0.9211, ECE: 0.0338, LogLoss: 0.3237
        ⏱️  Calib Fit: 1.58s, Calib Pred: 0.280s

🤖 Processing KNN classifier...
--------------------------------------------------
    🏋️  Training KNN base classifier...
    ✅ KNN base classifier trained successfully
    ⏱️  Fit: 0.00s, Predict: 0.046s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 85.9%] Testing calibration method: Uncalibrated on KNN
        ✅ Accuracy: 0.9351, ECE: 0.0393, LogLoss: 0.7026
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 86.4%] Testing calibration method: PlattScaling on KNN
        ✅ Accuracy: 0.9371, ECE: 0.0355, LogLoss: 0.2244
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 86.8%] Testing calibration method: IsotonicRegression on KNN
        ✅ Accuracy: 0.9351, ECE: 0.0261, LogLoss: 0.2228
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 87.3%] Testing calibration method: GPCalibration on KNN
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7852.178244
  Number of iterations: 62
  Number of functions evaluations: 70

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7852.178244
  Number of iterations: 62
  Number of functions evaluations: 70

        ✅ Accuracy: 0.9371, ECE: 0.0487, LogLoss: 0.7096
        ⏱️  Calib Fit: 1.35s, Calib Pred: 0.249s

🤖 Processing XGBoost classifier...
--------------------------------------------------
    🏋️  Training XGBoost base classifier...
[14:36:04] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
    ✅ XGBoost base classifier trained successfully
    ⏱️  Fit: 0.63s, Predict: 0.010s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 87.7%] Testing calibration method: Uncalibrated on XGBoost
        ✅ Accuracy: 0.9530, ECE: 0.0334, LogLoss: 0.1556
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 88.2%] Testing calibration method: PlattScaling on XGBoost
        ✅ Accuracy: 0.9510, ECE: 0.0358, LogLoss: 0.2177
        ⏱️  Calib Fit: 0.03s, Calib Pred: 0.002s

    🔧 [ 88.6%] Testing calibration method: IsotonicRegression on XGBoost
        ✅ Accuracy: 0.9540, ECE: 0.0404, LogLoss: 0.2742
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.002s

    🔧 [ 89.1%] Testing calibration method: GPCalibration on XGBoost
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 74.510348
  Number of iterations: 181
  Number of functions evaluations: 208

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 74.510348
  Number of iterations: 181
  Number of functions evaluations: 208

        ✅ Accuracy: 0.9520, ECE: 0.0427, LogLoss: 0.1294
        ⏱️  Calib Fit: 1.69s, Calib Pred: 0.245s

🤖 Processing DecisionTree classifier...
--------------------------------------------------
    🏋️  Training DecisionTree base classifier...
    ✅ DecisionTree base classifier trained successfully
    ⏱️  Fit: 0.03s, Predict: 0.008s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 89.5%] Testing calibration method: Uncalibrated on DecisionTree
        ✅ Accuracy: 0.9111, ECE: 0.0389, LogLoss: 3.0709
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 90.0%] Testing calibration method: PlattScaling on DecisionTree
        ✅ Accuracy: 0.9111, ECE: 0.0738, LogLoss: 0.4067
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 90.5%] Testing calibration method: IsotonicRegression on DecisionTree
        ✅ Accuracy: 0.9111, ECE: 0.0738, LogLoss: 0.4616
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 90.9%] Testing calibration method: GPCalibration on DecisionTree
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 35292.640976
  Number of iterations: 73
  Number of functions evaluations: 176

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 35292.640976
  Number of iterations: 73
  Number of functions evaluations: 176

        ✅ Accuracy: 0.9111, ECE: 0.2359, LogLoss: 0.5567
        ⏱️  Calib Fit: 1.55s, Calib Pred: 0.241s

🤖 Processing SVC classifier...
--------------------------------------------------
    🏋️  Training SVC base classifier...
    ✅ SVC base classifier trained successfully
    ⏱️  Fit: 0.51s, Predict: 0.130s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 91.4%] Testing calibration method: Uncalibrated on SVC
        ✅ Accuracy: 0.9361, ECE: 0.0382, LogLoss: 0.1533
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 91.8%] Testing calibration method: PlattScaling on SVC
        ✅ Accuracy: 0.9391, ECE: 0.0329, LogLoss: 0.2012
        ⏱️  Calib Fit: 0.03s, Calib Pred: 0.003s

    🔧 [ 92.3%] Testing calibration method: IsotonicRegression on SVC
        ✅ Accuracy: 0.9361, ECE: 0.0403, LogLoss: 0.4036
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.005s

    🔧 [ 92.7%] Testing calibration method: GPCalibration on SVC
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 34
  Number of functions evaluations: 39

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 34
  Number of functions evaluations: 39

        ✅ Accuracy: 0.9361, ECE: 0.0382, LogLoss: 0.1533
        ⏱️  Calib Fit: 1.31s, Calib Pred: 0.229s

🤖 Processing ExtraTree classifier...
--------------------------------------------------
    🏋️  Training ExtraTree base classifier...
    ✅ ExtraTree base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.003s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 93.2%] Testing calibration method: Uncalibrated on ExtraTree
        ✅ Accuracy: 0.8701, ECE: 0.0799, LogLoss: 4.4856
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 93.6%] Testing calibration method: PlattScaling on ExtraTree
        ✅ Accuracy: 0.8701, ECE: 0.0076, LogLoss: 0.5043
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.000s

    🔧 [ 94.1%] Testing calibration method: IsotonicRegression on ExtraTree
        ✅ Accuracy: 0.8701, ECE: 0.0076, LogLoss: 0.5043
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 94.5%] Testing calibration method: GPCalibration on ExtraTree
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53467.485480
  Number of iterations: 23
  Number of functions evaluations: 109

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53467.485480
  Number of iterations: 23
  Number of functions evaluations: 109

        ✅ Accuracy: 0.8701, ECE: 0.0799, LogLoss: 4.4856
        ⏱️  Calib Fit: 1.76s, Calib Pred: 0.239s

🤖 Processing SGD classifier...
--------------------------------------------------
    🏋️  Training SGD base classifier...
    ✅ SGD base classifier trained successfully
    ⏱️  Fit: 0.08s, Predict: 0.004s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 95.0%] Testing calibration method: Uncalibrated on SGD
        ✅ Accuracy: 0.8362, ECE: 0.1326, LogLoss: 0.5357
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 95.5%] Testing calibration method: PlattScaling on SGD
        ✅ Accuracy: 0.8422, ECE: 0.0582, LogLoss: 0.4555
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.002s

    🔧 [ 95.9%] Testing calibration method: IsotonicRegression on SGD
        ✅ Accuracy: 0.8412, ECE: 0.0508, LogLoss: 0.7054
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.001s

    🔧 [ 96.4%] Testing calibration method: GPCalibration on SGD
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.307741
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.307741
  Number of iterations: 200
  Number of functions evaluations: 230

        ✅ Accuracy: 0.8362, ECE: 0.0263, LogLoss: 0.4821
        ⏱️  Calib Fit: 2.09s, Calib Pred: 0.234s

🤖 Processing MLP classifier...
--------------------------------------------------
    🏋️  Training MLP base classifier...
    ✅ MLP base classifier trained successfully
    ⏱️  Fit: 8.66s, Predict: 0.005s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 96.8%] Testing calibration method: Uncalibrated on MLP
        ✅ Accuracy: 0.9510, ECE: 0.0283, LogLoss: 0.1466
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 97.3%] Testing calibration method: PlattScaling on MLP
        ✅ Accuracy: 0.9510, ECE: 0.0322, LogLoss: 0.1837
        ⏱️  Calib Fit: 0.02s, Calib Pred: 0.008s

    🔧 [ 97.7%] Testing calibration method: IsotonicRegression on MLP
        ✅ Accuracy: 0.9481, ECE: 0.0409, LogLoss: 0.5414
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 98.2%] Testing calibration method: GPCalibration on MLP
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.351994
  Number of iterations: 119
  Number of functions evaluations: 127

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.351994
  Number of iterations: 119
  Number of functions evaluations: 127

        ✅ Accuracy: 0.9520, ECE: 0.0366, LogLoss: 0.1424
        ⏱️  Calib Fit: 1.78s, Calib Pred: 0.278s

🤖 Processing BernoulliNB classifier...
--------------------------------------------------
    🏋️  Training BernoulliNB base classifier...
    ✅ BernoulliNB base classifier trained successfully
    ⏱️  Fit: 0.01s, Predict: 0.000s
    📊 Uncalibrated probabilities shape: (1001, 4)
    🔧 Data types - Proba: float64, Labels: int64

    🔧 [ 98.6%] Testing calibration method: Uncalibrated on BernoulliNB
        ✅ Accuracy: 0.8252, ECE: 0.0357, LogLoss: 0.3893
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.000s

    🔧 [ 99.1%] Testing calibration method: PlattScaling on BernoulliNB
        ✅ Accuracy: 0.8262, ECE: 0.0809, LogLoss: 0.4461
        ⏱️  Calib Fit: 0.01s, Calib Pred: 0.000s

    🔧 [ 99.5%] Testing calibration method: IsotonicRegression on BernoulliNB
        ✅ Accuracy: 0.8222, ECE: 0.0462, LogLoss: 0.5138
        ⏱️  Calib Fit: 0.00s, Calib Pred: 0.008s

    🔧 [100.0%] Testing calibration method: GPCalibration on BernoulliNB
        🔧 GP input shapes: proba (500, 4), labels (500,)
        🔧 GP input dtypes: proba float64, labels int64
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.148019
  Number of iterations: 70
  Number of functions evaluations: 82

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.148019
  Number of iterations: 70
  Number of functions evaluations: 82

        ✅ Accuracy: 0.8252, ECE: 0.0284, LogLoss: 0.3893
        ⏱️  Calib Fit: 1.62s, Calib Pred: 0.275s

================================================================================
✅ CALIBRATION COMPLETED: 220 combinations processed
📊 Total classifier-calibration combinations: 11 × 4 = 44 per dataset
================================================================================

In [132]:
# Create comprehensive calibration results DataFrame
calibration_results_df = pd.DataFrame(calibration_results)

print("="*80)
print("📊 CALIBRATION RESULTS ANALYSIS")
print("="*80)

if len(calibration_results_df) > 0:
    # Remove error rows for analysis
    valid_results = calibration_results_df.dropna(subset=['ECE', 'LogLoss', 'Accuracy'])
    
    if len(valid_results) > 0:
        print(f"\nValid results: {len(valid_results)} out of {len(calibration_results_df)}")
        
        # Summary by calibration method
        print("\n📋 SUMMARY BY CALIBRATION METHOD:")
        print("-" * 80)
        
        method_summary = valid_results.groupby('CalibrationMethod').agg({
            'ECE': ['mean', 'std', 'min', 'max'],
            'LogLoss': ['mean', 'std', 'min', 'max'],
            'Accuracy': ['mean', 'std', 'min', 'max']
        }).round(4)
        
        print(f"{'Method':<20} {'ECE_Mean':<10} {'ECE_Std':<10} {'LogLoss_Mean':<12} {'LogLoss_Std':<12}")
        print("-" * 80)
        
        for method in method_summary.index:
            ece_mean = method_summary.loc[method, ('ECE', 'mean')]
            ece_std = method_summary.loc[method, ('ECE', 'std')]
            logloss_mean = method_summary.loc[method, ('LogLoss', 'mean')]
            logloss_std = method_summary.loc[method, ('LogLoss', 'std')]
            
            print(f"{method:<20} {ece_mean:<10.4f} {ece_std:<10.4f} {logloss_mean:<12.4f} {logloss_std:<12.4f}")
        
        # Detailed results table
        print(f"\n📋 DETAILED CALIBRATION RESULTS:")
        print("-" * 140)
        print(f"{'Dataset':<15} {'Classifier':<12} {'Method':<20} {'Accuracy':<10} {'ECE':<8} {'LogLoss':<10} {'CalibTime':<10}")
        print("-" * 140)
        
        for _, row in valid_results.iterrows():
            calib_time = row['CalibFitTime'] + row['CalibPredTime'] if pd.notna(row['CalibFitTime']) else 0
            classifier = row.get('Classifier', 'N/A')
            print(f"{row['Dataset']:<15} {classifier:<12} {row['CalibrationMethod']:<20} {row['Accuracy']:<10.4f} "
                  f"{row['ECE']:<8.4f} {row['LogLoss']:<10.4f} {calib_time:<10.3f}")
        
        # Best performers analysis
        print(f"\n🏆 BEST CALIBRATION METHODS:")
        print("-" * 60)
        
        # Best ECE (lowest is better)
        best_ece = valid_results.loc[valid_results['ECE'].idxmin()]
        print(f"Best ECE: {best_ece['CalibrationMethod']} on {best_ece['Dataset']} = {best_ece['ECE']:.4f}")
        
        # Best LogLoss (lowest is better)
        best_logloss = valid_results.loc[valid_results['LogLoss'].idxmin()]
        print(f"Best LogLoss: {best_logloss['CalibrationMethod']} on {best_logloss['Dataset']} = {best_logloss['LogLoss']:.4f}")
        
        # Improvement analysis
        print(f"\n📈 CALIBRATION IMPROVEMENTS:")
        print("-" * 60)
        
        if 'Uncalibrated' in valid_results['CalibrationMethod'].values:
            for dataset in valid_results['Dataset'].unique():
                dataset_results = valid_results[valid_results['Dataset'] == dataset]
                
                uncal_result = dataset_results[dataset_results['CalibrationMethod'] == 'Uncalibrated']
                if len(uncal_result) > 0:
                    uncal_ece = uncal_result['ECE'].iloc[0]
                    uncal_logloss = uncal_result['LogLoss'].iloc[0]
                    
                    print(f"\n{dataset}:")
                    print(f"  Uncalibrated - ECE: {uncal_ece:.4f}, LogLoss: {uncal_logloss:.4f}")
                    
                    # Find best calibrated method for this dataset
                    calib_results = dataset_results[dataset_results['CalibrationMethod'] != 'Uncalibrated']
                    if len(calib_results) > 0:
                        best_ece_method = calib_results.loc[calib_results['ECE'].idxmin()]
                        best_logloss_method = calib_results.loc[calib_results['LogLoss'].idxmin()]
                        
                        ece_improvement = ((uncal_ece - best_ece_method['ECE']) / uncal_ece) * 100
                        logloss_improvement = ((uncal_logloss - best_logloss_method['LogLoss']) / uncal_logloss) * 100
                        
                        print(f"  Best ECE: {best_ece_method['CalibrationMethod']} - "
                              f"ECE: {best_ece_method['ECE']:.4f} ({ece_improvement:+.1f}% improvement)")
                        print(f"  Best LogLoss: {best_logloss_method['CalibrationMethod']} - "
                              f"LogLoss: {best_logloss_method['LogLoss']:.4f} ({logloss_improvement:+.1f}% improvement)")
        
        # Save calibration results
        print(f"\n💾 CALIBRATION RESULTS SAVED:")
        print("-" * 40)
        print("- calibration_results_df: Complete DataFrame with all calibration results")
        print("- method_summary: Summary statistics by calibration method")
        print("- detailed_calibration_results: Dictionary with nested results")
        
    else:
        print("❌ No valid calibration results found")
        
else:
    print("❌ No calibration results to analyze")

print(f"\n🎯 CALIBRATION ANALYSIS COMPLETE!")
print("="*80)

================================================================================
📊 CALIBRATION RESULTS ANALYSIS
================================================================================

Valid results: 220 out of 220

📋 SUMMARY BY CALIBRATION METHOD:
--------------------------------------------------------------------------------
Method               ECE_Mean   ECE_Std    LogLoss_Mean LogLoss_Std
--------------------------------------------------------------------------------
GPCalibration        0.0917     0.0793     1.2513       2.3768
IsotonicRegression   0.0615     0.0361     0.6976       0.4821
PlattScaling         0.0627     0.0332     0.5078       0.2619
Uncalibrated         0.1224     0.1267     2.1362       3.2607

📋 DETAILED CALIBRATION RESULTS:
--------------------------------------------------------------------------------------------------------------------------------------------
Dataset         Classifier   Method               Accuracy   ECE      LogLoss    CalibTime
--------------------------------------------------------------------------------------------------------------------------------------------
car_evaluation  RandomForest Uncalibrated         0.9798     0.1291   0.1691     0.000
car_evaluation  RandomForest PlattScaling         0.9711     0.0549   0.4339     0.049
car_evaluation  RandomForest IsotonicRegression   0.9682     0.0479   0.5332     0.006
car_evaluation  RandomForest GPCalibration        0.9798     0.0525   0.0716     2.040
car_evaluation  AdaBoost     Uncalibrated         0.7919     0.1006   0.5450     0.000
car_evaluation  AdaBoost     PlattScaling         0.8121     0.0734   0.4859     0.022
car_evaluation  AdaBoost     IsotonicRegression   0.8353     0.0812   0.5193     0.005
car_evaluation  AdaBoost     GPCalibration        0.7832     0.0937   0.4132     1.769
car_evaluation  NaiveBayes   Uncalibrated         0.7977     0.0333   4.8376     0.000
car_evaluation  NaiveBayes   PlattScaling         0.7977     0.0549   0.5347     0.028
car_evaluation  NaiveBayes   IsotonicRegression   0.8613     0.0638   0.6426     0.005
car_evaluation  NaiveBayes   GPCalibration        0.8555     0.0564   1.3956     1.845
car_evaluation  KNN          Uncalibrated         0.8931     0.1061   0.4035     0.000
car_evaluation  KNN          PlattScaling         0.9162     0.0792   0.2873     0.021
car_evaluation  KNN          IsotonicRegression   0.8555     0.0859   0.3698     0.008
car_evaluation  KNN          GPCalibration        0.8844     0.0740   0.3819     1.956
car_evaluation  XGBoost      Uncalibrated         0.9942     0.0586   0.0310     0.000
car_evaluation  XGBoost      PlattScaling         0.9942     0.0451   0.0256     0.032
car_evaluation  XGBoost      IsotonicRegression   0.9942     0.0507   0.0151     0.008
car_evaluation  XGBoost      GPCalibration        0.9942     0.0476   0.0252     2.102
car_evaluation  DecisionTree Uncalibrated         0.9711     0.0211   0.9982     0.000
car_evaluation  DecisionTree PlattScaling         0.9711     0.0424   0.1598     0.027
car_evaluation  DecisionTree IsotonicRegression   0.9711     0.0424   0.1598     0.009
car_evaluation  DecisionTree GPCalibration        0.9711     0.2547   0.3934     1.817
car_evaluation  SVC          Uncalibrated         0.9798     0.0507   0.0562     0.000
car_evaluation  SVC          PlattScaling         0.9769     0.0524   0.2024     0.026
car_evaluation  SVC          IsotonicRegression   0.9711     0.0463   0.2390     0.011
car_evaluation  SVC          GPCalibration        0.9798     0.0507   0.0562     1.636
car_evaluation  ExtraTree    Uncalibrated         0.8844     0.0656   3.9929     0.000
car_evaluation  ExtraTree    PlattScaling         0.8844     0.0576   0.4395     0.016
car_evaluation  ExtraTree    IsotonicRegression   0.8844     0.0576   0.4395     0.007
car_evaluation  ExtraTree    GPCalibration        0.8844     0.0656   3.9929     1.745
car_evaluation  SGD          Uncalibrated         0.9104     0.0790   0.2169     0.000
car_evaluation  SGD          PlattScaling         0.9046     0.0627   0.1880     0.025
car_evaluation  SGD          IsotonicRegression   0.9191     0.0562   0.3600     0.010
car_evaluation  SGD          GPCalibration        0.9104     0.0700   0.2099     1.960
car_evaluation  MLP          Uncalibrated         0.9913     0.0568   0.0332     0.000
car_evaluation  MLP          PlattScaling         0.9913     0.0491   0.0363     0.025
car_evaluation  MLP          IsotonicRegression   0.9913     0.0514   0.2102     0.006
car_evaluation  MLP          GPCalibration        0.9913     0.0536   0.0309     2.270
car_evaluation  BernoulliNB  Uncalibrated         0.8728     0.0923   0.2792     0.000
car_evaluation  BernoulliNB  PlattScaling         0.8786     0.0501   0.2526     0.027
car_evaluation  BernoulliNB  IsotonicRegression   0.8960     0.0651   0.2259     0.008
car_evaluation  BernoulliNB  GPCalibration        0.8757     0.0575   0.2533     2.111
dry_bean        RandomForest Uncalibrated         0.9177     0.0316   0.3954     0.000
dry_bean        RandomForest PlattScaling         0.9174     0.0341   0.2819     0.065
dry_bean        RandomForest IsotonicRegression   0.9163     0.0314   0.2819     0.017
dry_bean        RandomForest GPCalibration        0.9174     0.0313   0.3954     2.043
dry_bean        AdaBoost     Uncalibrated         0.4679     0.2159   1.7752     0.000
dry_bean        AdaBoost     PlattScaling         0.4341     0.0416   1.3013     0.054
dry_bean        AdaBoost     IsotonicRegression   0.4708     0.0847   1.2270     0.012
dry_bean        AdaBoost     GPCalibration        0.4326     0.0881   1.3168     2.831
dry_bean        NaiveBayes   Uncalibrated         0.8924     0.0692   0.9678     0.000
dry_bean        NaiveBayes   PlattScaling         0.8931     0.0483   0.4496     0.050
dry_bean        NaiveBayes   IsotonicRegression   0.9005     0.0295   0.3769     0.013
dry_bean        NaiveBayes   GPCalibration        0.8696     0.0400   0.5973     3.434
dry_bean        KNN          Uncalibrated         0.9130     0.0287   0.9623     0.000
dry_bean        KNN          PlattScaling         0.9141     0.0396   0.3007     0.054
dry_bean        KNN          IsotonicRegression   0.9152     0.0342   0.2792     0.012
dry_bean        KNN          GPCalibration        0.9133     0.0452   0.9737     2.005
dry_bean        XGBoost      Uncalibrated         0.9170     0.0284   0.2727     0.000
dry_bean        XGBoost      PlattScaling         0.9166     0.0183   0.3255     0.070
dry_bean        XGBoost      IsotonicRegression   0.9163     0.0339   0.3841     0.011
dry_bean        XGBoost      GPCalibration        0.9188     0.0364   0.2276     3.045
dry_bean        DecisionTree Uncalibrated         0.8902     0.0598   3.7925     0.000
dry_bean        DecisionTree PlattScaling         0.8902     0.0575   0.5049     0.045
dry_bean        DecisionTree IsotonicRegression   0.8902     0.0575   0.5049     0.009
dry_bean        DecisionTree GPCalibration        0.8902     0.1450   0.6197     2.149
dry_bean        SVC          Uncalibrated         0.9225     0.0355   0.2125     0.000
dry_bean        SVC          PlattScaling         0.9247     0.0307   0.2737     0.046
dry_bean        SVC          IsotonicRegression   0.9210     0.0295   0.4519     0.012
dry_bean        SVC          GPCalibration        0.9225     0.0355   0.2125     2.290
dry_bean        ExtraTree    Uncalibrated         0.8806     0.0694   4.1223     0.000
dry_bean        ExtraTree    PlattScaling         0.8806     0.0148   0.5386     0.045
dry_bean        ExtraTree    IsotonicRegression   0.8806     0.0148   0.5386     0.010
dry_bean        ExtraTree    GPCalibration        0.8806     0.1881   0.6886     2.139
dry_bean        SGD          Uncalibrated         0.9097     0.0538   0.2563     0.000
dry_bean        SGD          PlattScaling         0.9185     0.0382   0.2714     0.056
dry_bean        SGD          IsotonicRegression   0.9111     0.0331   0.3986     0.019
dry_bean        SGD          GPCalibration        0.9089     0.0339   0.2453     3.214
dry_bean        MLP          Uncalibrated         0.9232     0.0333   0.2143     0.000
dry_bean        MLP          PlattScaling         0.9236     0.0281   0.2783     0.049
dry_bean        MLP          IsotonicRegression   0.9221     0.0347   0.4170     0.018
dry_bean        MLP          GPCalibration        0.9232     0.0333   0.2143     2.009
dry_bean        BernoulliNB  Uncalibrated         0.7150     0.1397   1.1424     0.000
dry_bean        BernoulliNB  PlattScaling         0.7312     0.0272   0.8529     0.040
dry_bean        BernoulliNB  IsotonicRegression   0.7492     0.0271   0.7783     0.018
dry_bean        BernoulliNB  GPCalibration        0.7154     0.0378   0.9158     3.785
student_dropout RandomForest Uncalibrated         0.7856     0.0786   0.6187     0.000
student_dropout RandomForest PlattScaling         0.7912     0.0591   0.5366     0.016
student_dropout RandomForest IsotonicRegression   0.7889     0.0420   0.7671     0.000
student_dropout RandomForest GPCalibration        0.7867     0.0556   0.6102     1.988
student_dropout AdaBoost     Uncalibrated         0.7664     0.3805   1.0561     0.000
student_dropout AdaBoost     PlattScaling         0.7483     0.1460   0.6778     0.019
student_dropout AdaBoost     IsotonicRegression   0.7664     0.0659   0.7579     0.003
student_dropout AdaBoost     GPCalibration        0.7483     0.0741   0.6351     2.118
student_dropout NaiveBayes   Uncalibrated         0.6840     0.2014   2.6933     0.000
student_dropout NaiveBayes   PlattScaling         0.6761     0.0904   0.7978     0.016
student_dropout NaiveBayes   IsotonicRegression   0.6874     0.0619   0.7968     0.010
student_dropout NaiveBayes   GPCalibration        0.5621     0.1570   2.0198     2.119
student_dropout KNN          Uncalibrated         0.6840     0.0447   3.1689     0.000
student_dropout KNN          PlattScaling         0.6998     0.0650   0.7436     0.019
student_dropout KNN          IsotonicRegression   0.7088     0.0592   0.8018     0.002
student_dropout KNN          GPCalibration        0.6727     0.0762   0.8680     1.859
student_dropout XGBoost      Uncalibrated         0.7765     0.0703   0.6116     0.000
student_dropout XGBoost      PlattScaling         0.7799     0.0825   0.5923     0.022
student_dropout XGBoost      IsotonicRegression   0.7630     0.0386   0.7495     0.009
student_dropout XGBoost      GPCalibration        0.7777     0.0304   0.5527     2.227
student_dropout DecisionTree Uncalibrated         0.7122     0.2378   9.9406     0.000
student_dropout DecisionTree PlattScaling         0.7122     0.1056   0.7823     0.020
student_dropout DecisionTree IsotonicRegression   0.7122     0.1056   0.7823     0.007
student_dropout DecisionTree GPCalibration        0.7122     0.0449   0.8031     1.692
student_dropout SVC          Uncalibrated         0.7596     0.0470   0.5922     0.000
student_dropout SVC          PlattScaling         0.7596     0.0588   0.6077     0.013
student_dropout SVC          IsotonicRegression   0.7641     0.0284   0.7003     0.006
student_dropout SVC          GPCalibration        0.7596     0.0469   0.5922     1.553
student_dropout ExtraTree    Uncalibrated         0.6546     0.2954   11.9287    0.000
student_dropout ExtraTree    PlattScaling         0.6558     0.0827   0.8543     0.019
student_dropout ExtraTree    IsotonicRegression   0.6558     0.0827   0.8543     0.007
student_dropout ExtraTree    GPCalibration        0.6546     0.0415   0.8894     1.616
student_dropout SGD          Uncalibrated         0.7551     0.0277   0.6788     0.000
student_dropout SGD          PlattScaling         0.7562     0.0665   0.6475     0.015
student_dropout SGD          IsotonicRegression   0.7494     0.0546   0.9209     0.008
student_dropout SGD          GPCalibration        0.7573     0.0457   0.6632     2.121
student_dropout MLP          Uncalibrated         0.7156     0.1619   1.4514     0.000
student_dropout MLP          PlattScaling         0.7280     0.0712   0.7243     0.010
student_dropout MLP          IsotonicRegression   0.7528     0.0605   0.8131     0.011
student_dropout MLP          GPCalibration        0.6806     0.0750   1.0153     2.085
student_dropout BernoulliNB  Uncalibrated         0.7404     0.0945   0.8490     0.000
student_dropout BernoulliNB  PlattScaling         0.7573     0.0523   0.6749     0.013
student_dropout BernoulliNB  IsotonicRegression   0.7415     0.0294   0.7657     0.007
student_dropout BernoulliNB  GPCalibration        0.7302     0.0438   0.7367     2.120
cirrhosis       RandomForest Uncalibrated         0.7619     0.1099   0.6345     0.000
cirrhosis       RandomForest PlattScaling         0.7619     0.1281   0.6298     0.013
cirrhosis       RandomForest IsotonicRegression   0.7262     0.1426   2.1405     0.002
cirrhosis       RandomForest GPCalibration        0.7619     0.1099   0.6345     1.440
cirrhosis       AdaBoost     Uncalibrated         0.7619     0.1979   0.7679     0.000
cirrhosis       AdaBoost     PlattScaling         0.7381     0.1085   0.6711     0.019
cirrhosis       AdaBoost     IsotonicRegression   0.7500     0.1133   1.8328     0.011
cirrhosis       AdaBoost     GPCalibration        0.7619     0.1979   0.7679     1.524
cirrhosis       NaiveBayes   Uncalibrated         0.2143     0.7226   11.1010    0.000
cirrhosis       NaiveBayes   PlattScaling         0.6190     0.0341   0.8165     0.011
cirrhosis       NaiveBayes   IsotonicRegression   0.6310     0.1336   1.5078     0.001
cirrhosis       NaiveBayes   GPCalibration        0.4643     0.3860   3.5520     1.880
cirrhosis       KNN          Uncalibrated         0.6667     0.1165   4.5147     0.000
cirrhosis       KNN          PlattScaling         0.6667     0.1497   1.0113     0.024
cirrhosis       KNN          IsotonicRegression   0.6667     0.1129   0.7507     0.003
cirrhosis       KNN          GPCalibration        0.6548     0.1243   4.5570     1.825
cirrhosis       XGBoost      Uncalibrated         0.7500     0.1438   0.9150     0.000
cirrhosis       XGBoost      PlattScaling         0.7500     0.1088   0.6781     0.020
cirrhosis       XGBoost      IsotonicRegression   0.7381     0.1024   1.3636     0.006
cirrhosis       XGBoost      GPCalibration        0.7024     0.1217   0.6647     1.535
cirrhosis       DecisionTree Uncalibrated         0.6905     0.2595   10.6906    0.000
cirrhosis       DecisionTree PlattScaling         0.7143     0.0651   0.7476     0.014
cirrhosis       DecisionTree IsotonicRegression   0.7143     0.0651   0.7476     0.001
cirrhosis       DecisionTree GPCalibration        0.6905     0.2595   10.6906    1.532
cirrhosis       SVC          Uncalibrated         0.7619     0.0723   0.6449     0.000
cirrhosis       SVC          PlattScaling         0.7381     0.1084   0.6696     0.015
cirrhosis       SVC          IsotonicRegression   0.6667     0.1486   1.0180     0.004
cirrhosis       SVC          GPCalibration        0.7619     0.0701   0.6444     2.023
cirrhosis       ExtraTree    Uncalibrated         0.6071     0.3429   13.5688    0.000
cirrhosis       ExtraTree    PlattScaling         0.6667     0.0586   0.7732     0.019
cirrhosis       ExtraTree    IsotonicRegression   0.6667     0.0195   0.7877     0.006
cirrhosis       ExtraTree    GPCalibration        0.6071     0.3429   13.5688    1.660
cirrhosis       SGD          Uncalibrated         0.7976     0.1674   1.7397     0.000
cirrhosis       SGD          PlattScaling         0.7976     0.0813   0.6275     0.019
cirrhosis       SGD          IsotonicRegression   0.7976     0.0660   1.3398     0.006
cirrhosis       SGD          GPCalibration        0.7143     0.1402   1.0814     1.774
cirrhosis       MLP          Uncalibrated         0.6905     0.1838   1.0871     0.000
cirrhosis       MLP          PlattScaling         0.7143     0.0435   0.7474     0.015
cirrhosis       MLP          IsotonicRegression   0.6905     0.0847   2.5657     0.004
cirrhosis       MLP          GPCalibration        0.5952     0.1506   0.7889     1.583
cirrhosis       BernoulliNB  Uncalibrated         0.6071     0.2625   1.1268     0.000
cirrhosis       BernoulliNB  PlattScaling         0.6071     0.1122   0.7871     0.016
cirrhosis       BernoulliNB  IsotonicRegression   0.5952     0.1340   1.1285     0.004
cirrhosis       BernoulliNB  GPCalibration        0.5833     0.1370   0.8036     1.803
air_quality     RandomForest Uncalibrated         0.9530     0.0647   0.1395     0.000
air_quality     RandomForest PlattScaling         0.9540     0.0489   0.1531     0.020
air_quality     RandomForest IsotonicRegression   0.9540     0.0430   0.2755     0.007
air_quality     RandomForest GPCalibration        0.9540     0.0490   0.1256     1.792
air_quality     AdaBoost     Uncalibrated         0.6144     0.4355   1.3139     0.000
air_quality     AdaBoost     PlattScaling         0.8262     0.1410   0.6182     0.027
air_quality     AdaBoost     IsotonicRegression   0.7812     0.1702   0.5523     0.004
air_quality     AdaBoost     GPCalibration        0.7782     0.1031   0.5506     2.428
air_quality     NaiveBayes   Uncalibrated         0.9201     0.0271   0.3399     0.000
air_quality     NaiveBayes   PlattScaling         0.9201     0.0217   0.2937     0.021
air_quality     NaiveBayes   IsotonicRegression   0.9201     0.0340   0.6668     0.009
air_quality     NaiveBayes   GPCalibration        0.9211     0.0338   0.3237     1.860
air_quality     KNN          Uncalibrated         0.9351     0.0393   0.7026     0.000
air_quality     KNN          PlattScaling         0.9371     0.0355   0.2244     0.019
air_quality     KNN          IsotonicRegression   0.9351     0.0261   0.2228     0.009
air_quality     KNN          GPCalibration        0.9371     0.0487   0.7096     1.599
air_quality     XGBoost      Uncalibrated         0.9530     0.0334   0.1556     0.000
air_quality     XGBoost      PlattScaling         0.9510     0.0358   0.2177     0.031
air_quality     XGBoost      IsotonicRegression   0.9540     0.0404   0.2742     0.008
air_quality     XGBoost      GPCalibration        0.9520     0.0427   0.1294     1.930
air_quality     DecisionTree Uncalibrated         0.9111     0.0389   3.0709     0.000
air_quality     DecisionTree PlattScaling         0.9111     0.0738   0.4067     0.021
air_quality     DecisionTree IsotonicRegression   0.9111     0.0738   0.4616     0.009
air_quality     DecisionTree GPCalibration        0.9111     0.2359   0.5567     1.791
air_quality     SVC          Uncalibrated         0.9361     0.0382   0.1533     0.000
air_quality     SVC          PlattScaling         0.9391     0.0329   0.2012     0.028
air_quality     SVC          IsotonicRegression   0.9361     0.0403   0.4036     0.009
air_quality     SVC          GPCalibration        0.9361     0.0382   0.1533     1.538
air_quality     ExtraTree    Uncalibrated         0.8701     0.0799   4.4856     0.000
air_quality     ExtraTree    PlattScaling         0.8701     0.0076   0.5043     0.021
air_quality     ExtraTree    IsotonicRegression   0.8701     0.0076   0.5043     0.004
air_quality     ExtraTree    GPCalibration        0.8701     0.0799   4.4856     2.000
air_quality     SGD          Uncalibrated         0.8362     0.1326   0.5357     0.000
air_quality     SGD          PlattScaling         0.8422     0.0582   0.4555     0.021
air_quality     SGD          IsotonicRegression   0.8412     0.0508   0.7054     0.007
air_quality     SGD          GPCalibration        0.8362     0.0263   0.4821     2.326
air_quality     MLP          Uncalibrated         0.9510     0.0283   0.1466     0.000
air_quality     MLP          PlattScaling         0.9510     0.0322   0.1837     0.033
air_quality     MLP          IsotonicRegression   0.9481     0.0409   0.5414     0.008
air_quality     MLP          GPCalibration        0.9520     0.0366   0.1424     2.061

In [133]:
calibration_results_df

,Dataset,Classifier,CalibrationMethod,Accuracy,ECE,LogLoss,BaseFitTime,BasePredTime,CalibFitTime,CalibPredTime,TotalTime,TrainSamples,CalibSamples,TestSamples,NumClasses,NumFeatures
0,car_evaluation,RandomForest,Uncalibrated,0.979769,0.129127,0.169055,0.273559,0.239690,0.000000,0.000000,0.513249,1209,173,346,4,21
1,car_evaluation,RandomForest,PlattScaling,0.971098,0.054897,0.433887,0.273559,0.239690,0.048593,0.000000,0.561842,1209,173,346,4,21
2,car_evaluation,RandomForest,IsotonicRegression,0.968208,0.047890,0.533222,0.273559,0.239690,0.006276,0.000000,0.519526,1209,173,346,4,21
3,car_evaluation,RandomForest,GPCalibration,0.979769,0.052457,0.071613,0.273559,0.239690,1.779932,0.259887,2.553068,1209,173,346,4,21
4,car_evaluation,AdaBoost,Uncalibrated,0.791908,0.100642,0.544952,0.111172,0.025883,0.000000,0.000000,0.137055,1209,173,346,4,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,air_quality,MLP,GPCalibration,0.952048,0.036648,0.142437,8.658581,0.005421,1.783179,0.278007,10.725188,3499,500,1001,4,9
216,air_quality,BernoulliNB,Uncalibrated,0.825175,0.035659,0.389303,0.005540,0.000000,0.000000,0.000000,0.005540,3499,500,1001,4,9
217,air_quality,BernoulliNB,PlattScaling,0.826174,0.080852,0.446095,0.005540,0.000000,0.012700,0.000000,0.018240,3499,500,1001,4,9
218,air_quality,BernoulliNB,IsotonicRegression,0.822178,0.046209,0.513777,0.005540,0.000000,0.000000,0.008322,0.013862,3499,500,1001,4,9
219,air_quality,BernoulliNB,GPCalibration,0.825175,0.028394,0.389297,0.005540,0.000000,1.618429,0.275021,1.898990,3499,500,1001,4,9

## 🔬 Kernel Comparison - Menggunakan Data dari Eksperimen Sebelumnya

Membandingkan semua kernel GPCalibration menggunakan data yang sudah di-split sebelumnya untuk menemukan kernel dengan ECE terkecil.

## ⚠️ CATATAN PENTING - Kernel Names & Performance

**Kernel yang tersedia di pycalib (LOWERCASE):**
- `'rbf'` - Radial Basis Function (Default, paling cepat)
- `'matern12'`, `'matern32'`, `'matern52'` - Matern kernels
- `'exponential'` - Exponential kernel
- `'linear'` - Linear kernel (sangat cepat)
- `'polynomial'` - Polynomial kernel
- `'cosine'` - Cosine kernel
- `'periodic'` - Periodic kernel
- `'white'` - White noise kernel
- `'rational_quadratic'` - Rational quadratic (GUNAKAN UNDERSCORE!)
- `'arc_cosine'` - Arc cosine kernel (GUNAKAN UNDERSCORE!)

**Tips untuk mempercepat:**
1. Kurangi `maxiter` dari 200 ke 100 atau 50
2. Kurangi `n_inducing_points` ke 5
3. Pilih subset kernel (mis. hanya rbf, matern32, matern52, linear)
4. Test pada 1-2 dataset dulu sebelum semua

In [110]:
# VERSI OPTIMIZED - Kernel Comparison yang Lebih Cepat
import time
import warnings
from pycalib.scoring import expected_calibration_error
from sklearn.metrics import log_loss
from pycalib.calibration_methods import GPCalibration
import numpy as np
import pandas as pd
warnings.filterwarnings('ignore')

print("="*100)
print("🔬 OPTIMIZED KERNEL COMPARISON - Fast Version")
print("="*100)

# KERNEL YANG BENAR (lowercase dengan underscore untuk yang terdiri dari 2 kata)
available_kernels_fast = [
    'rbf',              # Paling populer dan cepat
    'matern32',         # Balance antara smooth dan flexibility
    'matern52',         # Lebih smooth dari matern32
    'linear',           # Paling cepat, untuk relasi linear
]

# Jika ingin test semua (akan lebih lama):
available_kernels_all = [
    'rbf', 'matern12', 'matern32', 'matern52', 'exponential',
    'cosine', 'linear', 'polynomial', 'periodic',
    'white', 'rational_quadratic', 'arc_cosine'  # PERHATIKAN UNDERSCORE!
]

# PILIH MANA YANG MAU DIPAKAI:
USE_FAST_MODE = False  # Ubah ke False untuk test semua kernel

if USE_FAST_MODE:
    available_kernels = available_kernels_fast
    maxiter_value = 100  # Lebih cepat
    n_inducing = 5       # Lebih sedikit inducing points
    print("\n⚡ MODE: FAST (4 kernel populer, optimized parameters)")
else:
    available_kernels = available_kernels_all
    maxiter_value = 200  # Lebih akurat
    n_inducing = 10      # Lebih banyak inducing points
    print("\n🐢 MODE: COMPREHENSIVE (12 kernels, standard parameters)")

print(f"\n🎯 Kernels to test: {len(available_kernels)}")
print(f"   {', '.join(available_kernels)}")
print(f"   maxiter: {maxiter_value}, n_inducing_points: {n_inducing}")

print(f"\n📊 Datasets: {len(split_datasets)}")
print(f"   {', '.join(split_datasets.keys())}")
print(f"\n🤖 Classifiers: {len(multiclass_classifiers)}")
print(f"   {', '.join(multiclass_classifiers.keys())}")

# Calculate total combinations
total_combinations = len(split_datasets) * len(multiclass_classifiers) * len(available_kernels)
print(f"\n📈 Total combinations: {total_combinations}")

# Estimasi waktu (rough estimate)
avg_time_per_combination = 3 if USE_FAST_MODE else 8  # seconds
estimated_time = total_combinations * avg_time_per_combination
print(f"⏱️  Estimated time: ~{estimated_time//60} minutes ({estimated_time} seconds)")

# Store results untuk semua kernel
all_kernel_results = []
current_combination = 0
start_experiment_time = time.time()

print(f"\n{'='*100}")
print(f"🔄 STARTING KERNEL COMPARISON...")
print(f"{'='*100}")

# Loop through each dataset
for dataset_name, data_splits in split_datasets.items():
    print(f"\n{'='*100}")
    print(f"📂 DATASET: {dataset_name.upper()}")
    print(f"{'='*100}")
    
    # Extract splits
    X_train = data_splits['X_train']
    X_calib = data_splits['X_calib']
    X_test = data_splits['X_test']
    y_train = data_splits['y_train']
    y_calib = data_splits['y_calib']
    y_test = data_splits['y_test']
    
    # Encode labels if needed
    y_train_encoded, y_calib_encoded, y_test_encoded, label_encoder = encode_target_if_needed_calib(
        y_train, y_calib, y_test
    )
    
    n_classes = len(np.unique(y_train_encoded))
    
    print(f"   📊 Classes: {n_classes}")
    print(f"   📊 Train: {len(X_train)}, Calib: {len(X_calib)}, Test: {len(X_test)}")
    
    # Loop through each classifier
    for clf_name, clf_class in multiclass_classifiers.items():
        print(f"\n   🤖 CLASSIFIER: {clf_name}")
        print(f"   {'-'*90}")
        
        try:
            # Train classifier
            classifier = clf_class
            classifier.fit(X_train, y_train_encoded)
            
            # Get uncalibrated probabilities
            y_calib_proba_uncal = classifier.predict_proba(X_calib)
            y_test_proba_uncal = classifier.predict_proba(X_test)
            
            # Ensure proper dtype
            y_calib_proba_uncal, y_calib_encoded_safe = ensure_float64_dtype(
                y_calib_proba_uncal, y_calib_encoded
            )
            y_test_proba_uncal, y_test_encoded_safe = ensure_float64_dtype(
                y_test_proba_uncal, y_test_encoded
            )
            
            # Compute uncalibrated metrics
            uncal_ece = expected_calibration_error(y_test_encoded_safe, y_test_proba_uncal, n_bins=15)
            uncal_logloss = log_loss(y_test_encoded_safe, y_test_proba_uncal)
            
            print(f"      📊 Uncalibrated - ECE: {uncal_ece:.6f}, LogLoss: {uncal_logloss:.6f}")
            
            # Test each kernel
            for kernel in available_kernels:
                current_combination += 1
                progress = (current_combination / total_combinations) * 100
                elapsed_time = time.time() - start_experiment_time
                avg_time_so_far = elapsed_time / current_combination
                remaining_time = avg_time_so_far * (total_combinations - current_combination)
                
                print(f"      [{current_combination}/{total_combinations}] ({progress:.1f}%) {kernel}... ", end="")
                print(f"[ETA: {remaining_time/60:.1f}min] ", end="")
                
                try:
                    start_time = time.time()
                    
                    # Configure GPCalibration with OPTIMIZED parameters
                    gp_calib = GPCalibration(
                        n_classes=n_classes,
                        maxiter=maxiter_value,  # REDUCED for speed
                        n_inducing_points=min(n_inducing, len(y_calib_encoded_safe)//3),  # REDUCED
                        verbose=False,
                        random_state=42,
                        kernel=kernel,  # Will be converted to lowercase automatically
                        add_white_noise=True
                    )
                    
                    # Fit calibration
                    fit_start = time.time()
                    gp_calib.fit(y_calib_proba_uncal, y_calib_encoded_safe)
                    fit_time = time.time() - fit_start
                    
                    # Predict calibrated probabilities
                    pred_start = time.time()
                    y_test_proba_cal = gp_calib.predict_proba(y_test_proba_uncal)
                    pred_time = time.time() - pred_start
                    
                    total_time = time.time() - start_time
                    
                    # Compute calibrated metrics
                    cal_ece = expected_calibration_error(y_test_encoded_safe, y_test_proba_cal, n_bins=15)
                    cal_logloss = log_loss(y_test_encoded_safe, y_test_proba_cal)
                    
                    # Compute improvements
                    ece_improvement = ((uncal_ece - cal_ece) / uncal_ece * 100) if uncal_ece > 0 else 0
                    logloss_improvement = ((uncal_logloss - cal_logloss) / uncal_logloss * 100) if uncal_logloss > 0 else 0
                    
                    # Store results
                    all_kernel_results.append({
                        'Dataset': dataset_name,
                        'Classifier': clf_name,
                        'Kernel': kernel,
                        'n_classes': n_classes,
                        'Uncal_ECE': uncal_ece,
                        'Cal_ECE': cal_ece,
                        'ECE_Delta': uncal_ece - cal_ece,
                        'ECE_Improvement_%': ece_improvement,
                        'Uncal_LogLoss': uncal_logloss,
                        'Cal_LogLoss': cal_logloss,
                        'LogLoss_Delta': uncal_logloss - cal_logloss,
                        'LogLoss_Improvement_%': logloss_improvement,
                        'Fit_Time_sec': fit_time,
                        'Pred_Time_sec': pred_time,
                        'Total_Time_sec': total_time,
                        'Status': 'Success'
                    })
                    
                    print(f"✅ ECE: {cal_ece:.4f} ({ece_improvement:+.1f}%), {total_time:.1f}s")
                    
                except Exception as e:
                    print(f"❌ {str(e)[:40]}")
                    
                    # Store error result
                    all_kernel_results.append({
                        'Dataset': dataset_name,
                        'Classifier': clf_name,
                        'Kernel': kernel,
                        'n_classes': n_classes,
                        'Uncal_ECE': uncal_ece,
                        'Cal_ECE': np.nan,
                        'ECE_Delta': np.nan,
                        'ECE_Improvement_%': np.nan,
                        'Uncal_LogLoss': uncal_logloss,
                        'Cal_LogLoss': np.nan,
                        'LogLoss_Delta': np.nan,
                        'LogLoss_Improvement_%': np.nan,
                        'Fit_Time_sec': np.nan,
                        'Pred_Time_sec': np.nan,
                        'Total_Time_sec': np.nan,
                        'Status': f'Error: {str(e)[:80]}'
                    })
        
        except Exception as e:
            print(f"   ❌ Classifier {clf_name} failed: {str(e)[:100]}")
            continue

# Calculate total experiment time
total_experiment_time = time.time() - start_experiment_time

# Create comprehensive results DataFrame
kernel_comparison_df = pd.DataFrame(all_kernel_results)

print(f"\n{'='*100}")
print(f"📊 KERNEL COMPARISON COMPLETE!")
print(f"{'='*100}")
print(f"⏱️  Total experiment time: {total_experiment_time/60:.1f} minutes ({total_experiment_time:.0f} seconds)")

# Display summary statistics
print(f"\n📈 Summary:")
print(f"   Total experiments: {len(kernel_comparison_df)}")
success_count = (kernel_comparison_df['Status'] == 'Success').sum()
print(f"   Successful: {success_count} ({success_count/len(kernel_comparison_df)*100:.1f}%)")
print(f"   Failed: {len(kernel_comparison_df) - success_count}")

# Filter successful results
successful_results = kernel_comparison_df[kernel_comparison_df['Status'] == 'Success'].copy()

if len(successful_results) > 0:
    print(f"\n{'='*100}")
    print(f"🏆 OVERALL BEST KERNELS (Across All Datasets & Classifiers)")
    print(f"{'='*100}")
    
    # Best average ECE by kernel
    kernel_avg_ece = successful_results.groupby('Kernel')['Cal_ECE'].agg(['mean', 'std', 'min', 'max', 'count'])
    kernel_avg_ece = kernel_avg_ece.sort_values('mean')
    
    print(f"\n📊 Average Calibrated ECE by Kernel:")
    print(kernel_avg_ece.to_string())
    
    # Best kernel overall
    best_kernel = kernel_avg_ece.index[0]
    print(f"\n🥇 BEST KERNEL (Lowest Average ECE): {best_kernel}")
    print(f"   Average ECE: {kernel_avg_ece.loc[best_kernel, 'mean']:.6f} ± {kernel_avg_ece.loc[best_kernel, 'std']:.6f}")
    print(f"   Min ECE: {kernel_avg_ece.loc[best_kernel, 'min']:.6f}")
    print(f"   Max ECE: {kernel_avg_ece.loc[best_kernel, 'max']:.6f}")
    print(f"   Success rate: {kernel_avg_ece.loc[best_kernel, 'count']}/{len(split_datasets) * len(multiclass_classifiers)}")
    
    # Best improvement by kernel
    kernel_avg_improvement = successful_results.groupby('Kernel')['ECE_Improvement_%'].agg(['mean', 'std', 'min', 'max'])
    kernel_avg_improvement = kernel_avg_improvement.sort_values('mean', ascending=False)
    
    print(f"\n📈 Average ECE Improvement by Kernel:")
    print(kernel_avg_improvement.to_string())
    
    # Fastest kernel
    kernel_avg_time = successful_results.groupby('Kernel')['Total_Time_sec'].agg(['mean', 'std', 'min', 'max'])
    kernel_avg_time = kernel_avg_time.sort_values('mean')
    
    print(f"\n⏱️  Average Computation Time by Kernel:")
    print(kernel_avg_time.to_string())
    
    fastest_kernel = kernel_avg_time.index[0]
    print(f"\n⚡ FASTEST KERNEL: {fastest_kernel}")
    print(f"   Average Time: {kernel_avg_time.loc[fastest_kernel, 'mean']:.3f}s ± {kernel_avg_time.loc[fastest_kernel, 'std']:.3f}s")

print(f"\n{'='*100}")
print(f"✅ Kernel Comparison Analysis Completed!")
print(f"{'='*100}")

====================================================================================================
🔬 OPTIMIZED KERNEL COMPARISON - Fast Version
====================================================================================================

🐢 MODE: COMPREHENSIVE (12 kernels, standard parameters)

🎯 Kernels to test: 12
   rbf, matern12, matern32, matern52, exponential, cosine, linear, polynomial, periodic, white, rational_quadratic, arc_cosine
   maxiter: 200, n_inducing_points: 10

📊 Datasets: 5
   car_evaluation, dry_bean, student_dropout, cirrhosis, air_quality

🤖 Classifiers: 11
   RandomForest, AdaBoost, NaiveBayes, KNN, XGBoost, DecisionTree, SVC, ExtraTree, SGD, MLP, BernoulliNB

📈 Total combinations: 660
⏱️  Estimated time: ~88 minutes (5280 seconds)

====================================================================================================
🔄 STARTING KERNEL COMPARISON...
====================================================================================================

====================================================================================================
📂 DATASET: CAR_EVALUATION
====================================================================================================
   📊 Classes: 4
   📊 Train: 1209, Calib: 173, Test: 346

   🤖 CLASSIFIER: RandomForest
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.124068, LogLoss: 0.169055
      [1/660] (0.2%) rbf... [ETA: 7.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.599537
  Number of iterations: 200
  Number of functions evaluations: 223

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.599537
  Number of iterations: 200
  Number of functions evaluations: 223

✅ ECE: 0.0501 (+59.6%), 2.1s
      [2/660] (0.3%) matern12... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 24.162017
  Number of iterations: 39
  Number of functions evaluations: 67

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 24.162017
  Number of iterations: 39
  Number of functions evaluations: 67

✅ ECE: 0.0565 (+54.5%), 1.6s
      [3/660] (0.5%) matern32... [ETA: 16.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.926953
  Number of iterations: 200
  Number of functions evaluations: 227

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.926953
  Number of iterations: 200
  Number of functions evaluations: 227

✅ ECE: 0.0486 (+60.8%), 2.1s
      [4/660] (0.6%) matern52... [ETA: 17.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.782198
  Number of iterations: 200
  Number of functions evaluations: 234

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.782198
  Number of iterations: 200
  Number of functions evaluations: 234

✅ ECE: 0.0480 (+61.3%), 2.2s
      [5/660] (0.8%) exponential... [ETA: 19.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 24.075151
  Number of iterations: 40
  Number of functions evaluations: 59

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 24.075151
  Number of iterations: 40
  Number of functions evaluations: 59

✅ ECE: 0.0499 (+59.8%), 2.0s
      [6/660] (0.9%) cosine... [ETA: 19.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 20.820989
  Number of iterations: 98
  Number of functions evaluations: 112

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 20.820989
  Number of iterations: 98
  Number of functions evaluations: 112

✅ ECE: 0.0498 (+59.9%), 1.7s
      [7/660] (1.1%) linear... [ETA: 19.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 20.387122
  Number of iterations: 50
  Number of functions evaluations: 52

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 20.387122
  Number of iterations: 50
  Number of functions evaluations: 52

✅ ECE: 0.0511 (+58.8%), 1.2s
      [8/660] (1.2%) polynomial... [ETA: 18.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 20.768090
  Number of iterations: 64
  Number of functions evaluations: 73

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 20.768090
  Number of iterations: 64
  Number of functions evaluations: 73

✅ ECE: 0.0451 (+63.6%), 1.5s
      [9/660] (1.4%) periodic... [ETA: 18.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.619653
  Number of iterations: 200
  Number of functions evaluations: 239

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.619653
  Number of iterations: 200
  Number of functions evaluations: 239

✅ ECE: 0.0462 (+62.8%), 2.0s
      [10/660] (1.5%) white... [ETA: 18.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 33.194562
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 33.194562
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.1241 (+0.0%), 0.8s
      [11/660] (1.7%) rational_quadratic... [ETA: 17.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.603634
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 21.603634
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.0481 (+61.2%), 2.5s
      [12/660] (1.8%) arc_cosine... [ETA: 18.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: AdaBoost
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.122877, LogLoss: 0.544952
      [13/660] (2.0%) rbf... [ETA: 17.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.766139
  Number of iterations: 200
  Number of functions evaluations: 233

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.766139
  Number of iterations: 200
  Number of functions evaluations: 233

✅ ECE: 0.1158 (+5.8%), 2.1s
      [14/660] (2.1%) matern12... [ETA: 17.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 86.849605
  Number of iterations: 113
  Number of functions evaluations: 182

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 86.849605
  Number of iterations: 113
  Number of functions evaluations: 182

✅ ECE: 0.0919 (+25.2%), 1.9s
      [15/660] (2.3%) matern32... [ETA: 17.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 79.486818
  Number of iterations: 200
  Number of functions evaluations: 234

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 79.486818
  Number of iterations: 200
  Number of functions evaluations: 234

✅ ECE: 0.0811 (+34.0%), 2.1s
      [16/660] (2.4%) matern52... [ETA: 17.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.036457
  Number of iterations: 200
  Number of functions evaluations: 246

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.036457
  Number of iterations: 200
  Number of functions evaluations: 246

✅ ECE: 0.0943 (+23.2%), 2.3s
      [17/660] (2.6%) exponential... [ETA: 18.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 85.243411
  Number of iterations: 200
  Number of functions evaluations: 323

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 85.243411
  Number of iterations: 200
  Number of functions evaluations: 323

✅ ECE: 0.0915 (+25.6%), 2.2s
      [18/660] (2.7%) cosine... [ETA: 18.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 71.204887
  Number of iterations: 200
  Number of functions evaluations: 268

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 71.204887
  Number of iterations: 200
  Number of functions evaluations: 268

✅ ECE: 0.1083 (+11.8%), 2.4s
      [19/660] (2.9%) linear... [ETA: 18.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 94.172739
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 94.172739
  Number of iterations: 33
  Number of functions evaluations: 36

✅ ECE: 0.1425 (-16.0%), 1.2s
      [20/660] (3.0%) polynomial... [ETA: 18.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 83.405925
  Number of iterations: 200
  Number of functions evaluations: 266

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 83.405925
  Number of iterations: 200
  Number of functions evaluations: 266

✅ ECE: 0.1118 (+9.0%), 1.9s
      [21/660] (3.2%) periodic... [ETA: 18.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 84.462932
  Number of iterations: 200
  Number of functions evaluations: 241

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 84.462932
  Number of iterations: 200
  Number of functions evaluations: 241

✅ ECE: 0.0937 (+23.7%), 2.1s
      [22/660] (3.3%) white... [ETA: 18.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 98.057230
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 98.057230
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.1229 (+0.0%), 0.9s
      [23/660] (3.5%) rational_quadratic... [ETA: 18.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.569769
  Number of iterations: 200
  Number of functions evaluations: 239

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 81.569769
  Number of iterations: 200
  Number of functions evaluations: 239

✅ ECE: 0.1174 (+4.5%), 2.2s
      [24/660] (3.6%) arc_cosine... [ETA: 18.5min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: NaiveBayes
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.050000, LogLoss: 4.837557
      [25/660] (3.8%) rbf... [ETA: 17.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 221.707216
  Number of iterations: 52
  Number of functions evaluations: 171

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 221.707216
  Number of iterations: 52
  Number of functions evaluations: 171

✅ ECE: 0.0512 (-2.5%), 1.8s
      [26/660] (3.9%) matern12... [ETA: 17.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 493.784363
  Number of iterations: 51
  Number of functions evaluations: 130

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 493.784363
  Number of iterations: 51
  Number of functions evaluations: 130

✅ ECE: 0.0467 (+6.6%), 2.1s
      [27/660] (4.1%) matern32... [ETA: 17.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 218.929042
  Number of iterations: 147
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 218.929042
  Number of iterations: 147
  Number of functions evaluations: 232

✅ ECE: 0.0358 (+28.5%), 2.0s
      [28/660] (4.2%) matern52... [ETA: 18.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 227.589129
  Number of iterations: 45
  Number of functions evaluations: 85

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 227.589129
  Number of iterations: 45
  Number of functions evaluations: 85

✅ ECE: 0.0437 (+12.6%), 1.8s
      [29/660] (4.4%) exponential... [ETA: 18.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 854.542654
  Number of iterations: 39
  Number of functions evaluations: 115

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 854.542654
  Number of iterations: 39
  Number of functions evaluations: 115

✅ ECE: 0.0525 (-4.9%), 1.6s
      [30/660] (4.5%) cosine... [ETA: 17.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 217.753496
  Number of iterations: 200
  Number of functions evaluations: 248

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 217.753496
  Number of iterations: 200
  Number of functions evaluations: 248

✅ ECE: 0.0436 (+12.8%), 1.9s
      [31/660] (4.7%) linear... [ETA: 18.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 219.377637
  Number of iterations: 67
  Number of functions evaluations: 109

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 219.377637
  Number of iterations: 67
  Number of functions evaluations: 109

✅ ECE: 0.0372 (+25.5%), 1.4s
      [32/660] (4.8%) polynomial... [ETA: 17.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 213.961155
  Number of iterations: 200
  Number of functions evaluations: 265

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 213.961155
  Number of iterations: 200
  Number of functions evaluations: 265

✅ ECE: 0.0427 (+14.6%), 1.8s
      [33/660] (5.0%) periodic... [ETA: 17.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 845.519300
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 845.519300
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0580 (-15.9%), 1.8s
      [34/660] (5.2%) white... [ETA: 17.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 845.519300
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 845.519300
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0540 (-8.0%), 1.0s
      [35/660] (5.3%) rational_quadratic... [ETA: 17.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 222.379474
  Number of iterations: 86
  Number of functions evaluations: 121

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 222.379474
  Number of iterations: 86
  Number of functions evaluations: 121

✅ ECE: 0.0367 (+26.7%), 1.8s
      [36/660] (5.5%) arc_cosine... [ETA: 17.6min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: KNN
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.099205, LogLoss: 0.403463
      [37/660] (5.6%) rbf... [ETA: 17.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.530133
  Number of iterations: 173
  Number of functions evaluations: 210

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.530133
  Number of iterations: 173
  Number of functions evaluations: 210

✅ ECE: 0.0711 (+28.4%), 1.9s
      [38/660] (5.8%) matern12... [ETA: 17.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.779305
  Number of iterations: 107
  Number of functions evaluations: 269

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.779305
  Number of iterations: 107
  Number of functions evaluations: 269

✅ ECE: 0.0716 (+27.8%), 2.0s
      [39/660] (5.9%) matern32... [ETA: 17.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.549077
  Number of iterations: 147
  Number of functions evaluations: 188

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.549077
  Number of iterations: 147
  Number of functions evaluations: 188

✅ ECE: 0.0750 (+24.4%), 1.9s
      [40/660] (6.1%) matern52... [ETA: 17.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.532763
  Number of iterations: 158
  Number of functions evaluations: 185

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.532763
  Number of iterations: 158
  Number of functions evaluations: 185

✅ ECE: 0.0711 (+28.4%), 2.3s
      [41/660] (6.2%) exponential... [ETA: 17.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 769.121747
  Number of iterations: 79
  Number of functions evaluations: 166

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 769.121747
  Number of iterations: 79
  Number of functions evaluations: 166

✅ ECE: 0.0821 (+17.3%), 1.9s
      [42/660] (6.4%) cosine... [ETA: 17.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.837143
  Number of iterations: 61
  Number of functions evaluations: 68

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.837143
  Number of iterations: 61
  Number of functions evaluations: 68

✅ ECE: 0.0716 (+27.8%), 1.5s
      [43/660] (6.5%) linear... [ETA: 17.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 769.087963
  Number of iterations: 25
  Number of functions evaluations: 27

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 769.087963
  Number of iterations: 25
  Number of functions evaluations: 27

✅ ECE: 0.0756 (+23.8%), 1.1s
      [44/660] (6.7%) polynomial... [ETA: 17.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.530886
  Number of iterations: 31
  Number of functions evaluations: 33

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.530886
  Number of iterations: 31
  Number of functions evaluations: 33

✅ ECE: 0.0639 (+35.6%), 2.0s
      [45/660] (6.8%) periodic... [ETA: 17.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.513163
  Number of iterations: 113
  Number of functions evaluations: 156

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.513163
  Number of iterations: 113
  Number of functions evaluations: 156

✅ ECE: 0.0721 (+27.3%), 2.2s
      [46/660] (7.0%) white... [ETA: 17.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 769.265504
  Number of iterations: 21
  Number of functions evaluations: 22

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 769.265504
  Number of iterations: 21
  Number of functions evaluations: 22

✅ ECE: 0.0932 (+6.1%), 1.0s
      [47/660] (7.1%) rational_quadratic... [ETA: 17.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.680165
  Number of iterations: 155
  Number of functions evaluations: 180

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 768.680165
  Number of iterations: 155
  Number of functions evaluations: 180

✅ ECE: 0.0823 (+17.0%), 2.5s
      [48/660] (7.3%) arc_cosine... [ETA: 17.3min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: XGBoost
   ------------------------------------------------------------------------------------------
[15:04:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
      📊 Uncalibrated - ECE: 0.040597, LogLoss: 0.031049
      [49/660] (7.4%) rbf... [ETA: 17.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.707459
  Number of iterations: 200
  Number of functions evaluations: 213

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.707459
  Number of iterations: 200
  Number of functions evaluations: 213

✅ ECE: 0.0349 (+14.2%), 2.2s
      [50/660] (7.6%) matern12... [ETA: 17.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.997116
  Number of iterations: 103
  Number of functions evaluations: 178

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.997116
  Number of iterations: 103
  Number of functions evaluations: 178

✅ ECE: 0.0385 (+5.1%), 2.0s
      [51/660] (7.7%) matern32... [ETA: 17.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.769821
  Number of iterations: 200
  Number of functions evaluations: 215

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.769821
  Number of iterations: 200
  Number of functions evaluations: 215

✅ ECE: 0.0372 (+8.4%), 2.1s
      [52/660] (7.9%) matern52... [ETA: 17.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.733214
  Number of iterations: 200
  Number of functions evaluations: 220

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.733214
  Number of iterations: 200
  Number of functions evaluations: 220

✅ ECE: 0.0355 (+12.6%), 2.5s
      [53/660] (8.0%) exponential... [ETA: 17.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.950061
  Number of iterations: 153
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.950061
  Number of iterations: 153
  Number of functions evaluations: 232

✅ ECE: 0.0374 (+8.0%), 2.6s
      [54/660] (8.2%) cosine... [ETA: 17.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.140576
  Number of iterations: 115
  Number of functions evaluations: 136

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.140576
  Number of iterations: 115
  Number of functions evaluations: 136

✅ ECE: 0.0283 (+30.4%), 2.3s
      [55/660] (8.3%) linear... [ETA: 17.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.912473
  Number of iterations: 35
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.912473
  Number of iterations: 35
  Number of functions evaluations: 38

✅ ECE: 0.0360 (+11.3%), 1.2s
      [56/660] (8.5%) polynomial... [ETA: 17.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.809127
  Number of iterations: 109
  Number of functions evaluations: 141

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 8.809127
  Number of iterations: 109
  Number of functions evaluations: 141

✅ ECE: 0.0366 (+10.0%), 1.6s
      [57/660] (8.6%) periodic... [ETA: 17.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.708666
  Number of iterations: 200
  Number of functions evaluations: 217

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.708666
  Number of iterations: 200
  Number of functions evaluations: 217

✅ ECE: 0.0349 (+14.2%), 2.1s
      [58/660] (8.8%) white... [ETA: 17.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 9.010124
  Number of iterations: 18
  Number of functions evaluations: 19

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 9.010124
  Number of iterations: 18
  Number of functions evaluations: 19

✅ ECE: 0.0406 (+0.0%), 0.9s
      [59/660] (8.9%) rational_quadratic... [ETA: 17.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.724775
  Number of iterations: 200
  Number of functions evaluations: 221

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 8.724775
  Number of iterations: 200
  Number of functions evaluations: 221

✅ ECE: 0.0350 (+13.8%), 2.2s
      [60/660] (9.1%) arc_cosine... [ETA: 17.3min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: DecisionTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.004432, LogLoss: 0.998231
      [61/660] (9.2%) rbf... [ETA: 17.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 10565.459810
  Number of iterations: 41
  Number of functions evaluations: 129

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 10565.459810
  Number of iterations: 41
  Number of functions evaluations: 129

✅ ECE: 0.2529 (-5605.7%), 1.7s
      [62/660] (9.4%) matern12... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 6829.604368
  Number of iterations: 18
  Number of functions evaluations: 76

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 6829.604368
  Number of iterations: 18
  Number of functions evaluations: 76

✅ ECE: 0.0044 (+0.0%), 1.8s
      [63/660] (9.5%) matern32... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 9428.228035
  Number of iterations: 50
  Number of functions evaluations: 158

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 9428.228035
  Number of iterations: 50
  Number of functions evaluations: 158

✅ ECE: 0.4010 (-8948.1%), 1.9s
      [64/660] (9.7%) matern52... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8429.099227
  Number of iterations: 43
  Number of functions evaluations: 134

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8429.099227
  Number of iterations: 43
  Number of functions evaluations: 134

✅ ECE: 0.0044 (+0.0%), 1.9s
      [65/660] (9.8%) exponential... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8861.792556
  Number of iterations: 21
  Number of functions evaluations: 98

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8861.792556
  Number of iterations: 21
  Number of functions evaluations: 98

✅ ECE: 0.0044 (+0.0%), 1.6s
      [66/660] (10.0%) cosine... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 122.544440
  Number of iterations: 200
  Number of functions evaluations: 429

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 122.544440
  Number of iterations: 200
  Number of functions evaluations: 429

✅ ECE: 0.0532 (-1101.4%), 2.2s
      [67/660] (10.2%) linear... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 78.873182
  Number of iterations: 200
  Number of functions evaluations: 352

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 78.873182
  Number of iterations: 200
  Number of functions evaluations: 352

✅ ECE: 0.0044 (+0.0%), 1.8s
      [68/660] (10.3%) polynomial... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 76.432637
  Number of iterations: 200
  Number of functions evaluations: 292

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 76.432637
  Number of iterations: 200
  Number of functions evaluations: 292

✅ ECE: 0.0500 (-1028.2%), 1.8s
      [69/660] (10.5%) periodic... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 7083.964185
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 7083.964185
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0044 (+0.0%), 1.8s
      [70/660] (10.6%) white... [ETA: 16.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 7083.964185
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 7083.964185
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0044 (+0.0%), 0.8s
      [71/660] (10.8%) rational_quadratic... [ETA: 16.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 10978.339389
  Number of iterations: 48
  Number of functions evaluations: 141

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 10978.339389
  Number of iterations: 48
  Number of functions evaluations: 141

✅ ECE: 0.2016 (-4450.2%), 1.8s
      [72/660] (10.9%) arc_cosine... [ETA: 16.7min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SVC
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.038580, LogLoss: 0.056233
      [73/660] (11.1%) rbf... [ETA: 16.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 36
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 36
  Number of functions evaluations: 41

✅ ECE: 0.0386 (+0.0%), 1.6s
      [74/660] (11.2%) matern12... [ETA: 16.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 36
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 36
  Number of functions evaluations: 41

✅ ECE: 0.0386 (+0.0%), 1.6s
      [75/660] (11.4%) matern32... [ETA: 16.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

✅ ECE: 0.0386 (+0.0%), 1.6s
      [76/660] (11.5%) matern52... [ETA: 16.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

✅ ECE: 0.0386 (+0.0%), 1.9s
      [77/660] (11.7%) exponential... [ETA: 16.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 35
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 35
  Number of functions evaluations: 41

✅ ECE: 0.0386 (+0.0%), 1.6s
      [78/660] (11.8%) cosine... [ETA: 16.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 34
  Number of functions evaluations: 38

✅ ECE: 0.0386 (+0.0%), 1.6s
      [79/660] (12.0%) linear... [ETA: 16.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398455
  Number of iterations: 38
  Number of functions evaluations: 44

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398455
  Number of iterations: 38
  Number of functions evaluations: 44

✅ ECE: 0.0386 (+0.0%), 1.3s
      [80/660] (12.1%) polynomial... [ETA: 16.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398453
  Number of iterations: 32
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398453
  Number of iterations: 32
  Number of functions evaluations: 35

✅ ECE: 0.0386 (+0.0%), 1.4s
      [81/660] (12.3%) periodic... [ETA: 16.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 15.865688
  Number of iterations: 200
  Number of functions evaluations: 226

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 15.865688
  Number of iterations: 200
  Number of functions evaluations: 226

✅ ECE: 0.0444 (-15.0%), 2.1s
      [82/660] (12.4%) white... [ETA: 16.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 16.398463
  Number of iterations: 18
  Number of functions evaluations: 19

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 16.398463
  Number of iterations: 18
  Number of functions evaluations: 19

✅ ECE: 0.0386 (+0.0%), 0.9s
      [83/660] (12.6%) rational_quadratic... [ETA: 16.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 16.398459
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0386 (+0.0%), 2.0s
      [84/660] (12.7%) arc_cosine... [ETA: 16.1min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: ExtraTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.082274, LogLoss: 3.992922
      [85/660] (12.9%) rbf... [ETA: 15.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 25880.112080
  Number of iterations: 37
  Number of functions evaluations: 131

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 25880.112080
  Number of iterations: 37
  Number of functions evaluations: 131

✅ ECE: 0.0823 (+0.0%), 1.8s
      [86/660] (13.0%) matern12... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 22699.899052
  Number of iterations: 22
  Number of functions evaluations: 96

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 22699.899052
  Number of iterations: 22
  Number of functions evaluations: 96

✅ ECE: 0.3304 (-301.5%), 1.6s
      [87/660] (13.2%) matern32... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 19221.870206
  Number of iterations: 39
  Number of functions evaluations: 120

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 19221.870206
  Number of iterations: 39
  Number of functions evaluations: 120

✅ ECE: 0.0823 (+0.0%), 1.8s
      [88/660] (13.3%) matern52... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 22526.645013
  Number of iterations: 41
  Number of functions evaluations: 129

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 22526.645013
  Number of iterations: 41
  Number of functions evaluations: 129

✅ ECE: 0.2157 (-162.1%), 1.8s
      [89/660] (13.5%) exponential... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 24113.995670
  Number of iterations: 19
  Number of functions evaluations: 108

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 24113.995670
  Number of iterations: 19
  Number of functions evaluations: 108

✅ ECE: 0.0217 (+73.7%), 1.7s
      [90/660] (13.6%) cosine... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 168.940884
  Number of iterations: 200
  Number of functions evaluations: 377

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 168.940884
  Number of iterations: 200
  Number of functions evaluations: 377

✅ ECE: 0.0153 (+81.3%), 2.4s
      [91/660] (13.8%) linear... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 135.172383
  Number of iterations: 200
  Number of functions evaluations: 344

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 135.172383
  Number of iterations: 200
  Number of functions evaluations: 344

✅ ECE: 0.0153 (+81.3%), 1.7s
      [92/660] (13.9%) polynomial... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 132.813472
  Number of iterations: 200
  Number of functions evaluations: 293

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 132.813472
  Number of iterations: 200
  Number of functions evaluations: 293

✅ ECE: 0.0153 (+81.3%), 1.7s
      [93/660] (14.1%) periodic... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 15584.721208
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 15584.721208
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0823 (+0.0%), 1.4s
      [94/660] (14.2%) white... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 15584.721208
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 15584.721208
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0823 (+0.0%), 0.8s
      [95/660] (14.4%) rational_quadratic... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 22887.486885
  Number of iterations: 41
  Number of functions evaluations: 139

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 22887.486885
  Number of iterations: 41
  Number of functions evaluations: 139

✅ ECE: 0.1870 (-127.3%), 1.8s
      [96/660] (14.5%) arc_cosine... [ETA: 15.6min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SGD
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.079452, LogLoss: 0.216907
      [97/660] (14.7%) rbf... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.554059
  Number of iterations: 200
  Number of functions evaluations: 220

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.554059
  Number of iterations: 200
  Number of functions evaluations: 220

✅ ECE: 0.0588 (+26.0%), 2.0s
      [98/660] (14.8%) matern12... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.648676
  Number of iterations: 44
  Number of functions evaluations: 54

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.648676
  Number of iterations: 44
  Number of functions evaluations: 54

✅ ECE: 0.0795 (+0.0%), 1.9s
      [99/660] (15.0%) matern32... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.605642
  Number of iterations: 112
  Number of functions evaluations: 121

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.605642
  Number of iterations: 112
  Number of functions evaluations: 121

✅ ECE: 0.0637 (+19.8%), 2.0s
      [100/660] (15.2%) matern52... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.587594
  Number of iterations: 188
  Number of functions evaluations: 218

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.587594
  Number of iterations: 188
  Number of functions evaluations: 218

✅ ECE: 0.0665 (+16.4%), 2.3s
      [101/660] (15.3%) exponential... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.648676
  Number of iterations: 41
  Number of functions evaluations: 46

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.648676
  Number of iterations: 41
  Number of functions evaluations: 46

✅ ECE: 0.0795 (+0.0%), 1.6s
      [102/660] (15.5%) cosine... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.151396
  Number of iterations: 69
  Number of functions evaluations: 81

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.151396
  Number of iterations: 69
  Number of functions evaluations: 81

✅ ECE: 0.0696 (+12.4%), 1.6s
      [103/660] (15.6%) linear... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.608173
  Number of iterations: 33
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.608173
  Number of iterations: 33
  Number of functions evaluations: 41

✅ ECE: 0.0555 (+30.2%), 1.2s
      [104/660] (15.8%) polynomial... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40.516625
  Number of iterations: 35
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40.516625
  Number of iterations: 35
  Number of functions evaluations: 37

✅ ECE: 0.0630 (+20.7%), 1.5s
      [105/660] (15.9%) periodic... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.554277
  Number of iterations: 200
  Number of functions evaluations: 222

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.554277
  Number of iterations: 200
  Number of functions evaluations: 222

✅ ECE: 0.0682 (+14.1%), 2.4s
      [106/660] (16.1%) white... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 41.648667
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 41.648667
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0795 (+0.0%), 0.9s
      [107/660] (16.2%) rational_quadratic... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.554156
  Number of iterations: 200
  Number of functions evaluations: 223

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 41.554156
  Number of iterations: 200
  Number of functions evaluations: 223

✅ ECE: 0.0638 (+19.7%), 2.2s
      [108/660] (16.4%) arc_cosine... [ETA: 15.3min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: MLP
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.045162, LogLoss: 0.033175
      [109/660] (16.5%) rbf... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.744209
  Number of iterations: 174
  Number of functions evaluations: 191

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.744209
  Number of iterations: 174
  Number of functions evaluations: 191

✅ ECE: 0.0386 (+14.5%), 1.9s
      [110/660] (16.7%) matern12... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.833044
  Number of iterations: 178
  Number of functions evaluations: 355

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.833044
  Number of iterations: 178
  Number of functions evaluations: 355

✅ ECE: 0.0407 (+10.0%), 2.2s
      [111/660] (16.8%) matern32... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.753202
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.753202
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.0402 (+10.9%), 2.1s
      [112/660] (17.0%) matern52... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.744944
  Number of iterations: 200
  Number of functions evaluations: 213

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.744944
  Number of iterations: 200
  Number of functions evaluations: 213

✅ ECE: 0.0364 (+19.4%), 2.4s
      [113/660] (17.1%) exponential... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.819441
  Number of iterations: 188
  Number of functions evaluations: 287

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.819441
  Number of iterations: 188
  Number of functions evaluations: 287

✅ ECE: 0.0405 (+10.3%), 2.3s
      [114/660] (17.3%) cosine... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.456561
  Number of iterations: 60
  Number of functions evaluations: 64

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.456561
  Number of iterations: 60
  Number of functions evaluations: 64

✅ ECE: 0.0378 (+16.3%), 1.6s
      [115/660] (17.4%) linear... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.705617
  Number of iterations: 106
  Number of functions evaluations: 127

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.705617
  Number of iterations: 106
  Number of functions evaluations: 127

✅ ECE: 0.0381 (+15.6%), 1.4s
      [116/660] (17.6%) polynomial... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.508642
  Number of iterations: 45
  Number of functions evaluations: 48

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 5.508642
  Number of iterations: 45
  Number of functions evaluations: 48

✅ ECE: 0.0375 (+17.1%), 1.5s
      [117/660] (17.7%) periodic... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.744309
  Number of iterations: 200
  Number of functions evaluations: 224

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.744309
  Number of iterations: 200
  Number of functions evaluations: 224

✅ ECE: 0.0393 (+13.1%), 2.0s
      [118/660] (17.9%) white... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 5.844768
  Number of iterations: 18
  Number of functions evaluations: 19

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 5.844768
  Number of iterations: 18
  Number of functions evaluations: 19

✅ ECE: 0.0452 (+0.0%), 0.9s
      [119/660] (18.0%) rational_quadratic... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.713186
  Number of iterations: 200
  Number of functions evaluations: 220

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 5.713186
  Number of iterations: 200
  Number of functions evaluations: 220

✅ ECE: 0.0387 (+14.3%), 2.6s
      [120/660] (18.2%) arc_cosine... [ETA: 15.3min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: BernoulliNB
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.083230, LogLoss: 0.279178
      [121/660] (18.3%) rbf... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.092927
  Number of iterations: 200
  Number of functions evaluations: 225

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.092927
  Number of iterations: 200
  Number of functions evaluations: 225

✅ ECE: 0.0514 (+38.2%), 2.1s
      [122/660] (18.5%) matern12... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 51.277551
  Number of iterations: 194
  Number of functions evaluations: 271

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 51.277551
  Number of iterations: 194
  Number of functions evaluations: 271

✅ ECE: 0.0589 (+29.3%), 2.1s
      [123/660] (18.6%) matern32... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.382529
  Number of iterations: 200
  Number of functions evaluations: 235

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.382529
  Number of iterations: 200
  Number of functions evaluations: 235

✅ ECE: 0.0468 (+43.8%), 2.3s
      [124/660] (18.8%) matern52... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.225729
  Number of iterations: 200
  Number of functions evaluations: 221

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.225729
  Number of iterations: 200
  Number of functions evaluations: 221

✅ ECE: 0.0487 (+41.4%), 2.1s
      [125/660] (18.9%) exponential... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 51.211258
  Number of iterations: 152
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 51.211258
  Number of iterations: 152
  Number of functions evaluations: 232

✅ ECE: 0.0548 (+34.2%), 2.1s
      [126/660] (19.1%) cosine... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 49.568744
  Number of iterations: 97
  Number of functions evaluations: 113

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 49.568744
  Number of iterations: 97
  Number of functions evaluations: 113

✅ ECE: 0.0516 (+38.0%), 2.0s
      [127/660] (19.2%) linear... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 49.530032
  Number of iterations: 62
  Number of functions evaluations: 75

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 49.530032
  Number of iterations: 62
  Number of functions evaluations: 75

✅ ECE: 0.0507 (+39.1%), 1.4s
      [128/660] (19.4%) polynomial... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 49.860718
  Number of iterations: 46
  Number of functions evaluations: 55

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 49.860718
  Number of iterations: 46
  Number of functions evaluations: 55

✅ ECE: 0.0646 (+22.4%), 1.4s
      [129/660] (19.5%) periodic... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.059546
  Number of iterations: 200
  Number of functions evaluations: 229

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.059546
  Number of iterations: 200
  Number of functions evaluations: 229

✅ ECE: 0.0539 (+35.3%), 2.2s
      [130/660] (19.7%) white... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 51.999299
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 51.999299
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0832 (+0.0%), 0.9s
      [131/660] (19.8%) rational_quadratic... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.263832
  Number of iterations: 200
  Number of functions evaluations: 222

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 50.263832
  Number of iterations: 200
  Number of functions evaluations: 222

✅ ECE: 0.0561 (+32.6%), 2.2s
      [132/660] (20.0%) arc_cosine... [ETA: 15.0min] ❌ __init__() missing 1 required positional

====================================================================================================
📂 DATASET: DRY_BEAN
====================================================================================================
   📊 Classes: 7
   📊 Train: 9527, Calib: 1361, Test: 2723

   🤖 CLASSIFIER: RandomForest
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.020230, LogLoss: 0.395379
      [133/660] (20.2%) rbf... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914497
  Number of iterations: 27
  Number of functions evaluations: 31

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914497
  Number of iterations: 27
  Number of functions evaluations: 31

✅ ECE: 0.0197 (+2.5%), 1.8s
      [134/660] (20.3%) matern12... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914463
  Number of iterations: 27
  Number of functions evaluations: 30

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914463
  Number of iterations: 27
  Number of functions evaluations: 30

✅ ECE: 0.0199 (+1.8%), 2.1s
      [135/660] (20.5%) matern32... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914524
  Number of iterations: 25
  Number of functions evaluations: 28

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914524
  Number of iterations: 25
  Number of functions evaluations: 28

✅ ECE: 0.0210 (-4.0%), 1.9s
      [136/660] (20.6%) matern52... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914573
  Number of iterations: 24
  Number of functions evaluations: 29

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914573
  Number of iterations: 24
  Number of functions evaluations: 29

✅ ECE: 0.0198 (+2.2%), 1.9s
      [137/660] (20.8%) exponential... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914467
  Number of iterations: 28
  Number of functions evaluations: 32

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914467
  Number of iterations: 28
  Number of functions evaluations: 32

✅ ECE: 0.0198 (+2.2%), 1.8s
      [138/660] (20.9%) cosine... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914497
  Number of iterations: 27
  Number of functions evaluations: 31

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914497
  Number of iterations: 27
  Number of functions evaluations: 31

✅ ECE: 0.0201 (+0.4%), 1.8s
      [139/660] (21.1%) linear... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914549
  Number of iterations: 26
  Number of functions evaluations: 28

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914549
  Number of iterations: 26
  Number of functions evaluations: 28

✅ ECE: 0.0201 (+0.4%), 1.4s
      [140/660] (21.2%) polynomial... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914389
  Number of iterations: 25
  Number of functions evaluations: 27

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914389
  Number of iterations: 25
  Number of functions evaluations: 27

✅ ECE: 0.0202 (+0.2%), 1.5s
      [141/660] (21.4%) periodic... [ETA: 14.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914465
  Number of iterations: 28
  Number of functions evaluations: 32

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914465
  Number of iterations: 28
  Number of functions evaluations: 32

✅ ECE: 0.0205 (-1.4%), 2.1s
      [142/660] (21.5%) white... [ETA: 14.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 4490.914382
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 4490.914382
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0202 (+0.4%), 1.1s
      [143/660] (21.7%) rational_quadratic... [ETA: 14.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914466
  Number of iterations: 28
  Number of functions evaluations: 31

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4490.914466
  Number of iterations: 28
  Number of functions evaluations: 31

✅ ECE: 0.0193 (+4.4%), 1.9s
      [144/660] (21.8%) arc_cosine... [ETA: 14.6min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: AdaBoost
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.202447, LogLoss: 1.775216
      [145/660] (22.0%) rbf... [ETA: 14.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1811.889908
  Number of iterations: 200
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1811.889908
  Number of iterations: 200
  Number of functions evaluations: 244

✅ ECE: 0.0631 (+68.8%), 3.7s
      [146/660] (22.1%) matern12... [ETA: 14.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1846.690381
  Number of iterations: 94
  Number of functions evaluations: 315

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1846.690381
  Number of iterations: 94
  Number of functions evaluations: 315

✅ ECE: 0.0637 (+68.6%), 4.4s
      [147/660] (22.3%) matern32... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1713.422908
  Number of iterations: 200
  Number of functions evaluations: 266

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1713.422908
  Number of iterations: 200
  Number of functions evaluations: 266

✅ ECE: 0.0318 (+84.3%), 4.2s
      [148/660] (22.4%) matern52... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1816.798559
  Number of iterations: 200
  Number of functions evaluations: 254

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1816.798559
  Number of iterations: 200
  Number of functions evaluations: 254

✅ ECE: 0.0604 (+70.2%), 4.5s
      [149/660] (22.6%) exponential... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1880.851602
  Number of iterations: 26
  Number of functions evaluations: 113

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1880.851602
  Number of iterations: 26
  Number of functions evaluations: 113

✅ ECE: 0.0702 (+65.3%), 2.6s
      [150/660] (22.7%) cosine... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1771.582758
  Number of iterations: 200
  Number of functions evaluations: 261

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1771.582758
  Number of iterations: 200
  Number of functions evaluations: 261

✅ ECE: 0.0601 (+70.3%), 4.0s
      [151/660] (22.9%) linear... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1834.820606
  Number of iterations: 88
  Number of functions evaluations: 107

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1834.820606
  Number of iterations: 88
  Number of functions evaluations: 107

✅ ECE: 0.0526 (+74.0%), 1.9s
      [152/660] (23.0%) polynomial... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1802.780290
  Number of iterations: 200
  Number of functions evaluations: 286

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1802.780290
  Number of iterations: 200
  Number of functions evaluations: 286

✅ ECE: 0.0695 (+65.7%), 3.4s
      [153/660] (23.2%) periodic... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1715.452971
  Number of iterations: 200
  Number of functions evaluations: 271

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1715.452971
  Number of iterations: 200
  Number of functions evaluations: 271

✅ ECE: 0.0413 (+79.6%), 4.0s
      [154/660] (23.3%) white... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 2376.737893
  Number of iterations: 24
  Number of functions evaluations: 25

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 2376.737893
  Number of iterations: 24
  Number of functions evaluations: 25

✅ ECE: 0.2024 (+0.0%), 1.1s
      [155/660] (23.5%) rational_quadratic... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1725.897690
  Number of iterations: 200
  Number of functions evaluations: 282

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1725.897690
  Number of iterations: 200
  Number of functions evaluations: 282

✅ ECE: 0.0255 (+87.4%), 5.1s
      [156/660] (23.6%) arc_cosine... [ETA: 15.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: NaiveBayes
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.084447, LogLoss: 0.967788
      [157/660] (23.8%) rbf... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 783.966314
  Number of iterations: 200
  Number of functions evaluations: 280

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 783.966314
  Number of iterations: 200
  Number of functions evaluations: 280

✅ ECE: 0.0599 (+29.1%), 4.1s
      [158/660] (23.9%) matern12... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 707.629643
  Number of iterations: 200
  Number of functions evaluations: 508

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 707.629643
  Number of iterations: 200
  Number of functions evaluations: 508

✅ ECE: 0.0344 (+59.2%), 6.1s
      [159/660] (24.1%) matern32... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 729.894539
  Number of iterations: 200
  Number of functions evaluations: 263

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 729.894539
  Number of iterations: 200
  Number of functions evaluations: 263

✅ ECE: 0.0538 (+36.3%), 4.0s
      [160/660] (24.2%) matern52... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 734.324733
  Number of iterations: 200
  Number of functions evaluations: 264

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 734.324733
  Number of iterations: 200
  Number of functions evaluations: 264

✅ ECE: 0.0538 (+36.3%), 4.1s
      [161/660] (24.4%) exponential... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 720.822529
  Number of iterations: 125
  Number of functions evaluations: 327

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 720.822529
  Number of iterations: 125
  Number of functions evaluations: 327

✅ ECE: 0.0332 (+60.7%), 3.9s
      [162/660] (24.5%) cosine... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 834.115421
  Number of iterations: 102
  Number of functions evaluations: 120

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 834.115421
  Number of iterations: 102
  Number of functions evaluations: 120

✅ ECE: 0.0474 (+43.8%), 3.1s
      [163/660] (24.7%) linear... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 829.428758
  Number of iterations: 61
  Number of functions evaluations: 69

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 829.428758
  Number of iterations: 61
  Number of functions evaluations: 69

✅ ECE: 0.0470 (+44.4%), 1.8s
      [164/660] (24.8%) polynomial... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 773.150898
  Number of iterations: 200
  Number of functions evaluations: 272

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 773.150898
  Number of iterations: 200
  Number of functions evaluations: 272

✅ ECE: 0.0691 (+18.2%), 3.5s
      [165/660] (25.0%) periodic... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 762.314057
  Number of iterations: 200
  Number of functions evaluations: 258

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 762.314057
  Number of iterations: 200
  Number of functions evaluations: 258

✅ ECE: 0.0412 (+51.2%), 4.0s
      [166/660] (25.2%) white... [ETA: 15.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1223.410794
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1223.410794
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0874 (-3.5%), 1.1s
      [167/660] (25.3%) rational_quadratic... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 691.754255
  Number of iterations: 142
  Number of functions evaluations: 267

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 691.754255
  Number of iterations: 142
  Number of functions evaluations: 267

✅ ECE: 0.0223 (+73.6%), 3.8s
      [168/660] (25.5%) arc_cosine... [ETA: 15.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: KNN
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.013453, LogLoss: 0.962346
      [169/660] (25.6%) rbf... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.663008
  Number of iterations: 28
  Number of functions evaluations: 29

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.663008
  Number of iterations: 28
  Number of functions evaluations: 29

✅ ECE: 0.0336 (-150.0%), 1.6s
      [170/660] (25.8%) matern12... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 11103.882526
  Number of iterations: 71
  Number of functions evaluations: 233

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 11103.882526
  Number of iterations: 71
  Number of functions evaluations: 233

✅ ECE: 0.0285 (-111.9%), 3.5s
      [171/660] (25.9%) matern32... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 20731.131862
  Number of iterations: 39
  Number of functions evaluations: 123

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 20731.131862
  Number of iterations: 39
  Number of functions evaluations: 123

✅ ECE: 0.0415 (-208.3%), 2.5s
      [172/660] (26.1%) matern52... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 6579.538125
  Number of iterations: 200
  Number of functions evaluations: 320

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 6579.538125
  Number of iterations: 200
  Number of functions evaluations: 320

✅ ECE: 0.5067 (-3666.7%), 3.9s
      [173/660] (26.2%) exponential... [ETA: 15.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19270.270064
  Number of iterations: 11
  Number of functions evaluations: 54

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19270.270064
  Number of iterations: 11
  Number of functions evaluations: 54

✅ ECE: 0.0217 (-61.0%), 1.9s
      [174/660] (26.4%) cosine... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.089191
  Number of iterations: 40
  Number of functions evaluations: 44

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.089191
  Number of iterations: 40
  Number of functions evaluations: 44

✅ ECE: 0.0321 (-138.3%), 1.8s
      [175/660] (26.5%) linear... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19261.202623
  Number of iterations: 28
  Number of functions evaluations: 31

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19261.202623
  Number of iterations: 28
  Number of functions evaluations: 31

✅ ECE: 0.0377 (-180.6%), 1.3s
      [176/660] (26.7%) polynomial... [ETA: 15.7min] ❌ Cholesky decomposition was not successfu
      [177/660] (26.8%) periodic... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 18774.544958
  Number of iterations: 200
  Number of functions evaluations: 319

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 18774.544958
  Number of iterations: 200
  Number of functions evaluations: 319

✅ ECE: 0.0209 (-55.6%), 3.8s
      [178/660] (27.0%) white... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19278.697818
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19278.697818
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0168 (-25.0%), 1.0s
      [179/660] (27.1%) rational_quadratic... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.650982
  Number of iterations: 151
  Number of functions evaluations: 167

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 19264.650982
  Number of iterations: 151
  Number of functions evaluations: 167

✅ ECE: 0.0335 (-148.8%), 2.9s
      [180/660] (27.3%) arc_cosine... [ETA: 15.7min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: XGBoost
   ------------------------------------------------------------------------------------------
[15:09:20] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
      📊 Uncalibrated - ECE: 0.023944, LogLoss: 0.272672
      [181/660] (27.4%) rbf... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 250.003244
  Number of iterations: 125
  Number of functions evaluations: 138

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 250.003244
  Number of iterations: 125
  Number of functions evaluations: 138

✅ ECE: 0.0292 (-21.9%), 2.8s
      [182/660] (27.6%) matern12... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 253.313221
  Number of iterations: 200
  Number of functions evaluations: 260

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 253.313221
  Number of iterations: 200
  Number of functions evaluations: 260

✅ ECE: 0.0288 (-20.2%), 3.7s
      [183/660] (27.7%) matern32... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 250.766469
  Number of iterations: 195
  Number of functions evaluations: 231

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 250.766469
  Number of iterations: 195
  Number of functions evaluations: 231

✅ ECE: 0.0242 (-1.1%), 3.6s
      [184/660] (27.9%) matern52... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 250.369835
  Number of iterations: 200
  Number of functions evaluations: 218

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 250.369835
  Number of iterations: 200
  Number of functions evaluations: 218

✅ ECE: 0.0273 (-14.2%), 4.3s
      [185/660] (28.0%) exponential... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 253.280546
  Number of iterations: 200
  Number of functions evaluations: 255

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 253.280546
  Number of iterations: 200
  Number of functions evaluations: 255

✅ ECE: 0.0281 (-17.2%), 3.9s
      [186/660] (28.2%) cosine... [ETA: 15.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 248.824509
  Number of iterations: 91
  Number of functions evaluations: 98

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 248.824509
  Number of iterations: 91
  Number of functions evaluations: 98

✅ ECE: 0.0289 (-20.7%), 2.6s
      [187/660] (28.3%) linear... [ETA: 15.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 246.772037
  Number of iterations: 50
  Number of functions evaluations: 57

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 246.772037
  Number of iterations: 50
  Number of functions evaluations: 57

✅ ECE: 0.0265 (-10.9%), 1.7s
      [188/660] (28.5%) polynomial... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 246.160466
  Number of iterations: 62
  Number of functions evaluations: 71

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 246.160466
  Number of iterations: 62
  Number of functions evaluations: 71

✅ ECE: 0.0288 (-20.4%), 2.0s
      [189/660] (28.6%) periodic... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 250.211903
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 250.211903
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.0261 (-9.2%), 3.6s
      [190/660] (28.8%) white... [ETA: 15.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 288.887033
  Number of iterations: 21
  Number of functions evaluations: 22

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 288.887033
  Number of iterations: 21
  Number of functions evaluations: 22

✅ ECE: 0.0239 (+0.0%), 1.2s
      [191/660] (28.9%) rational_quadratic... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 250.004508
  Number of iterations: 200
  Number of functions evaluations: 215

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 250.004508
  Number of iterations: 200
  Number of functions evaluations: 215

✅ ECE: 0.0260 (-8.5%), 4.4s
      [192/660] (29.1%) arc_cosine... [ETA: 15.8min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: DecisionTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.076472, LogLoss: 3.792543
      [193/660] (29.2%) rbf... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 103478.698074
  Number of iterations: 67
  Number of functions evaluations: 163

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 103478.698074
  Number of iterations: 67
  Number of functions evaluations: 163

✅ ECE: 0.1444 (-88.9%), 2.5s
      [194/660] (29.4%) matern12... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 45086.612556
  Number of iterations: 62
  Number of functions evaluations: 178

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 45086.612556
  Number of iterations: 62
  Number of functions evaluations: 178

✅ ECE: 0.2399 (-213.7%), 2.4s
      [195/660] (29.5%) matern32... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 105552.432073
  Number of iterations: 38
  Number of functions evaluations: 130

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 105552.432073
  Number of iterations: 38
  Number of functions evaluations: 130

✅ ECE: 0.3005 (-293.0%), 2.2s
      [196/660] (29.7%) matern52... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 107312.554624
  Number of iterations: 73
  Number of functions evaluations: 190

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 107312.554624
  Number of iterations: 73
  Number of functions evaluations: 190

✅ ECE: 0.2059 (-169.2%), 2.8s
      [197/660] (29.8%) exponential... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 43292.706303
  Number of iterations: 46
  Number of functions evaluations: 220

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 43292.706303
  Number of iterations: 46
  Number of functions evaluations: 220

✅ ECE: 0.0954 (-24.8%), 2.6s
      [198/660] (30.0%) cosine... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1002.552023
  Number of iterations: 200
  Number of functions evaluations: 335

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1002.552023
  Number of iterations: 200
  Number of functions evaluations: 335

✅ ECE: 0.0200 (+73.8%), 3.9s
      [199/660] (30.2%) linear... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 875.762482
  Number of iterations: 200
  Number of functions evaluations: 307

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 875.762482
  Number of iterations: 200
  Number of functions evaluations: 307

✅ ECE: 0.0200 (+73.8%), 2.5s
      [200/660] (30.3%) polynomial... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 748.929387
  Number of iterations: 200
  Number of functions evaluations: 352

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 748.929387
  Number of iterations: 200
  Number of functions evaluations: 352

✅ ECE: 0.0200 (+73.8%), 3.0s
      [201/660] (30.5%) periodic... [ETA: 15.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 95633.516502
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 95633.516502
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0765 (+0.0%), 1.5s
      [202/660] (30.6%) white... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 95633.516502
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 95633.516502
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0765 (+0.0%), 0.9s
      [203/660] (30.8%) rational_quadratic... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 105188.509651
  Number of iterations: 57
  Number of functions evaluations: 158

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 105188.509651
  Number of iterations: 57
  Number of functions evaluations: 158

✅ ECE: 0.0225 (+70.6%), 2.5s
      [204/660] (30.9%) arc_cosine... [ETA: 15.5min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SVC
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.030974, LogLoss: 0.212481
      [205/660] (31.1%) rbf... [ETA: 15.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0310 (+0.0%), 2.2s
      [206/660] (31.2%) matern12... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111203
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111203
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0310 (+0.1%), 2.5s
      [207/660] (31.4%) matern32... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 33
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 33
  Number of functions evaluations: 38

✅ ECE: 0.0310 (+0.0%), 2.4s
      [208/660] (31.5%) matern52... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111200
  Number of iterations: 35
  Number of functions evaluations: 40

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111200
  Number of iterations: 35
  Number of functions evaluations: 40

✅ ECE: 0.0310 (+0.0%), 2.8s
      [209/660] (31.7%) exponential... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111200
  Number of iterations: 33
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111200
  Number of iterations: 33
  Number of functions evaluations: 35

✅ ECE: 0.0306 (+1.2%), 2.7s
      [210/660] (31.8%) cosine... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 32
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111201
  Number of iterations: 32
  Number of functions evaluations: 35

✅ ECE: 0.0306 (+1.2%), 2.4s
      [211/660] (32.0%) linear... [ETA: 15.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111154
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111154
  Number of iterations: 33
  Number of functions evaluations: 36

✅ ECE: 0.0310 (+0.0%), 2.0s
      [212/660] (32.1%) polynomial... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111133
  Number of iterations: 30
  Number of functions evaluations: 32

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111133
  Number of iterations: 30
  Number of functions evaluations: 32

✅ ECE: 0.0310 (+0.0%), 2.0s
      [213/660] (32.3%) periodic... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 244.551606
  Number of iterations: 200
  Number of functions evaluations: 240

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 244.551606
  Number of iterations: 200
  Number of functions evaluations: 240

✅ ECE: 0.0285 (+7.9%), 4.6s
      [214/660] (32.4%) white... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 245.111139
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 245.111139
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0310 (+0.0%), 1.4s
      [215/660] (32.6%) rational_quadratic... [ETA: 15.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111202
  Number of iterations: 32
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.111202
  Number of iterations: 32
  Number of functions evaluations: 36

✅ ECE: 0.0310 (+0.0%), 2.4s
      [216/660] (32.7%) arc_cosine... [ETA: 15.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: ExtraTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.086020, LogLoss: 4.122329
      [217/660] (32.9%) rbf... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 134280.984243
  Number of iterations: 46
  Number of functions evaluations: 142

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 134280.984243
  Number of iterations: 46
  Number of functions evaluations: 142

✅ ECE: 0.1878 (-118.3%), 2.3s
      [218/660] (33.0%) matern12... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 132817.430508
  Number of iterations: 76
  Number of functions evaluations: 234

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 132817.430508
  Number of iterations: 76
  Number of functions evaluations: 234

✅ ECE: 0.3159 (-267.2%), 2.5s
      [219/660] (33.2%) matern32... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 12901.951390
  Number of iterations: 77
  Number of functions evaluations: 174

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 12901.951390
  Number of iterations: 77
  Number of functions evaluations: 174

✅ ECE: 0.1413 (-64.3%), 2.5s
      [220/660] (33.3%) matern52... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 135445.457990
  Number of iterations: 52
  Number of functions evaluations: 152

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 135445.457990
  Number of iterations: 52
  Number of functions evaluations: 152

✅ ECE: 0.2265 (-163.3%), 2.8s
      [221/660] (33.5%) exponential... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 10987.399192
  Number of iterations: 60
  Number of functions evaluations: 243

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 10987.399192
  Number of iterations: 60
  Number of functions evaluations: 243

✅ ECE: 0.2206 (-156.4%), 2.8s
      [222/660] (33.6%) cosine... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1170.977841
  Number of iterations: 200
  Number of functions evaluations: 325

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1170.977841
  Number of iterations: 200
  Number of functions evaluations: 325

✅ ECE: 0.0285 (+66.9%), 3.3s
      [223/660] (33.8%) linear... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1078.936374
  Number of iterations: 200
  Number of functions evaluations: 319

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1078.936374
  Number of iterations: 200
  Number of functions evaluations: 319

✅ ECE: 0.0269 (+68.7%), 2.5s
      [224/660] (33.9%) polynomial... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 953.396105
  Number of iterations: 200
  Number of functions evaluations: 325

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 953.396105
  Number of iterations: 200
  Number of functions evaluations: 325

✅ ECE: 0.0269 (+68.7%), 2.7s
      [225/660] (34.1%) periodic... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 126094.562499
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 126094.562499
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0860 (+0.0%), 1.5s
      [226/660] (34.2%) white... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 126094.562499
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 126094.562499
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0860 (+0.0%), 0.9s
      [227/660] (34.4%) rational_quadratic... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 131623.863086
  Number of iterations: 65
  Number of functions evaluations: 191

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 131623.863086
  Number of iterations: 65
  Number of functions evaluations: 191

✅ ECE: 0.2259 (-162.6%), 3.1s
      [228/660] (34.5%) arc_cosine... [ETA: 15.0min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SGD
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.046846, LogLoss: 0.256308
      [229/660] (34.7%) rbf... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 318.348023
  Number of iterations: 180
  Number of functions evaluations: 211

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 318.348023
  Number of iterations: 180
  Number of functions evaluations: 211

✅ ECE: 0.0254 (+45.9%), 3.9s
      [230/660] (34.8%) matern12... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 319.829103
  Number of iterations: 142
  Number of functions evaluations: 173

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 319.829103
  Number of iterations: 142
  Number of functions evaluations: 173

✅ ECE: 0.0284 (+39.4%), 3.5s
      [231/660] (35.0%) matern32... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 318.806208
  Number of iterations: 200
  Number of functions evaluations: 227

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 318.806208
  Number of iterations: 200
  Number of functions evaluations: 227

✅ ECE: 0.0265 (+43.4%), 4.2s
      [232/660] (35.2%) matern52... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 318.620923
  Number of iterations: 200
  Number of functions evaluations: 225

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 318.620923
  Number of iterations: 200
  Number of functions evaluations: 225

✅ ECE: 0.0272 (+41.9%), 4.3s
      [233/660] (35.3%) exponential... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 319.824627
  Number of iterations: 94
  Number of functions evaluations: 119

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 319.824627
  Number of iterations: 94
  Number of functions evaluations: 119

✅ ECE: 0.0295 (+37.0%), 3.0s
      [234/660] (35.5%) cosine... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 317.167630
  Number of iterations: 77
  Number of functions evaluations: 89

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 317.167630
  Number of iterations: 77
  Number of functions evaluations: 89

✅ ECE: 0.0257 (+45.2%), 3.1s
      [235/660] (35.6%) linear... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 316.769151
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 316.769151
  Number of iterations: 33
  Number of functions evaluations: 36

✅ ECE: 0.0235 (+49.9%), 2.0s
      [236/660] (35.8%) polynomial... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 315.516219
  Number of iterations: 41
  Number of functions evaluations: 45

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 315.516219
  Number of iterations: 41
  Number of functions evaluations: 45

✅ ECE: 0.0223 (+52.4%), 2.2s
      [237/660] (35.9%) periodic... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 318.346759
  Number of iterations: 135
  Number of functions evaluations: 143

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 318.346759
  Number of iterations: 135
  Number of functions evaluations: 143

✅ ECE: 0.0233 (+50.3%), 3.3s
      [238/660] (36.1%) white... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 328.828349
  Number of iterations: 23
  Number of functions evaluations: 24

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 328.828349
  Number of iterations: 23
  Number of functions evaluations: 24

✅ ECE: 0.0468 (+0.0%), 1.5s
      [239/660] (36.2%) rational_quadratic... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 318.419758
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 318.419758
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.0271 (+42.2%), 4.1s
      [240/660] (36.4%) arc_cosine... [ETA: 14.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: MLP
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.026020, LogLoss: 0.214331
      [241/660] (36.5%) rbf... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325747
  Number of iterations: 34
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325747
  Number of iterations: 34
  Number of functions evaluations: 37

✅ ECE: 0.0264 (-1.3%), 1.9s
      [242/660] (36.7%) matern12... [ETA: 15.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325745
  Number of iterations: 33
  Number of functions evaluations: 34

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325745
  Number of iterations: 33
  Number of functions evaluations: 34

✅ ECE: 0.0264 (-1.3%), 2.5s
      [243/660] (36.8%) matern32... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325724
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325724
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0260 (+0.0%), 2.3s
      [244/660] (37.0%) matern52... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325737
  Number of iterations: 34
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325737
  Number of iterations: 34
  Number of functions evaluations: 36

✅ ECE: 0.0264 (-1.3%), 2.2s
      [245/660] (37.1%) exponential... [ETA: 15.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325748
  Number of iterations: 33
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325748
  Number of iterations: 33
  Number of functions evaluations: 35

✅ ECE: 0.0260 (+0.0%), 2.0s
      [246/660] (37.3%) cosine... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325674
  Number of iterations: 43
  Number of functions evaluations: 57

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325674
  Number of iterations: 43
  Number of functions evaluations: 57

✅ ECE: 0.0264 (-1.3%), 2.1s
      [247/660] (37.4%) linear... [ETA: 15.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.323322
  Number of iterations: 46
  Number of functions evaluations: 52

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.323322
  Number of iterations: 46
  Number of functions evaluations: 52

✅ ECE: 0.0265 (-1.8%), 1.8s
      [248/660] (37.6%) polynomial... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.264795
  Number of iterations: 32
  Number of functions evaluations: 34

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.264795
  Number of iterations: 32
  Number of functions evaluations: 34

✅ ECE: 0.0278 (-6.8%), 1.8s
      [249/660] (37.7%) periodic... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325749
  Number of iterations: 34
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325749
  Number of iterations: 34
  Number of functions evaluations: 37

✅ ECE: 0.0260 (+0.0%), 2.4s
      [250/660] (37.9%) white... [ETA: 15.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 224.325699
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 224.325699
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0260 (+0.0%), 1.3s
      [251/660] (38.0%) rational_quadratic... [ETA: 14.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325739
  Number of iterations: 37
  Number of functions evaluations: 43

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 224.325739
  Number of iterations: 37
  Number of functions evaluations: 43

✅ ECE: 0.0260 (+0.0%), 2.4s
      [252/660] (38.2%) arc_cosine... [ETA: 14.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: BernoulliNB
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.151370, LogLoss: 1.142436
      [253/660] (38.3%) rbf... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1117.153338
  Number of iterations: 200
  Number of functions evaluations: 274

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1117.153338
  Number of iterations: 200
  Number of functions evaluations: 274

✅ ECE: 0.0429 (+71.7%), 3.9s
      [254/660] (38.5%) matern12... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1126.374854
  Number of iterations: 115
  Number of functions evaluations: 223

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1126.374854
  Number of iterations: 115
  Number of functions evaluations: 223

✅ ECE: 0.0537 (+64.5%), 3.4s
      [255/660] (38.6%) matern32... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1102.129812
  Number of iterations: 200
  Number of functions evaluations: 242

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1102.129812
  Number of iterations: 200
  Number of functions evaluations: 242

✅ ECE: 0.0711 (+53.0%), 3.6s
      [256/660] (38.8%) matern52... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1116.719518
  Number of iterations: 200
  Number of functions evaluations: 243

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1116.719518
  Number of iterations: 200
  Number of functions evaluations: 243

✅ ECE: 0.0746 (+50.7%), 4.7s
      [257/660] (38.9%) exponential... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1127.341863
  Number of iterations: 159
  Number of functions evaluations: 316

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1127.341863
  Number of iterations: 159
  Number of functions evaluations: 316

✅ ECE: 0.0586 (+61.3%), 4.6s
      [258/660] (39.1%) cosine... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1134.759310
  Number of iterations: 200
  Number of functions evaluations: 270

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1134.759310
  Number of iterations: 200
  Number of functions evaluations: 270

✅ ECE: 0.0910 (+39.9%), 4.1s
      [259/660] (39.2%) linear... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1155.953434
  Number of iterations: 45
  Number of functions evaluations: 53

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 1155.953434
  Number of iterations: 45
  Number of functions evaluations: 53

✅ ECE: 0.0750 (+50.5%), 1.7s
      [260/660] (39.4%) polynomial... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1114.263540
  Number of iterations: 200
  Number of functions evaluations: 267

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1114.263540
  Number of iterations: 200
  Number of functions evaluations: 267

✅ ECE: 0.0476 (+68.6%), 3.3s
      [261/660] (39.5%) periodic... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1109.802776
  Number of iterations: 200
  Number of functions evaluations: 241

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1109.802776
  Number of iterations: 200
  Number of functions evaluations: 241

✅ ECE: 0.0778 (+48.6%), 3.7s
      [262/660] (39.7%) white... [ETA: 14.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1392.559226
  Number of iterations: 23
  Number of functions evaluations: 24

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1392.559226
  Number of iterations: 23
  Number of functions evaluations: 24

✅ ECE: 0.1513 (+0.0%), 1.2s
      [263/660] (39.8%) rational_quadratic... [ETA: 14.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1115.926288
  Number of iterations: 200
  Number of functions evaluations: 240

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 1115.926288
  Number of iterations: 200
  Number of functions evaluations: 240

✅ ECE: 0.0598 (+60.5%), 4.7s
      [264/660] (40.0%) arc_cosine... [ETA: 14.7min] ❌ __init__() missing 1 required positional

====================================================================================================
📂 DATASET: STUDENT_DROPOUT
====================================================================================================
   📊 Classes: 3
   📊 Train: 3096, Calib: 442, Test: 886

   🤖 CLASSIFIER: RandomForest
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.075997, LogLoss: 0.618725
      [265/660] (40.2%) rbf... [ETA: 14.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.829681
  Number of iterations: 99
  Number of functions evaluations: 119

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.829681
  Number of iterations: 99
  Number of functions evaluations: 119

✅ ECE: 0.0571 (+24.8%), 1.9s
      [266/660] (40.3%) matern12... [ETA: 14.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.101290
  Number of iterations: 73
  Number of functions evaluations: 104

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.101290
  Number of iterations: 73
  Number of functions evaluations: 104

✅ ECE: 0.0657 (+13.6%), 1.9s
      [267/660] (40.5%) matern32... [ETA: 14.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.931018
  Number of iterations: 134
  Number of functions evaluations: 150

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.931018
  Number of iterations: 134
  Number of functions evaluations: 150

✅ ECE: 0.0598 (+21.3%), 2.2s
      [268/660] (40.6%) matern52... [ETA: 14.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.893872
  Number of iterations: 98
  Number of functions evaluations: 113

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.893872
  Number of iterations: 98
  Number of functions evaluations: 113

✅ ECE: 0.0587 (+22.7%), 2.1s
      [269/660] (40.8%) exponential... [ETA: 14.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.248131
  Number of iterations: 39
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.248131
  Number of iterations: 39
  Number of functions evaluations: 41

✅ ECE: 0.0722 (+5.0%), 1.7s
      [270/660] (40.9%) cosine... [ETA: 14.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.312318
  Number of iterations: 67
  Number of functions evaluations: 90

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.312318
  Number of iterations: 67
  Number of functions evaluations: 90

✅ ECE: 0.0585 (+23.0%), 2.2s
      [271/660] (41.1%) linear... [ETA: 14.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.706525
  Number of iterations: 34
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.706525
  Number of iterations: 34
  Number of functions evaluations: 38

✅ ECE: 0.0608 (+20.0%), 1.3s
      [272/660] (41.2%) polynomial... [ETA: 14.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.706528
  Number of iterations: 43
  Number of functions evaluations: 47

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.706528
  Number of iterations: 43
  Number of functions evaluations: 47

✅ ECE: 0.0552 (+27.4%), 1.5s
      [273/660] (41.4%) periodic... [ETA: 14.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.831259
  Number of iterations: 160
  Number of functions evaluations: 178

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 270.831259
  Number of iterations: 160
  Number of functions evaluations: 178

✅ ECE: 0.0582 (+23.4%), 2.2s
      [274/660] (41.5%) white... [ETA: 14.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 271.248092
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 271.248092
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0731 (+3.9%), 0.9s
      [275/660] (41.7%) rational_quadratic... [ETA: 14.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 270.831357
  Number of iterations: 200
  Number of functions evaluations: 219

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 270.831357
  Number of iterations: 200
  Number of functions evaluations: 219

✅ ECE: 0.0560 (+26.3%), 2.4s
      [276/660] (41.8%) arc_cosine... [ETA: 14.2min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: AdaBoost
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.396942, LogLoss: 1.056108
      [277/660] (42.0%) rbf... [ETA: 14.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 331.059754
  Number of iterations: 200
  Number of functions evaluations: 257

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 331.059754
  Number of iterations: 200
  Number of functions evaluations: 257

✅ ECE: 0.0727 (+81.7%), 2.2s
      [278/660] (42.1%) matern12... [ETA: 14.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 328.085026
  Number of iterations: 200
  Number of functions evaluations: 287

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 328.085026
  Number of iterations: 200
  Number of functions evaluations: 287

✅ ECE: 0.0618 (+84.4%), 2.9s
      [279/660] (42.3%) matern32... [ETA: 14.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 332.374813
  Number of iterations: 200
  Number of functions evaluations: 279

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 332.374813
  Number of iterations: 200
  Number of functions evaluations: 279

✅ ECE: 0.0755 (+81.0%), 2.5s
      [280/660] (42.4%) matern52... [ETA: 14.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 365.786777
  Number of iterations: 200
  Number of functions evaluations: 310

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 365.786777
  Number of iterations: 200
  Number of functions evaluations: 310

✅ ECE: 0.0928 (+76.6%), 2.8s
      [281/660] (42.6%) exponential... [ETA: 14.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 338.720359
  Number of iterations: 143
  Number of functions evaluations: 280

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 338.720359
  Number of iterations: 143
  Number of functions evaluations: 280

✅ ECE: 0.0812 (+79.5%), 2.6s
      [282/660] (42.7%) cosine... [ETA: 13.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 326.154167
  Number of iterations: 200
  Number of functions evaluations: 271

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 326.154167
  Number of iterations: 200
  Number of functions evaluations: 271

✅ ECE: 0.0771 (+80.6%), 2.2s
      [283/660] (42.9%) linear... [ETA: 13.9min] ❌ Cholesky decomposition was not successfu
      [284/660] (43.0%) polynomial... [ETA: 13.8min] ❌ Cholesky decomposition was not successfu
      [285/660] (43.2%) periodic... [ETA: 13.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.834569
  Number of iterations: 200
  Number of functions evaluations: 276

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.834569
  Number of iterations: 200
  Number of functions evaluations: 276

✅ ECE: 0.0560 (+85.9%), 2.7s
      [286/660] (43.3%) white... [ETA: 13.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 468.672963
  Number of iterations: 23
  Number of functions evaluations: 24

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 468.672963
  Number of iterations: 23
  Number of functions evaluations: 24

✅ ECE: 0.3969 (+0.0%), 0.9s
      [287/660] (43.5%) rational_quadratic... [ETA: 13.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 367.839274
  Number of iterations: 200
  Number of functions evaluations: 261

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 367.839274
  Number of iterations: 200
  Number of functions evaluations: 261

✅ ECE: 0.1113 (+72.0%), 2.6s
      [288/660] (43.6%) arc_cosine... [ETA: 13.7min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: NaiveBayes
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.215572, LogLoss: 2.693294
      [289/660] (43.8%) rbf... [ETA: 13.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 891.456333
  Number of iterations: 200
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 891.456333
  Number of iterations: 200
  Number of functions evaluations: 244

✅ ECE: 0.1612 (+25.2%), 2.3s
      [290/660] (43.9%) matern12... [ETA: 13.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 861.780269
  Number of iterations: 101
  Number of functions evaluations: 324

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 861.780269
  Number of iterations: 101
  Number of functions evaluations: 324

✅ ECE: 0.1566 (+27.4%), 2.6s
      [291/660] (44.1%) matern32... [ETA: 13.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 863.270961
  Number of iterations: 200
  Number of functions evaluations: 293

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 863.270961
  Number of iterations: 200
  Number of functions evaluations: 293

✅ ECE: 0.1357 (+37.0%), 2.5s
      [292/660] (44.2%) matern52... [ETA: 13.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 890.871442
  Number of iterations: 200
  Number of functions evaluations: 231

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 890.871442
  Number of iterations: 200
  Number of functions evaluations: 231

✅ ECE: 0.1508 (+30.0%), 2.9s
      [293/660] (44.4%) exponential... [ETA: 13.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 910.841097
  Number of iterations: 70
  Number of functions evaluations: 189

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 910.841097
  Number of iterations: 70
  Number of functions evaluations: 189

✅ ECE: 0.1401 (+35.0%), 2.2s
      [294/660] (44.5%) cosine... [ETA: 13.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 943.566351
  Number of iterations: 200
  Number of functions evaluations: 267

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 943.566351
  Number of iterations: 200
  Number of functions evaluations: 267

✅ ECE: 0.1752 (+18.7%), 2.6s
      [295/660] (44.7%) linear... [ETA: 13.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 949.706219
  Number of iterations: 56
  Number of functions evaluations: 69

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 949.706219
  Number of iterations: 56
  Number of functions evaluations: 69

✅ ECE: 0.1976 (+8.3%), 1.3s
      [296/660] (44.8%) polynomial... [ETA: 13.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 895.085594
  Number of iterations: 200
  Number of functions evaluations: 258

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 895.085594
  Number of iterations: 200
  Number of functions evaluations: 258

✅ ECE: 0.1840 (+14.6%), 2.0s
      [297/660] (45.0%) periodic... [ETA: 13.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 859.957961
  Number of iterations: 200
  Number of functions evaluations: 278

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 859.957961
  Number of iterations: 200
  Number of functions evaluations: 278

✅ ECE: 0.1804 (+16.3%), 2.5s
      [298/660] (45.2%) white... [ETA: 13.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1219.879254
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1219.879254
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.2142 (+0.6%), 0.9s
      [299/660] (45.3%) rational_quadratic... [ETA: 13.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 877.816594
  Number of iterations: 200
  Number of functions evaluations: 254

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 877.816594
  Number of iterations: 200
  Number of functions evaluations: 254

✅ ECE: 0.1115 (+48.3%), 3.0s
      [300/660] (45.5%) arc_cosine... [ETA: 13.2min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: KNN
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.053365, LogLoss: 3.168910
      [301/660] (45.6%) rbf... [ETA: 13.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 37795.352761
  Number of iterations: 97
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 37795.352761
  Number of iterations: 97
  Number of functions evaluations: 244

✅ ECE: 0.0747 (-40.0%), 2.1s
      [302/660] (45.8%) matern12... [ETA: 13.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 41594.674992
  Number of iterations: 29
  Number of functions evaluations: 126

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 41594.674992
  Number of iterations: 29
  Number of functions evaluations: 126

✅ ECE: 0.0599 (-12.2%), 1.9s
      [303/660] (45.9%) matern32... [ETA: 13.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 30763.836094
  Number of iterations: 27
  Number of functions evaluations: 106

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 30763.836094
  Number of iterations: 27
  Number of functions evaluations: 106

✅ ECE: 0.0894 (-67.6%), 1.9s
      [304/660] (46.1%) matern52... [ETA: 13.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 30559.153800
  Number of iterations: 27
  Number of functions evaluations: 108

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 30559.153800
  Number of iterations: 27
  Number of functions evaluations: 108

✅ ECE: 0.0928 (-73.9%), 1.8s
      [305/660] (46.2%) exponential... [ETA: 12.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 30431.758009
  Number of iterations: 29
  Number of functions evaluations: 95

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 30431.758009
  Number of iterations: 29
  Number of functions evaluations: 95

✅ ECE: 0.0766 (-43.6%), 2.0s
      [306/660] (46.4%) cosine... [ETA: 12.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 28479.300330
  Number of iterations: 200
  Number of functions evaluations: 283

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 28479.300330
  Number of iterations: 200
  Number of functions evaluations: 283

✅ ECE: 0.1657 (-210.6%), 2.3s
      [307/660] (46.5%) linear... [ETA: 12.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 28510.604312
  Number of iterations: 23
  Number of functions evaluations: 25

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 28510.604312
  Number of iterations: 23
  Number of functions evaluations: 25

✅ ECE: 0.2076 (-288.9%), 1.2s
      [308/660] (46.7%) polynomial... [ETA: 12.8min] ❌ Cholesky decomposition was not successfu
      [309/660] (46.8%) periodic... [ETA: 12.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 10445.563082
  Number of iterations: 83
  Number of functions evaluations: 187

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 10445.563082
  Number of iterations: 83
  Number of functions evaluations: 187

✅ ECE: 0.0844 (-58.2%), 2.0s
      [310/660] (47.0%) white... [ETA: 12.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 28551.264780
  Number of iterations: 19
  Number of functions evaluations: 20

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 28551.264780
  Number of iterations: 19
  Number of functions evaluations: 20

✅ ECE: 0.0374 (+30.0%), 0.8s
      [311/660] (47.1%) rational_quadratic... [ETA: 12.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 31848.933232
  Number of iterations: 33
  Number of functions evaluations: 115

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 31848.933232
  Number of iterations: 33
  Number of functions evaluations: 115

✅ ECE: 0.0812 (-52.3%), 1.9s
      [312/660] (47.3%) arc_cosine... [ETA: 12.6min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: XGBoost
   ------------------------------------------------------------------------------------------
[15:14:46] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
      📊 Uncalibrated - ECE: 0.083785, LogLoss: 0.611635
      [313/660] (47.4%) rbf... [ETA: 12.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.044374
  Number of iterations: 200
  Number of functions evaluations: 222

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.044374
  Number of iterations: 200
  Number of functions evaluations: 222

✅ ECE: 0.0363 (+56.6%), 2.5s
      [314/660] (47.6%) matern12... [ETA: 12.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 275.333253
  Number of iterations: 200
  Number of functions evaluations: 253

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 275.333253
  Number of iterations: 200
  Number of functions evaluations: 253

✅ ECE: 0.0440 (+47.5%), 2.5s
      [315/660] (47.7%) matern32... [ETA: 12.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.705160
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.705160
  Number of iterations: 200
  Number of functions evaluations: 230

✅ ECE: 0.0408 (+51.3%), 3.1s
      [316/660] (47.9%) matern52... [ETA: 12.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 273.303564
  Number of iterations: 166
  Number of functions evaluations: 185

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 273.303564
  Number of iterations: 166
  Number of functions evaluations: 185

✅ ECE: 0.0350 (+58.3%), 2.9s
      [317/660] (48.0%) exponential... [ETA: 12.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 275.187034
  Number of iterations: 200
  Number of functions evaluations: 253

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 275.187034
  Number of iterations: 200
  Number of functions evaluations: 253

✅ ECE: 0.0412 (+50.8%), 3.0s
      [318/660] (48.2%) cosine... [ETA: 12.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.918562
  Number of iterations: 123
  Number of functions evaluations: 146

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.918562
  Number of iterations: 123
  Number of functions evaluations: 146

✅ ECE: 0.0472 (+43.7%), 2.5s
      [319/660] (48.3%) linear... [ETA: 12.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.046855
  Number of iterations: 66
  Number of functions evaluations: 84

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 271.046855
  Number of iterations: 66
  Number of functions evaluations: 84

✅ ECE: 0.0336 (+59.9%), 1.7s
      [320/660] (48.5%) polynomial... [ETA: 12.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.537659
  Number of iterations: 200
  Number of functions evaluations: 229

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.537659
  Number of iterations: 200
  Number of functions evaluations: 229

✅ ECE: 0.0352 (+58.0%), 3.0s
      [321/660] (48.6%) periodic... [ETA: 12.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.123805
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.123805
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.0413 (+50.7%), 3.0s
      [322/660] (48.8%) white... [ETA: 12.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 301.227777
  Number of iterations: 21
  Number of functions evaluations: 22

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 301.227777
  Number of iterations: 21
  Number of functions evaluations: 22

✅ ECE: 0.0838 (+0.0%), 1.1s
      [323/660] (48.9%) rational_quadratic... [ETA: 12.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.080285
  Number of iterations: 200
  Number of functions evaluations: 219

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 273.080285
  Number of iterations: 200
  Number of functions evaluations: 219

✅ ECE: 0.0375 (+55.3%), 3.0s
      [324/660] (49.1%) arc_cosine... [ETA: 12.2min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: DecisionTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.254477, LogLoss: 9.940618
      [325/660] (49.2%) rbf... [ETA: 12.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 125840.553971
  Number of iterations: 53
  Number of functions evaluations: 145

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 125840.553971
  Number of iterations: 53
  Number of functions evaluations: 145

✅ ECE: 0.0411 (+83.8%), 2.1s
      [326/660] (49.4%) matern12... [ETA: 12.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 125146.612831
  Number of iterations: 54
  Number of functions evaluations: 155

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 125146.612831
  Number of iterations: 54
  Number of functions evaluations: 155

✅ ECE: 0.0832 (+67.3%), 1.9s
      [327/660] (49.5%) matern32... [ETA: 12.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 129963.797414
  Number of iterations: 40
  Number of functions evaluations: 124

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 129963.797414
  Number of iterations: 40
  Number of functions evaluations: 124

✅ ECE: 0.0314 (+87.7%), 1.9s
      [328/660] (49.7%) matern52... [ETA: 12.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 13614.261137
  Number of iterations: 83
  Number of functions evaluations: 181

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 13614.261137
  Number of iterations: 83
  Number of functions evaluations: 181

✅ ECE: 0.0673 (+73.5%), 2.5s
      [329/660] (49.8%) exponential... [ETA: 12.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40044.323998
  Number of iterations: 17
  Number of functions evaluations: 103

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40044.323998
  Number of iterations: 17
  Number of functions evaluations: 103

✅ ECE: 0.2545 (+0.0%), 2.5s
      [330/660] (50.0%) cosine... [ETA: 12.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 640.676636
  Number of iterations: 200
  Number of functions evaluations: 302

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 640.676636
  Number of iterations: 200
  Number of functions evaluations: 302

✅ ECE: 0.0884 (+65.3%), 2.8s
      [331/660] (50.2%) linear... [ETA: 12.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 591.691241
  Number of iterations: 200
  Number of functions evaluations: 291

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 591.691241
  Number of iterations: 200
  Number of functions evaluations: 291

✅ ECE: 0.0455 (+82.1%), 2.2s
      [332/660] (50.3%) polynomial... [ETA: 11.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 507.577647
  Number of iterations: 200
  Number of functions evaluations: 291

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 507.577647
  Number of iterations: 200
  Number of functions evaluations: 291

✅ ECE: 0.1312 (+48.4%), 2.8s
      [333/660] (50.5%) periodic... [ETA: 11.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 119010.598313
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 119010.598313
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.2545 (+0.0%), 1.9s
      [334/660] (50.6%) white... [ETA: 11.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 119010.598313
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 119010.598313
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.2545 (+0.0%), 1.3s
      [335/660] (50.8%) rational_quadratic... [ETA: 11.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 123876.045795
  Number of iterations: 67
  Number of functions evaluations: 170

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 123876.045795
  Number of iterations: 67
  Number of functions evaluations: 170

✅ ECE: 0.0483 (+81.0%), 2.5s
      [336/660] (50.9%) arc_cosine... [ETA: 11.8min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SVC
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.061389, LogLoss: 0.592215
      [337/660] (51.1%) rbf... [ETA: 11.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724502
  Number of iterations: 31
  Number of functions evaluations: 34

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724502
  Number of iterations: 31
  Number of functions evaluations: 34

✅ ECE: 0.0614 (+0.0%), 2.1s
      [338/660] (51.2%) matern12... [ETA: 11.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0614 (+0.0%), 2.1s
      [339/660] (51.4%) matern32... [ETA: 11.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 36

✅ ECE: 0.0614 (+0.0%), 2.5s
      [340/660] (51.5%) matern52... [ETA: 11.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724501
  Number of iterations: 32
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724501
  Number of iterations: 32
  Number of functions evaluations: 37

✅ ECE: 0.0614 (+0.0%), 2.7s
      [341/660] (51.7%) exponential... [ETA: 11.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0614 (+0.0%), 2.8s
      [342/660] (51.8%) cosine... [ETA: 11.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 32
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 32
  Number of functions evaluations: 35

✅ ECE: 0.0614 (+0.0%), 2.4s
      [343/660] (52.0%) linear... [ETA: 11.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724441
  Number of iterations: 31
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724441
  Number of iterations: 31
  Number of functions evaluations: 35

✅ ECE: 0.0614 (+0.0%), 2.0s
      [344/660] (52.1%) polynomial... [ETA: 11.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724420
  Number of iterations: 31
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724420
  Number of iterations: 31
  Number of functions evaluations: 35

✅ ECE: 0.0614 (+0.0%), 2.1s
      [345/660] (52.3%) periodic... [ETA: 11.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724501
  Number of iterations: 32
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724501
  Number of iterations: 32
  Number of functions evaluations: 38

✅ ECE: 0.0614 (+0.0%), 2.2s
      [346/660] (52.4%) white... [ETA: 11.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 272.724428
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 272.724428
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0614 (+0.0%), 1.3s
      [347/660] (52.6%) rational_quadratic... [ETA: 11.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 272.724499
  Number of iterations: 33
  Number of functions evaluations: 36

✅ ECE: 0.0614 (+0.0%), 2.6s
      [348/660] (52.7%) arc_cosine... [ETA: 11.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: ExtraTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.312039, LogLoss: 11.928742
      [349/660] (52.9%) rbf... [ETA: 11.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 139159.699948
  Number of iterations: 42
  Number of functions evaluations: 127

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 139159.699948
  Number of iterations: 42
  Number of functions evaluations: 127

✅ ECE: 0.0466 (+85.1%), 2.8s
      [350/660] (53.0%) matern12... [ETA: 11.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 135587.864975
  Number of iterations: 50
  Number of functions evaluations: 153

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 135587.864975
  Number of iterations: 50
  Number of functions evaluations: 153

✅ ECE: 0.0886 (+71.6%), 2.4s
      [351/660] (53.2%) matern32... [ETA: 11.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 137119.523111
  Number of iterations: 59
  Number of functions evaluations: 154

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 137119.523111
  Number of iterations: 59
  Number of functions evaluations: 154

✅ ECE: 0.1527 (+51.1%), 2.8s
      [352/660] (53.3%) matern52... [ETA: 11.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 55820.960466
  Number of iterations: 57
  Number of functions evaluations: 149

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 55820.960466
  Number of iterations: 57
  Number of functions evaluations: 149

✅ ECE: 0.1491 (+52.2%), 2.6s
      [353/660] (53.5%) exponential... [ETA: 11.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 140449.062949
  Number of iterations: 39
  Number of functions evaluations: 195

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 140449.062949
  Number of iterations: 39
  Number of functions evaluations: 195

✅ ECE: 0.0999 (+68.0%), 2.6s
      [354/660] (53.6%) cosine... [ETA: 11.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 673.722846
  Number of iterations: 200
  Number of functions evaluations: 332

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 673.722846
  Number of iterations: 200
  Number of functions evaluations: 332

✅ ECE: 0.0308 (+90.1%), 3.7s
      [355/660] (53.8%) linear... [ETA: 11.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 629.895770
  Number of iterations: 200
  Number of functions evaluations: 299

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 629.895770
  Number of iterations: 200
  Number of functions evaluations: 299

✅ ECE: 0.0308 (+90.1%), 3.4s
      [356/660] (53.9%) polynomial... [ETA: 11.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 491.454571
  Number of iterations: 200
  Number of functions evaluations: 300

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 491.454571
  Number of iterations: 200
  Number of functions evaluations: 300

✅ ECE: 0.0531 (+83.0%), 2.9s
      [357/660] (54.1%) periodic... [ETA: 11.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 128219.751754
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 128219.751754
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.3120 (+0.0%), 2.0s
      [358/660] (54.2%) white... [ETA: 11.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 128219.751754
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 128219.751754
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.3120 (+0.0%), 1.1s
      [359/660] (54.4%) rational_quadratic... [ETA: 11.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 138263.900672
  Number of iterations: 48
  Number of functions evaluations: 146

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 138263.900672
  Number of iterations: 48
  Number of functions evaluations: 146

✅ ECE: 0.0682 (+78.1%), 2.8s
      [360/660] (54.5%) arc_cosine... [ETA: 11.0min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SGD
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.032592, LogLoss: 0.678797
      [361/660] (54.7%) rbf... [ETA: 10.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.317705
  Number of iterations: 200
  Number of functions evaluations: 220

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.317705
  Number of iterations: 200
  Number of functions evaluations: 220

✅ ECE: 0.0480 (-47.3%), 3.1s
      [362/660] (54.8%) matern12... [ETA: 10.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 316.061655
  Number of iterations: 200
  Number of functions evaluations: 272

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 316.061655
  Number of iterations: 200
  Number of functions evaluations: 272

✅ ECE: 0.0456 (-39.9%), 3.2s
      [363/660] (55.0%) matern32... [ETA: 10.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.109441
  Number of iterations: 200
  Number of functions evaluations: 216

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.109441
  Number of iterations: 200
  Number of functions evaluations: 216

✅ ECE: 0.0392 (-20.3%), 3.6s
      [364/660] (55.2%) matern52... [ETA: 10.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 314.959187
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 314.959187
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.0412 (-26.4%), 3.5s
      [365/660] (55.3%) exponential... [ETA: 10.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 316.011958
  Number of iterations: 200
  Number of functions evaluations: 266

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 316.011958
  Number of iterations: 200
  Number of functions evaluations: 266

✅ ECE: 0.0505 (-55.0%), 3.4s
      [366/660] (55.5%) cosine... [ETA: 10.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 315.184653
  Number of iterations: 61
  Number of functions evaluations: 67

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 315.184653
  Number of iterations: 61
  Number of functions evaluations: 67

✅ ECE: 0.0512 (-57.1%), 2.3s
      [367/660] (55.6%) linear... [ETA: 10.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 314.109430
  Number of iterations: 116
  Number of functions evaluations: 134

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 314.109430
  Number of iterations: 116
  Number of functions evaluations: 134

✅ ECE: 0.0491 (-50.8%), 2.1s
      [368/660] (55.8%) polynomial... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 314.268607
  Number of iterations: 41
  Number of functions evaluations: 43

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 314.268607
  Number of iterations: 41
  Number of functions evaluations: 43

✅ ECE: 0.0509 (-56.1%), 1.9s
      [369/660] (55.9%) periodic... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.177611
  Number of iterations: 200
  Number of functions evaluations: 242

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.177611
  Number of iterations: 200
  Number of functions evaluations: 242

✅ ECE: 0.0363 (-11.4%), 3.2s
      [370/660] (56.1%) white... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 319.208312
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 319.208312
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0326 (+0.0%), 1.5s
      [371/660] (56.2%) rational_quadratic... [ETA: 10.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.386473
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 315.386473
  Number of iterations: 200
  Number of functions evaluations: 230

✅ ECE: 0.0443 (-36.0%), 3.5s
      [372/660] (56.4%) arc_cosine... [ETA: 10.6min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: MLP
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.172621, LogLoss: 1.451413
      [373/660] (56.5%) rbf... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 521.151662
  Number of iterations: 200
  Number of functions evaluations: 250

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 521.151662
  Number of iterations: 200
  Number of functions evaluations: 250

✅ ECE: 0.0687 (+60.2%), 3.2s
      [374/660] (56.7%) matern12... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 493.843399
  Number of iterations: 200
  Number of functions evaluations: 317

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 493.843399
  Number of iterations: 200
  Number of functions evaluations: 317

✅ ECE: 0.0798 (+53.8%), 3.3s
      [375/660] (56.8%) matern32... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 490.848866
  Number of iterations: 200
  Number of functions evaluations: 248

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 490.848866
  Number of iterations: 200
  Number of functions evaluations: 248

✅ ECE: 0.1069 (+38.1%), 3.3s
      [376/660] (57.0%) matern52... [ETA: 10.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 496.891194
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 496.891194
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.0702 (+59.4%), 3.0s
      [377/660] (57.1%) exponential... [ETA: 10.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 503.402891
  Number of iterations: 200
  Number of functions evaluations: 347

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 503.402891
  Number of iterations: 200
  Number of functions evaluations: 347

✅ ECE: 0.0899 (+47.9%), 3.7s
      [378/660] (57.3%) cosine... [ETA: 10.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 538.166439
  Number of iterations: 132
  Number of functions evaluations: 159

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 538.166439
  Number of iterations: 132
  Number of functions evaluations: 159

✅ ECE: 0.1379 (+20.1%), 2.6s
      [379/660] (57.4%) linear... [ETA: 10.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 534.708591
  Number of iterations: 54
  Number of functions evaluations: 63

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 534.708591
  Number of iterations: 54
  Number of functions evaluations: 63

✅ ECE: 0.1297 (+24.9%), 1.6s
      [380/660] (57.6%) polynomial... [ETA: 10.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 524.178006
  Number of iterations: 200
  Number of functions evaluations: 268

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 524.178006
  Number of iterations: 200
  Number of functions evaluations: 268

✅ ECE: 0.0893 (+48.3%), 2.4s
      [381/660] (57.7%) periodic... [ETA: 10.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 481.405600
  Number of iterations: 200
  Number of functions evaluations: 275

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 481.405600
  Number of iterations: 200
  Number of functions evaluations: 275

✅ ECE: 0.1082 (+37.3%), 2.8s
      [382/660] (57.9%) white... [ETA: 10.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 706.746904
  Number of iterations: 21
  Number of functions evaluations: 22

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 706.746904
  Number of iterations: 21
  Number of functions evaluations: 22

✅ ECE: 0.1727 (-0.0%), 1.2s
      [383/660] (58.0%) rational_quadratic... [ETA: 10.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 493.576525
  Number of iterations: 200
  Number of functions evaluations: 253

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 493.576525
  Number of iterations: 200
  Number of functions evaluations: 253

✅ ECE: 0.0845 (+51.1%), 2.7s
      [384/660] (58.2%) arc_cosine... [ETA: 10.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: BernoulliNB
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.104821, LogLoss: 0.849049
      [385/660] (58.3%) rbf... [ETA: 10.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 340.057193
  Number of iterations: 200
  Number of functions evaluations: 245

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 340.057193
  Number of iterations: 200
  Number of functions evaluations: 245

✅ ECE: 0.0381 (+63.7%), 3.0s
      [386/660] (58.5%) matern12... [ETA: 10.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 343.020205
  Number of iterations: 200
  Number of functions evaluations: 282

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 343.020205
  Number of iterations: 200
  Number of functions evaluations: 282

✅ ECE: 0.0563 (+46.3%), 3.1s
      [387/660] (58.6%) matern32... [ETA: 10.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 339.744022
  Number of iterations: 200
  Number of functions evaluations: 222

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 339.744022
  Number of iterations: 200
  Number of functions evaluations: 222

✅ ECE: 0.0361 (+65.5%), 2.7s
      [388/660] (58.8%) matern52... [ETA: 10.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 339.388333
  Number of iterations: 200
  Number of functions evaluations: 227

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 339.388333
  Number of iterations: 200
  Number of functions evaluations: 227

✅ ECE: 0.0401 (+61.7%), 3.0s
      [389/660] (58.9%) exponential... [ETA: 10.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 342.697968
  Number of iterations: 200
  Number of functions evaluations: 271

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 342.697968
  Number of iterations: 200
  Number of functions evaluations: 271

✅ ECE: 0.0420 (+59.9%), 2.9s
      [390/660] (59.1%) cosine... [ETA: 10.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 346.473243
  Number of iterations: 150
  Number of functions evaluations: 181

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 346.473243
  Number of iterations: 150
  Number of functions evaluations: 181

✅ ECE: 0.0700 (+33.2%), 2.2s
      [391/660] (59.2%) linear... [ETA: 10.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 347.990145
  Number of iterations: 52
  Number of functions evaluations: 59

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 347.990145
  Number of iterations: 52
  Number of functions evaluations: 59

✅ ECE: 0.0615 (+41.4%), 1.8s
      [392/660] (59.4%) polynomial... [ETA: 10.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 340.565315
  Number of iterations: 200
  Number of functions evaluations: 254

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 340.565315
  Number of iterations: 200
  Number of functions evaluations: 254

✅ ECE: 0.0488 (+53.5%), 2.6s
      [393/660] (59.5%) periodic... [ETA: 10.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 340.575105
  Number of iterations: 200
  Number of functions evaluations: 228

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 340.575105
  Number of iterations: 200
  Number of functions evaluations: 228

✅ ECE: 0.0556 (+47.0%), 2.8s
      [394/660] (59.7%) white... [ETA: 10.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 396.645245
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 396.645245
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.1048 (+0.0%), 1.0s
      [395/660] (59.8%) rational_quadratic... [ETA: 10.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 339.291270
  Number of iterations: 200
  Number of functions evaluations: 227

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 339.291270
  Number of iterations: 200
  Number of functions evaluations: 227

✅ ECE: 0.0516 (+50.8%), 3.0s
      [396/660] (60.0%) arc_cosine... [ETA: 9.9min] ❌ __init__() missing 1 required positional

====================================================================================================
📂 DATASET: CIRRHOSIS
====================================================================================================
   📊 Classes: 3
   📊 Train: 292, Calib: 42, Test: 84

   🤖 CLASSIFIER: RandomForest
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.164172, LogLoss: 0.634501
      [397/660] (60.2%) rbf... [ETA: 9.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 40

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 40

✅ ECE: 0.1647 (-0.3%), 1.9s
      [398/660] (60.3%) matern12... [ETA: 9.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 37
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 37
  Number of functions evaluations: 41

✅ ECE: 0.1647 (-0.3%), 1.8s
      [399/660] (60.5%) matern32... [ETA: 9.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449513
  Number of iterations: 32
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449513
  Number of iterations: 32
  Number of functions evaluations: 35

✅ ECE: 0.1642 (+0.0%), 2.0s
      [400/660] (60.6%) matern52... [ETA: 9.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 39

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 39

✅ ECE: 0.1642 (+0.0%), 1.9s
      [401/660] (60.8%) exponential... [ETA: 9.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449513
  Number of iterations: 31
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449513
  Number of iterations: 31
  Number of functions evaluations: 35

✅ ECE: 0.1647 (-0.3%), 1.7s
      [402/660] (60.9%) cosine... [ETA: 9.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 40

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 40

✅ ECE: 0.1642 (+0.0%), 1.7s
      [403/660] (61.1%) linear... [ETA: 9.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449507
  Number of iterations: 29
  Number of functions evaluations: 32

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449507
  Number of iterations: 29
  Number of functions evaluations: 32

✅ ECE: 0.1642 (+0.0%), 1.3s
      [404/660] (61.2%) polynomial... [ETA: 9.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449505
  Number of iterations: 33
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449505
  Number of iterations: 33
  Number of functions evaluations: 38

✅ ECE: 0.1647 (-0.3%), 1.5s
      [405/660] (61.4%) periodic... [ETA: 9.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 34
  Number of functions evaluations: 37

✅ ECE: 0.1647 (-0.3%), 1.7s
      [406/660] (61.5%) white... [ETA: 9.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 26.449511
  Number of iterations: 19
  Number of functions evaluations: 20

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 26.449511
  Number of iterations: 19
  Number of functions evaluations: 20

✅ ECE: 0.1647 (-0.3%), 1.3s
      [407/660] (61.7%) rational_quadratic... [ETA: 9.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 26.449512
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.1647 (-0.3%), 1.9s
      [408/660] (61.8%) arc_cosine... [ETA: 9.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: AdaBoost
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.199320, LogLoss: 0.767859
      [409/660] (62.0%) rbf... [ETA: 9.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878010
  Number of iterations: 32
  Number of functions evaluations: 34

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878010
  Number of iterations: 32
  Number of functions evaluations: 34

✅ ECE: 0.1993 (+0.0%), 1.6s
      [410/660] (62.1%) matern12... [ETA: 9.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878009
  Number of iterations: 39
  Number of functions evaluations: 47

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878009
  Number of iterations: 39
  Number of functions evaluations: 47

✅ ECE: 0.1993 (+0.0%), 1.6s
      [411/660] (62.3%) matern32... [ETA: 9.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878008
  Number of iterations: 39
  Number of functions evaluations: 44

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878008
  Number of iterations: 39
  Number of functions evaluations: 44

✅ ECE: 0.1993 (+0.0%), 1.8s
      [412/660] (62.4%) matern52... [ETA: 9.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878013
  Number of iterations: 32
  Number of functions evaluations: 34

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878013
  Number of iterations: 32
  Number of functions evaluations: 34

✅ ECE: 0.1993 (+0.0%), 1.8s
      [413/660] (62.6%) exponential... [ETA: 9.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878009
  Number of iterations: 38
  Number of functions evaluations: 42

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878009
  Number of iterations: 38
  Number of functions evaluations: 42

✅ ECE: 0.1993 (+0.0%), 1.9s
      [414/660] (62.7%) cosine... [ETA: 9.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.810491
  Number of iterations: 110
  Number of functions evaluations: 131

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.810491
  Number of iterations: 110
  Number of functions evaluations: 131

✅ ECE: 0.1701 (+14.7%), 1.9s
      [415/660] (62.9%) linear... [ETA: 9.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.877999
  Number of iterations: 31
  Number of functions evaluations: 33

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.877999
  Number of iterations: 31
  Number of functions evaluations: 33

✅ ECE: 0.1993 (+0.0%), 1.4s
      [416/660] (63.0%) polynomial... [ETA: 9.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.784926
  Number of iterations: 34
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.784926
  Number of iterations: 34
  Number of functions evaluations: 37

✅ ECE: 0.1655 (+17.0%), 1.5s
      [417/660] (63.2%) periodic... [ETA: 9.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878010
  Number of iterations: 42
  Number of functions evaluations: 48

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878010
  Number of iterations: 42
  Number of functions evaluations: 48

✅ ECE: 0.1993 (+0.0%), 1.6s
      [418/660] (63.3%) white... [ETA: 9.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 32.878008
  Number of iterations: 19
  Number of functions evaluations: 20

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 32.878008
  Number of iterations: 19
  Number of functions evaluations: 20

✅ ECE: 0.1993 (+0.0%), 1.0s
      [419/660] (63.5%) rational_quadratic... [ETA: 8.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878009
  Number of iterations: 33
  Number of functions evaluations: 34

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.878009
  Number of iterations: 33
  Number of functions evaluations: 34

✅ ECE: 0.1993 (+0.0%), 1.7s
      [420/660] (63.6%) arc_cosine... [ETA: 8.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: NaiveBayes
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.743806, LogLoss: 11.101042
      [421/660] (63.8%) rbf... [ETA: 8.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 864.698851
  Number of iterations: 200
  Number of functions evaluations: 277

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 864.698851
  Number of iterations: 200
  Number of functions evaluations: 277

✅ ECE: 0.4175 (+43.9%), 2.4s
      [422/660] (63.9%) matern12... [ETA: 8.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 899.089849
  Number of iterations: 22
  Number of functions evaluations: 115

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 899.089849
  Number of iterations: 22
  Number of functions evaluations: 115

✅ ECE: 0.3676 (+50.6%), 1.8s
      [423/660] (64.1%) matern32... [ETA: 8.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 853.128533
  Number of iterations: 200
  Number of functions evaluations: 277

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 853.128533
  Number of iterations: 200
  Number of functions evaluations: 277

✅ ECE: 0.3888 (+47.7%), 2.2s
      [424/660] (64.2%) matern52... [ETA: 8.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 855.572020
  Number of iterations: 200
  Number of functions evaluations: 274

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 855.572020
  Number of iterations: 200
  Number of functions evaluations: 274

✅ ECE: 0.3702 (+50.2%), 2.2s
      [425/660] (64.4%) exponential... [ETA: 8.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 861.511230
  Number of iterations: 28
  Number of functions evaluations: 122

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 861.511230
  Number of iterations: 28
  Number of functions evaluations: 122

✅ ECE: 0.4217 (+43.3%), 1.9s
      [426/660] (64.5%) cosine... [ETA: 8.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 890.663796
  Number of iterations: 86
  Number of functions evaluations: 101

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 890.663796
  Number of iterations: 86
  Number of functions evaluations: 101

✅ ECE: 0.4033 (+45.8%), 1.8s
      [427/660] (64.7%) linear... [ETA: 8.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 888.095749
  Number of iterations: 45
  Number of functions evaluations: 53

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 888.095749
  Number of iterations: 45
  Number of functions evaluations: 53

✅ ECE: 0.4090 (+45.0%), 1.6s
      [428/660] (64.8%) polynomial... [ETA: 8.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 885.086849
  Number of iterations: 93
  Number of functions evaluations: 114

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 885.086849
  Number of iterations: 93
  Number of functions evaluations: 114

✅ ECE: 0.4089 (+45.0%), 1.6s
      [429/660] (65.0%) periodic... [ETA: 8.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 851.203505
  Number of iterations: 200
  Number of functions evaluations: 261

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 851.203505
  Number of iterations: 200
  Number of functions evaluations: 261

✅ ECE: 0.4322 (+41.9%), 2.0s
      [430/660] (65.2%) white... [ETA: 8.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1122.835120
  Number of iterations: 16
  Number of functions evaluations: 17

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 1122.835120
  Number of iterations: 16
  Number of functions evaluations: 17

✅ ECE: 0.7438 (+0.0%), 1.0s
      [431/660] (65.3%) rational_quadratic... [ETA: 8.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 852.520596
  Number of iterations: 200
  Number of functions evaluations: 258

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 852.520596
  Number of iterations: 200
  Number of functions evaluations: 258

✅ ECE: 0.3958 (+46.8%), 2.2s
      [432/660] (65.5%) arc_cosine... [ETA: 8.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: KNN
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.127778, LogLoss: 4.514707
      [433/660] (65.6%) rbf... [ETA: 8.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 6038.437862
  Number of iterations: 166
  Number of functions evaluations: 298

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 6038.437862
  Number of iterations: 166
  Number of functions evaluations: 298

✅ ECE: 0.1298 (-1.6%), 2.0s
      [434/660] (65.8%) matern12... [ETA: 8.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4263.410116
  Number of iterations: 12
  Number of functions evaluations: 47

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4263.410116
  Number of iterations: 12
  Number of functions evaluations: 47

✅ ECE: 0.1320 (-3.3%), 1.5s
      [435/660] (65.9%) matern32... [ETA: 8.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4182.918951
  Number of iterations: 55
  Number of functions evaluations: 132

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4182.918951
  Number of iterations: 55
  Number of functions evaluations: 132

✅ ECE: 0.1986 (-55.5%), 2.3s
      [436/660] (66.1%) matern52... [ETA: 8.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 5518.495621
  Number of iterations: 43
  Number of functions evaluations: 125

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 5518.495621
  Number of iterations: 43
  Number of functions evaluations: 125

✅ ECE: 0.1164 (+8.9%), 2.0s
      [437/660] (66.2%) exponential... [ETA: 8.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4214.131603
  Number of iterations: 40
  Number of functions evaluations: 113

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4214.131603
  Number of iterations: 40
  Number of functions evaluations: 113

✅ ECE: 0.1731 (-35.4%), 1.8s
      [438/660] (66.4%) cosine... [ETA: 8.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4262.495455
  Number of iterations: 34
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4262.495455
  Number of iterations: 34
  Number of functions evaluations: 37

✅ ECE: 0.1209 (+5.4%), 1.7s
      [439/660] (66.5%) linear... [ETA: 8.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4260.995722
  Number of iterations: 32
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4260.995722
  Number of iterations: 32
  Number of functions evaluations: 37

✅ ECE: 0.1917 (-50.0%), 1.3s
      [440/660] (66.7%) polynomial... [ETA: 8.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4260.333582
  Number of iterations: 41
  Number of functions evaluations: 43

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4260.333582
  Number of iterations: 41
  Number of functions evaluations: 43

✅ ECE: 0.2121 (-66.0%), 1.5s
      [441/660] (66.8%) periodic... [ETA: 8.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 4469.831138
  Number of iterations: 83
  Number of functions evaluations: 208

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 4469.831138
  Number of iterations: 83
  Number of functions evaluations: 208

✅ ECE: 0.1516 (-18.7%), 2.0s
      [442/660] (67.0%) white... [ETA: 8.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 4264.902357
  Number of iterations: 19
  Number of functions evaluations: 20

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 4264.902357
  Number of iterations: 19
  Number of functions evaluations: 20

✅ ECE: 0.1282 (-0.4%), 1.3s
      [443/660] (67.1%) rational_quadratic... [ETA: 7.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4015.231864
  Number of iterations: 96
  Number of functions evaluations: 205

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 4015.231864
  Number of iterations: 96
  Number of functions evaluations: 205

✅ ECE: 0.1324 (-3.6%), 2.0s
      [444/660] (67.3%) arc_cosine... [ETA: 7.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: XGBoost
   ------------------------------------------------------------------------------------------
[15:19:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
      📊 Uncalibrated - ECE: 0.165703, LogLoss: 0.914978
      [445/660] (67.4%) rbf... [ETA: 7.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 34.214996
  Number of iterations: 80
  Number of functions evaluations: 84

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 34.214996
  Number of iterations: 80
  Number of functions evaluations: 84

✅ ECE: 0.1617 (+2.4%), 1.8s
      [446/660] (67.6%) matern12... [ETA: 7.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.704603
  Number of iterations: 121
  Number of functions evaluations: 235

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.704603
  Number of iterations: 121
  Number of functions evaluations: 235

✅ ECE: 0.1501 (+9.4%), 2.1s
      [447/660] (67.7%) matern32... [ETA: 7.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.816490
  Number of iterations: 200
  Number of functions evaluations: 248

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.816490
  Number of iterations: 200
  Number of functions evaluations: 248

✅ ECE: 0.1197 (+27.7%), 2.1s
      [448/660] (67.9%) matern52... [ETA: 7.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.374768
  Number of iterations: 200
  Number of functions evaluations: 226

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.374768
  Number of iterations: 200
  Number of functions evaluations: 226

✅ ECE: 0.1532 (+7.6%), 2.2s
      [449/660] (68.0%) exponential... [ETA: 7.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 33.776591
  Number of iterations: 82
  Number of functions evaluations: 160

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 33.776591
  Number of iterations: 82
  Number of functions evaluations: 160

✅ ECE: 0.1816 (-9.6%), 2.3s
      [450/660] (68.2%) cosine... [ETA: 7.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 33.438120
  Number of iterations: 78
  Number of functions evaluations: 85

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 33.438120
  Number of iterations: 78
  Number of functions evaluations: 85

✅ ECE: 0.1333 (+19.5%), 1.8s
      [451/660] (68.3%) linear... [ETA: 7.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.144867
  Number of iterations: 42
  Number of functions evaluations: 46

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 32.144867
  Number of iterations: 42
  Number of functions evaluations: 46

✅ ECE: 0.1257 (+24.2%), 1.3s
      [452/660] (68.5%) polynomial... [ETA: 7.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.226632
  Number of iterations: 50
  Number of functions evaluations: 57

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.226632
  Number of iterations: 50
  Number of functions evaluations: 57

✅ ECE: 0.1658 (-0.0%), 1.5s
      [453/660] (68.6%) periodic... [ETA: 7.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 30.370302
  Number of iterations: 200
  Number of functions evaluations: 233

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 30.370302
  Number of iterations: 200
  Number of functions evaluations: 233

✅ ECE: 0.1139 (+31.3%), 2.0s
      [454/660] (68.8%) white... [ETA: 7.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 38.835475
  Number of iterations: 17
  Number of functions evaluations: 18

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 38.835475
  Number of iterations: 17
  Number of functions evaluations: 18

✅ ECE: 0.1657 (+0.0%), 1.1s
      [455/660] (68.9%) rational_quadratic... [ETA: 7.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.314191
  Number of iterations: 200
  Number of functions evaluations: 235

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.314191
  Number of iterations: 200
  Number of functions evaluations: 235

✅ ECE: 0.1342 (+19.0%), 2.3s
      [456/660] (69.1%) arc_cosine... [ETA: 7.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: DecisionTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.276190, LogLoss: 10.690574
      [457/660] (69.2%) rbf... [ETA: 7.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11788.011839
  Number of iterations: 45
  Number of functions evaluations: 127

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11788.011839
  Number of iterations: 45
  Number of functions evaluations: 127

✅ ECE: 0.2762 (+0.0%), 2.1s
      [458/660] (69.4%) matern12... [ETA: 7.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 15617.896982
  Number of iterations: 18
  Number of functions evaluations: 109

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 15617.896982
  Number of iterations: 18
  Number of functions evaluations: 109

✅ ECE: 0.1044 (+62.2%), 1.8s
      [459/660] (69.5%) matern32... [ETA: 7.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11995.240821
  Number of iterations: 34
  Number of functions evaluations: 114

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11995.240821
  Number of iterations: 34
  Number of functions evaluations: 114

✅ ECE: 0.2762 (+0.0%), 2.0s
      [460/660] (69.7%) matern52... [ETA: 7.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11533.236417
  Number of iterations: 41
  Number of functions evaluations: 131

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 11533.236417
  Number of iterations: 41
  Number of functions evaluations: 131

✅ ECE: 0.2762 (+0.0%), 2.1s
      [461/660] (69.8%) exponential... [ETA: 7.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 9332.182019
  Number of iterations: 15
  Number of functions evaluations: 93

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 9332.182019
  Number of iterations: 15
  Number of functions evaluations: 93

✅ ECE: 0.2762 (+0.0%), 1.8s
      [462/660] (70.0%) cosine... [ETA: 7.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 89.833312
  Number of iterations: 200
  Number of functions evaluations: 348

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 89.833312
  Number of iterations: 200
  Number of functions evaluations: 348

✅ ECE: 0.0190 (+93.1%), 2.5s
      [463/660] (70.2%) linear... [ETA: 7.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 65.741948
  Number of iterations: 200
  Number of functions evaluations: 292

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 65.741948
  Number of iterations: 200
  Number of functions evaluations: 292

✅ ECE: 0.0238 (+91.4%), 1.8s
      [464/660] (70.3%) polynomial... [ETA: 7.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 57.176061
  Number of iterations: 200
  Number of functions evaluations: 287

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 57.176061
  Number of iterations: 200
  Number of functions evaluations: 287

✅ ECE: 0.0284 (+89.7%), 2.1s
      [465/660] (70.5%) periodic... [ETA: 7.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 9917.549859
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 9917.549859
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.2762 (+0.0%), 1.6s
      [466/660] (70.6%) white... [ETA: 7.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 9917.549859
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 9917.549859
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.2762 (+0.0%), 0.9s
      [467/660] (70.8%) rational_quadratic... [ETA: 7.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 16194.742504
  Number of iterations: 45
  Number of functions evaluations: 135

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 16194.742504
  Number of iterations: 45
  Number of functions evaluations: 135

✅ ECE: 0.0772 (+72.1%), 2.2s
      [468/660] (70.9%) arc_cosine... [ETA: 6.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SVC
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.096032, LogLoss: 0.644898
      [469/660] (71.1%) rbf... [ETA: 6.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.050035
  Number of iterations: 123
  Number of functions evaluations: 136

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.050035
  Number of iterations: 123
  Number of functions evaluations: 136

✅ ECE: 0.0802 (+16.5%), 1.9s
      [470/660] (71.2%) matern12... [ETA: 6.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.096421
  Number of iterations: 34
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.096421
  Number of iterations: 34
  Number of functions evaluations: 36

✅ ECE: 0.0960 (+0.0%), 2.1s
      [471/660] (71.4%) matern32... [ETA: 6.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.062821
  Number of iterations: 119
  Number of functions evaluations: 134

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.062821
  Number of iterations: 119
  Number of functions evaluations: 134

✅ ECE: 0.0922 (+4.0%), 2.1s
      [472/660] (71.5%) matern52... [ETA: 6.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.059162
  Number of iterations: 139
  Number of functions evaluations: 158

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.059162
  Number of iterations: 139
  Number of functions evaluations: 158

✅ ECE: 0.0800 (+16.6%), 2.2s
      [473/660] (71.7%) exponential... [ETA: 6.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.096421
  Number of iterations: 33
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.096421
  Number of iterations: 33
  Number of functions evaluations: 35

✅ ECE: 0.0960 (+0.0%), 1.8s
      [474/660] (71.8%) cosine... [ETA: 6.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 30.894132
  Number of iterations: 54
  Number of functions evaluations: 65

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 30.894132
  Number of iterations: 54
  Number of functions evaluations: 65

✅ ECE: 0.0904 (+5.9%), 1.8s
      [475/660] (72.0%) linear... [ETA: 6.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.042308
  Number of iterations: 32
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.042308
  Number of iterations: 32
  Number of functions evaluations: 35

✅ ECE: 0.1188 (-23.7%), 1.2s
      [476/660] (72.1%) polynomial... [ETA: 6.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 30.995425
  Number of iterations: 35
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 30.995425
  Number of iterations: 35
  Number of functions evaluations: 36

✅ ECE: 0.1036 (-7.9%), 1.5s
      [477/660] (72.3%) periodic... [ETA: 6.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.096421
  Number of iterations: 37
  Number of functions evaluations: 41

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 31.096421
  Number of iterations: 37
  Number of functions evaluations: 41

✅ ECE: 0.0960 (+0.0%), 2.2s
      [478/660] (72.4%) white... [ETA: 6.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 31.096420
  Number of iterations: 19
  Number of functions evaluations: 20

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 31.096420
  Number of iterations: 19
  Number of functions evaluations: 20

✅ ECE: 0.0960 (+0.0%), 1.0s
      [479/660] (72.6%) rational_quadratic... [ETA: 6.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.050192
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 31.050192
  Number of iterations: 200
  Number of functions evaluations: 230

✅ ECE: 0.0969 (-0.9%), 2.3s
      [480/660] (72.7%) arc_cosine... [ETA: 6.5min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: ExtraTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.359524, LogLoss: 13.568805
      [481/660] (72.9%) rbf... [ETA: 6.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 13565.906768
  Number of iterations: 41
  Number of functions evaluations: 128

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 13565.906768
  Number of iterations: 41
  Number of functions evaluations: 128

✅ ECE: 0.3595 (+0.0%), 1.7s
      [482/660] (73.0%) matern12... [ETA: 6.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 15901.295679
  Number of iterations: 17
  Number of functions evaluations: 95

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 15901.295679
  Number of iterations: 17
  Number of functions evaluations: 95

✅ ECE: 0.3595 (+0.0%), 1.7s
      [483/660] (73.2%) matern32... [ETA: 6.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 13802.402079
  Number of iterations: 37
  Number of functions evaluations: 115

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 13802.402079
  Number of iterations: 37
  Number of functions evaluations: 115

✅ ECE: 0.3595 (+0.0%), 1.9s
      [484/660] (73.3%) matern52... [ETA: 6.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 16255.285560
  Number of iterations: 40
  Number of functions evaluations: 115

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 16255.285560
  Number of iterations: 40
  Number of functions evaluations: 115

✅ ECE: 0.3595 (+0.0%), 2.3s
      [485/660] (73.5%) exponential... [ETA: 6.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 15020.060677
  Number of iterations: 23
  Number of functions evaluations: 106

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 15020.060677
  Number of iterations: 23
  Number of functions evaluations: 106

✅ ECE: 0.3595 (+0.0%), 1.8s
      [486/660] (73.6%) cosine... [ETA: 6.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 108.494903
  Number of iterations: 200
  Number of functions evaluations: 394

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 108.494903
  Number of iterations: 200
  Number of functions evaluations: 394

✅ ECE: 0.0595 (+83.4%), 2.2s
      [487/660] (73.8%) linear... [ETA: 6.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 68.910919
  Number of iterations: 200
  Number of functions evaluations: 306

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 68.910919
  Number of iterations: 200
  Number of functions evaluations: 306

✅ ECE: 0.0595 (+83.4%), 1.8s
      [488/660] (73.9%) polynomial... [ETA: 6.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.386960
  Number of iterations: 200
  Number of functions evaluations: 282

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.386960
  Number of iterations: 200
  Number of functions evaluations: 282

✅ ECE: 0.0307 (+91.5%), 1.9s
      [489/660] (74.1%) periodic... [ETA: 6.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 11334.342697
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 11334.342697
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.3595 (+0.0%), 1.8s
      [490/660] (74.2%) white... [ETA: 6.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 11334.342697
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 11334.342697
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.3595 (+0.0%), 1.1s
      [491/660] (74.4%) rational_quadratic... [ETA: 6.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 18284.845028
  Number of iterations: 38
  Number of functions evaluations: 141

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 18284.845028
  Number of iterations: 38
  Number of functions evaluations: 141

✅ ECE: 0.3381 (+6.0%), 2.5s
      [492/660] (74.5%) arc_cosine... [ETA: 6.0min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SGD
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.177707, LogLoss: 1.739699
      [493/660] (74.7%) rbf... [ETA: 6.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.218848
  Number of iterations: 200
  Number of functions evaluations: 236

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.218848
  Number of iterations: 200
  Number of functions evaluations: 236

✅ ECE: 0.1688 (+5.0%), 2.4s
      [494/660] (74.8%) matern12... [ETA: 5.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.259661
  Number of iterations: 61
  Number of functions evaluations: 195

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.259661
  Number of iterations: 61
  Number of functions evaluations: 195

✅ ECE: 0.1687 (+5.1%), 2.1s
      [495/660] (75.0%) matern32... [ETA: 5.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 66.086543
  Number of iterations: 200
  Number of functions evaluations: 249

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 66.086543
  Number of iterations: 200
  Number of functions evaluations: 249

✅ ECE: 0.1248 (+29.8%), 2.3s
      [496/660] (75.2%) matern52... [ETA: 5.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 64.256685
  Number of iterations: 200
  Number of functions evaluations: 248

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 64.256685
  Number of iterations: 200
  Number of functions evaluations: 248

✅ ECE: 0.1094 (+38.4%), 2.5s
      [497/660] (75.3%) exponential... [ETA: 5.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.548196
  Number of iterations: 70
  Number of functions evaluations: 197

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.548196
  Number of iterations: 70
  Number of functions evaluations: 197

✅ ECE: 0.1166 (+34.4%), 1.9s
      [498/660] (75.5%) cosine... [ETA: 5.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 70.101289
  Number of iterations: 200
  Number of functions evaluations: 247

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 70.101289
  Number of iterations: 200
  Number of functions evaluations: 247

✅ ECE: 0.2143 (-20.6%), 2.1s
      [499/660] (75.6%) linear... [ETA: 5.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 71.681703
  Number of iterations: 33
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 71.681703
  Number of iterations: 33
  Number of functions evaluations: 38

✅ ECE: 0.2451 (-37.9%), 1.6s
      [500/660] (75.8%) polynomial... [ETA: 5.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.150114
  Number of iterations: 70
  Number of functions evaluations: 85

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.150114
  Number of iterations: 70
  Number of functions evaluations: 85

✅ ECE: 0.2154 (-21.2%), 1.7s
      [501/660] (75.9%) periodic... [ETA: 5.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.992194
  Number of iterations: 200
  Number of functions evaluations: 281

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 63.992194
  Number of iterations: 200
  Number of functions evaluations: 281

✅ ECE: 0.1437 (+19.1%), 2.2s
      [502/660] (76.1%) white... [ETA: 5.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 95.400783
  Number of iterations: 16
  Number of functions evaluations: 17

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 95.400783
  Number of iterations: 16
  Number of functions evaluations: 17

✅ ECE: 0.1777 (+0.0%), 1.0s
      [503/660] (76.2%) rational_quadratic... [ETA: 5.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 64.297585
  Number of iterations: 200
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 64.297585
  Number of iterations: 200
  Number of functions evaluations: 244

✅ ECE: 0.1404 (+21.0%), 2.2s
      [504/660] (76.4%) arc_cosine... [ETA: 5.6min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: MLP
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.207547, LogLoss: 1.087130
      [505/660] (76.5%) rbf... [ETA: 5.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 37.018758
  Number of iterations: 200
  Number of functions evaluations: 258

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 37.018758
  Number of iterations: 200
  Number of functions evaluations: 258

✅ ECE: 0.1721 (+17.1%), 2.1s
      [506/660] (76.7%) matern12... [ETA: 5.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 40.861307
  Number of iterations: 200
  Number of functions evaluations: 401

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 40.861307
  Number of iterations: 200
  Number of functions evaluations: 401

✅ ECE: 0.1557 (+25.0%), 2.9s
      [507/660] (76.8%) matern32... [ETA: 5.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 37.050581
  Number of iterations: 200
  Number of functions evaluations: 234

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 37.050581
  Number of iterations: 200
  Number of functions evaluations: 234

✅ ECE: 0.1408 (+32.2%), 3.1s
      [508/660] (77.0%) matern52... [ETA: 5.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 36.481122
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 36.481122
  Number of iterations: 200
  Number of functions evaluations: 230

✅ ECE: 0.1544 (+25.6%), 3.0s
      [509/660] (77.1%) exponential... [ETA: 5.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40.904505
  Number of iterations: 184
  Number of functions evaluations: 359

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40.904505
  Number of iterations: 184
  Number of functions evaluations: 359

✅ ECE: 0.2115 (-1.9%), 3.3s
      [510/660] (77.3%) cosine... [ETA: 5.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 46.241318
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 46.241318
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.1517 (+26.9%), 3.5s
      [511/660] (77.4%) linear... [ETA: 5.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 43.956553
  Number of iterations: 105
  Number of functions evaluations: 125

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 43.956553
  Number of iterations: 105
  Number of functions evaluations: 125

✅ ECE: 0.1790 (+13.8%), 3.2s
      [512/660] (77.6%) polynomial... [ETA: 5.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 42.647117
  Number of iterations: 68
  Number of functions evaluations: 82

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 42.647117
  Number of iterations: 68
  Number of functions evaluations: 82

✅ ECE: 0.1661 (+20.0%), 3.1s
      [513/660] (77.7%) periodic... [ETA: 5.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 34.527210
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 34.527210
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.1323 (+36.3%), 4.0s
      [514/660] (77.9%) white... [ETA: 5.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 63.313629
  Number of iterations: 18
  Number of functions evaluations: 19

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 63.313629
  Number of iterations: 18
  Number of functions evaluations: 19

✅ ECE: 0.2075 (+0.0%), 1.5s
      [515/660] (78.0%) rational_quadratic... [ETA: 5.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 36.408688
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 36.408688
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.1678 (+19.2%), 3.5s
      [516/660] (78.2%) arc_cosine... [ETA: 5.2min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: BernoulliNB
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.262642, LogLoss: 1.126787
      [517/660] (78.3%) rbf... [ETA: 5.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.649714
  Number of iterations: 200
  Number of functions evaluations: 245

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.649714
  Number of iterations: 200
  Number of functions evaluations: 245

✅ ECE: 0.1354 (+48.5%), 3.0s
      [518/660] (78.5%) matern12... [ETA: 5.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 43.126603
  Number of iterations: 192
  Number of functions evaluations: 379

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 43.126603
  Number of iterations: 192
  Number of functions evaluations: 379

✅ ECE: 0.1887 (+28.2%), 3.1s
      [519/660] (78.6%) matern32... [ETA: 5.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.464368
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.464368
  Number of iterations: 200
  Number of functions evaluations: 230

✅ ECE: 0.1793 (+31.8%), 3.3s
      [520/660] (78.8%) matern52... [ETA: 5.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.366471
  Number of iterations: 200
  Number of functions evaluations: 235

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.366471
  Number of iterations: 200
  Number of functions evaluations: 235

✅ ECE: 0.2018 (+23.2%), 3.8s
      [521/660] (78.9%) exponential... [ETA: 5.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 43.059197
  Number of iterations: 200
  Number of functions evaluations: 309

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 43.059197
  Number of iterations: 200
  Number of functions evaluations: 309

✅ ECE: 0.1657 (+36.9%), 2.5s
      [522/660] (79.1%) cosine... [ETA: 5.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.798939
  Number of iterations: 147
  Number of functions evaluations: 177

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 41.798939
  Number of iterations: 147
  Number of functions evaluations: 177

✅ ECE: 0.1480 (+43.7%), 2.0s
      [523/660] (79.2%) linear... [ETA: 4.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 40.520954
  Number of iterations: 200
  Number of functions evaluations: 227

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 40.520954
  Number of iterations: 200
  Number of functions evaluations: 227

✅ ECE: 0.1571 (+40.2%), 1.6s
      [524/660] (79.4%) polynomial... [ETA: 4.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40.117962
  Number of iterations: 59
  Number of functions evaluations: 72

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 40.117962
  Number of iterations: 59
  Number of functions evaluations: 72

✅ ECE: 0.1656 (+36.9%), 1.9s
      [525/660] (79.5%) periodic... [ETA: 4.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.205210
  Number of iterations: 200
  Number of functions evaluations: 228

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.205210
  Number of iterations: 200
  Number of functions evaluations: 228

✅ ECE: 0.1990 (+24.2%), 2.7s
      [526/660] (79.7%) white... [ETA: 4.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 49.427701
  Number of iterations: 18
  Number of functions evaluations: 19

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 49.427701
  Number of iterations: 18
  Number of functions evaluations: 19

✅ ECE: 0.2626 (+0.0%), 1.4s
      [527/660] (79.8%) rational_quadratic... [ETA: 4.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.331919
  Number of iterations: 200
  Number of functions evaluations: 228

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 42.331919
  Number of iterations: 200
  Number of functions evaluations: 228

✅ ECE: 0.1811 (+31.1%), 3.1s
      [528/660] (80.0%) arc_cosine... [ETA: 4.7min] ❌ __init__() missing 1 required positional

====================================================================================================
📂 DATASET: AIR_QUALITY
====================================================================================================
   📊 Classes: 4
   📊 Train: 3499, Calib: 500, Test: 1001

   🤖 CLASSIFIER: RandomForest
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.055418, LogLoss: 0.139528
      [529/660] (80.2%) rbf... [ETA: 4.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.624761
  Number of iterations: 63
  Number of functions evaluations: 71

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.624761
  Number of iterations: 63
  Number of functions evaluations: 71

✅ ECE: 0.0403 (+27.3%), 2.4s
      [530/660] (80.3%) matern12... [ETA: 4.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 775.191845
  Number of iterations: 153
  Number of functions evaluations: 231

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 775.191845
  Number of iterations: 153
  Number of functions evaluations: 231

✅ ECE: 0.0397 (+28.4%), 3.8s
      [531/660] (80.5%) matern32... [ETA: 4.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.632108
  Number of iterations: 172
  Number of functions evaluations: 183

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.632108
  Number of iterations: 172
  Number of functions evaluations: 183

✅ ECE: 0.0368 (+33.6%), 3.5s
      [532/660] (80.6%) matern52... [ETA: 4.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.532746
  Number of iterations: 181
  Number of functions evaluations: 206

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 774.532746
  Number of iterations: 181
  Number of functions evaluations: 206

✅ ECE: 0.0391 (+29.5%), 3.4s
      [533/660] (80.8%) exponential... [ETA: 4.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 775.144102
  Number of iterations: 107
  Number of functions evaluations: 195

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 775.144102
  Number of iterations: 107
  Number of functions evaluations: 195

✅ ECE: 0.0393 (+29.2%), 2.9s
      [534/660] (80.9%) cosine... [ETA: 4.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 773.827371
  Number of iterations: 73
  Number of functions evaluations: 89

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 773.827371
  Number of iterations: 73
  Number of functions evaluations: 89

✅ ECE: 0.0385 (+30.5%), 3.0s
      [535/660] (81.1%) linear... [ETA: 4.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 773.562289
  Number of iterations: 40
  Number of functions evaluations: 46

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 773.562289
  Number of iterations: 40
  Number of functions evaluations: 46

✅ ECE: 0.0380 (+31.5%), 2.0s
      [536/660] (81.2%) polynomial... [ETA: 4.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 773.666400
  Number of iterations: 37
  Number of functions evaluations: 40

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 773.666400
  Number of iterations: 37
  Number of functions evaluations: 40

✅ ECE: 0.0370 (+33.3%), 2.0s
      [537/660] (81.4%) periodic... [ETA: 4.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 774.468653
  Number of iterations: 200
  Number of functions evaluations: 219

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 774.468653
  Number of iterations: 200
  Number of functions evaluations: 219

✅ ECE: 0.0368 (+33.6%), 3.2s
      [538/660] (81.5%) white... [ETA: 4.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 778.075253
  Number of iterations: 21
  Number of functions evaluations: 22

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 778.075253
  Number of iterations: 21
  Number of functions evaluations: 22

✅ ECE: 0.0555 (-0.1%), 1.5s
      [539/660] (81.7%) rational_quadratic... [ETA: 4.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 774.422944
  Number of iterations: 200
  Number of functions evaluations: 231

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 774.422944
  Number of iterations: 200
  Number of functions evaluations: 231

✅ ECE: 0.0385 (+30.6%), 3.6s
      [540/660] (81.8%) arc_cosine... [ETA: 4.3min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: AdaBoost
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.313892, LogLoss: 1.313942
      [541/660] (82.0%) rbf... [ETA: 4.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 282.589186
  Number of iterations: 200
  Number of functions evaluations: 263

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 282.589186
  Number of iterations: 200
  Number of functions evaluations: 263

✅ ECE: 0.1287 (+59.0%), 3.5s
      [542/660] (82.1%) matern12... [ETA: 4.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 313.150411
  Number of iterations: 200
  Number of functions evaluations: 369

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 313.150411
  Number of iterations: 200
  Number of functions evaluations: 369

✅ ECE: 0.1255 (+60.0%), 5.0s
      [543/660] (82.3%) matern32... [ETA: 4.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 292.283428
  Number of iterations: 200
  Number of functions evaluations: 243

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 292.283428
  Number of iterations: 200
  Number of functions evaluations: 243

✅ ECE: 0.0969 (+69.1%), 3.8s
      [544/660] (82.4%) matern52... [ETA: 4.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 289.379772
  Number of iterations: 200
  Number of functions evaluations: 243

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 289.379772
  Number of iterations: 200
  Number of functions evaluations: 243

✅ ECE: 0.0951 (+69.7%), 3.9s
      [545/660] (82.6%) exponential... [ETA: 4.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 316.734774
  Number of iterations: 200
  Number of functions evaluations: 373

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 316.734774
  Number of iterations: 200
  Number of functions evaluations: 373

✅ ECE: 0.1403 (+55.3%), 4.3s
      [546/660] (82.7%) cosine... [ETA: 4.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 331.828112
  Number of iterations: 200
  Number of functions evaluations: 291

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 331.828112
  Number of iterations: 200
  Number of functions evaluations: 291

✅ ECE: 0.1615 (+48.5%), 3.9s
      [547/660] (82.9%) linear... [ETA: 4.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 585.285985
  Number of iterations: 34
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 585.285985
  Number of iterations: 34
  Number of functions evaluations: 37

✅ ECE: 0.2488 (+20.7%), 2.1s
      [548/660] (83.0%) polynomial... [ETA: 4.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 372.989539
  Number of iterations: 200
  Number of functions evaluations: 270

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 372.989539
  Number of iterations: 200
  Number of functions evaluations: 270

✅ ECE: 0.2203 (+29.8%), 3.4s
      [549/660] (83.2%) periodic... [ETA: 4.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 311.399553
  Number of iterations: 200
  Number of functions evaluations: 249

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 311.399553
  Number of iterations: 200
  Number of functions evaluations: 249

✅ ECE: 0.0687 (+78.1%), 4.0s
      [550/660] (83.3%) white... [ETA: 4.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 639.901203
  Number of iterations: 23
  Number of functions evaluations: 24

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 639.901203
  Number of iterations: 23
  Number of functions evaluations: 24

✅ ECE: 0.3139 (+0.0%), 1.5s
      [551/660] (83.5%) rational_quadratic... [ETA: 4.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 288.603412
  Number of iterations: 200
  Number of functions evaluations: 278

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 288.603412
  Number of iterations: 200
  Number of functions evaluations: 278

✅ ECE: 0.1060 (+66.2%), 4.3s
      [552/660] (83.6%) arc_cosine... [ETA: 4.0min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: NaiveBayes
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.024736, LogLoss: 0.339864
      [553/660] (83.8%) rbf... [ETA: 3.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.347660
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.347660
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.0271 (-9.8%), 3.4s
      [554/660] (83.9%) matern12... [ETA: 3.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 176.075612
  Number of iterations: 200
  Number of functions evaluations: 316

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 176.075612
  Number of iterations: 200
  Number of functions evaluations: 316

✅ ECE: 0.0271 (-9.6%), 4.0s
      [555/660] (84.1%) matern32... [ETA: 3.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.666420
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.666420
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.0259 (-4.8%), 3.6s
      [556/660] (84.2%) matern52... [ETA: 3.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.531398
  Number of iterations: 200
  Number of functions evaluations: 228

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.531398
  Number of iterations: 200
  Number of functions evaluations: 228

✅ ECE: 0.0240 (+2.8%), 4.3s
      [557/660] (84.4%) exponential... [ETA: 3.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 176.074258
  Number of iterations: 200
  Number of functions evaluations: 291

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 176.074258
  Number of iterations: 200
  Number of functions evaluations: 291

✅ ECE: 0.0317 (-28.2%), 3.9s
      [558/660] (84.5%) cosine... [ETA: 3.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 174.493539
  Number of iterations: 59
  Number of functions evaluations: 67

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 174.493539
  Number of iterations: 59
  Number of functions evaluations: 67

✅ ECE: 0.0354 (-43.0%), 2.8s
      [559/660] (84.7%) linear... [ETA: 3.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 173.848961
  Number of iterations: 100
  Number of functions evaluations: 119

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 173.848961
  Number of iterations: 100
  Number of functions evaluations: 119

✅ ECE: 0.0329 (-32.8%), 2.2s
      [560/660] (84.8%) polynomial... [ETA: 3.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 173.978982
  Number of iterations: 47
  Number of functions evaluations: 49

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 173.978982
  Number of iterations: 47
  Number of functions evaluations: 49

✅ ECE: 0.0280 (-13.4%), 2.2s
      [561/660] (85.0%) periodic... [ETA: 3.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.354496
  Number of iterations: 200
  Number of functions evaluations: 231

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 175.354496
  Number of iterations: 200
  Number of functions evaluations: 231

✅ ECE: 0.0304 (-22.9%), 3.6s
      [562/660] (85.2%) white... [ETA: 3.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 179.654279
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 179.654279
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0246 (+0.4%), 1.3s
      [563/660] (85.3%) rational_quadratic... [ETA: 3.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 175.392014
  Number of iterations: 136
  Number of functions evaluations: 163

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 175.392014
  Number of iterations: 136
  Number of functions evaluations: 163

✅ ECE: 0.0275 (-11.1%), 3.9s
      [564/660] (85.5%) arc_cosine... [ETA: 3.5min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: KNN
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.025275, LogLoss: 0.702587
      [565/660] (85.6%) rbf... [ETA: 3.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7852.178244
  Number of iterations: 62
  Number of functions evaluations: 70

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7852.178244
  Number of iterations: 62
  Number of functions evaluations: 70

✅ ECE: 0.0380 (-50.5%), 2.6s
      [566/660] (85.8%) matern12... [ETA: 3.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8667.512106
  Number of iterations: 95
  Number of functions evaluations: 249

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8667.512106
  Number of iterations: 95
  Number of functions evaluations: 249

✅ ECE: 0.0258 (-1.9%), 3.7s
      [567/660] (85.9%) matern32... [ETA: 3.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8176.717188
  Number of iterations: 68
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 8176.717188
  Number of iterations: 68
  Number of functions evaluations: 244

✅ ECE: 0.0432 (-70.8%), 4.1s
      [568/660] (86.1%) matern52... [ETA: 3.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7598.201961
  Number of iterations: 104
  Number of functions evaluations: 206

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7598.201961
  Number of iterations: 104
  Number of functions evaluations: 206

✅ ECE: 0.0180 (+28.6%), 3.6s
      [569/660] (86.2%) exponential... [ETA: 3.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7812.164504
  Number of iterations: 23
  Number of functions evaluations: 109

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7812.164504
  Number of iterations: 23
  Number of functions evaluations: 109

✅ ECE: 0.0400 (-58.3%), 3.2s
      [570/660] (86.4%) cosine... [ETA: 3.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7851.690684
  Number of iterations: 26
  Number of functions evaluations: 27

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7851.690684
  Number of iterations: 26
  Number of functions evaluations: 27

✅ ECE: 0.0387 (-53.2%), 1.9s
      [571/660] (86.5%) linear... [ETA: 3.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7850.299604
  Number of iterations: 24
  Number of functions evaluations: 26

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7850.299604
  Number of iterations: 24
  Number of functions evaluations: 26

✅ ECE: 0.0476 (-88.5%), 1.4s
      [572/660] (86.7%) polynomial... [ETA: 3.3min] ❌ Cholesky decomposition was not successfu
      [573/660] (86.8%) periodic... [ETA: 3.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 3194.525219
  Number of iterations: 200
  Number of functions evaluations: 379

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 3194.525219
  Number of iterations: 200
  Number of functions evaluations: 379

✅ ECE: 0.2691 (-964.6%), 3.2s
      [574/660] (87.0%) white... [ETA: 3.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7852.709202
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7852.709202
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0264 (-4.6%), 0.9s
      [575/660] (87.1%) rational_quadratic... [ETA: 3.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7684.002800
  Number of iterations: 114
  Number of functions evaluations: 273

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 7684.002800
  Number of iterations: 114
  Number of functions evaluations: 273

✅ ECE: 0.0298 (-17.7%), 2.7s
      [576/660] (87.3%) arc_cosine... [ETA: 3.1min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: XGBoost
   ------------------------------------------------------------------------------------------
[15:24:44] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
      📊 Uncalibrated - ECE: 0.022156, LogLoss: 0.155589
      [577/660] (87.4%) rbf... [ETA: 3.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 74.506166
  Number of iterations: 102
  Number of functions evaluations: 112

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 74.506166
  Number of iterations: 102
  Number of functions evaluations: 112

✅ ECE: 0.0322 (-45.5%), 2.3s
      [578/660] (87.6%) matern12... [ETA: 3.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 76.219034
  Number of iterations: 173
  Number of functions evaluations: 254

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 76.219034
  Number of iterations: 173
  Number of functions evaluations: 254

✅ ECE: 0.0308 (-39.1%), 2.9s
      [579/660] (87.7%) matern32... [ETA: 3.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.005764
  Number of iterations: 169
  Number of functions evaluations: 180

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.005764
  Number of iterations: 169
  Number of functions evaluations: 180

✅ ECE: 0.0307 (-38.7%), 3.0s
      [580/660] (87.9%) matern52... [ETA: 3.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 74.772490
  Number of iterations: 164
  Number of functions evaluations: 188

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 74.772490
  Number of iterations: 164
  Number of functions evaluations: 188

✅ ECE: 0.0330 (-49.0%), 3.0s
      [581/660] (88.0%) exponential... [ETA: 2.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 76.234325
  Number of iterations: 180
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 76.234325
  Number of iterations: 180
  Number of functions evaluations: 237

✅ ECE: 0.0326 (-47.1%), 3.2s
      [582/660] (88.2%) cosine... [ETA: 2.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 73.281823
  Number of iterations: 71
  Number of functions evaluations: 83

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 73.281823
  Number of iterations: 71
  Number of functions evaluations: 83

✅ ECE: 0.0298 (-34.4%), 2.1s
      [583/660] (88.3%) linear... [ETA: 2.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.556730
  Number of iterations: 46
  Number of functions evaluations: 52

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.556730
  Number of iterations: 46
  Number of functions evaluations: 52

✅ ECE: 0.0359 (-62.0%), 1.5s
      [584/660] (88.5%) polynomial... [ETA: 2.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.422634
  Number of iterations: 60
  Number of functions evaluations: 63

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 72.422634
  Number of iterations: 60
  Number of functions evaluations: 63

✅ ECE: 0.0349 (-57.3%), 1.9s
      [585/660] (88.6%) periodic... [ETA: 2.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 74.585532
  Number of iterations: 200
  Number of functions evaluations: 237

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 74.585532
  Number of iterations: 200
  Number of functions evaluations: 237

✅ ECE: 0.0306 (-38.1%), 3.3s
      [586/660] (88.8%) white... [ETA: 2.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 89.129152
  Number of iterations: 19
  Number of functions evaluations: 20

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 89.129152
  Number of iterations: 19
  Number of functions evaluations: 20

✅ ECE: 0.0222 (+0.0%), 1.0s
      [587/660] (88.9%) rational_quadratic... [ETA: 2.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 74.497377
  Number of iterations: 200
  Number of functions evaluations: 227

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 74.497377
  Number of iterations: 200
  Number of functions evaluations: 227

✅ ECE: 0.0324 (-46.2%), 3.0s
      [588/660] (89.1%) arc_cosine... [ETA: 2.7min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: DecisionTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.055578, LogLoss: 3.070880
      [589/660] (89.2%) rbf... [ETA: 2.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 35292.640976
  Number of iterations: 73
  Number of functions evaluations: 176

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 35292.640976
  Number of iterations: 73
  Number of functions evaluations: 176

✅ ECE: 0.2344 (-321.8%), 2.2s
      [590/660] (89.4%) matern12... [ETA: 2.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 32383.767340
  Number of iterations: 28
  Number of functions evaluations: 104

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 32383.767340
  Number of iterations: 28
  Number of functions evaluations: 104

✅ ECE: 0.0565 (-1.7%), 1.9s
      [591/660] (89.5%) matern32... [ETA: 2.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 36090.939544
  Number of iterations: 61
  Number of functions evaluations: 153

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 36090.939544
  Number of iterations: 61
  Number of functions evaluations: 153

✅ ECE: 0.2352 (-323.2%), 2.1s
      [592/660] (89.7%) matern52... [ETA: 2.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 29577.453242
  Number of iterations: 49
  Number of functions evaluations: 142

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 29577.453242
  Number of iterations: 49
  Number of functions evaluations: 142

✅ ECE: 0.2705 (-386.7%), 2.7s
      [593/660] (89.8%) exponential... [ETA: 2.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 34839.446578
  Number of iterations: 25
  Number of functions evaluations: 106

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 34839.446578
  Number of iterations: 25
  Number of functions evaluations: 106

✅ ECE: 0.0556 (+0.0%), 1.9s
      [594/660] (90.0%) cosine... [ETA: 2.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 252.786739
  Number of iterations: 200
  Number of functions evaluations: 353

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 252.786739
  Number of iterations: 200
  Number of functions evaluations: 353

✅ ECE: 0.0068 (+87.8%), 2.8s
      [595/660] (90.2%) linear... [ETA: 2.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.033660
  Number of iterations: 200
  Number of functions evaluations: 351

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.033660
  Number of iterations: 200
  Number of functions evaluations: 351

✅ ECE: 0.0068 (+87.8%), 2.3s
      [596/660] (90.3%) polynomial... [ETA: 2.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 212.762989
  Number of iterations: 200
  Number of functions evaluations: 310

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 212.762989
  Number of iterations: 200
  Number of functions evaluations: 310

✅ ECE: 0.0068 (+87.8%), 2.3s
      [597/660] (90.5%) periodic... [ETA: 2.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 26210.667486
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 26210.667486
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0556 (+0.0%), 1.7s
      [598/660] (90.6%) white... [ETA: 2.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 26210.667486
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 26210.667486
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0556 (+0.0%), 0.9s
      [599/660] (90.8%) rational_quadratic... [ETA: 2.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 36355.190844
  Number of iterations: 41
  Number of functions evaluations: 125

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 36355.190844
  Number of iterations: 41
  Number of functions evaluations: 125

✅ ECE: 0.1942 (-249.4%), 2.2s
      [600/660] (90.9%) arc_cosine... [ETA: 2.2min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SVC
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.030598, LogLoss: 0.153307
      [601/660] (91.1%) rbf... [ETA: 2.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 34
  Number of functions evaluations: 40

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 34
  Number of functions evaluations: 40

✅ ECE: 0.0306 (+0.0%), 1.9s
      [602/660] (91.2%) matern12... [ETA: 2.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 30
  Number of functions evaluations: 32

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 30
  Number of functions evaluations: 32

✅ ECE: 0.0306 (+0.0%), 1.8s
      [603/660] (91.4%) matern32... [ETA: 2.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 32
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 32
  Number of functions evaluations: 36

✅ ECE: 0.0306 (+0.0%), 1.8s
      [604/660] (91.5%) matern52... [ETA: 2.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 33
  Number of functions evaluations: 38

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 33
  Number of functions evaluations: 38

✅ ECE: 0.0306 (+0.0%), 2.1s
      [605/660] (91.7%) exponential... [ETA: 2.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 32
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 32
  Number of functions evaluations: 35

✅ ECE: 0.0306 (+0.0%), 1.9s
      [606/660] (91.8%) cosine... [ETA: 2.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782445
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0306 (+0.0%), 2.3s
      [607/660] (92.0%) linear... [ETA: 1.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782431
  Number of iterations: 34
  Number of functions evaluations: 39

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782431
  Number of iterations: 34
  Number of functions evaluations: 39

✅ ECE: 0.0306 (+0.0%), 1.4s
      [608/660] (92.1%) polynomial... [ETA: 1.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782425
  Number of iterations: 29
  Number of functions evaluations: 32

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782425
  Number of iterations: 29
  Number of functions evaluations: 32

✅ ECE: 0.0306 (+0.0%), 1.6s
      [609/660] (92.3%) periodic... [ETA: 1.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 31
  Number of functions evaluations: 35

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 31
  Number of functions evaluations: 35

✅ ECE: 0.0306 (+0.0%), 1.9s
      [610/660] (92.4%) white... [ETA: 1.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 75.782433
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 75.782433
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0306 (+0.0%), 1.0s
      [611/660] (92.6%) rational_quadratic... [ETA: 1.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 34
  Number of functions evaluations: 40

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 75.782446
  Number of iterations: 34
  Number of functions evaluations: 40

✅ ECE: 0.0306 (+0.0%), 1.9s
      [612/660] (92.7%) arc_cosine... [ETA: 1.8min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: ExtraTree
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.096537, LogLoss: 4.485555
      [613/660] (92.9%) rbf... [ETA: 1.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53467.485480
  Number of iterations: 23
  Number of functions evaluations: 109

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53467.485480
  Number of iterations: 23
  Number of functions evaluations: 109

✅ ECE: 0.0965 (+0.0%), 1.8s
      [614/660] (93.0%) matern12... [ETA: 1.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53116.216976
  Number of iterations: 28
  Number of functions evaluations: 123

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53116.216976
  Number of iterations: 28
  Number of functions evaluations: 123

✅ ECE: 0.0965 (+0.0%), 2.3s
      [615/660] (93.2%) matern32... [ETA: 1.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 54825.541991
  Number of iterations: 53
  Number of functions evaluations: 149

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 54825.541991
  Number of iterations: 53
  Number of functions evaluations: 149

✅ ECE: 0.1904 (-97.2%), 1.9s
      [616/660] (93.3%) matern52... [ETA: 1.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 59563.073634
  Number of iterations: 86
  Number of functions evaluations: 192

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 59563.073634
  Number of iterations: 86
  Number of functions evaluations: 192

✅ ECE: 0.1018 (-5.5%), 2.3s
      [617/660] (93.5%) exponential... [ETA: 1.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53292.955929
  Number of iterations: 37
  Number of functions evaluations: 137

INFO:tensorflow:Optimization terminated with:
  Message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
  Objective function value: 53292.955929
  Number of iterations: 37
  Number of functions evaluations: 137

✅ ECE: 0.2100 (-117.5%), 1.8s
      [618/660] (93.6%) cosine... [ETA: 1.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 392.988769
  Number of iterations: 200
  Number of functions evaluations: 337

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 392.988769
  Number of iterations: 200
  Number of functions evaluations: 337

✅ ECE: 0.0011 (+98.9%), 2.5s
      [619/660] (93.8%) linear... [ETA: 1.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 356.531322
  Number of iterations: 200
  Number of functions evaluations: 335

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 356.531322
  Number of iterations: 200
  Number of functions evaluations: 335

✅ ECE: 0.0011 (+98.9%), 2.2s
      [620/660] (93.9%) polynomial... [ETA: 1.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 306.612955
  Number of iterations: 200
  Number of functions evaluations: 302

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 306.612955
  Number of iterations: 200
  Number of functions evaluations: 302

✅ ECE: 0.0011 (+98.9%), 2.5s
      [621/660] (94.1%) periodic... [ETA: 1.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 43920.577949
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 43920.577949
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0965 (+0.0%), 1.7s
      [622/660] (94.2%) white... [ETA: 1.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 43920.577949
  Number of iterations: 0
  Number of functions evaluations: 1

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 43920.577949
  Number of iterations: 0
  Number of functions evaluations: 1

✅ ECE: 0.0965 (+0.0%), 1.1s
      [623/660] (94.4%) rational_quadratic... [ETA: 1.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 12694.534826
  Number of iterations: 59
  Number of functions evaluations: 146

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 12694.534826
  Number of iterations: 59
  Number of functions evaluations: 146

✅ ECE: 0.1561 (-61.7%), 2.4s
      [624/660] (94.5%) arc_cosine... [ETA: 1.3min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: SGD
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.135060, LogLoss: 0.535700
      [625/660] (94.7%) rbf... [ETA: 1.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.309532
  Number of iterations: 200
  Number of functions evaluations: 233

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.309532
  Number of iterations: 200
  Number of functions evaluations: 233

✅ ECE: 0.0357 (+73.6%), 2.3s
      [626/660] (94.8%) matern12... [ETA: 1.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.199030
  Number of iterations: 170
  Number of functions evaluations: 244

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 245.199030
  Number of iterations: 170
  Number of functions evaluations: 244

✅ ECE: 0.0556 (+58.8%), 2.5s
      [627/660] (95.0%) matern32... [ETA: 1.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 243.104993
  Number of iterations: 200
  Number of functions evaluations: 220

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 243.104993
  Number of iterations: 200
  Number of functions evaluations: 220

✅ ECE: 0.0555 (+58.9%), 2.8s
      [628/660] (95.2%) matern52... [ETA: 1.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.886111
  Number of iterations: 200
  Number of functions evaluations: 232

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.886111
  Number of iterations: 200
  Number of functions evaluations: 232

✅ ECE: 0.0401 (+70.3%), 3.3s
      [629/660] (95.3%) exponential... [ETA: 1.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 245.064523
  Number of iterations: 200
  Number of functions evaluations: 246

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 245.064523
  Number of iterations: 200
  Number of functions evaluations: 246

✅ ECE: 0.0509 (+62.3%), 2.8s
      [630/660] (95.5%) cosine... [ETA: 1.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 239.399819
  Number of iterations: 173
  Number of functions evaluations: 217

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 239.399819
  Number of iterations: 173
  Number of functions evaluations: 217

✅ ECE: 0.0479 (+64.6%), 2.9s
      [631/660] (95.6%) linear... [ETA: 1.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 253.971357
  Number of iterations: 37
  Number of functions evaluations: 39

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 253.971357
  Number of iterations: 37
  Number of functions evaluations: 39

✅ ECE: 0.0831 (+38.5%), 1.4s
      [632/660] (95.8%) polynomial... [ETA: 1.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 246.462595
  Number of iterations: 200
  Number of functions evaluations: 238

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 246.462595
  Number of iterations: 200
  Number of functions evaluations: 238

✅ ECE: 0.0557 (+58.7%), 2.4s
      [633/660] (95.9%) periodic... [ETA: 1.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 241.806010
  Number of iterations: 200
  Number of functions evaluations: 239

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 241.806010
  Number of iterations: 200
  Number of functions evaluations: 239

✅ ECE: 0.0436 (+67.7%), 3.0s
      [634/660] (96.1%) white... [ETA: 1.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 260.080792
  Number of iterations: 23
  Number of functions evaluations: 24

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 260.080792
  Number of iterations: 23
  Number of functions evaluations: 24

✅ ECE: 0.1351 (+0.0%), 1.0s
      [635/660] (96.2%) rational_quadratic... [ETA: 0.9min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.848291
  Number of iterations: 200
  Number of functions evaluations: 234

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 242.848291
  Number of iterations: 200
  Number of functions evaluations: 234

✅ ECE: 0.0423 (+68.7%), 3.5s
      [636/660] (96.4%) arc_cosine... [ETA: 0.9min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: MLP
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.020681, LogLoss: 0.146635
      [637/660] (96.5%) rbf... [ETA: 0.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.352138
  Number of iterations: 96
  Number of functions evaluations: 109

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.352138
  Number of iterations: 96
  Number of functions evaluations: 109

✅ ECE: 0.0331 (-60.2%), 2.4s
      [638/660] (96.7%) matern12... [ETA: 0.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.519779
  Number of iterations: 67
  Number of functions evaluations: 118

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.519779
  Number of iterations: 67
  Number of functions evaluations: 118

✅ ECE: 0.0263 (-27.0%), 2.7s
      [639/660] (96.8%) matern32... [ETA: 0.8min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.431419
  Number of iterations: 112
  Number of functions evaluations: 120

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.431419
  Number of iterations: 112
  Number of functions evaluations: 120

✅ ECE: 0.0291 (-40.9%), 3.0s
      [640/660] (97.0%) matern52... [ETA: 0.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.407048
  Number of iterations: 117
  Number of functions evaluations: 131

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.407048
  Number of iterations: 117
  Number of functions evaluations: 131

✅ ECE: 0.0284 (-37.3%), 3.0s
      [641/660] (97.1%) exponential... [ETA: 0.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.537720
  Number of iterations: 120
  Number of functions evaluations: 177

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 79.537720
  Number of iterations: 120
  Number of functions evaluations: 177

✅ ECE: 0.0259 (-25.5%), 2.9s
      [642/660] (97.3%) cosine... [ETA: 0.7min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 78.885470
  Number of iterations: 60
  Number of functions evaluations: 64

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 78.885470
  Number of iterations: 60
  Number of functions evaluations: 64

✅ ECE: 0.0276 (-33.7%), 3.0s
      [643/660] (97.4%) linear... [ETA: 0.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 78.736959
  Number of iterations: 200
  Number of functions evaluations: 215

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 78.736959
  Number of iterations: 200
  Number of functions evaluations: 215

✅ ECE: 0.0333 (-60.9%), 2.4s
      [644/660] (97.6%) polynomial... [ETA: 0.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 78.379172
  Number of iterations: 51
  Number of functions evaluations: 55

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 78.379172
  Number of iterations: 51
  Number of functions evaluations: 55

✅ ECE: 0.0311 (-50.2%), 1.9s
      [645/660] (97.7%) periodic... [ETA: 0.6min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 79.351665
  Number of iterations: 200
  Number of functions evaluations: 210

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 79.351665
  Number of iterations: 200
  Number of functions evaluations: 210

✅ ECE: 0.0282 (-36.6%), 3.5s
      [646/660] (97.9%) white... [ETA: 0.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 80.007627
  Number of iterations: 20
  Number of functions evaluations: 21

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 80.007627
  Number of iterations: 20
  Number of functions evaluations: 21

✅ ECE: 0.0207 (+0.0%), 1.3s
      [647/660] (98.0%) rational_quadratic... [ETA: 0.5min] INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 79.353249
  Number of iterations: 200
  Number of functions evaluations: 230

INFO:tensorflow:Optimization terminated with:
  Message: b'STOP: TOTAL NO. of ITERATIONS REACHED LIMIT'
  Objective function value: 79.353249
  Number of iterations: 200
  Number of functions evaluations: 230

✅ ECE: 0.0306 (-48.1%), 3.3s
      [648/660] (98.2%) arc_cosine... [ETA: 0.4min] ❌ __init__() missing 1 required positional

   🤖 CLASSIFIER: BernoulliNB
   ------------------------------------------------------------------------------------------
      📊 Uncalibrated - ECE: 0.031597, LogLoss: 0.389303
      [649/660] (98.3%) rbf... [ETA: 0.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.147999
  Number of iterations: 86
  Number of functions evaluations: 100

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.147999
  Number of iterations: 86
  Number of functions evaluations: 100

✅ ECE: 0.0292 (+7.6%), 2.9s
      [650/660] (98.5%) matern12... [ETA: 0.4min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150752
  Number of iterations: 31
  Number of functions evaluations: 33

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150752
  Number of iterations: 31
  Number of functions evaluations: 33

✅ ECE: 0.0316 (+0.0%), 2.7s
      [651/660] (98.6%) matern32... [ETA: 0.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150746
  Number of iterations: 53
  Number of functions evaluations: 59

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150746
  Number of iterations: 53
  Number of functions evaluations: 59

✅ ECE: 0.0316 (+0.0%), 2.3s
      [652/660] (98.8%) matern52... [ETA: 0.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150749
  Number of iterations: 54
  Number of functions evaluations: 58

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150749
  Number of iterations: 54
  Number of functions evaluations: 58

✅ ECE: 0.0316 (+0.0%), 2.7s
      [653/660] (98.9%) exponential... [ETA: 0.3min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150751
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150751
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0316 (+0.0%), 2.4s
      [654/660] (99.1%) cosine... [ETA: 0.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 214.995028
  Number of iterations: 70
  Number of functions evaluations: 85

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 214.995028
  Number of iterations: 70
  Number of functions evaluations: 85

✅ ECE: 0.0352 (-11.4%), 2.4s
      [655/660] (99.2%) linear... [ETA: 0.2min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.069863
  Number of iterations: 33
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.069863
  Number of iterations: 33
  Number of functions evaluations: 36

✅ ECE: 0.0335 (-6.1%), 1.8s
      [656/660] (99.4%) polynomial... [ETA: 0.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 214.841300
  Number of iterations: 34
  Number of functions evaluations: 36

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 214.841300
  Number of iterations: 34
  Number of functions evaluations: 36

✅ ECE: 0.0331 (-4.9%), 2.7s
      [657/660] (99.5%) periodic... [ETA: 0.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150760
  Number of iterations: 33
  Number of functions evaluations: 37

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150760
  Number of iterations: 33
  Number of functions evaluations: 37

✅ ECE: 0.0316 (+0.0%), 2.2s
      [658/660] (99.7%) white... [ETA: 0.1min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 215.150707
  Number of iterations: 22
  Number of functions evaluations: 23

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 215.150707
  Number of iterations: 22
  Number of functions evaluations: 23

✅ ECE: 0.0316 (+0.0%), 1.2s
      [659/660] (99.8%) rational_quadratic... [ETA: 0.0min] INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150749
  Number of iterations: 42
  Number of functions evaluations: 45

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 215.150749
  Number of iterations: 42
  Number of functions evaluations: 45

✅ ECE: 0.0316 (+0.0%), 2.7s
      [660/660] (100.0%) arc_cosine... [ETA: 0.0min] ❌ __init__() missing 1 required positional

====================================================================================================
📊 KERNEL COMPARISON COMPLETE!
====================================================================================================
⏱️  Total experiment time: 24.4 minutes (1464 seconds)

📈 Summary:
   Total experiments: 660
   Successful: 600 (90.9%)
   Failed: 60

====================================================================================================
🏆 OVERALL BEST KERNELS (Across All Datasets & Classifiers)
====================================================================================================

📊 Average Calibrated ECE by Kernel:
                        mean       std       min       max  count
Kernel
cosine              0.073998  0.068515  0.001082  0.403330     55
polynomial          0.077382  0.075843  0.001082  0.408866     51
linear              0.079147  0.079462  0.001082  0.408966     54
rational_quadratic  0.089587  0.079421  0.019348  0.395805     55
matern12            0.093880  0.087507  0.004432  0.367609     55
rbf                 0.094647  0.086274  0.019715  0.417460     55
exponential         0.095456  0.088213  0.004432  0.421712     55
periodic            0.096435  0.092569  0.004432  0.432200     55
matern32            0.101767  0.095590  0.021036  0.400974     55
matern52            0.103977  0.101843  0.004432  0.506716     55
white               0.124976  0.127793  0.004432  0.743806     55

🥇 BEST KERNEL (Lowest Average ECE): cosine
   Average ECE: 0.073998 ± 0.068515
   Min ECE: 0.001082
   Max ECE: 0.403330
   Success rate: 55/55

📈 Average ECE Improvement by Kernel:
                          mean          std          min        max
Kernel
linear               11.828358    65.966245  -288.941485  98.878924
exponential           6.864046    45.323684  -156.420570  79.545054
polynomial            4.532970   152.877839 -1028.183230  98.878924
matern12              1.468192    72.654161  -301.526430  84.431657
white                -0.011376     5.565631   -24.972144  29.972807
cosine               -0.910393   160.517704 -1101.397516  98.878924
periodic             -4.128561   135.575376  -964.619800  85.880441
matern52            -64.235361   500.380581 -3666.687714  76.616343
rational_quadratic  -73.688638   604.364364 -4450.155280  87.421192
rbf                 -97.789786   759.209367 -5605.667702  85.073547
matern32           -164.038465  1208.884252 -8948.059006  87.661570

⏱️  Average Computation Time by Kernel:
                        mean       std       min       max
Kernel
white               1.084869  0.201980  0.818293  1.525738
linear              1.725302  0.482602  1.143521  3.408739
polynomial          2.103791  0.604480  1.372404  3.460591
rbf                 2.369951  0.628936  1.607210  4.111233
cosine              2.436930  0.664635  1.539710  4.110291
exponential         2.479741  0.745460  1.606463  4.616180
periodic            2.528972  0.813239  1.423159  4.621442
matern12            2.562559  0.919985  1.546296  6.068965
matern32            2.571501  0.726558  1.593644  4.243729
rational_quadratic  2.736344  0.780851  1.746992  5.050707
matern52            2.761043  0.787365  1.797804  4.674771

⚡ FASTEST KERNEL: white
   Average Time: 1.085s ± 0.202s

====================================================================================================
✅ Kernel Comparison Analysis Completed!
====================================================================================================

In [112]:
kernel_comparison_df.to_csv("kernel_comparison_results_all_kernels.csv", index=False)

In [113]:
kernel_comparison_df

,Dataset,Classifier,Kernel,n_classes,Uncal_ECE,Cal_ECE,ECE_Delta,ECE_Improvement_%,Uncal_LogLoss,Cal_LogLoss,LogLoss_Delta,LogLoss_Improvement_%,Fit_Time_sec,Pred_Time_sec,Total_Time_sec,Status
0,car_evaluation,RandomForest,rbf,4,0.124068,0.050062,0.074006,59.649463,0.169055,0.071510,0.097545,57.699900,1.888701,0.229373,2.132157,Success
1,car_evaluation,RandomForest,matern12,4,0.124068,0.056479,0.067589,54.477384,0.169055,0.078511,0.090544,53.558804,1.419327,0.223953,1.645425,Success
2,car_evaluation,RandomForest,matern32,4,0.124068,0.048637,0.075430,60.797582,0.169055,0.072272,0.096783,57.249176,1.854661,0.230493,2.087788,Success
3,car_evaluation,RandomForest,matern52,4,0.124068,0.048035,0.076032,61.282897,0.169055,0.072328,0.096727,57.216229,1.930896,0.246127,2.179734,Success
4,car_evaluation,RandomForest,exponential,4,0.124068,0.049852,0.074216,59.818631,0.169055,0.076885,0.092170,54.520507,1.736581,0.222889,1.967784,Success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,air_quality,BernoulliNB,polynomial,4,0.031597,0.033137,-0.001540,-4.874285,0.389303,0.390730,-0.001427,-0.366550,2.284311,0.366692,2.654002,Success
656,air_quality,BernoulliNB,periodic,4,0.031597,0.031597,0.000000,0.000000,0.389303,0.389302,0.000001,0.000270,1.894902,0.296262,2.199165,Success
657,air_quality,BernoulliNB,white,4,0.031597,0.031597,0.000000,0.000000,0.389303,0.389300,0.000003,0.000836,1.063408,0.180075,1.244481,Success
658,air_quality,BernoulliNB,rational_quadratic,4,0.031597,0.031597,0.000000,0.000000,0.389303,0.389309,-0.000005,-0.001318,2.254596,0.393984,2.652591,Success
659,air_quality,BernoulliNB,arc_cosine,4,0.031597,NaN,NaN,NaN,0.389303,NaN,NaN,NaN,NaN,NaN,NaN,Error: __init__() missing 1 required positiona...

In [1]:
import pandas as pd
kernel_comparison_df = pd.read_csv("kernel_comparison_results.csv")

In [134]:
# Detailed analysis per dataset and classifier
print("="*100)
print("📊 DETAILED RESULTS BY DATASET & CLASSIFIER")
print("="*100)

successful_results = kernel_comparison_df[kernel_comparison_df['Status'] == 'Success'].copy()

if len(successful_results) > 0:
    # For each dataset, show best kernel
    print("\n" + "="*100)
    print("🏆 BEST KERNEL PER DATASET (Averaged Across All Classifiers)")
    print("="*100)
    
    for dataset in successful_results['Dataset'].unique():
        dataset_results = successful_results[successful_results['Dataset'] == dataset]
        
        # Average ECE by kernel for this dataset
        kernel_performance = dataset_results.groupby('Kernel')['Cal_ECE'].agg(['mean', 'std', 'count'])
        kernel_performance = kernel_performance.sort_values('mean')
        
        best_kernel_dataset = kernel_performance.index[0]
        
        print(f"\n📂 {dataset.upper()}")
        print(f"   🥇 Best Kernel: {best_kernel_dataset}")
        print(f"      Average ECE: {kernel_performance.loc[best_kernel_dataset, 'mean']:.6f} ± {kernel_performance.loc[best_kernel_dataset, 'std']:.6f}")
        print(f"      Success rate: {kernel_performance.loc[best_kernel_dataset, 'count']}/{len(multiclass_classifiers)}")
        
        # Show top 3 kernels
        print(f"   📈 Top 3 Kernels:")
        for rank, (kernel_name, row) in enumerate(kernel_performance.head(3).iterrows(), 1):
            print(f"      {rank}. {kernel_name}: {row['mean']:.6f} (±{row['std']:.6f})")
    
    # For each classifier, show best kernel
    print("\n" + "="*100)
    print("🏆 BEST KERNEL PER CLASSIFIER (Averaged Across All Datasets)")
    print("="*100)
    
    for classifier in successful_results['Classifier'].unique():
        clf_results = successful_results[successful_results['Classifier'] == classifier]
        
        # Average ECE by kernel for this classifier
        kernel_performance = clf_results.groupby('Kernel')['Cal_ECE'].agg(['mean', 'std', 'count'])
        kernel_performance = kernel_performance.sort_values('mean')
        
        best_kernel_clf = kernel_performance.index[0]
        
        print(f"\n🤖 {classifier}")
        print(f"   🥇 Best Kernel: {best_kernel_clf}")
        print(f"      Average ECE: {kernel_performance.loc[best_kernel_clf, 'mean']:.6f} ± {kernel_performance.loc[best_kernel_clf, 'std']:.6f}")
        print(f"      Success rate: {kernel_performance.loc[best_kernel_clf, 'count']}/{len(split_datasets)}")
        
        # Show top 3 kernels
        print(f"   📈 Top 3 Kernels:")
        for rank, (kernel_name, row) in enumerate(kernel_performance.head(3).iterrows(), 1):
            print(f"      {rank}. {kernel_name}: {row['mean']:.6f} (±{row['std']:.6f})")
    
    # Specific combinations - best for each dataset-classifier pair
    print("\n" + "="*100)
    print("🎯 BEST KERNEL FOR EACH DATASET-CLASSIFIER COMBINATION")
    print("="*100)
    
    best_combinations = []
    
    for dataset in successful_results['Dataset'].unique():
        for classifier in successful_results['Classifier'].unique():
            combo_results = successful_results[
                (successful_results['Dataset'] == dataset) & 
                (successful_results['Classifier'] == classifier)
            ]
            
            if len(combo_results) > 0:
                best_idx = combo_results['Cal_ECE'].idxmin()
                best_result = combo_results.loc[best_idx]
                
                best_combinations.append({
                    'Dataset': dataset,
                    'Classifier': classifier,
                    'Best_Kernel': best_result['Kernel'],
                    'Cal_ECE': best_result['Cal_ECE'],
                    'ECE_Improvement_%': best_result['ECE_Improvement_%'],
                    'Total_Time_sec': best_result['Total_Time_sec']
                })
    
    best_combo_df = pd.DataFrame(best_combinations)
    
    # Create pivot table
    pivot_best_kernel = best_combo_df.pivot(index='Dataset', columns='Classifier', values='Best_Kernel')
    pivot_best_ece = best_combo_df.pivot(index='Dataset', columns='Classifier', values='Cal_ECE')
    
    print("\n📋 Best Kernel for Each Combination:")
    print(pivot_best_kernel.to_string())
    
    print("\n📋 Corresponding ECE Values:")
    print(pivot_best_ece.to_string())
    
    # Overall statistics
    print("\n" + "="*100)
    print("📊 KERNEL USAGE STATISTICS")
    print("="*100)
    
    kernel_counts = best_combo_df['Best_Kernel'].value_counts()
    print(f"\nHow many times each kernel was the best:")
    for kernel, count in kernel_counts.items():
        percentage = (count / len(best_combo_df)) * 100
        print(f"   {kernel}: {count} times ({percentage:.1f}%)")
    
    print(f"\n🏆 Most frequently best kernel: {kernel_counts.index[0]} ({kernel_counts.iloc[0]} times)")

print("\n" + "="*100)
print("✅ Detailed Analysis Complete!")
print("="*100)

====================================================================================================
📊 DETAILED RESULTS BY DATASET & CLASSIFIER
====================================================================================================

====================================================================================================
🏆 BEST KERNEL PER DATASET (Averaged Across All Classifiers)
====================================================================================================

📂 CAR_EVALUATION
   🥇 Best Kernel: linear
      Average ECE: 0.049547 ± 0.036257
      Success rate: 11/11
   📈 Top 3 Kernels:
      1. linear: 0.049547 (±0.036257)
      2. exponential: 0.050240 (±0.026275)
      3. cosine: 0.051616 (±0.024970)

📂 DRY_BEAN
   🥇 Best Kernel: linear
      Average ECE: 0.035167 ± 0.016917
      Success rate: 11/11
   📈 Top 3 Kernels:
      1. linear: 0.035167 (±0.016917)
      2. polynomial: 0.036320 (±0.019066)
      3. cosine: 0.037351 (±0.021401)

📂 STUDENT_DROPOUT
   🥇 Best Kernel: rbf
      Average ECE: 0.064169 ± 0.034968
      Success rate: 11/11
   📈 Top 3 Kernels:
      1. rbf: 0.064169 (±0.034968)
      2. rational_quadratic: 0.068716 (±0.025590)
      3. matern12: 0.072984 (±0.031200)

📂 CIRRHOSIS
   🥇 Best Kernel: cosine
      Average ECE: 0.152249 ± 0.099443
      Success rate: 11/11
   📈 Top 3 Kernels:
      1. cosine: 0.152249 (±0.099443)
      2. polynomial: 0.166063 (±0.102314)
      3. linear: 0.170279 (±0.101254)

📂 AIR_QUALITY
   🥇 Best Kernel: cosine
      Average ECE: 0.041187 ± 0.042218
      Success rate: 11/11
   📈 Top 3 Kernels:
      1. cosine: 0.041187 (±0.042218)
      2. polynomial: 0.047856 (±0.062503)
      3. matern12: 0.049639 (±0.032877)

====================================================================================================
🏆 BEST KERNEL PER CLASSIFIER (Averaged Across All Datasets)
====================================================================================================

🤖 RandomForest
   🥇 Best Kernel: polynomial
      Average ECE: 0.064430 ± 0.057489
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. polynomial: 0.064430 (±0.057489)
      2. periodic: 0.065278 (±0.057249)
      3. rational_quadratic: 0.065326 (±0.057206)

🤖 AdaBoost
   🥇 Best Kernel: periodic
      Average ECE: 0.091816 ± 0.063109
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. periodic: 0.091816 (±0.063109)
      2. matern32: 0.096914 (±0.062131)
      3. matern52: 0.108387 (±0.052889)

🤖 NaiveBayes
   🥇 Best Kernel: rational_quadratic
      Average ECE: 0.118757 ± 0.159042
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. rational_quadratic: 0.118757 (±0.159042)
      2. matern12: 0.126489 (±0.144704)
      3. matern32: 0.127999 (±0.152094)

🤖 KNN
   🥇 Best Kernel: white
      Average ECE: 0.060406 ± 0.048111
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. white: 0.060406 (±0.048111)
      2. matern12: 0.063551 (±0.043082)
      3. rbf: 0.069441 (±0.038531)

🤖 XGBoost
   🥇 Best Kernel: periodic
      Average ECE: 0.049358 ± 0.036504
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. periodic: 0.049358 (±0.036504)
      2. matern32: 0.050521 (±0.039202)
      3. linear: 0.051541 (±0.041624)

🤖 DecisionTree
   🥇 Best Kernel: linear
      Average ECE: 0.020108 ± 0.016457
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. linear: 0.020108 (±0.016457)
      2. cosine: 0.037489 (±0.033269)
      3. polynomial: 0.047283 (±0.049491)

🤖 SVC
   🥇 Best Kernel: matern52
      Average ECE: 0.048317 ± 0.021720
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. matern52: 0.048317 (±0.021720)
      2. rbf: 0.048340 (±0.021762)
      3. cosine: 0.050307 (±0.025697)

🤖 ExtraTree
   🥇 Best Kernel: polynomial
      Average ECE: 0.025425 ± 0.019291
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. polynomial: 0.025425 (±0.019291)
      2. linear: 0.026735 (±0.021677)
      3. cosine: 0.027050 (±0.021692)

🤖 SGD
   🥇 Best Kernel: matern52
      Average ECE: 0.056881 ± 0.032641
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. matern52: 0.056881 (±0.032641)
      2. matern32: 0.061953 (±0.037951)
      3. periodic: 0.063033 (±0.047973)

🤖 MLP
   🥇 Best Kernel: matern52
      Average ECE: 0.063140 ± 0.053957
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. matern52: 0.063140 (±0.053957)
      2. matern12: 0.065756 (±0.054827)
      3. periodic: 0.066799 (±0.049765)

🤖 BernoulliNB
   🥇 Best Kernel: rbf
      Average ECE: 0.059387 ± 0.043230
      Success rate: 5/5
   📈 Top 3 Kernels:
      1. rbf: 0.059387 (±0.043230)
      2. exponential: 0.070537 (±0.054260)
      3. polynomial: 0.071938 (±0.053553)

====================================================================================================
🎯 BEST KERNEL FOR EACH DATASET-CLASSIFIER COMBINATION
====================================================================================================

📋 Best Kernel for Each Combination:
Classifier                 AdaBoost BernoulliNB DecisionTree   ExtraTree         KNN       MLP          NaiveBayes        RandomForest         SGD       SVC   XGBoost
Dataset
air_quality                periodic         rbf       cosine      cosine    matern52     white            matern52            matern32         rbf       rbf     white
car_evaluation             matern32    matern32     matern12      cosine  polynomial  matern52            matern32          polynomial      linear       rbf    cosine
cirrhosis                polynomial         rbf       cosine  polynomial    matern52  periodic            matern12            matern32    matern52  matern52  periodic
dry_bean         rational_quadratic         rbf       cosine      linear       white  matern32  rational_quadratic  rational_quadratic  polynomial  periodic     white
student_dropout            periodic    matern32     matern32      cosine       white       rbf  rational_quadratic          polynomial       white       rbf    linear

📋 Corresponding ECE Values:
Classifier       AdaBoost  BernoulliNB  DecisionTree  ExtraTree       KNN       MLP  NaiveBayes  RandomForest       SGD       SVC   XGBoost
Dataset
air_quality      0.068715     0.029210      0.006768   0.001082  0.018040  0.020681    0.024041      0.036783  0.035680  0.030598  0.022156
car_evaluation   0.081059     0.046766      0.004432   0.015345  0.063873  0.036416    0.035774      0.045135  0.055450  0.038580  0.028258
cirrhosis        0.165476     0.135374      0.019048   0.030726  0.116440  0.132256    0.367609      0.164172  0.109439  0.080045  0.113889
dry_bean         0.025465     0.042871      0.020009   0.026905  0.016812  0.026020    0.022323      0.019348  0.022318  0.028526  0.023944
student_dropout  0.056046     0.036123      0.031398   0.030818  0.037370  0.068688    0.111510      0.055176  0.032592  0.061389  0.033564

====================================================================================================
📊 KERNEL USAGE STATISTICS
====================================================================================================

How many times each kernel was the best:
   matern32: 8 times (14.5%)
   rbf: 8 times (14.5%)
   cosine: 7 times (12.7%)
   white: 6 times (10.9%)
   matern52: 6 times (10.9%)
   polynomial: 6 times (10.9%)
   periodic: 5 times (9.1%)
   rational_quadratic: 4 times (7.3%)
   linear: 3 times (5.5%)
   matern12: 2 times (3.6%)

🏆 Most frequently best kernel: matern32 (8 times)

====================================================================================================
✅ Detailed Analysis Complete!
====================================================================================================

In [135]:
#drop CalibrationMethod = 'GPCalibration'
calibration_results_df = calibration_results_df[calibration_results_df['CalibrationMethod'] != 'GPCalibration']
calibration_results_df

,Dataset,Classifier,CalibrationMethod,Accuracy,ECE,LogLoss,BaseFitTime,BasePredTime,CalibFitTime,CalibPredTime,TotalTime,TrainSamples,CalibSamples,TestSamples,NumClasses,NumFeatures
0,car_evaluation,RandomForest,Uncalibrated,0.979769,0.129127,0.169055,0.273559,0.239690,0.000000,0.000000,0.513249,1209,173,346,4,21
1,car_evaluation,RandomForest,PlattScaling,0.971098,0.054897,0.433887,0.273559,0.239690,0.048593,0.000000,0.561842,1209,173,346,4,21
2,car_evaluation,RandomForest,IsotonicRegression,0.968208,0.047890,0.533222,0.273559,0.239690,0.006276,0.000000,0.519526,1209,173,346,4,21
4,car_evaluation,AdaBoost,Uncalibrated,0.791908,0.100642,0.544952,0.111172,0.025883,0.000000,0.000000,0.137055,1209,173,346,4,21
5,car_evaluation,AdaBoost,PlattScaling,0.812139,0.073410,0.485944,0.111172,0.025883,0.018706,0.003356,0.159117,1209,173,346,4,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,air_quality,MLP,PlattScaling,0.951049,0.032173,0.183724,8.658581,0.005421,0.024940,0.008214,8.697155,3499,500,1001,4,9
214,air_quality,MLP,IsotonicRegression,0.948052,0.040892,0.541445,8.658581,0.005421,0.008186,0.000000,8.672188,3499,500,1001,4,9
216,air_quality,BernoulliNB,Uncalibrated,0.825175,0.035659,0.389303,0.005540,0.000000,0.000000,0.000000,0.005540,3499,500,1001,4,9
217,air_quality,BernoulliNB,PlattScaling,0.826174,0.080852,0.446095,0.005540,0.000000,0.012700,0.000000,0.018240,3499,500,1001,4,9
218,air_quality,BernoulliNB,IsotonicRegression,0.822178,0.046209,0.513777,0.005540,0.000000,0.000000,0.008322,0.013862,3499,500,1001,4,9

In [136]:
# Create final calibration summary table
if len(calibration_results_df) > 0:
    valid_results = calibration_results_df.dropna(subset=['ECE'])
    
    if len(valid_results) > 0:
        print("="*80)
        print("📊 FINAL CALIBRATION SUMMARY: Method Performance Comparison")
        print("="*80)
        
        # Create summary table by method across all datasets
        final_calib_summary = valid_results.groupby('CalibrationMethod').agg({
            'ECE': 'mean'
        }).round(4)
        
        # Reset index to make CalibrationMethod a column
        final_calib_summary = final_calib_summary.reset_index()
        final_calib_summary = final_calib_summary.sort_values('ECE')  # Sort by ECE (lower is better)
        
        # Display the table
        print(f"{'Method':<25} {'Mean_ECE':<12}" )
        print("-" * 80)
        
        for _, row in final_calib_summary.iterrows():
            print(f"{row['CalibrationMethod']:<25} {row['ECE']:<12.4f}")

        print("-" * 80)
        
        # Calculate overall statistics
        best_ece_method = final_calib_summary.iloc[0]  # First row after sorting by ECE
        
        print(f"\n🏆 OVERALL BEST METHODS:")
        print(f"Best ECE (Calibration): {best_ece_method['CalibrationMethod']} ({best_ece_method['ECE']:.4f})")
        
        # Calculate improvement statistics if uncalibrated baseline exists
        if 'Uncalibrated' in final_calib_summary['CalibrationMethod'].values:
            uncal_row = final_calib_summary[final_calib_summary['CalibrationMethod'] == 'Uncalibrated'].iloc[0]
            
            print(f"\n📈 CALIBRATION EFFECTIVENESS:")
            print(f"Uncalibrated baseline - ECE: {uncal_row['ECE']:.4f}")
            # Calculate improvements for each method
            calib_methods = final_calib_summary[final_calib_summary['CalibrationMethod'] != 'Uncalibrated']
            
            if len(calib_methods) > 0:
                print("\nCalibration improvements (vs uncalibrated):")
                for _, method_row in calib_methods.iterrows():
                    ece_improv = ((uncal_row['ECE'] - method_row['ECE']) / uncal_row['ECE']) * 100
                    print(f"  {method_row['CalibrationMethod']:<20}: ECE {ece_improv:+6.1f}%")

        # Save final summary
        final_calibration_summary_df = final_calib_summary.copy()
        
        print(f"\n💾 Final summary saved as 'final_calibration_summary_df'")
        print("Columns: CalibrationMethod, ECE")
        print(f"Shape: {final_calibration_summary_df.shape}")
        
        print(f"\nDataFrame Preview:")
        print(final_calibration_summary_df)
        
    else:
        print("❌ No valid results for final summary")
else:
    print("❌ No results available for final summary")

print(f"\n🎯 MULTICLASS CALIBRATION EXPERIMENT COMPLETE!")
print("="*80)

================================================================================
📊 FINAL CALIBRATION SUMMARY: Method Performance Comparison
================================================================================
Method                    Mean_ECE
--------------------------------------------------------------------------------
IsotonicRegression        0.0615
PlattScaling              0.0627
Uncalibrated              0.1224
--------------------------------------------------------------------------------

🏆 OVERALL BEST METHODS:
Best ECE (Calibration): IsotonicRegression (0.0615)

📈 CALIBRATION EFFECTIVENESS:
Uncalibrated baseline - ECE: 0.1224

Calibration improvements (vs uncalibrated):
  IsotonicRegression  : ECE  +49.8%
  PlattScaling        : ECE  +48.8%

💾 Final summary saved as 'final_calibration_summary_df'
Columns: CalibrationMethod, ECE
Shape: (3, 2)

DataFrame Preview:
    CalibrationMethod     ECE
0  IsotonicRegression  0.0615
1        PlattScaling  0.0627
2        Uncalibrated  0.1224

🎯 MULTICLASS CALIBRATION EXPERIMENT COMPLETE!
================================================================================

## 🔄 Add BestGPCalibration to calibration_results_df

Menambahkan metode kalibrasi "BestGPCalibration" ke dalam `calibration_results_df` dengan mengambil kernel terbaik (ECE terendah) untuk setiap kombinasi Dataset-Classifier dari hasil kernel comparison.

In [88]:
kernel_comparison_df

,Dataset,Classifier,Kernel,n_classes,Uncal_ECE,Cal_ECE,ECE_Delta,ECE_Improvement_%,Uncal_LogLoss,Cal_LogLoss,LogLoss_Delta,LogLoss_Improvement_%,Fit_Time_sec,Pred_Time_sec,Total_Time_sec,Status
0,car_evaluation,RandomForest,rbf,4,0.124068,0.050062,0.074006,59.649463,0.169055,0.071639,9.741552e-02,57.623572,1.740889,0.293165,2.040461,Success
1,car_evaluation,RandomForest,matern32,4,0.124068,0.048142,0.075926,61.196927,0.169055,0.072266,9.678913e-02,57.253049,1.555048,0.594072,2.152884,Success
2,car_evaluation,RandomForest,matern52,4,0.124068,0.045675,0.078393,63.185335,0.169055,0.072496,9.655934e-02,57.117120,1.621704,0.307994,1.946678,Success
3,car_evaluation,RandomForest,linear,4,0.124068,0.051060,0.073008,58.845226,0.169055,0.069147,9.990760e-02,59.097696,1.040491,0.204097,1.244588,Success
4,car_evaluation,AdaBoost,rbf,4,0.122877,0.097437,0.025440,20.703945,0.544952,0.399008,1.459434e-01,26.780978,1.482040,0.243660,1.736451,Success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,air_quality,MLP,linear,4,0.020681,0.032345,-0.011664,-56.397098,0.146635,0.140856,5.778566e-03,3.940781,1.098593,0.255331,1.353924,Success
216,air_quality,BernoulliNB,rbf,4,0.031597,0.029210,0.002387,7.554201,0.389303,0.389297,6.822113e-06,0.001752,2.022063,0.256576,2.282652,Success
217,air_quality,BernoulliNB,matern32,4,0.031597,0.031597,0.000000,0.000000,0.389303,0.389303,6.173205e-07,0.000159,1.603134,0.295463,1.907690,Success
218,air_quality,BernoulliNB,matern52,4,0.031597,0.031597,0.000000,0.000000,0.389303,0.389304,-8.344480e-07,-0.000214,1.691743,0.299283,1.995064,Success
219,air_quality,BernoulliNB,linear,4,0.031597,0.033520,-0.001923,-6.086269,0.389303,0.390285,-9.817775e-04,-0.252188,1.110317,0.229913,1.342754,Success

In [137]:
# Step 1: Find the best kernel (lowest ECE) for each Dataset-Classifier combination
print("="*80)
print("🔍 Finding Best Kernel for each Dataset-Classifier combination...")
print("="*80)

best_gp_kernels = kernel_comparison_df.loc[
    kernel_comparison_df.groupby(['Dataset', 'Classifier'])['Cal_ECE'].idxmin()
].copy()

print(f"Found {len(best_gp_kernels)} best kernel combinations\n")

# Step 2: Create BestGPCalibration rows with matching column structure
best_gp_rows = []
for _, row in best_gp_kernels.iterrows():
    best_gp_rows.append({
        'Dataset': row['Dataset'],
        'Classifier': row['Classifier'],
        'CalibrationMethod': 'BestGPCalibration',
        'ECE': row['Cal_ECE'],
        #add kernel name
        'Kernel': row['Kernel'],
    })

# Step 3: Create DataFrame from BestGPCalibration rows
best_gp_df = pd.DataFrame(best_gp_rows)

print("="*80)
print("📊 Sample BestGPCalibration entries:")
print("="*80)
print(best_gp_df.head(10))

# Step 4: Concatenate with existing calibration_results_df
calibration_results_df_with_best_gp = pd.concat(
    [calibration_results_df, best_gp_df], 
    ignore_index=True
)

# Step 5: Sort by Dataset, Classifier, and CalibrationMethod
calibration_results_df_with_best_gp = calibration_results_df_with_best_gp.sort_values(
    ['Dataset', 'Classifier', 'CalibrationMethod']
).reset_index(drop=True)

# Display summary
print("\n" + "="*80)
print("✅ UPDATED CALIBRATION RESULTS")
print("="*80)
print(f"Original rows: {len(calibration_results_df)}")
print(f"BestGPCalibration rows added: {len(best_gp_df)}")
print(f"Total rows: {len(calibration_results_df_with_best_gp)}")
print(f"\nCalibration Methods: {sorted(calibration_results_df_with_best_gp['CalibrationMethod'].unique())}")
print(f"Datasets: {calibration_results_df_with_best_gp['Dataset'].nunique()}")
print(f"Classifiers: {calibration_results_df_with_best_gp['Classifier'].nunique()}")

# Show sample comparing methods for one dataset-classifier combination
print("\n" + "="*80)
print("📋 Example: All methods for first Dataset-Classifier combination")
print("="*80)
first_dataset = calibration_results_df_with_best_gp['Dataset'].iloc[0]
first_classifier = calibration_results_df_with_best_gp['Classifier'].iloc[0]
example = calibration_results_df_with_best_gp[
    (calibration_results_df_with_best_gp['Dataset'] == first_dataset) &
    (calibration_results_df_with_best_gp['Classifier'] == first_classifier)
].copy()
print(f"\nDataset: {first_dataset}, Classifier: {first_classifier}")
print(example[['CalibrationMethod', 'ECE']].to_string(index=False))

# Update the main variable
calibration_results_df = calibration_results_df_with_best_gp.copy()

print(f"\n✅ calibration_results_df has been updated with BestGPCalibration!")
print("="*80)

================================================================================
🔍 Finding Best Kernel for each Dataset-Classifier combination...
================================================================================
Found 55 best kernel combinations

================================================================================
📊 Sample BestGPCalibration entries:
================================================================================
       Dataset    Classifier  CalibrationMethod       ECE    Kernel
0  air_quality      AdaBoost  BestGPCalibration  0.068715  periodic
1  air_quality   BernoulliNB  BestGPCalibration  0.029210       rbf
2  air_quality  DecisionTree  BestGPCalibration  0.006768    cosine
3  air_quality     ExtraTree  BestGPCalibration  0.001082    cosine
4  air_quality           KNN  BestGPCalibration  0.018040  matern52
5  air_quality           MLP  BestGPCalibration  0.020681     white
6  air_quality    NaiveBayes  BestGPCalibration  0.024041  matern52
7  air_quality  RandomForest  BestGPCalibration  0.036783  matern32
8  air_quality           SGD  BestGPCalibration  0.035680       rbf
9  air_quality           SVC  BestGPCalibration  0.030598       rbf

================================================================================
✅ UPDATED CALIBRATION RESULTS
================================================================================
Original rows: 165
BestGPCalibration rows added: 55
Total rows: 220

Calibration Methods: ['BestGPCalibration', 'IsotonicRegression', 'PlattScaling', 'Uncalibrated']
Datasets: 5
Classifiers: 11

================================================================================
📋 Example: All methods for first Dataset-Classifier combination
================================================================================

Dataset: air_quality, Classifier: AdaBoost
  CalibrationMethod       ECE
  BestGPCalibration  0.068715
 IsotonicRegression  0.170163
       PlattScaling  0.140953
       Uncalibrated  0.435509

✅ calibration_results_df has been updated with BestGPCalibration!
================================================================================

In [138]:
calibration_results_df

,Dataset,Classifier,CalibrationMethod,Accuracy,ECE,LogLoss,BaseFitTime,BasePredTime,CalibFitTime,CalibPredTime,TotalTime,TrainSamples,CalibSamples,TestSamples,NumClasses,NumFeatures,Kernel
0,air_quality,AdaBoost,BestGPCalibration,NaN,0.068715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,periodic
1,air_quality,AdaBoost,IsotonicRegression,0.781219,0.170163,0.552343,0.318152,0.040428,0.004357,0.000000,0.362937,3499.0,500.0,1001.0,4.0,9.0,NaN
2,air_quality,AdaBoost,PlattScaling,0.826174,0.140953,0.618162,0.318152,0.040428,0.025765,0.001084,0.385429,3499.0,500.0,1001.0,4.0,9.0,NaN
3,air_quality,AdaBoost,Uncalibrated,0.614386,0.435509,1.313942,0.318152,0.040428,0.000000,0.000000,0.358580,3499.0,500.0,1001.0,4.0,9.0,NaN
4,air_quality,BernoulliNB,BestGPCalibration,NaN,0.029210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rbf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,student_dropout,SVC,Uncalibrated,0.759594,0.047003,0.592215,2.299489,0.246764,0.000000,0.000000,2.546254,3096.0,442.0,886.0,3.0,36.0,NaN
216,student_dropout,XGBoost,BestGPCalibration,NaN,0.033564,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,linear
217,student_dropout,XGBoost,IsotonicRegression,0.762980,0.038596,0.749517,0.732052,0.017298,0.006234,0.003139,0.758723,3096.0,442.0,886.0,3.0,36.0,NaN
218,student_dropout,XGBoost,PlattScaling,0.779910,0.082460,0.592278,0.732052,0.017298,0.019631,0.002060,0.771041,3096.0,442.0,886.0,3.0,36.0,NaN
219,student_dropout,XGBoost,Uncalibrated,0.776524,0.070258,0.611635,0.732052,0.017298,0.000000,0.000000,0.749350,3096.0,442.0,886.0,3.0,36.0,NaN

In [139]:
calibration_results_df = calibration_results_df[['Dataset','Classifier','CalibrationMethod','ECE','Kernel']]
calibration_results_df

             Dataset   Classifier   CalibrationMethod       ECE    Kernel
0        air_quality     AdaBoost   BestGPCalibration  0.068715  periodic
1        air_quality     AdaBoost  IsotonicRegression  0.170163       NaN
2        air_quality     AdaBoost        PlattScaling  0.140953       NaN
3        air_quality     AdaBoost        Uncalibrated  0.435509       NaN
4        air_quality  BernoulliNB   BestGPCalibration  0.029210       rbf
..               ...          ...                 ...       ...       ...
215  student_dropout          SVC        Uncalibrated  0.047003       NaN
216  student_dropout      XGBoost   BestGPCalibration  0.033564    linear
217  student_dropout      XGBoost  IsotonicRegression  0.038596       NaN
218  student_dropout      XGBoost        PlattScaling  0.082460       NaN
219  student_dropout      XGBoost        Uncalibrated  0.070258       NaN

[220 rows x 5 columns]

In [140]:
# drop duplicate row of Dataset, Classifier, CalibrationMethod keeping the one with lowest ECE
calibration_results_df2 = calibration_results_df.loc[
    calibration_results_df.groupby(['Dataset', 'Classifier', 'CalibrationMethod'])['ECE'].idxmin()
].reset_index(drop=True)
calibration_results_df2

             Dataset   Classifier   CalibrationMethod       ECE    Kernel
0        air_quality     AdaBoost   BestGPCalibration  0.068715  periodic
1        air_quality     AdaBoost  IsotonicRegression  0.170163       NaN
2        air_quality     AdaBoost        PlattScaling  0.140953       NaN
3        air_quality     AdaBoost        Uncalibrated  0.435509       NaN
4        air_quality  BernoulliNB   BestGPCalibration  0.029210       rbf
..               ...          ...                 ...       ...       ...
215  student_dropout          SVC        Uncalibrated  0.047003       NaN
216  student_dropout      XGBoost   BestGPCalibration  0.033564    linear
217  student_dropout      XGBoost  IsotonicRegression  0.038596       NaN
218  student_dropout      XGBoost        PlattScaling  0.082460       NaN
219  student_dropout      XGBoost        Uncalibrated  0.070258       NaN

[220 rows x 5 columns]

In [ ]:
calibration_results_df2.to_excel("all_kernels_calibration_results_with_kernel_name.xlsx", index=False)

In [142]:
# Filter to get the best calibration method (lowest ECE) for each dataset-classifier combination
print("="*80)
print("🏆 FINDING BEST CALIBRATION METHOD FOR EACH DATASET-CLASSIFIER COMBINATION")
print("="*80)

# Remove rows with missing ECE values
valid_calibration_results = calibration_results_df2.dropna(subset=['ECE']).copy()

print(f"Valid calibration results: {len(valid_calibration_results)} rows")
print(f"Datasets: {valid_calibration_results['Dataset'].nunique()}")
print(f"Classifiers: {valid_calibration_results['Classifier'].nunique()}")
print(f"Calibration Methods: {sorted(valid_calibration_results['CalibrationMethod'].unique())}")

# Find the best method (lowest ECE) for each dataset-classifier combination
best_calibration_methods = valid_calibration_results.loc[
    valid_calibration_results.groupby(['Dataset', 'Classifier'])['ECE'].idxmin()
].copy()

print(f"\n📊 Best calibration methods found: {len(best_calibration_methods)} combinations")

# Display the results
print("\n" + "="*100)
print("📋 BEST CALIBRATION METHOD FOR EACH DATASET-CLASSIFIER COMBINATION")
print("="*100)
print(f"{'Dataset':<20} {'Classifier':<15} {'Best_Method':<20} {'ECE':<10}")
print("-" * 100)

for _, row in best_calibration_methods.iterrows():
    dataset = row['Dataset']
    classifier = row['Classifier']
    method = row['CalibrationMethod']
    ece = row['ECE']

    print(f"{dataset:<20} {classifier:<15} {method:<20} {ece:<10.6f}")

# Create summary statistics
print("\n" + "="*80)
print("📊 SUMMARY STATISTICS")
print("="*80)

# Count how often each method is the best
method_counts = best_calibration_methods['CalibrationMethod'].value_counts()
print(f"\nHow often each method was the best (out of {len(best_calibration_methods)} combinations):")
for method, count in method_counts.items():
    percentage = (count / len(best_calibration_methods)) * 100
    print(f"  {method:<25}: {count:>3} times ({percentage:>5.1f}%)")

print(f"\n🏆 Most frequently best method: {method_counts.index[0]} ({method_counts.iloc[0]} times)")

# Average ECE by method for the best combinations
print(f"\n📈 Average ECE when each method was the best:")
for method in method_counts.index:
    method_best_results = best_calibration_methods[best_calibration_methods['CalibrationMethod'] == method]
    avg_ece = method_best_results['ECE'].mean()
    std_ece = method_best_results['ECE'].std()
    print(f"  {method:<25}: {avg_ece:.6f} ± {std_ece:.6f}")

# Create pivot table showing best method for each combination
pivot_best_methods = best_calibration_methods.pivot(
    index='Dataset', 
    columns='Classifier', 
    values='CalibrationMethod'
)

print(f"\n📋 PIVOT TABLE: Best Method for Each Combination")
print("-" * 100)
print(pivot_best_methods.to_string())

# Create pivot table showing ECE values for best methods
pivot_best_ece = best_calibration_methods.pivot(
    index='Dataset', 
    columns='Classifier', 
    values='ECE'
)

print(f"\n📋 PIVOT TABLE: ECE Values for Best Methods")
print("-" * 100)
print(pivot_best_ece.round(6).to_string())

# Overall statistics
print(f"\n📊 OVERALL PERFORMANCE OF BEST METHODS:")
print("-" * 60)
print(f"Mean ECE: {best_calibration_methods['ECE'].mean():.6f} ± {best_calibration_methods['ECE'].std():.6f}")
print(f"Min ECE:  {best_calibration_methods['ECE'].min():.6f}")
print(f"Max ECE:  {best_calibration_methods['ECE'].max():.6f}")

# Find the absolute best combination
absolute_best = best_calibration_methods.loc[best_calibration_methods['ECE'].idxmin()]
print(f"\n🥇 ABSOLUTE BEST COMBINATION:")
print(f"   Dataset: {absolute_best['Dataset']}")
print(f"   Classifier: {absolute_best['Classifier']}")
print(f"   Method: {absolute_best['CalibrationMethod']}")
print(f"   ECE: {absolute_best['ECE']:.6f}")

# Save the best methods dataframe
best_calibration_methods_df = best_calibration_methods.copy()

print(f"\n💾 Results saved as 'best_calibration_methods_df'")
print(f"Shape: {best_calibration_methods_df.shape}")
print("="*80)

================================================================================
🏆 FINDING BEST CALIBRATION METHOD FOR EACH DATASET-CLASSIFIER COMBINATION
================================================================================
Valid calibration results: 220 rows
Datasets: 5
Classifiers: 11
Calibration Methods: ['BestGPCalibration', 'IsotonicRegression', 'PlattScaling', 'Uncalibrated']

📊 Best calibration methods found: 55 combinations

====================================================================================================
📋 BEST CALIBRATION METHOD FOR EACH DATASET-CLASSIFIER COMBINATION
====================================================================================================
Dataset              Classifier      Best_Method          ECE
----------------------------------------------------------------------------------------------------
air_quality          AdaBoost        BestGPCalibration    0.068715
air_quality          BernoulliNB     BestGPCalibration    0.029210
air_quality          DecisionTree    BestGPCalibration    0.006768
air_quality          ExtraTree       BestGPCalibration    0.001082
air_quality          KNN             BestGPCalibration    0.018040
air_quality          MLP             BestGPCalibration    0.020681
air_quality          NaiveBayes      PlattScaling         0.021712
air_quality          RandomForest    BestGPCalibration    0.036783
air_quality          SGD             BestGPCalibration    0.035680
air_quality          SVC             BestGPCalibration    0.030598
air_quality          XGBoost         BestGPCalibration    0.022156
car_evaluation       AdaBoost        PlattScaling         0.073410
car_evaluation       BernoulliNB     BestGPCalibration    0.046766
car_evaluation       DecisionTree    BestGPCalibration    0.004432
car_evaluation       ExtraTree       BestGPCalibration    0.015345
car_evaluation       KNN             BestGPCalibration    0.063873
car_evaluation       MLP             BestGPCalibration    0.036416
car_evaluation       NaiveBayes      Uncalibrated         0.033333
car_evaluation       RandomForest    BestGPCalibration    0.045135
car_evaluation       SGD             BestGPCalibration    0.055450
car_evaluation       SVC             BestGPCalibration    0.038580
car_evaluation       XGBoost         BestGPCalibration    0.028258
cirrhosis            AdaBoost        PlattScaling         0.108510
cirrhosis            BernoulliNB     PlattScaling         0.112169
cirrhosis            DecisionTree    BestGPCalibration    0.019048
cirrhosis            ExtraTree       IsotonicRegression   0.019489
cirrhosis            KNN             IsotonicRegression   0.112875
cirrhosis            MLP             PlattScaling         0.043474
cirrhosis            NaiveBayes      PlattScaling         0.034083
cirrhosis            RandomForest    Uncalibrated         0.109877
cirrhosis            SGD             IsotonicRegression   0.066049
cirrhosis            SVC             Uncalibrated         0.072266
cirrhosis            XGBoost         IsotonicRegression   0.102425
dry_bean             AdaBoost        BestGPCalibration    0.025465
dry_bean             BernoulliNB     IsotonicRegression   0.027128
dry_bean             DecisionTree    BestGPCalibration    0.020009
dry_bean             ExtraTree       IsotonicRegression   0.014773
dry_bean             KNN             BestGPCalibration    0.016812
dry_bean             MLP             BestGPCalibration    0.026020
dry_bean             NaiveBayes      BestGPCalibration    0.022323
dry_bean             RandomForest    BestGPCalibration    0.019348
dry_bean             SGD             BestGPCalibration    0.022318
dry_bean             SVC             BestGPCalibration    0.028526
dry_bean             XGBoost         PlattScaling         0.018287
student_dropout      AdaBoost        BestGPCalibration    0.056046
student_dropout      BernoulliNB     IsotonicRegression   0.029446
student_dropout      DecisionTree    BestGPCalibration    0.031398
student_dropout      ExtraTree       BestGPCalibration    0.030818
student_dropout      KNN             BestGPCalibration    0.037370
student_dropout      MLP             IsotonicRegression   0.060480
student_dropout      NaiveBayes      IsotonicRegression   0.061943
student_dropout      RandomForest    IsotonicRegression   0.042045
student_dropout      SGD             Uncalibrated         0.027698
student_dropout      SVC             IsotonicRegression   0.028447
student_dropout      XGBoost         BestGPCalibration    0.033564

================================================================================
📊 SUMMARY STATISTICS
================================================================================

How often each method was the best (out of 55 combinations):
  BestGPCalibration        :  33 times ( 60.0%)
  IsotonicRegression       :  11 times ( 20.0%)
  PlattScaling             :   7 times ( 12.7%)
  Uncalibrated             :   4 times (  7.3%)

🏆 Most frequently best method: BestGPCalibration (33 times)

📈 Average ECE when each method was the best:
  BestGPCalibration        : 0.030092 ± 0.015760
  IsotonicRegression       : 0.051373 ± 0.032918
  PlattScaling             : 0.058807 ± 0.039572
  Uncalibrated             : 0.060794 ± 0.038254

📋 PIVOT TABLE: Best Method for Each Combination
----------------------------------------------------------------------------------------------------
Classifier                AdaBoost         BernoulliNB       DecisionTree           ExtraTree                 KNN                 MLP          NaiveBayes        RandomForest                 SGD                 SVC             XGBoost
Dataset
air_quality      BestGPCalibration   BestGPCalibration  BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration        PlattScaling   BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration
car_evaluation        PlattScaling   BestGPCalibration  BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration        Uncalibrated   BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration
cirrhosis             PlattScaling        PlattScaling  BestGPCalibration  IsotonicRegression  IsotonicRegression        PlattScaling        PlattScaling        Uncalibrated  IsotonicRegression        Uncalibrated  IsotonicRegression
dry_bean         BestGPCalibration  IsotonicRegression  BestGPCalibration  IsotonicRegression   BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration   BestGPCalibration        PlattScaling
student_dropout  BestGPCalibration  IsotonicRegression  BestGPCalibration   BestGPCalibration   BestGPCalibration  IsotonicRegression  IsotonicRegression  IsotonicRegression        Uncalibrated  IsotonicRegression   BestGPCalibration

📋 PIVOT TABLE: ECE Values for Best Methods
----------------------------------------------------------------------------------------------------
Classifier       AdaBoost  BernoulliNB  DecisionTree  ExtraTree       KNN       MLP  NaiveBayes  RandomForest       SGD       SVC   XGBoost
Dataset
air_quality      0.068715     0.029210      0.006768   0.001082  0.018040  0.020681    0.021712      0.036783  0.035680  0.030598  0.022156
car_evaluation   0.073410     0.046766      0.004432   0.015345  0.063873  0.036416    0.033333      0.045135  0.055450  0.038580  0.028258
cirrhosis        0.108510     0.112169      0.019048   0.019489  0.112875  0.043474    0.034083      0.109877  0.066049  0.072266  0.102425
dry_bean         0.025465     0.027128      0.020009   0.014773  0.016812  0.026020    0.022323      0.019348  0.022318  0.028526  0.018287
student_dropout  0.056046     0.029446      0.031398   0.030818  0.037370  0.060480    0.061943      0.042045  0.027698  0.028447  0.033564

📊 OVERALL PERFORMANCE OF BEST METHODS:
------------------------------------------------------------
Mean ECE: 0.040236 ± 0.027700
Min ECE:  0.001082
Max ECE:  0.112875

🥇 ABSOLUTE BEST COMBINATION:
   Dataset: air_quality
   Classifier: ExtraTree
   Method: BestGPCalibration
   ECE: 0.001082

💾 Results saved as 'best_calibration_methods_df'
Shape: (55, 5)
================================================================================

In [143]:
best_calibration_methods_df

,Dataset,Classifier,CalibrationMethod,ECE,Kernel
0,air_quality,AdaBoost,BestGPCalibration,0.068715,periodic
4,air_quality,BernoulliNB,BestGPCalibration,0.029210,rbf
8,air_quality,DecisionTree,BestGPCalibration,0.006768,cosine
12,air_quality,ExtraTree,BestGPCalibration,0.001082,cosine
16,air_quality,KNN,BestGPCalibration,0.018040,matern52
20,air_quality,MLP,BestGPCalibration,0.020681,white
26,air_quality,NaiveBayes,PlattScaling,0.021712,NaN
28,air_quality,RandomForest,BestGPCalibration,0.036783,matern32
32,air_quality,SGD,BestGPCalibration,0.035680,rbf
36,air_quality,SVC,BestGPCalibration,0.030598,rbf
40,air_quality,XGBoost,BestGPCalibration,0.022156,white
46,car_evaluation,AdaBoost,PlattScaling,0.073410,NaN
48,car_evaluation,BernoulliNB,BestGPCalibration,0.046766,matern32
52,car_evaluation,DecisionTree,BestGPCalibration,0.004432,matern12
56,car_evaluation,ExtraTree,BestGPCalibration,0.015345,cosine
60,car_evaluation,KNN,BestGPCalibration,0.063873,polynomial
64,car_evaluation,MLP,BestGPCalibration,0.036416,matern52
71,car_evaluation,NaiveBayes,Uncalibrated,0.033333,NaN
72,car_evaluation,RandomForest,BestGPCalibration,0.045135,polynomial
76,car_evaluation,SGD,BestGPCalibration,0.055450,linear
80,car_evaluation,SVC,BestGPCalibration,0.038580,rbf
84,car_evaluation,XGBoost,BestGPCalibration,0.028258,cosine
90,cirrhosis,AdaBoost,PlattScaling,0.108510,NaN
94,cirrhosis,BernoulliNB,PlattScaling,0.112169,NaN
96,cirrhosis,DecisionTree,BestGPCalibration,0.019048,cosine
101,cirrhosis,ExtraTree,IsotonicRegression,0.019489,NaN
105,cirrhosis,KNN,IsotonicRegression,0.112875,NaN
110,cirrhosis,MLP,PlattScaling,0.043474,NaN
114,cirrhosis,NaiveBayes,PlattScaling,0.034083,NaN
119,cirrhosis,RandomForest,Uncalibrated,0.109877,NaN
121,cirrhosis,SGD,IsotonicRegression,0.066049,NaN
127,cirrhosis,SVC,Uncalibrated,0.072266,NaN
129,cirrhosis,XGBoost,IsotonicRegression,0.102425,NaN
132,dry_bean,AdaBoost,BestGPCalibration,0.025465,rational_quadratic
137,dry_bean,BernoulliNB,IsotonicRegression,0.027128,NaN
140,dry_bean,DecisionTree,BestGPCalibration,0.020009,cosine
145,dry_bean,ExtraTree,IsotonicRegression,0.014773,NaN
148,dry_bean,KNN,BestGPCalibration,0.016812,white
152,dry_bean,MLP,BestGPCalibration,0.026020,matern32
156,dry_bean,NaiveBayes,BestGPCalibration,0.022323,rational_quadratic
160,dry_bean,RandomForest,BestGPCalibration,0.019348,rational_quadratic
164,dry_bean,SGD,BestGPCalibration,0.022318,polynomial
168,dry_bean,SVC,BestGPCalibration,0.028526,periodic
174,dry_bean,XGBoost,PlattScaling,0.018287,NaN
176,student_dropout,AdaBoost,BestGPCalibration,0.056046,periodic
181,student_dropout,BernoulliNB,IsotonicRegression,0.029446,NaN
184,student_dropout,DecisionTree,BestGPCalibration,0.031398,matern32
188,student_dropout,ExtraTree,BestGPCalibration,0.030818,cosine
192,student_dropout,KNN,BestGPCalibration,0.037370,white
197,student_dropout,MLP,IsotonicRegression,0.060480,NaN
201,student_dropout,NaiveBayes,IsotonicRegression,0.061943,NaN
205,student_dropout,RandomForest,IsotonicRegression,0.042045,NaN
211,student_dropout,SGD,Uncalibrated,0.027698,NaN
213,student_dropout,SVC,IsotonicRegression,0.028447,NaN
216,student_dropout,XGBoost,BestGPCalibration,0.033564,linear

In [145]:
best_calibration_methods_df['Dataset'].value_counts()

dry_bean           11
air_quality        11
cirrhosis          11
car_evaluation     11
student_dropout    11
Name: Dataset, dtype: int64

In [144]:
best_calibration_methods_df.to_excel("best_calibration_methods_with_kernel.xlsx", index=False)

# DIsplay

In [11]:
calib_results = pd.read_csv("all_kernels_calibration_results_with_kernel_name.csv")
calib_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Dataset            220 non-null    object
 1   Classifier         220 non-null    object
 2   CalibrationMethod  220 non-null    object
 3   ECE                220 non-null    float64
 4   Kernel             55 non-null     object
dtypes: float64(1), object(4)
memory usage: 8.7+ KB

In [18]:
calib_results['Classifier'].value_counts()

MLP             20
NaiveBayes      20
KNN             20
DecisionTree    20
ExtraTree       20
AdaBoost        20
BernoulliNB     20
SGD             20
XGBoost         20
RandomForest    20
SVC             20
Name: Classifier, dtype: int64

In [20]:
# drop NaiveBayes and BernoulliNB from calibration_results_df
calib_results = calib_results[
    ~calib_results['Classifier'].isin(['NaiveBayes', 'BernoulliNB','ExtraTree'])
].reset_index(drop=True)
calib_results['Classifier'].value_counts()

MLP             20
AdaBoost        20
SGD             20
XGBoost         20
RandomForest    20
SVC             20
KNN             20
DecisionTree    20
Name: Classifier, dtype: int64

## 📊 Tabel Perbandingan ECE: Dataset x Model x Metode Kalibrasi

Membuat tabel pivot yang menampilkan ECE untuk setiap kombinasi:
- **Baris**: Dataset dan Model ML
- **Kolom**: Metode Kalibrasi (Uncalibrated, IsotonicRegression, PlattScaling, BestGPCalibration, Best Kernel)

In [21]:
# Create ECE comparison table
# Columns: Dataset | Model ML | Uncalibrated | IsotonicRegression | PlattScaling | BestGPCalibration | Best Kernel

print("="*100)
print("📊 CREATING ECE COMPARISON TABLE")
print("="*100)

# Check available columns in calib_results
print("\nAvailable columns in calib_results:")
print(calib_results.columns.tolist())
print(f"\nShape: {calib_results.shape}")
print(f"Unique CalibrationMethod values: {sorted(calib_results['CalibrationMethod'].unique())}")

# Step 1: Filter only ECE data and relevant methods
# Define the methods we want to include in the table
desired_methods = ['Uncalibrated', 'IsotonicRegression', 'PlattScaling', 'BestGPCalibration']

# Check which methods are actually available
available_methods = calib_results['CalibrationMethod'].unique()
methods_to_include = [m for m in desired_methods if m in available_methods]

print(f"\nMethods to include in table: {methods_to_include}")

# Step 2: Create a subset with only the methods we want
ece_data = calib_results[calib_results['CalibrationMethod'].isin(methods_to_include)].copy()

# Step 3: Create pivot table with Dataset and Classifier as index, CalibrationMethod as columns
ece_pivot = ece_data.pivot_table(
    index=['Dataset', 'Classifier'],
    columns='CalibrationMethod',
    values='ECE',
    aggfunc='mean'  # Use mean in case there are duplicates
)

# Step 4: Add Best Kernel column (kernel with lowest ECE for each dataset-classifier)
# Find the best kernel for each dataset-classifier combination
if 'Kernel' in calib_results.columns:
    # Get best kernel info
    best_kernels = calib_results.loc[
        calib_results.groupby(['Dataset', 'Classifier'])['ECE'].idxmin()
    ][['Dataset', 'Classifier', 'Kernel', 'ECE']].set_index(['Dataset', 'Classifier'])
    
    # Add Best Kernel column to pivot table
    ece_pivot['Best Kernel'] = best_kernels['Kernel']
    
    print("\n✅ Added 'Best Kernel' column showing the kernel with lowest ECE")
else:
    print("\n⚠️  'Kernel' column not found in calib_results")

# Step 5: Reorder columns to match requested order
column_order = []
if 'Uncalibrated' in ece_pivot.columns:
    column_order.append('Uncalibrated')
if 'IsotonicRegression' in ece_pivot.columns:
    column_order.append('IsotonicRegression')
if 'PlattScaling' in ece_pivot.columns:
    column_order.append('PlattScaling')
if 'BestGPCalibration' in ece_pivot.columns:
    column_order.append('BestGPCalibration')
if 'Best Kernel' in ece_pivot.columns:
    column_order.append('Best Kernel')

# Reorder columns
ece_pivot = ece_pivot[column_order]

# Step 6: Reset index to make Dataset and Classifier regular columns
ece_comparison_table = ece_pivot.reset_index()

# Rename columns for clarity
ece_comparison_table.columns.name = None  # Remove the 'CalibrationMethod' name from columns

# Step 6.5: Round ECE values to 4 decimal places
numeric_cols = [col for col in ece_comparison_table.columns if col not in ['Dataset', 'Classifier', 'Best Kernel']]
ece_comparison_table[numeric_cols] = ece_comparison_table[numeric_cols].round(4)

print("\n" + "="*100)
print("✅ ECE COMPARISON TABLE CREATED")
print("="*100)
print(f"Shape: {ece_comparison_table.shape}")
print(f"Columns: {ece_comparison_table.columns.tolist()}")
print(f"\nFirst 10 rows:")
print(ece_comparison_table.head(10).to_string(index=False))

# Display full table
print("\n" + "="*100)
print("📋 FULL ECE COMPARISON TABLE")
print("="*100)
from IPython.display import display
display(ece_comparison_table)

# Step 7: Save to CSV
csv_filename = 'ece_comparison_table.csv'
ece_comparison_table.to_csv(csv_filename, index=False)
print(f"\n✅ Table saved to: {csv_filename}")

# Step 8: Show summary statistics
print("\n" + "="*100)
print("📊 SUMMARY STATISTICS")
print("="*100)
for col in column_order:
    if col != 'Best Kernel':
        print(f"\n{col}:")
        print(f"  Mean ECE: {ece_comparison_table[col].mean():.6f}")
        print(f"  Min ECE:  {ece_comparison_table[col].min():.6f}")
        print(f"  Max ECE:  {ece_comparison_table[col].max():.6f}")
        print(f"  Std ECE:  {ece_comparison_table[col].std():.6f}")

print("\n" + "="*100)

====================================================================================================
📊 CREATING ECE COMPARISON TABLE
====================================================================================================

Available columns in calib_results:
['Dataset', 'Classifier', 'CalibrationMethod', 'ECE', 'Kernel']

Shape: (160, 5)
Unique CalibrationMethod values: ['BestGPCalibration', 'IsotonicRegression', 'PlattScaling', 'Uncalibrated']

Methods to include in table: ['Uncalibrated', 'IsotonicRegression', 'PlattScaling', 'BestGPCalibration']

✅ Added 'Best Kernel' column showing the kernel with lowest ECE

====================================================================================================
✅ ECE COMPARISON TABLE CREATED
====================================================================================================
Shape: (40, 7)
Columns: ['Dataset', 'Classifier', 'Uncalibrated', 'IsotonicRegression', 'PlattScaling', 'BestGPCalibration', 'Best Kernel']

First 10 rows:
        Dataset    Classifier  Uncalibrated  IsotonicRegression  PlattScaling  BestGPCalibration Best Kernel
    air_quality      AdaBoost        0.4355              0.1702        0.1410             0.0687    periodic
    air_quality  DecisionTree        0.0389              0.0738        0.0738             0.0068      cosine
    air_quality           KNN        0.0393              0.0261        0.0355             0.0180    matern52
    air_quality           MLP        0.0283              0.0409        0.0322             0.0207       white
    air_quality  RandomForest        0.0647              0.0430        0.0489             0.0368    matern32
    air_quality           SGD        0.1326              0.0508        0.0582             0.0357         rbf
    air_quality           SVC        0.0382              0.0403        0.0329             0.0306         rbf
    air_quality       XGBoost        0.0334              0.0404        0.0358             0.0222       white
 car_evaluation      AdaBoost        0.1006              0.0812        0.0734             0.0811         NaN
 car_evaluation  DecisionTree        0.0211              0.0424        0.0424             0.0044    matern12

====================================================================================================
📋 FULL ECE COMPARISON TABLE
====================================================================================================

,Dataset,Classifier,Uncalibrated,IsotonicRegression,PlattScaling,BestGPCalibration,Best Kernel
0,air_quality,AdaBoost,0.4355,0.1702,0.1410,0.0687,periodic
1,air_quality,DecisionTree,0.0389,0.0738,0.0738,0.0068,cosine
2,air_quality,KNN,0.0393,0.0261,0.0355,0.0180,matern52
3,air_quality,MLP,0.0283,0.0409,0.0322,0.0207,white
4,air_quality,RandomForest,0.0647,0.0430,0.0489,0.0368,matern32
5,air_quality,SGD,0.1326,0.0508,0.0582,0.0357,rbf
6,air_quality,SVC,0.0382,0.0403,0.0329,0.0306,rbf
7,air_quality,XGBoost,0.0334,0.0404,0.0358,0.0222,white
8,car_evaluation,AdaBoost,0.1006,0.0812,0.0734,0.0811,NaN
9,car_evaluation,DecisionTree,0.0211,0.0424,0.0424,0.0044,matern12
10,car_evaluation,KNN,0.1061,0.0859,0.0792,0.0639,polynomial
11,car_evaluation,MLP,0.0568,0.0514,0.0491,0.0364,matern52
12,car_evaluation,RandomForest,0.1291,0.0479,0.0549,0.0451,polynomial
13,car_evaluation,SGD,0.0790,0.0562,0.0627,0.0555,linear
14,car_evaluation,SVC,0.0507,0.0463,0.0524,0.0386,rbf
15,car_evaluation,XGBoost,0.0586,0.0507,0.0451,0.0283,cosine
16,cirrhosis,AdaBoost,0.1979,0.1133,0.1085,0.1655,NaN
17,cirrhosis,DecisionTree,0.2595,0.0651,0.0651,0.0190,cosine
18,cirrhosis,KNN,0.1165,0.1129,0.1497,0.1164,NaN
19,cirrhosis,MLP,0.1838,0.0847,0.0435,0.1323,NaN
20,cirrhosis,RandomForest,0.1099,0.1426,0.1281,0.1642,NaN
21,cirrhosis,SGD,0.1674,0.0660,0.0813,0.1094,NaN
22,cirrhosis,SVC,0.0723,0.1486,0.1084,0.0800,NaN
23,cirrhosis,XGBoost,0.1438,0.1024,0.1088,0.1139,NaN
24,dry_bean,AdaBoost,0.2159,0.0847,0.0416,0.0255,rational_quadratic
25,dry_bean,DecisionTree,0.0598,0.0575,0.0575,0.0200,cosine
26,dry_bean,KNN,0.0287,0.0342,0.0396,0.0168,white
27,dry_bean,MLP,0.0333,0.0347,0.0281,0.0260,matern32
28,dry_bean,RandomForest,0.0316,0.0314,0.0341,0.0193,rational_quadratic
29,dry_bean,SGD,0.0538,0.0331,0.0382,0.0223,polynomial
30,dry_bean,SVC,0.0355,0.0295,0.0307,0.0285,periodic
31,dry_bean,XGBoost,0.0284,0.0339,0.0183,0.0239,NaN
32,student_dropout,AdaBoost,0.3805,0.0659,0.1460,0.0560,periodic
33,student_dropout,DecisionTree,0.2378,0.1056,0.1056,0.0314,matern32
34,student_dropout,KNN,0.0447,0.0592,0.0650,0.0374,white
35,student_dropout,MLP,0.1619,0.0605,0.0712,0.0687,NaN
36,student_dropout,RandomForest,0.0786,0.0420,0.0591,0.0552,NaN
37,student_dropout,SGD,0.0277,0.0546,0.0665,0.0326,NaN
38,student_dropout,SVC,0.0470,0.0284,0.0588,0.0614,NaN
39,student_dropout,XGBoost,0.0703,0.0386,0.0825,0.0336,linear

✅ Table saved to: ece_comparison_table.csv

====================================================================================================
📊 SUMMARY STATISTICS
====================================================================================================

Uncalibrated:
  Mean ECE: 0.104988
  Min ECE:  0.021100
  Max ECE:  0.435500
  Std ECE:  0.095072

IsotonicRegression:
  Mean ECE: 0.064423
  Min ECE:  0.026100
  Max ECE:  0.170200
  Std ECE:  0.035058

PlattScaling:
  Mean ECE: 0.066342
  Min ECE:  0.018300
  Max ECE:  0.149700
  Std ECE:  0.034142

BestGPCalibration:
  Mean ECE: 0.051303
  Min ECE:  0.004400
  Max ECE:  0.165500
  Std ECE:  0.040613

====================================================================================================

In [22]:
# Generate LaTeX code for ece_comparison_table using longtable
print("="*100)
print("📄 GENERATING LaTeX CODE FOR ECE COMPARISON TABLE")
print("="*100)

# Create a copy of the table with renamed columns and datasets
ece_table_latex = ece_comparison_table.copy()

# Rename columns
column_rename_map = {
    'Dataset': 'Dataset',
    'Classifier': 'Classifier',
    'Uncalibrated': 'Uncal.',
    'IsotonicRegression': 'IsoReg',
    'PlattScaling': 'Platt',
    'BestGPCalibration': 'GPCalib',
    'Best Kernel': 'Kernel'
}
ece_table_latex.rename(columns=column_rename_map, inplace=True)

# Rename dataset values
dataset_rename_map = {
    'air_quality': 'AirQty',
    'car_evaluation': 'CarEval',
    'cirrhosis': 'Cirrhosis',
    'dry_bean': 'DryBean',
    'student_dropout': 'StdntDrop'
}
ece_table_latex['Dataset'] = ece_table_latex['Dataset'].replace(dataset_rename_map)

# Prepare the LaTeX table
latex_code = []

# Add document preamble (optional - for standalone compilation)
latex_code.append("% Paste this in your Overleaf document")
latex_code.append("% Make sure to add these packages in your preamble:")
latex_code.append("% \\usepackage{longtable}")
latex_code.append("% \\usepackage{booktabs}")
latex_code.append("% \\usepackage{array}")
latex_code.append("")

# Start longtable
num_cols = len(ece_table_latex.columns)
col_alignment = "l" * num_cols  # Left align all columns
latex_code.append(f"\\begin{{longtable}}{{{col_alignment}}}")

# Add caption and label
latex_code.append("\\caption{ECE Comparison Table: Performance across Datasets, Classifiers, and Calibration Methods}")
latex_code.append("\\label{tab:ece_comparison} \\\\")

# Add top rule
latex_code.append("\\toprule")

# Add header row
header_row = " & ".join(ece_table_latex.columns) + " \\\\"
latex_code.append(header_row)
latex_code.append("\\midrule")

# Add endfirsthead (for first page header)
latex_code.append("\\endfirsthead")

# Add continued caption for subsequent pages
latex_code.append("")
latex_code.append("\\multicolumn{" + str(num_cols) + "}{c}")
latex_code.append("{\\tablename\\ \\thetable\\ -- \\textit{Continued from previous page}} \\\\")
latex_code.append("\\toprule")
latex_code.append(header_row)
latex_code.append("\\midrule")
latex_code.append("\\endhead")

# Add footer for all pages except last
latex_code.append("")
latex_code.append("\\midrule")
latex_code.append("\\multicolumn{" + str(num_cols) + "}{r}{\\textit{Continued on next page}} \\\\")
latex_code.append("\\bottomrule")
latex_code.append("\\endfoot")

# Add footer for last page
latex_code.append("")
latex_code.append("\\bottomrule")
latex_code.append("\\endlastfoot")

# Add data rows
latex_code.append("")
latex_code.append("% Data rows")

# Get numeric column names (ECE columns only) - using renamed columns
numeric_ece_cols = [col for col in ece_table_latex.columns 
                    if col not in ['Dataset', 'Classifier', 'Kernel']]

for idx, row in ece_table_latex.iterrows():
    # Find minimum ECE value in this row (among numeric columns)
    numeric_values = []
    for col in numeric_ece_cols:
        if pd.notna(row[col]):
            numeric_values.append(row[col])
    
    # Determine minimum value if there are any numeric values
    min_value = min(numeric_values) if numeric_values else None
    
    # Format each cell
    row_data = []
    for col in ece_table_latex.columns:
        value = row[col]
        
        if col in ['Dataset', 'Classifier', 'Kernel']:
            # Text columns - escape special characters
            value_str = str(value).replace('_', '\\_').replace('&', '\\&')
            row_data.append(value_str)
        else:
            # Numeric columns - format to 4 decimal places
            if pd.notna(value):
                formatted_value = f"{value:.4f}"
                # Bold if this is the minimum value in the row
                if min_value is not None and abs(value - min_value) < 1e-9:
                    formatted_value = f"\\textbf{{{formatted_value}}}"
                row_data.append(formatted_value)
            else:
                row_data.append("--")
    
    # Join row data
    row_str = " & ".join(row_data) + " \\\\"
    latex_code.append(row_str)

# End longtable
latex_code.append("")
latex_code.append("\\end{longtable}")

# Join all lines
latex_output = "\n".join(latex_code)

# Save to file
latex_filename = 'ece_comparison_table.tex'
with open(latex_filename, 'w', encoding='utf-8') as f:
    f.write(latex_output)

print(f"\n✅ LaTeX code generated and saved to: {latex_filename}")
print(f"📊 Table dimensions: {ece_comparison_table.shape[0]} rows × {ece_comparison_table.shape[1]} columns")

# Display preview (first 30 lines)
print("\n" + "="*100)
print("📋 LATEX CODE PREVIEW (First 30 lines):")
print("="*100)
latex_lines = latex_output.split('\n')
preview_lines = latex_lines[:30]
for line in preview_lines:
    print(line)

if len(latex_lines) > 30:
    print("...")
    remaining_lines = len(latex_lines) - 30
    print(f"(+ {remaining_lines} more lines)")

print("\n" + "="*100)
print("📝 USAGE INSTRUCTIONS:")
print("="*100)
print("1. Copy the content of 'ece_comparison_table.tex'")
print("2. In your Overleaf document preamble, add:")
print("   \\usepackage{longtable}")
print("   \\usepackage{booktabs}")
print("   \\usepackage{array}")
print("3. Paste the LaTeX code where you want the table to appear")
print("4. The table will automatically span multiple pages if needed")
print("")
print("💡 Optional enhancements:")
print("- Add \\usepackage{xcolor} for colored rows")
print("- Use \\rowcolors{2}{gray!10}{white} after \\begin{longtable} for alternating row colors")
print("- Adjust column alignment by changing 'l' to 'c' (center) or 'r' (right)")
print("="*100)

====================================================================================================
📄 GENERATING LaTeX CODE FOR ECE COMPARISON TABLE
====================================================================================================

✅ LaTeX code generated and saved to: ece_comparison_table.tex
📊 Table dimensions: 40 rows × 7 columns

====================================================================================================
📋 LATEX CODE PREVIEW (First 30 lines):
====================================================================================================
% Paste this in your Overleaf document
% Make sure to add these packages in your preamble:
% \usepackage{longtable}
% \usepackage{booktabs}
% \usepackage{array}

\begin{longtable}{lllllll}
\caption{ECE Comparison Table: Performance across Datasets, Classifiers, and Calibration Methods}
\label{tab:ece_comparison} \\
\toprule
Dataset & Classifier & Uncal. & IsoReg & Platt & GPCalib & Kernel \\
\midrule
\endfirsthead

\multicolumn{7}{c}
{\tablename\ \thetable\ -- \textit{Continued from previous page}} \\
\toprule
Dataset & Classifier & Uncal. & IsoReg & Platt & GPCalib & Kernel \\
\midrule
\endhead

\midrule
\multicolumn{7}{r}{\textit{Continued on next page}} \\
\bottomrule
\endfoot

\bottomrule
\endlastfoot

% Data rows
...
(+ 42 more lines)

====================================================================================================
📝 USAGE INSTRUCTIONS:
====================================================================================================
1. Copy the content of 'ece_comparison_table.tex'
2. In your Overleaf document preamble, add:
   \usepackage{longtable}
   \usepackage{booktabs}
   \usepackage{array}
3. Paste the LaTeX code where you want the table to appear
4. The table will automatically span multiple pages if needed

💡 Optional enhancements:
- Add \usepackage{xcolor} for colored rows
- Use \rowcolors{2}{gray!10}{white} after \begin{longtable} for alternating row colors
- Adjust column alignment by changing 'l' to 'c' (center) or 'r' (right)
====================================================================================================